# Copyright 2026 Life Sciences Suite Architecture Team
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl-3.0).
from . import ls_pharma_material_mixin
from . import ls_pharma_api
from . import ls_pharma_excipient
from . import ls_pharma_batch
from . import ls_pharma_batch_component
from . import ls_pharma_batch_equipment
from . import ls_pharma_batch_coproduct
from . import ls_pharma_batch_record
from . import ls_pharma_batch_record_step
from . import ls_pharma_batch_record_control
from . import ls_pharma_batch_record_discrepancy
from . import ls_pharma_batch_record_labeling
from . import ls_pharma_batch_record_sample
from . import ls_pharma_batch_record_clearance
from . import ls_pharma_batch_release
from . import ls_pharma_stability_condition
from . import ls_pharma_stability_study
from . import ls_pharma_stability_timepoint
from . import ls_pharma_stability_sample
from . import ls_pharma_stability_result
from . import ls_pharma_serialization
from . import ls_pharma_aggregation
from . import ls_pharma_ctd_dossier
from . import ls_pharma_ctd_section
from . import product_template
from . import res_company
from . import stock_move_line
