# Copyright 2026 Life Sciences Suite Architecture Team
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl-3.0).
"""Serialised saleable units."""

from odoo import api, fields, models
from odoo.exceptions import UserError, ValidationError

from .. import gs1
from ..constants import (
    SERIALIZATION_STATES,
    SERIALIZATION_TERMINAL_STATES,
)


class LsPharmaSerialization(models.Model):
    """A single serialised saleable unit of a medicinal product.

    Commission Delegated Regulation (EU) 2016/161 defines the unique
    identifier of a pack as the combination of a product code, a serial
    number, a national reimbursement or identification number where the
    Member State requires one, the batch number and the expiry date.  Those
    five data elements are the fields of this model.  The element string
    built from them uses the GS1 Application Identifiers that conventionally
    carry the first four: (01) for the product code, (21) for the serial
    number, (10) for the batch number and (17) for the expiry date.

    The Regulation also requires that the probability of a serial number
    being guessed be negligible.  Serial numbers generated by this module are
    therefore drawn from a cryptographically strong source of randomness; see
    :func:`~odoo.addons.ls_pharma.gs1.generate_random_serial`.

    What this model is not
    ----------------------
    This model does not connect to the European repositories system, to a
    national repository or to any other verification system, and it does not
    render barcode symbols.  It maintains the serialisation data inside the
    enterprise resource planning system so that the data can be exported to
    such a system.
    """

    _name = "ls.pharma.serialization"
    _description = "Serialised Saleable Unit"
    _order = "batch_id, serial_number"

    _gtin_serial_company_uniq = models.Constraint(
        "UNIQUE(gtin, serial_number, company_id)",
        "A serial number can only be used once for a given product code.",
    )

    batch_id = fields.Many2one(comodel_name="ls.pharma.batch", required=True,
                               ondelete="restrict",
                               index=True,)
    company_id = fields.Many2one(comodel_name="res.company", related="batch_id.company_id",
                                 store=True,
                                 index=True,)
    product_id = fields.Many2one(comodel_name="product.product", related="batch_id.product_id",
                                 store=True,)
    gtin = fields.Char(
        string="Product Code (GTIN-14)",
        required=True,
        index=True,
        help="Product code carried by GS1 Application Identifier (01).",
    )
    serial_number = fields.Char(required=True,
                                index=True,
                                help="Serial number carried by GS1 Application Identifier (21).",
                                )
    batch_number = fields.Char(required=True,
                               help="Batch number carried by GS1 Application Identifier (10).",
                               )
    expiry_date = fields.Date(required=True,
                              help="Expiry date carried by GS1 Application Identifier (17).",
                              )
    national_number = fields.Char(
        string="National Reimbursement Number",
        help=(
            "National reimbursement or identification number, where the "
            "Member State of destination requires one. The Application "
            "Identifier that carries it varies by Member State, so the value "
            "is stored separately and is not appended to the element string "
            "built by this module."
        ),
    )
    element_string = fields.Char(
        string="GS1 Element String",
        compute="_compute_element_string",
        store=True,
        help=(
            "Human-readable interpretation of the unique identifier. It is "
            "the data content that a barcode encoder consumes; this module "
            "does not render the symbol itself."
        ),
    )
    aggregation_id = fields.Many2one(
        comodel_name="ls.pharma.aggregation",
        string="Parent Container",
        index=True,
        ondelete="set null",
    )
    state = fields.Selection(
        selection=SERIALIZATION_STATES,
        string="Status",
        default="generated",
        required=True,
        index=True,
        copy=False,
    )
    date_commissioned = fields.Datetime(string="Commissioned On", copy=False)
    date_decommissioned = fields.Datetime(string="Decommissioned On", copy=False)
    decommission_reason = fields.Char(copy=False)

    # ------------------------------------------------------------------
    # Computed fields
    # ------------------------------------------------------------------
    @api.depends("gtin", "serial_number", "batch_number", "expiry_date")
    def _compute_element_string(self):
        """Build the element string of the unique identifier."""
        for unit in self:
            try:
                unit.element_string = gs1.build_unique_identifier(
                    unit.gtin,
                    unit.serial_number,
                    unit.batch_number,
                    unit.expiry_date,
                )
            except gs1.Gs1Error:
                unit.element_string = False

    @api.depends("gtin", "serial_number")
    def _compute_display_name(self):
        """Show the product code and the serial number."""
        for unit in self:
            unit.display_name = "%s / %s" % (
                unit.gtin or "",
                unit.serial_number or "",
            )

    # ------------------------------------------------------------------
    # Constraints
    # ------------------------------------------------------------------
    @api.constrains("gtin")
    def _check_gtin(self):
        """Reject a product code that is not a valid GTIN-14."""
        for unit in self:
            if not gs1.is_valid_gtin14(unit.gtin):
                raise ValidationError(
                    self.env._(
                        "The product code %(gtin)s is not a valid GTIN-14. A "
                        "GTIN-14 has fourteen digits and ends with a "
                        "modulo-10 check digit.",
                        gtin=unit.gtin,
                    )
                )

    @api.constrains("serial_number", "batch_number")
    def _check_variable_fields(self):
        """Reject data fields that exceed the length permitted by GS1."""
        for unit in self:
            try:
                gs1.validate_variable_field(
                    unit.serial_number, "serial number"
                )
                gs1.validate_variable_field(unit.batch_number, "batch number")
            except gs1.Gs1Error as error:
                raise ValidationError(str(error)) from error

    # ------------------------------------------------------------------
    # Overrides
    # ------------------------------------------------------------------
    def write(self, vals):
        """Protect the identifying data of a commissioned unit."""
        protected = {
            "gtin",
            "serial_number",
            "batch_number",
            "expiry_date",
            "batch_id",
        }
        touched = protected.intersection(vals)
        if touched:
            for unit in self:
                if unit.state != "generated":
                    raise UserError(
                        self.env._(
                            "Unit %(name)s has been commissioned. Its unique "
                            "identifier can no longer be modified.",
                            name=unit.display_name,
                        )
                    )
        return super().write(vals)

    @api.ondelete(at_uninstall=False)
    def _ls_unlink_check_ls_pharma_serialization(self):
        """Forbid the deletion of a unit that has been commissioned."""
        for unit in self:
            if unit.state != "generated":
                raise UserError(
                    self.env._(
                        "Unit %(name)s has been commissioned and can no "
                        "longer be deleted. Decommission it instead so that "
                        "the record is retained.",
                        name=unit.display_name,
                    )
                )

    # ------------------------------------------------------------------
    # State machine
    # ------------------------------------------------------------------
    def action_commission(self):
        """Commission the selected units."""
        for unit in self:
            if unit.state != "generated":
                raise UserError(
                    self.env._(
                        "Unit %(name)s is not in the generated state.",
                        name=unit.display_name,
                    )
                )
        self.write(
            {"state": "commissioned", "date_commissioned": fields.Datetime.now()}
        )
        return True

    def action_decommission(self):
        """Decommission the selected units."""
        for unit in self:
            if unit.state in SERIALIZATION_TERMINAL_STATES:
                raise UserError(
                    self.env._(
                        "Unit %(name)s has already reached a terminal state.",
                        name=unit.display_name,
                    )
                )
        self.write(
            {
                "state": "decommissioned",
                "date_decommissioned": fields.Datetime.now(),
            }
        )
        return True

    def action_mark_shipped(self):
        """Record that the selected units have been shipped."""
        for unit in self:
            if unit.state not in ("commissioned", "aggregated"):
                raise UserError(
                    self.env._(
                        "Unit %(name)s must be commissioned before it can be "
                        "shipped.",
                        name=unit.display_name,
                    )
                )
        self.write({"state": "shipped"})
        return True
