# Copyright 2026 Life Sciences Suite Architecture Team
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl-3.0).
"""Company level configuration of the pharmaceutical module."""

import string

from odoo import api, fields, models
from odoo.exceptions import ValidationError


class ResCompany(models.Model):
    """Configuration that applies to every pharmaceutical record of a company."""

    _inherit = "res.company"

    pharma_gs1_company_prefix = fields.Char(
        string="GS1 Company Prefix",
        help=(
            "GS1 Company Prefix allocated to this company by its GS1 Member "
            "Organisation. It is used to build Serial Shipping Container "
            "Codes."
        ),
    )
    pharma_sscc_extension_digit = fields.Char(
        string="SSCC Extension Digit",
        default="0",
        help=(
            "Single digit chosen by the company to increase the capacity of "
            "the Serial Shipping Container Code series."
        ),
    )
    pharma_serial_length = fields.Integer(
        string="Generated Serial Number Length",
        default=12,
        help=(
            "Number of characters of a serial number generated by this "
            "module. GS1 Application Identifier (21) permits up to twenty "
            "characters."
        ),
    )
    pharma_batch_expiry_alert_days = fields.Integer(
        string="Batch Expiry Alert Horizon (Days)",
        default=90,
        help=(
            "Number of days before expiry at which the scheduled action "
            "notifies released batches. A value of zero disables the "
            "notification for this company."
        ),
    )

    @api.constrains("pharma_gs1_company_prefix")
    def _check_gs1_company_prefix(self):
        """Reject a company prefix that is not a string of digits."""
        for company in self:
            prefix = company.pharma_gs1_company_prefix
            if not prefix:
                continue
            if not all(character in string.digits for character in prefix):
                raise ValidationError(
                    self.env._(
                        "The GS1 Company Prefix must consist of decimal "
                        "digits only."
                    )
                )
            # Eighteen digits, minus the extension digit and the check digit.
            if len(prefix) > 16:
                raise ValidationError(
                    self.env._(
                        "The GS1 Company Prefix is too long to leave room for "
                        "a serial reference inside an eighteen digit SSCC."
                    )
                )

    @api.constrains("pharma_sscc_extension_digit")
    def _check_sscc_extension_digit(self):
        """Reject an extension digit that is not a single digit."""
        for company in self:
            digit = company.pharma_sscc_extension_digit
            if not digit:
                continue
            if len(digit) != 1 or digit not in string.digits:
                raise ValidationError(
                    self.env._(
                        "The SSCC extension digit must be exactly one decimal "
                        "digit."
                    )
                )

    @api.constrains("pharma_serial_length")
    def _check_serial_length(self):
        """Reject a serial length outside the range permitted by AI (21)."""
        for company in self:
            if not 1 <= company.pharma_serial_length <= 20:
                raise ValidationError(
                    self.env._(
                        "The generated serial number length must lie between "
                        "1 and 20 characters."
                    )
                )

    @api.constrains("pharma_batch_expiry_alert_days")
    def _check_expiry_alert_days(self):
        """Reject a negative alert horizon."""
        for company in self:
            if company.pharma_batch_expiry_alert_days < 0:
                raise ValidationError(
                    self.env._("The alert horizon cannot be negative.")
                )
