#!/usr/bin/env python3
"""Generate static/description/index.html from README.md for ls_* modules.

Without static/description/index.html, Odoo renders the module README with
docutils (reStructuredText) for the Apps screen. A Markdown README then prints
"(ERROR/3)" messages in the install log, which the installation qualification
(check QI-3 of the production manual) reads as errors.

Modules whose manifest has a description, and hand-written index.html files,
are left untouched; files generated by this script carry GENERATED_MARK and
are refreshed on each run.

Usage: pip install markdown; python3 gen_module_descriptions.py [--check]
"""
import ast
import sys
from pathlib import Path

import markdown

ADDONS_DIR = Path("addons")
GENERATED_MARK = "<!-- Generated from README.md by gen_module_descriptions.py; do not edit. -->"


def render(readme):
    body = markdown.markdown(readme.read_text(encoding="utf-8"),
                             extensions=["tables", "fenced_code", "sane_lists"])
    return (f"{GENERATED_MARK}\n"
            f'<section class="oe_container">\n<div class="oe_row oe_spaced">\n'
            f"{body}\n</div>\n</section>\n")


def main():
    check = "--check" in sys.argv
    stale = []
    for module in sorted(ADDONS_DIR.glob("ls_*")):
        readme = module / "README.md"
        target = module / "static" / "description" / "index.html"
        manifest = ast.literal_eval((module / "__manifest__.py").read_text(encoding="utf-8"))
        if not readme.is_file() or manifest.get("description"):
            continue  # Odoo shows the manifest description, not the README
        if target.is_file() and GENERATED_MARK not in target.read_text(encoding="utf-8"):
            continue  # hand-written description
        html = render(readme)
        if target.is_file() and target.read_text(encoding="utf-8") == html:
            continue
        stale.append(module.name)
        if not check:
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_text(html, encoding="utf-8")
    verb = "out of date" if check else "written"
    print(f"{len(stale)} description(s) {verb}: {', '.join(stale) or '-'}")
    return 1 if check and stale else 0


if __name__ == "__main__":
    sys.exit(main())
