# -*- coding: utf-8 -*-
"""Part III (c) — Medical plastics (ls_medical_plastics) and laboratory (ls_lab)."""
from .helpers import module, sop, tr

M_MP = module(
    "mod-mp", "ls_medical_plastics", "Medical plastics", "Plastiques médicaux",
    [
        ("p", "**ls_medical_plastics** supports injection moulding of primary packaging and device components: "
              "components with approved material grades, qualified material grades, moulds (tools) with a cavity "
              "register, shot counters and preventive maintenance by shots and by time, versioned moulding parameter "
              "specifications (process windows) approved by people other than the author, moulding runs with setup, "
              "start-up verification, immutable parameter readings, material consumption, scrap by cavity and "
              "independent review, and a traceability enquiry by lot, material lot, component or tool."),
        ("table", ["Menu", "Content"], [
            ["{{Medical Plastics ▸ Products ▸ Components / Packaging}}", "Components"],
            ["{{Medical Plastics ▸ Tools ▸ Tool Register / Maintenance Records / Due For Maintenance}}", "Tools"],
            ["{{Medical Plastics ▸ Production ▸ Injection Moulding / Moulding Parameters / Parameter Readings}}", "Production"],
            ["{{Medical Plastics ▸ Reports ▸ Moulding Analysis / Traceability Enquiry}}", "Reports"],
            ["{{Medical Plastics ▸ Configuration ▸ Material Grades / Scrap Reasons}}", "Configuration"],
        ]),
        ("table", ["Group", "Main rights"], [
            ["Medical Plastics / Viewer · Operator", "Read; run production, record readings"],
            ["Medical Plastics / Tool Technician", "Tool maintenance"],
            ["Medical Plastics / Process Engineer", "Parameter specifications, run review"],
            ["Medical Plastics / Manager", "Approvals and configuration"],
        ]),
        ("schematic", "shot_counter", "Maintenance triggered by shots or time (illustrative)."),
        ("flow", "mp_run", "Lifecycle of a moulding run."),
    ],
    [
        ("p", "**ls_medical_plastics** outille le moulage par injection d'articles de conditionnement primaire et de "
              "composants de dispositifs : composants avec grades de matière approuvés, grades de matière qualifiés, "
              "moules (outillages) avec registre des empreintes, compteurs de coups et maintenance préventive par coups et "
              "par durée, spécifications de paramètres versionnées (fenêtres de procédé) approuvées par d'autres "
              "personnes que l'auteur, campagnes de moulage avec réglage, vérification de démarrage, relevés de "
              "paramètres immuables, consommation matière, rebuts par empreinte et revue indépendante, et une recherche de "
              "traçabilité par lot, lot matière, composant ou outillage."),
        ("table", ["Menu", "Contenu"], [
            ["{{Medical Plastics ▸ Products ▸ Components / Packaging}}", "Composants"],
            ["{{Medical Plastics ▸ Tools ▸ Tool Register / Maintenance Records / Due For Maintenance}}", "Outillages"],
            ["{{Medical Plastics ▸ Production ▸ Injection Moulding / Moulding Parameters / Parameter Readings}}", "Production"],
            ["{{Medical Plastics ▸ Reports ▸ Moulding Analysis / Traceability Enquiry}}", "Rapports"],
            ["{{Medical Plastics ▸ Configuration ▸ Material Grades / Scrap Reasons}}", "Paramétrage"],
        ]),
        ("table", ["Groupe", "Droits principaux"], [
            ["Medical Plastics / Viewer · Operator", "Lecture ; production, relevés"],
            ["Medical Plastics / Tool Technician", "Maintenance des outillages"],
            ["Medical Plastics / Process Engineer", "Spécifications de paramètres, revue des campagnes"],
            ["Medical Plastics / Manager", "Approbations et paramétrage"],
        ]),
        ("schematic", "shot_counter", "Maintenance déclenchée par nombre de coups ou par durée (illustratif)."),
        ("flow", "mp_run", "Cycle de vie d'une campagne de moulage."),
    ],
)

MP001 = sop(
    "SOP-MP-001", "ls_medical_plastics", "Medical Plastics ▸ Tools ▸ Tool Register",
    flows=[("mp_tool", tr("Lifecycle of a mould.", "Cycle de vie d'un moule."))],
    related=["SOP-MP-002", "SOP-MP-003", "SOP-VAL-002"],
    refs=["ISO-13485", "ISO-15378", "GHTF-PV", "EU-A15"],
    en=dict(
        title="Qualification and commissioning of moulds",
        owner="Tooling / Process Engineering Manager",
        objective="Register each mould with its cavities and the components it produces, qualify it before first production, and place it in service only when qualified with at least one active cavity.",
        scope="Injection moulds, family moulds, inserts, hot runners, core pin sets and fixtures used for GMP components.",
        roles=[("Tool Technician", "Registers the tool and cavity register, records maintenance."),
               ("Process Engineer", "Qualifies the tool (IQ/OQ/PQ as defined by validation)."),
               ("Manager", "Places in service, quarantines, decommissions.")],
        defs=[("Cavity register", "One record per cavity number with marking and status (Active, Blocked, Removed)."),
              ("Requalification interval", "Months after which the tool must be requalified.")],
        steps=[("Register", "In {{Tool Register}} click [[New]]: name, code, type, tool maker, serial number, acquisition date, steel, storage location, default work centre, components produced, cavity count, opening shot count, maintenance intervals (shots, months), requalification interval."),
               ("Cavities", "Check the cavity register (number and marking of each cavity)."),
               ("Qualify", "Perform the tool qualification (dimensional study per cavity, process capability) under SOP-VAL-002; record the qualification date and click [[Qualify]]."),
               ("Place in service", "Click [[Place In Service]] (at least one active cavity required)."),
               ("Quarantine / decommission", "Use [[Quarantine]] when the tool is suspect and [[Decommission]] at end of life (no run in progress)."),
               ("Requalify", "Monitor *Requalification Due*; requalify after major repair or modification.")],
        controls=["Qualification and placing in service require a qualification date; transitions are allowed only from the proper states; a tool without active cavity cannot be placed in service.",
                  "The cavity count cannot be reduced below a registered cavity number (parts remain traceable to that cavity).",
                  "A tool with runs in progress cannot be sent to maintenance, quarantined or decommissioned."],
        good=["Engrave cavity numbers on the parts so that scrap and complaints can be traced to the cavity.",
              "Store tools with their last-shot samples."],
        pitfalls=["Moving a tool to another press without checking the specification work centre restriction."],
        records=["Tool record, cavity register, qualification evidence"],
        kpis=["Tools in service past requalification (target 0)"],
        example="**Case.** Mould T-032 (8 cavities) for syringe plunger SP-5: registered with maintenance interval 250 000 shots or 6 months; OQ/PQ done with a dimensional study of all 8 cavities; qualified on 12 May; placed in service.",
    ),
    fr=dict(
        title="Qualification et mise en service des moules",
        owner="Responsable outillage / ingénierie procédé",
        objective="Enregistrer chaque moule avec ses empreintes et les composants qu'il produit, le qualifier avant la première production, et ne le mettre en service que qualifié avec au moins une empreinte active.",
        scope="Moules d'injection, moules famille, inserts, canaux chauds, jeux de broches et gabarits utilisés pour des composants BPF.",
        roles=[("Tool Technician", "Enregistre l'outillage et le registre des empreintes, consigne la maintenance."),
               ("Process Engineer", "Qualifie l'outillage (QI/QO/QP selon la validation)."),
               ("Manager", "Met en service, met en quarantaine, met au rebut.")],
        defs=[("Registre des empreintes", "Un enregistrement par numéro d'empreinte avec marquage et statut (Active, Blocked, Removed)."),
              ("Intervalle de requalification", "Mois après lesquels l'outillage doit être requalifié.")],
        steps=[("Enregistrer", "Dans {{Tool Register}}, cliquer sur [[New]] : nom, code, type, mouliste, numéro de série, date d'acquisition, acier, lieu de stockage, poste de travail par défaut, composants produits, nombre d'empreintes, compteur initial, intervalles de maintenance (coups, mois), intervalle de requalification."),
               ("Empreintes", "Vérifier le registre des empreintes (numéro et marquage de chacune)."),
               ("Qualifier", "Réaliser la qualification (étude dimensionnelle par empreinte, capabilité) selon la SOP-VAL-002 ; saisir la date de qualification et cliquer sur [[Qualify]]."),
               ("Mettre en service", "Cliquer sur [[Place In Service]] (au moins une empreinte active exigée)."),
               ("Quarantaine / rebut", "Utiliser [[Quarantine]] si l'outillage est suspect et [[Decommission]] en fin de vie (aucune campagne en cours)."),
               ("Requalifier", "Suivre *Requalification Due* ; requalifier après réparation ou modification majeure.")],
        controls=["Qualification et mise en service exigent une date de qualification ; les transitions ne sont permises que depuis les bons états ; un outillage sans empreinte active ne se met pas en service.",
                  "Le nombre d'empreintes ne peut descendre sous un numéro enregistré (les pièces restent traçables à cette empreinte).",
                  "Un outillage avec des campagnes en cours ne peut aller en maintenance, en quarantaine ni au rebut."],
        good=["Graver le numéro d'empreinte sur les pièces pour tracer rebuts et réclamations jusqu'à l'empreinte.",
              "Stocker les outillages avec les échantillons de dernière injection."],
        pitfalls=["Déplacer un outillage sur une autre presse sans vérifier la restriction de poste de la spécification."],
        records=["Fiche outillage, registre des empreintes, preuves de qualification"],
        kpis=["Outillages en service au-delà de la requalification (cible 0)"],
        example="**Cas.** Moule T-032 (8 empreintes) pour le piston de seringue SP-5 : enregistré avec maintenance à 250 000 coups ou 6 mois ; QO/QP réalisées avec étude dimensionnelle des 8 empreintes ; qualifié le 12 mai ; mis en service.",
    ),
)

MP002 = sop(
    "SOP-MP-002", "ls_medical_plastics", "Medical Plastics ▸ Tools ▸ Due For Maintenance / Maintenance Records",
    flows=[("mp_maint", tr("Lifecycle of a maintenance event.", "Cycle de vie d'une intervention de maintenance."))],
    schematics=[("shot_counter", tr("Shots since last maintenance against the interval.", "Coups depuis la dernière maintenance par rapport à l'intervalle."))],
    related=["SOP-MP-001", "SOP-GEN-003"],
    refs=["EU-GMP-3", "ISO-13485"],
    en=dict(
        title="Preventive maintenance of moulds (by shot count and by time) and cavity blocking",
        owner="Tooling Manager",
        objective="Maintain moulds before wear affects parts, by whichever of the shot-count and time intervals comes first, and block faulty cavities with a recorded reason so that production continues on good cavities only.",
        scope="All moulds in service.",
        roles=[("Tool Technician", "Performs maintenance and records findings and actions."),
               ("Process Engineer", "Decides on cavity blocking and requalification."),
               ("Operator", "Reports defects by cavity.")],
        defs=[("Maintenance status", "OK, Due Soon, Overdue, from shots since last maintenance and months since last maintenance."),
              ("Resets maintenance baseline", "Flag on a maintenance event that resets the shot counter baseline.")],
        steps=[("Monitor", "Daily, open {{Tools ▸ Due For Maintenance}}."),
               ("Plan", "Create a maintenance record: tool, type (preventive, corrective, cleaning, repair, modification, requalification), planned date."),
               ("Stop the tool", "When runs are finished, click [[Send To Maintenance]] on the tool."),
               ("Perform", "Click [[Start]] on the maintenance; record shot count at intervention, performer or provider, findings, actions taken, cavities affected, *Requalification Required*, *Resets Maintenance Baseline*; click [[Complete]]."),
               ("Return to service", "Click [[Return To Service]] on the tool (wizard); requalify first when required."),
               ("Block a cavity", "When a cavity produces defects, click [[Block]] on the cavity with a reason; [[Unblock]] after repair and verification.")],
        controls=["A maintenance cannot be completed without recording the actions taken; only draft maintenance can start; completed maintenance cannot be cancelled or deleted (tool history).",
                  "A cavity cannot be blocked or removed without a recorded reason; only active cavities can be blocked.",
                  "A tool with runs in progress cannot be sent to maintenance."],
        good=["Keep the last parts of the run before maintenance and the first parts after it for comparison.",
              "Trend corrective maintenance per tool to adjust the preventive interval."],
        pitfalls=["Blocking a cavity physically without recording it — parts counts and traceability become wrong."],
        records=["Maintenance records", "Cavity status history"],
        kpis=["Tools overdue for maintenance (target 0)", "Corrective / preventive ratio"],
        example="**Case.** T-032 reaches 236 000 shots (Due Soon). After the current run the technician sends it to maintenance, cleans vents and replaces ejector pins, records the shot count, ticks *Resets Maintenance Baseline*, completes. Cavity 6 showed flash: the engineer blocks it with reason *flash on parting line*; production continues on 7 cavities until repair.",
    ),
    fr=dict(
        title="Maintenance préventive des moules (par nombre de coups et par durée) et blocage d'empreintes",
        owner="Responsable outillage",
        objective="Entretenir les moules avant que l'usure n'affecte les pièces, selon le premier atteint des intervalles en coups et en durée, et bloquer les empreintes défectueuses avec un motif enregistré pour ne produire que sur les bonnes.",
        scope="Tous les moules en service.",
        roles=[("Tool Technician", "Réalise la maintenance et consigne constats et actions."),
               ("Process Engineer", "Décide du blocage d'empreintes et de la requalification."),
               ("Opérateur", "Signale les défauts par empreinte.")],
        defs=[("Statut de maintenance", "OK, Due Soon, Overdue, d'après les coups et les mois depuis la dernière maintenance."),
              ("Réinitialisation du compteur", "Indicateur d'une intervention qui remet à zéro la base du compteur de coups.")],
        steps=[("Surveiller", "Chaque jour, ouvrir {{Tools ▸ Due For Maintenance}}."),
               ("Planifier", "Créer une intervention : outillage, type (préventive, corrective, nettoyage, réparation, modification, requalification), date prévue."),
               ("Arrêter l'outillage", "Une fois les campagnes terminées, cliquer sur [[Send To Maintenance]] sur l'outillage."),
               ("Réaliser", "Cliquer sur [[Start]] ; saisir le compteur à l'intervention, l'intervenant ou le prestataire, les constats, les actions, les empreintes concernées, *Requalification Required*, *Resets Maintenance Baseline* ; cliquer sur [[Complete]]."),
               ("Remettre en service", "Cliquer sur [[Return To Service]] sur l'outillage (assistant) ; requalifier d'abord si nécessaire."),
               ("Bloquer une empreinte", "Si une empreinte produit des défauts, cliquer sur [[Block]] avec motif ; [[Unblock]] après réparation et vérification.")],
        controls=["Une intervention ne se termine pas sans les actions réalisées ; seul un brouillon démarre ; une intervention terminée ne s'annule ni ne se supprime (historique).",
                  "Une empreinte ne se bloque ni ne se retire sans motif ; seules les empreintes actives se bloquent.",
                  "Un outillage avec des campagnes en cours ne peut aller en maintenance."],
        good=["Conserver les dernières pièces avant maintenance et les premières après, pour comparaison.",
              "Suivre la maintenance corrective par outillage pour ajuster l'intervalle préventif."],
        pitfalls=["Bloquer physiquement une empreinte sans l'enregistrer — les comptages et la traçabilité deviennent faux."],
        records=["Interventions de maintenance", "Historique d'état des empreintes"],
        kpis=["Outillages en retard de maintenance (cible 0)", "Ratio corrective / préventive"],
        example="**Cas.** T-032 atteint 236 000 coups (Due Soon). Après la campagne en cours, le technicien l'envoie en maintenance, nettoie les évents et remplace les éjecteurs, saisit le compteur, coche *Resets Maintenance Baseline*, termine. L'empreinte 6 présentait des bavures : l'ingénieur la bloque avec le motif *bavure au plan de joint* ; la production continue sur 7 empreintes jusqu'à la réparation.",
    ),
)

MP003 = sop(
    "SOP-MP-003", "ls_medical_plastics", "Medical Plastics ▸ Production ▸ Moulding Parameters",
    flows=[("mp_param", tr("Lifecycle of a parameter specification.", "Cycle de vie d'une spécification de paramètres."))],
    related=["SOP-MP-004", "SOP-QA-030", "SOP-VAL-006"],
    refs=["GHTF-PV", "ISO-13485", "EU-A15"],
    en=dict(
        title="Process windows: drafting, review and approval",
        owner="Process Engineering Manager",
        objective="Define for each component/tool combination the validated process window (parameters with target, minimum and maximum, critical parameters and monitoring frequency), approved through author–reviewer–approver separation.",
        scope="All moulding parameter specifications used in production.",
        roles=[("Author (Process Engineer)", "Writes the specification from process validation data."),
               ("Reviewer", "Reviews (not the author)."),
               ("Approver", "Approves (neither author nor reviewer).")],
        defs=[("Critical parameter", "Parameter whose deviation may affect quality; recording is mandatory and out-of-tolerance at start-up blocks the run."),
              ("Monitoring frequency", "At setup only, at start-up verification, hourly, once per shift, once per lot, continuous.")],
        steps=[("Create", "In {{Moulding Parameters}} click [[New]]: component, tool, work centre (optional restriction), version, effective from, periodic review interval; for versions after the first, the reason for change."),
               ("Add parameters", "For each parameter: name, code, unit, value type (numeric or qualitative), target, minimum, maximum (or expected value), critical, monitoring frequency, recording required."),
               ("Submit", "Click [[Submit For Review]]."),
               ("Review", "The reviewer clicks [[Record Review]] (or [[Return To Draft]])."),
               ("Approve", "The approver clicks [[Approve]]; the previous approved version is superseded."),
               ("Change", "Use [[New Version]] under change control; [[Set Obsolete]] when the combination is no longer produced (no run in progress).")],
        controls=["The tool must be declared as producing the component; one approved specification per component and tool — supersede before approving another.",
                  "A specification needs at least one parameter; later versions need a reason for change.",
                  "Author ≠ reviewer ≠ approver; approval requires review.",
                  "Min ≤ target ≤ max; qualitative parameters need an expected value; critical parameters must have recording enabled.",
                  "Approved specifications cannot be cancelled (make obsolete); a specification used by runs in progress cannot be made obsolete; non-draft or referenced specifications cannot be deleted."],
        good=["Derive windows from the process validation (DoE, OQ/PQ), not from habits.",
              "Keep the number of critical parameters small and meaningful."],
        pitfalls=["Widening a window after a failed run without change control."],
        records=["Approved specifications with versions"],
        kpis=["Specifications past periodic review"],
        example="**Case.** SP-5 on T-032, v2: melt temperature 230 °C (220–240, critical, hourly), injection pressure 850 bar (800–900, critical, continuous), cooling time 8 s (7–9), visual aspect *no flash* (qualitative, once per lot). Author and reviewer from process engineering, approver from QA; v1 superseded.",
    ),
    fr=dict(
        title="Fenêtres de procédé : rédaction, revue et approbation",
        owner="Responsable ingénierie procédé",
        objective="Définir pour chaque couple composant/outillage la fenêtre de procédé validée (paramètres avec cible, minimum et maximum, paramètres critiques et fréquence de surveillance), approuvée avec séparation auteur–vérificateur–approbateur.",
        scope="Toutes les spécifications de paramètres de moulage utilisées en production.",
        roles=[("Auteur (Process Engineer)", "Rédige la spécification à partir des données de validation."),
               ("Vérificateur", "Revoit (pas l'auteur)."),
               ("Approbateur", "Approuve (ni l'auteur ni le vérificateur).")],
        defs=[("Paramètre critique", "Paramètre dont l'écart peut affecter la qualité ; enregistrement obligatoire et un hors tolérance au démarrage bloque la campagne."),
              ("Fréquence de surveillance", "Au réglage seulement, à la vérification de démarrage, horaire, par poste, par lot, en continu.")],
        steps=[("Créer", "Dans {{Moulding Parameters}}, cliquer sur [[New]] : composant, outillage, poste de travail (restriction facultative), version, date d'effet, intervalle de revue ; pour les versions suivantes, le motif de changement."),
               ("Ajouter les paramètres", "Pour chacun : nom, code, unité, type (numérique ou qualitatif), cible, minimum, maximum (ou valeur attendue), critique, fréquence, enregistrement requis."),
               ("Soumettre", "Cliquer sur [[Submit For Review]]."),
               ("Revoir", "Le vérificateur clique sur [[Record Review]] (ou [[Return To Draft]])."),
               ("Approuver", "L'approbateur clique sur [[Approve]] ; la version approuvée précédente est remplacée."),
               ("Modifier", "Utiliser [[New Version]] sous maîtrise des changements ; [[Set Obsolete]] quand le couple n'est plus produit (aucune campagne en cours).")],
        controls=["L'outillage doit être déclaré comme produisant le composant ; une seule spécification approuvée par composant et outillage — remplacer avant d'en approuver une autre.",
                  "Une spécification exige au moins un paramètre ; les versions suivantes exigent un motif.",
                  "Auteur ≠ vérificateur ≠ approbateur ; l'approbation exige la revue.",
                  "Min ≤ cible ≤ max ; un paramètre qualitatif exige une valeur attendue ; un paramètre critique doit avoir l'enregistrement activé.",
                  "Une spécification approuvée ne s'annule pas (la rendre obsolète) ; utilisée par une campagne en cours, elle ne devient pas obsolète ; non brouillon ou référencée, elle ne se supprime pas."],
        good=["Déduire les fenêtres de la validation du procédé (plans d'expériences, QO/QP), pas des habitudes.",
              "Garder peu de paramètres critiques, mais pertinents."],
        pitfalls=["Élargir une fenêtre après une campagne ratée sans maîtrise des changements."],
        records=["Spécifications approuvées et versions"],
        kpis=["Spécifications en retard de revue périodique"],
        example="**Cas.** SP-5 sur T-032, v2 : température matière 230 °C (220–240, critique, horaire), pression d'injection 850 bar (800–900, critique, continu), temps de refroidissement 8 s (7–9), aspect *sans bavure* (qualitatif, par lot). Auteur et vérificateur de l'ingénierie procédé, approbateur de l'AQ ; v1 remplacée.",
    ),
)

MP004 = sop(
    "SOP-MP-004", "ls_medical_plastics", "Medical Plastics ▸ Production ▸ Injection Moulding",
    flows=[("mp_run", tr("Lifecycle of a moulding run.", "Cycle de vie d'une campagne de moulage."))],
    related=["SOP-MP-003", "SOP-MP-005", "SOP-MP-006", "SOP-QA-020"],
    refs=["ISO-13485", "ISO-15378", "GHTF-PV"],
    en=dict(
        title="Start-up, operation and closure of a moulding run",
        owner="Moulding Production Manager",
        objective="Run production only with a released component, a tool in service and an approved specification; verify start-up parameters before running; record readings, material and scrap; have the run reviewed by someone other than its operator or setter before closure.",
        scope="All injection moulding runs of GMP components.",
        roles=[("Setter", "Sets up the tool and press."),
               ("Operator", "Runs production, records readings and scrap."),
               ("Reviewer (Process Engineer / QA)", "Reviews the run; cannot be the operator or setter.")],
        defs=[("Start-up verification", "Readings of every parameter required at start-up, within tolerance for critical ones, before the run can start."),
              ("Shot counter", "Tool counter at start and end; shots = end − start.")],
        steps=[("Create the run", "In {{Injection Moulding}} click [[New]]: component, tool, work centre, manufacturing order, produced lot, operator, shift, shot counter at start. The approved specification is proposed."),
               ("Setup", "Click [[Start Setup]]; the setter records setup readings ([[Record Readings]]); click [[Setup Complete]]."),
               ("Start-up verification", "Record start-up verification readings for the required parameters and the material consumption (grade, lot, quantity); click [[Confirm Start-up and Run]]."),
               ("Run", "Record in-process readings at the specified frequency; record scrap by reason and cavity; block cavities if needed (SOP-MP-002)."),
               ("Complete", "Record the end shot counter, quantities produced and rejected; click [[Complete Run]]."),
               ("Deviations", "If readings were out of tolerance, open a deviation (SOP-QA-020) and record its reference."),
               ("Review", "The reviewer (not operator nor setter) clicks [[Review]], or [[Return For Correction]] with a comment."),
               ("Close", "Click [[Close Run]].")],
        controls=["Production requires a released component, a tool in service declared for the component, and an approved specification for this component/tool (and work centre if restricted).",
                  "Start-up verification must be complete; critical parameters out of tolerance at start-up block the run; material consumption must be recorded before running.",
                  "Completion requires the end shot counter (≥ start); rejected ≤ produced.",
                  "Review requires completion, a reviewer who is neither operator nor setter, and a deviation reference if readings were out of tolerance; closure requires review.",
                  "Readings cannot be captured outside setup/start-up/running; closed runs are frozen; runs past draft cannot be deleted; cancellation requires a reason."],
        good=["Record readings at the time they are taken — the timestamp is part of the evidence.",
              "Quarantine parts produced between the last good reading and an out-of-tolerance one."],
        pitfalls=["Starting production \"while waiting\" for the start-up verification."],
        records=["Run with readings, material, scrap, review"],
        kpis=["Reject rate per run", "Runs with out-of-tolerance readings", "Runs returned for correction"],
        example="**Case.** Run MR-2027-118: SP-5 on T-032 (7 active cavities), lot SP5-2711. Setup and start-up readings within limits; material PP grade lot R-5531 recorded; 7 in-process readings; injection pressure once at 905 bar (max 900) for 10 min → parts of that period quarantined, deviation DEV/2027/00012 recorded. Completed: 96 600 shots, 676 200 parts, 1 900 rejects. Reviewed by the process engineer and closed.",
    ),
    fr=dict(
        title="Démarrage, conduite et clôture d'une campagne de moulage",
        owner="Responsable production moulage",
        objective="Ne produire qu'avec un composant libéré, un outillage en service et une spécification approuvée ; vérifier les paramètres de démarrage avant de produire ; enregistrer relevés, matière et rebuts ; faire revoir la campagne par une autre personne que son opérateur ou régleur avant clôture.",
        scope="Toutes les campagnes de moulage par injection de composants BPF.",
        roles=[("Régleur", "Règle l'outillage et la presse."),
               ("Opérateur", "Produit, saisit relevés et rebuts."),
               ("Vérificateur (Process Engineer / AQ)", "Revoit la campagne ; ne peut être ni l'opérateur ni le régleur.")],
        defs=[("Vérification de démarrage", "Relevés de chaque paramètre exigé au démarrage, dans la tolérance pour les critiques, avant de pouvoir produire."),
              ("Compteur de coups", "Compteur de l'outillage au début et à la fin ; coups = fin − début.")],
        steps=[("Créer la campagne", "Dans {{Injection Moulding}}, cliquer sur [[New]] : composant, outillage, poste, ordre de fabrication, lot produit, opérateur, poste horaire, compteur au début. La spécification approuvée est proposée."),
               ("Réglage", "Cliquer sur [[Start Setup]] ; le régleur saisit les relevés de réglage ([[Record Readings]]) ; cliquer sur [[Setup Complete]]."),
               ("Vérification de démarrage", "Saisir les relevés de vérification pour les paramètres exigés et la consommation matière (grade, lot, quantité) ; cliquer sur [[Confirm Start-up and Run]]."),
               ("Produire", "Saisir les relevés en cours selon la fréquence ; enregistrer les rebuts par motif et empreinte ; bloquer des empreintes si besoin (SOP-MP-002)."),
               ("Terminer", "Saisir le compteur de fin, les quantités produites et rejetées ; cliquer sur [[Complete Run]]."),
               ("Déviations", "En cas de relevés hors tolérance, ouvrir une déviation (SOP-QA-020) et saisir sa référence."),
               ("Revoir", "Le vérificateur (ni opérateur ni régleur) clique sur [[Review]], ou [[Return For Correction]] avec commentaire."),
               ("Clore", "Cliquer sur [[Close Run]].")],
        controls=["La production exige un composant libéré, un outillage en service déclaré pour le composant et une spécification approuvée pour ce couple (et ce poste si restreinte).",
                  "La vérification de démarrage doit être complète ; un paramètre critique hors tolérance au démarrage bloque la campagne ; la consommation matière doit être saisie avant de produire.",
                  "La fin exige le compteur de fin (≥ début) ; rejetés ≤ produits.",
                  "La revue exige la fin de campagne, un vérificateur ni opérateur ni régleur, et une référence de déviation en cas de relevés hors tolérance ; la clôture exige la revue.",
                  "Pas de relevé hors réglage/démarrage/production ; une campagne close est figée ; au-delà du brouillon elle ne se supprime pas ; l'annulation exige un motif."],
        good=["Saisir les relevés au moment où ils sont pris — l'horodatage fait partie de la preuve.",
              "Mettre en quarantaine les pièces produites entre le dernier relevé conforme et un relevé hors tolérance."],
        pitfalls=["Démarrer la production « en attendant » la vérification de démarrage."],
        records=["Campagne avec relevés, matière, rebuts, revue"],
        kpis=["Taux de rebut par campagne", "Campagnes avec relevés hors tolérance", "Campagnes renvoyées pour correction"],
        example="**Cas.** Campagne MR-2027-118 : SP-5 sur T-032 (7 empreintes actives), lot SP5-2711. Relevés de réglage et de démarrage conformes ; matière PP lot R-5531 saisie ; 7 relevés en cours ; pression d'injection une fois à 905 bar (max 900) pendant 10 min → pièces de la période en quarantaine, déviation DEV/2027/00012 saisie. Terminée : 96 600 coups, 676 200 pièces, 1 900 rebuts. Revue par l'ingénieur procédé et close.",
    ),
)

MP005 = sop(
    "SOP-MP-005", "ls_medical_plastics", "Medical Plastics ▸ Production ▸ Parameter Readings",
    related=["SOP-MP-004", "SOP-DI-002"],
    refs=["PICS-DI", "MHRA-DI", "EU-A11"],
    en=dict(
        title="Correction of parameter readings (without altering the original value)",
        owner="Moulding Production Manager with QA",
        objective="Correct an erroneous parameter reading by a new, justified reading that supersedes the original, so that the original value, the correction and its reason all remain visible.",
        scope="All parameter readings of moulding runs.",
        roles=[("Operator / setter", "Records the correcting reading with its reason."),
               ("Reviewer", "Checks corrections at run review.")],
        defs=[("Superseding reading", "New reading linked to the reading it corrects (same run, same parameter), with a mandatory reason; the original is marked superseded.")],
        steps=[("Detect", "An erroneous reading is noticed (typing error, wrong instrument, wrong parameter)."),
               ("Record the correction", "Use [[Record Readings]] on the run, select the parameter, enter the correct value, select the reading it supersedes and write the reason for correction."),
               ("Never edit", "Do not try to modify or delete the original reading — the system refuses it."),
               ("Review", "At run review, check each correction: reason plausible, time close to the original, same person or supervisor.")],
        controls=["Readings cannot be modified or deleted.",
                  "A correcting reading must record a reason, belong to the same run and address the same parameter as the reading it supersedes.",
                  "Qualitative parameters require an observed value; no reading on a run that is not open for readings."],
        good=["Explain the correction factually (\"typed 285 instead of 258, see press display photo\")."],
        pitfalls=["Using corrections to bring out-of-tolerance values back into range without evidence — a data integrity breach."],
        records=["Original and superseding readings with reasons"],
        kpis=["Corrections per 100 readings", "Corrections without evidence found at review"],
        example="**Case.** The operator types a cooling time of 80 s instead of 8.0 s. Two minutes later she records a new reading 8.0 s superseding the first, reason *\"decimal point omitted — press display shows 8.0 s\"*. At review the engineer sees both readings and accepts the correction.",
    ),
    fr=dict(
        title="Correction des relevés de paramètres (sans modifier la valeur d'origine)",
        owner="Responsable production moulage avec l'AQ",
        objective="Corriger un relevé erroné par un nouveau relevé justifié qui remplace l'original, de sorte que la valeur d'origine, la correction et son motif restent visibles.",
        scope="Tous les relevés de paramètres des campagnes de moulage.",
        roles=[("Opérateur / régleur", "Saisit le relevé correctif avec son motif."),
               ("Vérificateur", "Contrôle les corrections lors de la revue de campagne.")],
        defs=[("Relevé correctif", "Nouveau relevé lié au relevé qu'il corrige (même campagne, même paramètre), avec motif obligatoire ; l'original est marqué remplacé.")],
        steps=[("Détecter", "Un relevé erroné est constaté (faute de frappe, mauvais instrument, mauvais paramètre)."),
               ("Saisir la correction", "Utiliser [[Record Readings]] sur la campagne, choisir le paramètre, saisir la bonne valeur, sélectionner le relevé remplacé et rédiger le motif."),
               ("Ne jamais modifier", "Ne pas tenter de modifier ou supprimer le relevé d'origine — le système le refuse."),
               ("Revoir", "À la revue, contrôler chaque correction : motif plausible, heure proche de l'original, même personne ou encadrant.")],
        controls=["Les relevés ne se modifient ni ne se suppriment.",
                  "Un relevé correctif exige un motif, appartient à la même campagne et porte sur le même paramètre que le relevé remplacé.",
                  "Un paramètre qualitatif exige une valeur observée ; pas de relevé sur une campagne fermée aux relevés."],
        good=["Expliquer la correction factuellement (« tapé 285 au lieu de 258, voir photo de l'afficheur »)."],
        pitfalls=["Utiliser les corrections pour ramener des valeurs hors tolérance dans la fenêtre sans preuve — atteinte à l'intégrité des données."],
        records=["Relevés d'origine et correctifs avec motifs"],
        kpis=["Corrections pour 100 relevés", "Corrections sans preuve trouvées en revue"],
        example="**Cas.** L'opératrice saisit un temps de refroidissement de 80 s au lieu de 8,0 s. Deux minutes plus tard, elle saisit un relevé 8,0 s remplaçant le premier, motif *« virgule oubliée — l'afficheur indique 8,0 s »*. À la revue, l'ingénieur voit les deux relevés et accepte la correction.",
    ),
)

MP006 = sop(
    "SOP-MP-006", "ls_medical_plastics", "Medical Plastics ▸ Configuration ▸ Material Grades · Reports ▸ Traceability Enquiry",
    related=["SOP-MP-004", "SOP-QA-070", "SOP-QA-081"],
    refs=["ISO-13485", "ISO-15378", "ISO-10993"],
    en=dict(
        title="Material traceability",
        owner="Moulding Quality Manager",
        objective="Use only qualified material grades approved for each component, record the material lots consumed by each run, and be able to trace forward (material lot → parts) and backward (part lot → material, tool, cavity, run) within minutes.",
        scope="All resins, masterbatches and colorants used for GMP components.",
        roles=[("Quality / Process Engineer", "Qualify material grades and approve them for components."),
               ("Operators", "Record material lots at start-up and at each change."),
               ("Quality", "Performs traceability enquiries for complaints and recalls.")],
        defs=[("Qualification status", "Draft, Under Evaluation, Qualified, Conditionally Qualified (conditions recorded), Rejected, Obsolete."),
              ("Direct drug contact", "Grade used for parts in contact with the drug; a lot reference is mandatory at consumption.")],
        steps=[("Qualify the grade", "In {{Material Grades}}: polymer type, resin manufacturer, approved suppliers, compendial references, master file, change notification agreement, properties; [[Start Evaluation]], then [[Qualify]] (or [[Qualify Conditionally]] with conditions) with the qualification date and requalification due date."),
               ("Approve for components", "On the component list the approved material grades and the primary grade; release the component ([[Release]])."),
               ("Record consumption", "On each run, record material grade, lot and quantity before start-up and at every lot change."),
               ("Trace", "Use {{Reports ▸ Traceability Enquiry}} by produced lot, material lot, component and period, or tool and period; [[Open Results]] or [[Print Records]]."),
               ("Change of material", "A resin change (grade, supplier, site) goes through change control and requalification.")],
        controls=["A grade cannot be qualified without a qualification date; conditional qualification requires recorded conditions; requalification date after qualification.",
                  "Only qualified grades approved for the component can be consumed; a direct-drug-contact grade requires a lot reference; the lot must belong to the product.",
                  "A component cannot be released without at least one approved grade; the primary grade must be among the approved grades; sterile components need a sterilisation method."],
        good=["Obtain a change notification agreement from resin suppliers.",
              "Test the traceability enquiry during mock recalls (SOP-QA-083)."],
        pitfalls=["Mixing two resin lots in the dryer without recording both."],
        records=["Material grades with qualification", "Material consumption per run", "Traceability enquiry outputs"],
        kpis=["Time to answer a traceability enquiry", "Runs without material record (target 0)"],
        example="**Case.** A resin supplier notifies a contamination risk on lot R-5531. The quality manager runs the enquiry *By Material Lot*: 3 runs, lots SP5-2711 to SP5-2713, all on T-032. The lots are blocked and a deviation opened within 1 hour.",
    ),
    fr=dict(
        title="Traçabilité matière",
        owner="Responsable qualité moulage",
        objective="N'utiliser que des grades de matière qualifiés approuvés pour chaque composant, enregistrer les lots consommés par chaque campagne, et pouvoir tracer en aval (lot matière → pièces) et en amont (lot de pièces → matière, outillage, empreinte, campagne) en quelques minutes.",
        scope="Toutes les résines, mélanges-maîtres et colorants utilisés pour des composants BPF.",
        roles=[("Qualité / Process Engineer", "Qualifient les grades et les approuvent pour les composants."),
               ("Opérateurs", "Saisissent les lots matière au démarrage et à chaque changement."),
               ("Qualité", "Réalise les recherches de traçabilité pour réclamations et rappels.")],
        defs=[("Statut de qualification", "Draft, Under Evaluation, Qualified, Conditionally Qualified (conditions consignées), Rejected, Obsolete."),
              ("Contact direct avec le médicament", "Grade utilisé pour des pièces en contact avec le médicament ; la référence de lot est obligatoire à la consommation.")],
        steps=[("Qualifier le grade", "Dans {{Material Grades}} : type de polymère, fabricant, fournisseurs approuvés, références pharmacopée, master file, accord de notification des changements, propriétés ; [[Start Evaluation]], puis [[Qualify]] (ou [[Qualify Conditionally]] avec conditions) avec la date de qualification et la date de requalification."),
               ("Approuver pour les composants", "Sur le composant, lister les grades approuvés et le grade principal ; libérer le composant ([[Release]])."),
               ("Saisir la consommation", "Sur chaque campagne, saisir grade, lot et quantité avant le démarrage et à chaque changement de lot."),
               ("Tracer", "Utiliser {{Reports ▸ Traceability Enquiry}} par lot produit, lot matière, composant et période, ou outillage et période ; [[Open Results]] ou [[Print Records]]."),
               ("Changement de matière", "Tout changement de résine (grade, fournisseur, site) passe par la maîtrise des changements et une requalification.")],
        controls=["Un grade ne se qualifie pas sans date de qualification ; une qualification conditionnelle exige des conditions ; requalification postérieure à la qualification.",
                  "Seuls les grades qualifiés et approuvés pour le composant peuvent être consommés ; un grade en contact direct exige une référence de lot ; le lot doit appartenir au produit.",
                  "Un composant ne se libère pas sans au moins un grade approuvé ; le grade principal doit figurer parmi les approuvés ; un composant stérile exige une méthode de stérilisation."],
        good=["Obtenir des fournisseurs de résine un accord de notification des changements.",
              "Tester la recherche de traçabilité lors des rappels simulés (SOP-QA-083)."],
        pitfalls=["Mélanger deux lots de résine dans le sécheur sans les enregistrer tous les deux."],
        records=["Grades et qualification", "Consommations par campagne", "Résultats de recherches de traçabilité"],
        kpis=["Délai de réponse à une recherche de traçabilité", "Campagnes sans consommation matière (cible 0)"],
        example="**Cas.** Un fournisseur de résine signale un risque de contamination sur le lot R-5531. Le responsable qualité lance la recherche *By Material Lot* : 3 campagnes, lots SP5-2711 à SP5-2713, tous sur T-032. Les lots sont bloqués et une déviation ouverte en 1 heure.",
    ),
)

M_LAB = module(
    "mod-lab", "ls_lab", "Laboratory", "Laboratoire",
    [
        ("p", "**ls_lab** supports the quality control laboratory: controlled test methods and product specifications "
              "(draft, review, approval, versions), samples from receipt to reporting, results with automatic "
              "evaluation and second-person review, OOS/OOT investigations in two phases with retest and resample "
              "authorisation, stability studies with time points and pull samples, and certificates of analysis. "
              "Approvals and certificate issue record a *signature intent* (user, time, meaning), which the module "
              "states is **not** a 21 CFR Part 11 electronic signature. Lots held by an open investigation cannot be "
              "delivered."),
        ("table", ["Menu", "Content"], [
            ["{{Laboratory ▸ Tests ▸ Test Methods / Test Results}}", "Methods and results"],
            ["{{Laboratory ▸ Specifications ▸ Product Specifications / OOS / OOT}}", "Specifications and investigations"],
            ["{{Laboratory ▸ Samples ▸ Sample Receipt / Sample Register}}", "Samples"],
            ["{{Laboratory ▸ Stability ▸ Stability Studies / Time Points / Stability Samples}}", "Stability"],
            ["{{Laboratory ▸ Reports ▸ Certificates of Analysis / Test Result Analysis}}", "Reporting"],
        ]),
        ("table", ["Group", "Main rights"], [
            ["Laboratory Viewer · Analyst", "Read; perform tests and record results"],
            ["Laboratory Reviewer", "Review results and samples (not their own)"],
            ["Laboratory Manager", "Approve methods, specifications, samples; close investigations"],
        ]),
        ("schematic", "oos", "OOS investigation phases."),
        ("flow", "lab_sample", "Lifecycle of a laboratory sample."),
    ],
    [
        ("p", "**ls_lab** outille le laboratoire de contrôle qualité : méthodes d'analyse et spécifications produit "
              "maîtrisées (brouillon, revue, approbation, versions), échantillons de la réception au rapport, résultats "
              "évalués automatiquement et revus par une seconde personne, enquêtes OOS/OOT en deux phases avec "
              "autorisation de nouvel essai ou de nouvel échantillonnage, études de stabilité avec points et "
              "échantillons, et certificats d'analyse. Les approbations et l'émission des certificats enregistrent une "
              "*intention de signature* (utilisateur, heure, signification), dont le module précise qu'elle n'est **pas** "
              "une signature électronique 21 CFR Part 11. Les lots retenus par une enquête ouverte ne peuvent être livrés."),
        ("table", ["Menu", "Contenu"], [
            ["{{Laboratory ▸ Tests ▸ Test Methods / Test Results}}", "Méthodes et résultats"],
            ["{{Laboratory ▸ Specifications ▸ Product Specifications / OOS / OOT}}", "Spécifications et enquêtes"],
            ["{{Laboratory ▸ Samples ▸ Sample Receipt / Sample Register}}", "Échantillons"],
            ["{{Laboratory ▸ Stability ▸ Stability Studies / Time Points / Stability Samples}}", "Stabilité"],
            ["{{Laboratory ▸ Reports ▸ Certificates of Analysis / Test Result Analysis}}", "Rapports"],
        ]),
        ("table", ["Groupe", "Droits principaux"], [
            ["Laboratory Viewer · Analyst", "Lecture ; réalisation des essais et saisie"],
            ["Laboratory Reviewer", "Revue des résultats et échantillons (pas les siens)"],
            ["Laboratory Manager", "Approbation des méthodes, spécifications, échantillons ; clôture des enquêtes"],
        ]),
        ("schematic", "oos", "Phases d'une enquête OOS."),
        ("flow", "lab_sample", "Cycle de vie d'un échantillon de laboratoire."),
    ],
)

QC010 = sop(
    "SOP-QC-010", "ls_lab", "Laboratory ▸ Tests ▸ Test Methods · Specifications ▸ Product Specifications",
    flows=[("lab_method", tr("Lifecycle of a test method and of a specification.", "Cycle de vie d'une méthode et d'une spécification."))],
    related=["SOP-VAL-006", "SOP-QC-012", "SOP-QA-030"],
    refs=["EU-GMP-6", "CFR-211-160", "ICH-Q2"],
    en=dict(
        title="Approval of test methods and specifications",
        owner="QC Manager",
        objective="Use only approved, validated test methods and approved specifications with explicit acceptance criteria, and control their versions.",
        scope="Test methods and specifications for raw materials, packaging, in-process, finished product, stability and water.",
        roles=[("Analyst / QC specialist", "Drafts methods and specifications."),
               ("Laboratory Manager", "Approves; makes obsolete with a reason.")],
        defs=[("Method validation status", "Not Required, Planned, In Progress, Validated, Revalidation Due (with validation reference)."),
              ("Criterion type", "Between Min and Max, Not Less Than, Not More Than, Text Match, Pass/Fail, Informative Only; *Mandatory* and *Show on CoA* flags.")],
        steps=[("Method", "In {{Test Methods}} click [[New]]: name, code, version, technique, result type, unit, decimals, reference document, procedure summary, instrument category, validation status and reference. [[Submit for Review]] then [[Approve]]."),
               ("Specification", "In {{Product Specifications}} click [[New]]: name, code, version, product, type, effective date; add criteria lines (approved method, criterion type and limits, unit, mandatory, show on CoA). [[Submit for Review]] then [[Approve]]."),
               ("Revise", "Use [[Create Revision]] for any change; the new version supersedes the old when approved."),
               ("Obsolete", "Click [[Set Obsolete]] with the obsolescence reason; only one approved specification per product and type.")],
        controls=["A specification without criteria cannot be approved; only approved methods can be used in a specification; min ≤ max; a text criterion needs the expected text.",
                  "Only one approved specification per product and type — make the old one obsolete first.",
                  "Approved records are frozen (blocked fields listed); criteria of approved specifications cannot change; obsolescence requires a reason; only draft records can be deleted."],
        good=["Link each method to its validation report (SOP-VAL-006) before approval.",
              "Align criteria with the registered specification (marketing authorisation, pharmacopoeia)."],
        pitfalls=["Approving a method whose validation is still *In Progress* without a documented justification."],
        records=["Approved methods and specifications with versions"],
        kpis=["Methods with revalidation due", "Specifications revised per year"],
        example="**Case.** Specification *Tablets 10 mg — finished product v4*: assay 95.0–105.0 % (HPLC method AM-012 v3, validated), dissolution NLT 80 % (Q) at 30 min, related substances NMT 0.5 %, appearance text match. Approved; v3 made obsolete with reason *\"new impurity limit per variation 2027-02\"*.",
    ),
    fr=dict(
        title="Approbation des méthodes d'analyse et des spécifications",
        owner="Responsable CQ",
        objective="N'utiliser que des méthodes approuvées et validées et des spécifications approuvées aux critères explicites, et en maîtriser les versions.",
        scope="Méthodes et spécifications des matières premières, articles de conditionnement, contrôles en cours, produit fini, stabilité et eau.",
        roles=[("Analyste / spécialiste CQ", "Rédige méthodes et spécifications."),
               ("Laboratory Manager", "Approuve ; rend obsolète avec motif.")],
        defs=[("Statut de validation de la méthode", "Not Required, Planned, In Progress, Validated, Revalidation Due (avec référence de validation)."),
              ("Type de critère", "Between Min and Max, Not Less Than, Not More Than, Text Match, Pass/Fail, Informative Only ; indicateurs *Mandatory* et *Show on CoA*.")],
        steps=[("Méthode", "Dans {{Test Methods}}, cliquer sur [[New]] : nom, code, version, technique, type de résultat, unité, décimales, document de référence, résumé du mode opératoire, catégorie d'instrument, statut et référence de validation. [[Submit for Review]] puis [[Approve]]."),
               ("Spécification", "Dans {{Product Specifications}}, cliquer sur [[New]] : nom, code, version, produit, type, date d'effet ; ajouter les critères (méthode approuvée, type et limites, unité, obligatoire, affiché sur le CoA). [[Submit for Review]] puis [[Approve]]."),
               ("Réviser", "Utiliser [[Create Revision]] pour tout changement ; la nouvelle version remplace l'ancienne à son approbation."),
               ("Rendre obsolète", "Cliquer sur [[Set Obsolete]] avec le motif ; une seule spécification approuvée par produit et type.")],
        controls=["Une spécification sans critère ne s'approuve pas ; seules les méthodes approuvées s'utilisent dans une spécification ; min ≤ max ; un critère texte exige le texte attendu.",
                  "Une seule spécification approuvée par produit et type — rendre l'ancienne obsolète d'abord.",
                  "Un enregistrement approuvé est figé (champs bloqués listés) ; les critères d'une spécification approuvée ne changent plus ; l'obsolescence exige un motif ; seuls les brouillons se suppriment."],
        good=["Relier chaque méthode à son rapport de validation (SOP-VAL-006) avant approbation.",
              "Aligner les critères sur la spécification enregistrée (AMM, pharmacopée)."],
        pitfalls=["Approuver une méthode dont la validation est encore *In Progress* sans justification documentée."],
        records=["Méthodes et spécifications approuvées avec versions"],
        kpis=["Méthodes à revalider", "Spécifications révisées par an"],
        example="**Cas.** Spécification *Comprimés 10 mg — produit fini v4* : teneur 95,0–105,0 % (méthode HPLC AM-012 v3, validée), dissolution NLT 80 % (Q) à 30 min, impuretés NMT 0,5 %, aspect par comparaison de texte. Approuvée ; v3 rendue obsolète avec le motif *« nouvelle limite d'impureté selon variation 2027-02 »*.",
    ),
)

QC011 = sop(
    "SOP-QC-011", "ls_lab", "Laboratory ▸ Samples ▸ Sample Receipt",
    flows=[("lab_sample", tr("Sample lifecycle.", "Cycle de vie d'un échantillon."))],
    related=["SOP-QC-012", "SOP-QC-010"],
    refs=["EU-GMP-6", "CFR-211-160", "ISO-17025"],
    en=dict(
        title="Receipt and registration of samples",
        owner="QC Manager",
        objective="Register every sample received by the laboratory with its identity, specification and storage, so that it can be tested against the right criteria and traced.",
        scope="Raw material, packaging, in-process, finished product, stability, retain, water and cleaning verification samples.",
        roles=[("Sample receiver", "Checks labelling and condition, registers the sample."),
               ("Laboratory Manager", "Sets priorities and due dates.")],
        defs=[("Sample type", "Raw Material, Packaging Material, In Process, Finished Product, Stability, Retain, Water, Cleaning Verification.")],
        steps=[("Check", "Check label, container integrity, quantity and storage condition on arrival; refuse or annotate non-conforming samples."),
               ("Register", "In {{Sample Receipt}} click [[New]]: sample type, product, lot, batch reference, approved specification, quantity, sampling date, receipt date, due date, priority, sampled by, sampling point, storage condition."),
               ("Start", "Click [[Start]] to accept the sample into the laboratory; test result lines are prepared from the specification."),
               ("Store", "Store the sample in the recorded condition until testing."),
               ("Cancel", "If the sample cannot be tested, use [[Cancel]] with a reason — never delete.")],
        controls=["The specification must be approved; the lot must belong to the product.",
                  "State transitions are enforced; cancelled samples keep their reason; records that left draft cannot be deleted."],
        good=["Label the container with the system sample reference.",
              "Record the actual receipt time for time-sensitive samples (microbiology, water)."],
        pitfalls=["Testing a sample against the specification of another product version."],
        records=["Sample register"],
        kpis=["Samples received vs tested on time", "Samples cancelled"],
        example="**Case.** Finished product sample of batch 26T018 received: 60 tablets, specification *Tablets 10 mg — FP v4* (approved), priority normal, due in 5 working days; registered and started.",
    ),
    fr=dict(
        title="Réception et enregistrement des échantillons",
        owner="Responsable CQ",
        objective="Enregistrer chaque échantillon reçu au laboratoire avec son identité, sa spécification et son stockage, pour l'analyser selon les bons critères et le tracer.",
        scope="Échantillons de matières premières, conditionnement, en cours, produit fini, stabilité, échantillothèque, eau et vérification de nettoyage.",
        roles=[("Réceptionnaire", "Vérifie étiquetage et état, enregistre l'échantillon."),
               ("Laboratory Manager", "Fixe priorités et échéances.")],
        defs=[("Type d'échantillon", "Raw Material, Packaging Material, In Process, Finished Product, Stability, Retain, Water, Cleaning Verification.")],
        steps=[("Contrôler", "À l'arrivée, vérifier étiquette, intégrité du contenant, quantité et condition de conservation ; refuser ou annoter les échantillons non conformes."),
               ("Enregistrer", "Dans {{Sample Receipt}}, cliquer sur [[New]] : type, produit, lot, référence de lot de fabrication, spécification approuvée, quantité, date de prélèvement, date de réception, échéance, priorité, préleveur, point de prélèvement, condition de conservation."),
               ("Démarrer", "Cliquer sur [[Start]] pour accepter l'échantillon au laboratoire ; les lignes de résultats sont préparées depuis la spécification."),
               ("Stocker", "Conserver l'échantillon dans la condition enregistrée jusqu'à l'analyse."),
               ("Annuler", "Si l'échantillon ne peut être analysé, utiliser [[Cancel]] avec motif — jamais supprimer.")],
        controls=["La spécification doit être approuvée ; le lot doit appartenir au produit.",
                  "Les transitions sont imposées ; un échantillon annulé garde son motif ; un enregistrement sorti du brouillon ne se supprime pas."],
        good=["Étiqueter le contenant avec la référence d'échantillon du système.",
              "Noter l'heure réelle de réception pour les échantillons sensibles au temps (microbiologie, eau)."],
        pitfalls=["Analyser un échantillon avec la spécification d'une autre version du produit."],
        records=["Registre des échantillons"],
        kpis=["Échantillons reçus / analysés dans les délais", "Échantillons annulés"],
        example="**Cas.** Échantillon produit fini du lot 26T018 reçu : 60 comprimés, spécification *Comprimés 10 mg — PF v4* (approuvée), priorité normale, échéance 5 jours ouvrés ; enregistré et démarré.",
    ),
)

QC012 = sop(
    "SOP-QC-012", "ls_lab", "Laboratory ▸ Tests ▸ Test Results · Samples ▸ Sample Register",
    flows=[("lab_result", tr("Lifecycle of a test result.", "Cycle de vie d'un résultat."))],
    schematics=[("four_eyes", tr("Analyst, reviewer and approver are different people.", "Analyste, vérificateur et approbateur sont des personnes différentes."))],
    related=["SOP-QC-011", "SOP-QC-013", "SOP-QC-015", "SOP-DI-002"],
    refs=["CFR-211-160", "EU-GMP-6", "PICS-DI", "ISO-17025"],
    en=dict(
        title="Entry, review and approval of results",
        owner="QC Manager",
        objective="Record each result contemporaneously with its analyst, date and instrument, have it reviewed by a second analyst, and approve the sample only when all mandatory results are reviewed and no investigation is open.",
        scope="All results of laboratory samples.",
        roles=[("Analyst", "Performs the test and records the result."),
               ("Laboratory Reviewer", "Reviews results (not their own) and the sample."),
               ("Laboratory Manager (approver)", "Approves the sample (not the reviewer).")],
        defs=[("Evaluation", "Pending, Conforms, Out Of Specification, Informative — computed against the specification line."),
              ("Out of trend", "Flag set by the analyst/reviewer with a mandatory justification.")],
        steps=[("Test", "Click [[Start Testing]] on the sample."),
               ("Record", "For each result line enter the numeric, text or pass/fail result, analyst, test date, instrument reference, remarks; click [[Record Result]]. Attach raw data or reference it."),
               ("OOS / OOT", "If the evaluation is *Out Of Specification* or the result is out of trend, open an investigation (SOP-QC-013) — do not retest on your own."),
               ("Confirm", "When all mandatory results are recorded, click [[Confirm Results Recorded]]."),
               ("Review", "A reviewer who did not enter results reviews each result ([[Review]] on the result) and then the sample ([[Review]])."),
               ("Approve", "The approver (not the reviewer) clicks [[Approve]] and confirms the signature intent (meaning *Approved*)."),
               ("Report", "Click [[Mark Reported]] once the results are communicated or the CoA issued (SOP-QC-015).")],
        controls=["A result cannot be recorded on a sample not open for entry, nor entered twice; a criterion must belong to the sample's specification.",
                  "The analyst cannot review their own result; the result entrant cannot review the sample; the reviewer cannot approve it.",
                  "Approval requires every mandatory test recorded and reviewed and no open investigation.",
                  "Reviewed results cannot be modified (record a retest under an investigation); results with data cannot be deleted; results linked to an investigation cannot be reset.",
                  "An out-of-trend flag requires a justification; a retest requires a documented retest authorisation."],
        good=["Review raw data and the audit trail, not only the value typed (SOP-DI-002).",
              "Record instrument references to link results with calibration status."],
        pitfalls=["Resetting a result to draft to change an inconvenient value.",
                  "Averaging an OOS result with retest results."],
        records=["Results with analyst, reviewer, dates", "Sample approval with signature intent"],
        kpis=["Right-first-time results", "Review turnaround", "OOS rate"],
        example="**Case.** Sample of 26T018: 6 results entered by analyst A; assay 99.2 % (Conforms). Reviewer B reviews each result and the sample; manager C approves (signature intent *Approved*, timestamp recorded); sample marked reported after the CoA is issued.",
    ),
    fr=dict(
        title="Saisie, revue et approbation des résultats",
        owner="Responsable CQ",
        objective="Enregistrer chaque résultat au moment de l'essai avec analyste, date et instrument, le faire revoir par un second analyste, et n'approuver l'échantillon que lorsque tous les résultats obligatoires sont revus et qu'aucune enquête n'est ouverte.",
        scope="Tous les résultats des échantillons de laboratoire.",
        roles=[("Analyste", "Réalise l'essai et saisit le résultat."),
               ("Laboratory Reviewer", "Revoit les résultats (pas les siens) et l'échantillon."),
               ("Laboratory Manager (approbateur)", "Approuve l'échantillon (pas le vérificateur).")],
        defs=[("Évaluation", "Pending, Conforms, Out Of Specification, Informative — calculée par rapport à la ligne de spécification."),
              ("Hors tendance", "Indicateur posé par l'analyste/le vérificateur avec justification obligatoire.")],
        steps=[("Analyser", "Cliquer sur [[Start Testing]] sur l'échantillon."),
               ("Saisir", "Pour chaque ligne, saisir le résultat numérique, texte ou conforme/non conforme, l'analyste, la date, la référence de l'instrument, les remarques ; cliquer sur [[Record Result]]. Joindre ou référencer les données brutes."),
               ("OOS / OOT", "Si l'évaluation est *Out Of Specification* ou le résultat hors tendance, ouvrir une enquête (SOP-QC-013) — ne pas refaire l'essai de sa propre initiative."),
               ("Confirmer", "Quand tous les résultats obligatoires sont saisis, cliquer sur [[Confirm Results Recorded]]."),
               ("Revoir", "Un vérificateur qui n'a pas saisi revoit chaque résultat ([[Review]] sur le résultat) puis l'échantillon ([[Review]])."),
               ("Approuver", "L'approbateur (autre que le vérificateur) clique sur [[Approve]] et confirme l'intention de signature (signification *Approved*)."),
               ("Rapporter", "Cliquer sur [[Mark Reported]] une fois les résultats communiqués ou le CoA émis (SOP-QC-015).")],
        controls=["Un résultat ne se saisit pas sur un échantillon fermé à la saisie ni deux fois ; le critère doit appartenir à la spécification de l'échantillon.",
                  "L'analyste ne revoit pas son propre résultat ; celui qui a saisi ne revoit pas l'échantillon ; le vérificateur ne l'approuve pas.",
                  "L'approbation exige tous les essais obligatoires saisis et revus et aucune enquête ouverte.",
                  "Un résultat revu ne se modifie plus (nouvel essai sous enquête) ; un résultat avec données ne se supprime pas ; un résultat lié à une enquête ne se réinitialise pas.",
                  "Un indicateur hors tendance exige une justification ; un nouvel essai exige une autorisation documentée."],
        good=["Revoir les données brutes et la piste d'audit, pas seulement la valeur saisie (SOP-DI-002).",
              "Noter les références d'instrument pour relier les résultats au statut d'étalonnage."],
        pitfalls=["Remettre un résultat en brouillon pour changer une valeur gênante.",
                  "Moyenner un résultat OOS avec les résultats de nouvel essai."],
        records=["Résultats avec analyste, vérificateur, dates", "Approbation de l'échantillon avec intention de signature"],
        kpis=["Résultats bons du premier coup", "Délai de revue", "Taux d'OOS"],
        example="**Cas.** Échantillon de 26T018 : 6 résultats saisis par l'analyste A ; teneur 99,2 % (Conforms). Le vérificateur B revoit chaque résultat et l'échantillon ; la responsable C approuve (intention de signature *Approved*, horodatée) ; l'échantillon est marqué rapporté après l'émission du CoA.",
    ),
)

QC013 = sop(
    "SOP-QC-013", "ls_lab", "Laboratory ▸ Specifications ▸ OOS / OOT",
    flows=[("oos", tr("Lifecycle of an OOS/OOT investigation.", "Cycle de vie d'une enquête OOS/OOT."))],
    schematics=[("oos", tr("Phase I, Phase II, conclusion and closure.", "Phase I, phase II, conclusion et clôture."))],
    related=["SOP-QC-012", "SOP-QA-020", "SOP-QA-021", "SOP-QA-090"],
    refs=["FDA-OOS", "CFR-211-192", "EU-GMP-6"],
    en=dict(
        title="Investigation of OOS (out-of-specification) and OOT (out-of-trend) results",
        owner="QC Manager with QA",
        objective="Investigate every OOS or OOT result in a structured way — laboratory phase first, full investigation when no laboratory cause is found — authorise retests or resamples only with written scientific justification, and decide on the product with QA.",
        scope="All OOS and OOT results of release, stability, raw material and in-process testing.",
        roles=[("Investigator (analyst's supervisor)", "Conducts Phase I and Phase II."),
               ("QA / quality unit approver", "Approves closure; must not be the investigator."),
               ("Production", "Contributes to the manufacturing review in Phase II.")],
        defs=[("Phase I", "Laboratory investigation: analyst interview, calculations, instrument performance, standards and reagents, sample integrity, method adherence."),
              ("Phase II", "Full investigation including manufacturing review, when Phase I finds no assignable laboratory cause."),
              ("Final conclusion", "Assignable Laboratory Cause, Assignable Manufacturing Cause, No Assignable Cause Identified; disposition Reject, Release, Remain In Quarantine, Further Investigation Required.")],
        steps=[("Open", "In {{Specifications ▸ OOS / OOT}} click [[New]]: type (OOS or OOT), originating result, investigator, description. The lot is held: deliveries are refused while it is open."),
               ("Phase I", "Click [[Start Phase I]]; tick each check performed (analyst interviewed, calculation verified, instrument performance, standards and reagents, sample integrity, method adherence); record Phase I findings and conclusion; click [[Complete Phase I]]."),
               ("Laboratory cause", "If an assignable laboratory cause is identified, invalidate the result with justification and, when justified in writing, click [[Authorise Retest]]; the retest is recorded as a retest linked to the investigation."),
               ("Phase II", "If no laboratory cause, click [[Start Phase II]]: review manufacturing (batch record, deviations, equipment), determine root cause; resample only with [[Authorise Resample]] and justification; record Phase II findings; [[Complete Phase II]]."),
               ("Conclude", "Click [[Conclude]] with the final conclusion, product disposition and justification, CAPA reference if any."),
               ("Close", "A quality unit member who did not conduct the investigation clicks [[Close]].")],
        controls=["Investigations cannot be deleted — cancel with a reason.",
                  "Phase I needs findings and a conclusion; Phase II applies only when Phase I found no laboratory cause, and is mandatory in that case before concluding.",
                  "Retest and resample require a written scientific justification; a retest result cannot be recorded without authorisation.",
                  "Closure requires a final conclusion and a product disposition, by a user other than the investigator.",
                  "Lots held by an open investigation cannot be delivered; a sample cannot be approved while an investigation is open."],
        good=["Never test into compliance: the number of retests and the decision rule are defined before retesting.",
              "Report OOS trends in management review."],
        pitfalls=["Invalidating an OOS result without evidence of a laboratory error.",
                  "Closing the OOS with *Release* while a manufacturing cause is under investigation."],
        records=["Investigation with phases, checks, authorisations, conclusion, disposition"],
        kpis=["OOS invalidated in Phase I (%)", "Median time to closure", "OOS per product"],
        example="**Case.** Dissolution of 26T018 at 30 min: 76 % (NLT 80 %). Phase I: vessel 4 paddle height found out of tolerance at post-test check → assignable laboratory cause; the manager authorises a retest with justification. Retest on 6 new units: 88–93 %. Conclusion *Assignable Laboratory Cause*, disposition *Release*; closed by QA (not the investigator); CAPA opened for apparatus verification frequency.",
    ),
    fr=dict(
        title="Investigation des résultats OOS (hors spécification) et OOT (hors tendance)",
        owner="Responsable CQ avec l'AQ",
        objective="Investiguer chaque résultat OOS ou OOT de façon structurée — phase laboratoire d'abord, enquête complète quand aucune cause laboratoire n'est trouvée —, n'autoriser nouvel essai ou nouvel échantillonnage qu'avec une justification scientifique écrite, et décider du produit avec l'AQ.",
        scope="Tous les résultats OOS et OOT des contrôles de libération, de stabilité, des matières et en cours.",
        roles=[("Enquêteur (encadrant de l'analyste)", "Conduit les phases I et II."),
               ("Approbateur de l'unité qualité", "Approuve la clôture ; ne doit pas être l'enquêteur."),
               ("Production", "Contribue à la revue de fabrication en phase II.")],
        defs=[("Phase I", "Enquête laboratoire : entretien avec l'analyste, calculs, performance de l'instrument, étalons et réactifs, intégrité de l'échantillon, respect de la méthode."),
              ("Phase II", "Enquête complète incluant la revue de fabrication, lorsque la phase I ne trouve pas de cause laboratoire."),
              ("Conclusion finale", "Assignable Laboratory Cause, Assignable Manufacturing Cause, No Assignable Cause Identified ; disposition Reject, Release, Remain In Quarantine, Further Investigation Required.")],
        steps=[("Ouvrir", "Dans {{Specifications ▸ OOS / OOT}}, cliquer sur [[New]] : type (OOS ou OOT), résultat d'origine, enquêteur, description. Le lot est retenu : les livraisons sont refusées tant qu'elle est ouverte."),
               ("Phase I", "Cliquer sur [[Start Phase I]] ; cocher chaque vérification réalisée (entretien, calculs, instrument, étalons et réactifs, intégrité de l'échantillon, respect de la méthode) ; saisir constats et conclusion ; cliquer sur [[Complete Phase I]]."),
               ("Cause laboratoire", "Si une cause laboratoire est identifiée, invalider le résultat avec justification et, lorsque c'est justifié par écrit, cliquer sur [[Authorise Retest]] ; le nouvel essai est enregistré comme retest lié à l'enquête."),
               ("Phase II", "Sans cause laboratoire, cliquer sur [[Start Phase II]] : revue de fabrication (dossier de lot, déviations, équipements), cause racine ; nouvel échantillonnage seulement avec [[Authorise Resample]] et justification ; constats de phase II ; [[Complete Phase II]]."),
               ("Conclure", "Cliquer sur [[Conclude]] avec la conclusion finale, la disposition du produit et sa justification, la référence CAPA le cas échéant."),
               ("Clore", "Un membre de l'unité qualité qui n'a pas conduit l'enquête clique sur [[Close]].")],
        controls=["Une enquête ne se supprime pas — l'annuler avec motif.",
                  "La phase I exige constats et conclusion ; la phase II ne s'applique que si la phase I n'a pas trouvé de cause laboratoire, et elle est alors obligatoire avant de conclure.",
                  "Nouvel essai et nouvel échantillonnage exigent une justification scientifique écrite ; un résultat de retest ne s'enregistre pas sans autorisation.",
                  "La clôture exige une conclusion finale et une disposition, par un utilisateur autre que l'enquêteur.",
                  "Les lots retenus par une enquête ouverte ne peuvent être livrés ; un échantillon ne s'approuve pas tant qu'une enquête est ouverte."],
        good=["Ne jamais « tester jusqu'à la conformité » : nombre de retests et règle de décision fixés avant le retest.",
              "Présenter les tendances OOS en revue de direction."],
        pitfalls=["Invalider un résultat OOS sans preuve d'erreur de laboratoire.",
                  "Clore l'OOS en *Release* alors qu'une cause de fabrication est en cours d'investigation."],
        records=["Enquête avec phases, vérifications, autorisations, conclusion, disposition"],
        kpis=["OOS invalidés en phase I (%)", "Délai médian de clôture", "OOS par produit"],
        example="**Cas.** Dissolution de 26T018 à 30 min : 76 % (NLT 80 %). Phase I : hauteur de pale du bol 4 hors tolérance au contrôle après essai → cause laboratoire ; la responsable autorise un retest avec justification. Retest sur 6 nouvelles unités : 88–93 %. Conclusion *Assignable Laboratory Cause*, disposition *Release* ; clôture par l'AQ (pas l'enquêteur) ; CAPA ouverte sur la fréquence de vérification des appareils.",
    ),
)

QC014 = sop(
    "SOP-QC-014", "ls_lab", "Laboratory ▸ Stability",
    flows=[("lab_stability", tr("Lifecycle of a laboratory stability study.", "Cycle de vie d'une étude de stabilité du laboratoire."))],
    related=["SOP-QC-002", "SOP-QC-012", "SOP-QC-013"],
    refs=["ICH-Q1A", "CFR-211-166"],
    en=dict(
        title="Stability studies in the laboratory",
        owner="QC Manager",
        objective="Run stability studies with an approved protocol, generate pull samples at each time point, test them against the stability specification and record missed time points with reasons.",
        scope="Stability studies managed on the laboratory side (long term, intermediate, accelerated, in-use, photostability, ongoing/annual). Programme-level stability of pharmaceutical batches may be managed in ls_pharma (SOP-QC-002); choose one module per study to avoid double records.",
        roles=[("Stability analyst", "Pulls and tests samples."),
               ("Laboratory Manager", "Approves protocol, starts, completes or terminates studies.")],
        defs=[("Time point", "Planned, Sampled, Tested, Completed, Missed, Cancelled.")],
        steps=[("Create", "In {{Stability Studies}} click [[New]]: product, lot, batch, study type, storage condition, container closure, specification, protocol reference, planned end; add time points."),
               ("Approve and start", "Click [[Approve Protocol]]; set the start date; click [[Start Study]]."),
               ("Pull", "At each time point click [[Create Pull Sample]] on the time point: a laboratory sample is created and tested (SOP-QC-012)."),
               ("Progress", "Click [[Mark Tested]] then [[Complete]] on the time point; if not pulled, [[Mark Missed]] with notes."),
               ("Close", "Click [[Complete]] on the study when all time points are final, or [[Terminate]] with a reason.")],
        controls=["A study cannot be approved without time points; a start date is required to begin (due dates are derived from it).",
                  "Pull samples only for ongoing studies and planned time points; only sampled time points can be marked tested, only tested ones completed, only planned ones missed (with notes).",
                  "Completion requires every time point completed, missed or cancelled; termination requires a reason; the lot must belong to the product."],
        good=["Pull within the time window defined in the protocol and record the actual date."],
        pitfalls=["Managing the same study in both ls_pharma and ls_lab."],
        records=["Study, time points, samples, results"],
        kpis=["Time points missed", "Studies completed on time"],
        example="**Case.** Photostability study on 26T018 per ICH Q1B conditions: 2 time points (exposed, dark control); pull samples created and tested; both completed; study completed with conclusion *photostable in the proposed pack*.",
    ),
    fr=dict(
        title="Études de stabilité au laboratoire",
        owner="Responsable CQ",
        objective="Conduire les études de stabilité selon un protocole approuvé, générer les échantillons à chaque point, les analyser selon la spécification de stabilité et consigner avec motif les points manqués.",
        scope="Études de stabilité gérées côté laboratoire (long terme, intermédiaire, accélérée, en utilisation, photostabilité, continue/annuelle). La stabilité au niveau programme des lots pharmaceutiques peut être gérée dans ls_pharma (SOP-QC-002) ; choisir un seul module par étude pour éviter les doublons.",
        roles=[("Analyste stabilité", "Sort et analyse les échantillons."),
               ("Laboratory Manager", "Approuve le protocole, démarre, termine ou arrête les études.")],
        defs=[("Point de contrôle", "Planned, Sampled, Tested, Completed, Missed, Cancelled.")],
        steps=[("Créer", "Dans {{Stability Studies}}, cliquer sur [[New]] : produit, lot, lot de fabrication, type d'étude, condition, système de fermeture, spécification, référence du protocole, fin prévue ; ajouter les points."),
               ("Approuver et démarrer", "Cliquer sur [[Approve Protocol]] ; fixer la date de début ; cliquer sur [[Start Study]]."),
               ("Sortir", "À chaque point, cliquer sur [[Create Pull Sample]] : un échantillon de laboratoire est créé et analysé (SOP-QC-012)."),
               ("Avancer", "Cliquer sur [[Mark Tested]] puis [[Complete]] sur le point ; s'il n'a pas été sorti, [[Mark Missed]] avec des notes."),
               ("Clore", "Cliquer sur [[Complete]] sur l'étude quand tous les points sont finaux, ou [[Terminate]] avec motif.")],
        controls=["Une étude sans point ne s'approuve pas ; une date de début est exigée pour démarrer (les échéances en découlent).",
                  "Échantillons seulement pour les études en cours et les points planifiés ; seul un point échantillonné devient analysé, seul un point analysé devient terminé, seul un point planifié devient manqué (avec notes).",
                  "La fin exige tous les points terminés, manqués ou annulés ; l'arrêt exige un motif ; le lot doit appartenir au produit."],
        good=["Sortir dans la fenêtre fixée par le protocole et noter la date réelle."],
        pitfalls=["Gérer la même étude à la fois dans ls_pharma et ls_lab."],
        records=["Étude, points, échantillons, résultats"],
        kpis=["Points manqués", "Études terminées dans les délais"],
        example="**Cas.** Étude de photostabilité sur 26T018 selon les conditions ICH Q1B : 2 points (exposé, témoin à l'obscurité) ; échantillons créés et analysés ; points terminés ; étude close avec la conclusion *photostable dans le conditionnement proposé*.",
    ),
)

QC015 = sop(
    "SOP-QC-015", "ls_lab", "Laboratory ▸ Reports ▸ Certificates of Analysis",
    flows=[("coa", tr("Lifecycle of a certificate of analysis.", "Cycle de vie d'un certificat d'analyse."))],
    related=["SOP-QC-012", "SOP-QA-090"],
    refs=["EU-GMP-6", "CFR-211-160", "ICH-Q7"],
    en=dict(
        title="Issue of certificates of analysis",
        owner="QC Manager",
        objective="Issue certificates of analysis only from approved samples, showing the results and conclusion against the specification, and revise them in a traceable way.",
        scope="Certificates of analysis for customers and for internal release.",
        roles=[("QC officer", "Prepares the certificate."),
               ("Laboratory Manager", "Issues it (signature intent *Issued*).")],
        defs=[("Conclusion", "Conforms To Specification / Does Not Conform To Specification (Pending until issued)."),
              ("Revision", "New version superseding an issued certificate, with a revision reason.")],
        steps=[("Create", "In {{Reports ▸ Certificates of Analysis}} click [[New]] and select the approved sample; enter version, customer, remarks; results flagged *Show on CoA* in the specification are included."),
               ("Issue", "Click [[Issue Certificate]] and confirm the signature intent."),
               ("Send", "Send the PDF to the customer or attach it to the batch file."),
               ("Revise", "If a correction is needed, click [[Create Revision]] with the revision reason; the previous certificate becomes superseded."),
               ("Cancel", "Only a draft certificate can be cancelled, with a reason.")],
        controls=["A certificate can only be issued from an approved sample; issued certificates cannot be modified or deleted.",
                  "Only an issued certificate can be revised, with a revision reason; only drafts can be cancelled, with a reason."],
        good=["Include the specification version and the method references on the certificate.",
              "Check the customer-specific requirements (units, additional tests) before issue."],
        pitfalls=["Editing the PDF manually after issue."],
        records=["Issued and superseded certificates"],
        kpis=["Certificates revised after issue"],
        example="**Case.** CoA for batch 26T018: 6 results, conclusion *Conforms To Specification*; issued by the Laboratory Manager. A customer asks for the dissolution profile: a revision v2 is created with reason *\"customer request — add dissolution at 15/20/30 min\"*; v1 is superseded.",
    ),
    fr=dict(
        title="Émission des certificats d'analyse",
        owner="Responsable CQ",
        objective="N'émettre de certificats d'analyse qu'à partir d'échantillons approuvés, présentant résultats et conclusion par rapport à la spécification, et les réviser de façon traçable.",
        scope="Certificats d'analyse pour les clients et pour la libération interne.",
        roles=[("Chargé CQ", "Prépare le certificat."),
               ("Laboratory Manager", "L'émet (intention de signature *Issued*).")],
        defs=[("Conclusion", "Conforms To Specification / Does Not Conform To Specification (Pending jusqu'à l'émission)."),
              ("Révision", "Nouvelle version remplaçant un certificat émis, avec motif.")],
        steps=[("Créer", "Dans {{Reports ▸ Certificates of Analysis}}, cliquer sur [[New]] et choisir l'échantillon approuvé ; saisir version, client, remarques ; les résultats marqués *Show on CoA* dans la spécification sont repris."),
               ("Émettre", "Cliquer sur [[Issue Certificate]] et confirmer l'intention de signature."),
               ("Envoyer", "Envoyer le PDF au client ou le joindre au dossier de lot."),
               ("Réviser", "En cas de correction, cliquer sur [[Create Revision]] avec le motif ; le certificat précédent devient remplacé."),
               ("Annuler", "Seul un brouillon peut être annulé, avec motif.")],
        controls=["Un certificat ne s'émet que depuis un échantillon approuvé ; émis, il ne se modifie ni ne se supprime.",
                  "Seul un certificat émis se révise, avec motif ; seuls les brouillons s'annulent, avec motif."],
        good=["Faire figurer la version de la spécification et les références des méthodes.",
              "Vérifier les exigences propres au client (unités, essais supplémentaires) avant émission."],
        pitfalls=["Modifier le PDF à la main après émission."],
        records=["Certificats émis et remplacés"],
        kpis=["Certificats révisés après émission"],
        example="**Cas.** CoA du lot 26T018 : 6 résultats, conclusion *Conforms To Specification* ; émis par la responsable du laboratoire. Un client demande le profil de dissolution : une révision v2 est créée avec le motif *« demande client — ajout dissolution à 15/20/30 min »* ; la v1 est remplacée.",
    ),
)

ITEMS = [M_MP, MP001, MP002, MP003, MP004, MP005, MP006, M_LAB, QC010, QC011, QC012, QC013, QC014, QC015]
