# -*- coding: utf-8 -*-
"""Part I (a) — Document system (ls_qms, ls_document_management) and training (ls_training)."""
from .helpers import module, part, sop, tr

P1 = part(
    "I", "part1",
    "Quality management system", "Système de management de la qualité",
    "The procedures that organise the quality system itself: documents and records, training, quality events "
    "(deviations, CAPA, complaints, changes), audits, risk management and suppliers.",
    "Les procédures qui organisent le système qualité lui-même : documents et enregistrements, formation, "
    "événements qualité (déviations, CAPA, réclamations, changements), audits, gestion des risques et fournisseurs.",
    ["Document system — ls_qms, ls_document_management", "Training — ls_training",
     "Deviations and CAPA — ls_deviation, ls_capa", "Change control — ls_change_control",
     "Complaints — ls_complaint", "Audits — ls_audit", "Risk management — ls_risk_management",
     "Suppliers — ls_supplier_qualification"],
    ["Système documentaire — ls_qms, ls_document_management", "Formation — ls_training",
     "Déviations et CAPA — ls_deviation, ls_capa", "Maîtrise des changements — ls_change_control",
     "Réclamations — ls_complaint", "Audits — ls_audit", "Gestion des risques — ls_risk_management",
     "Fournisseurs — ls_supplier_qualification"],
)

M_DOC = module(
    "mod-doc", "ls_qms · ls_document_management",
    "Document system", "Système documentaire",
    [
        ("p", "Two modules carry controlled documentation. **ls_qms** holds the structured quality documents — quality "
              "policy, SOPs, work instructions and quality plans — whose content is typed in sections, plus quality "
              "objectives and quality records. **ls_document_management** holds controlled *files* (PDF, drawings, "
              "forms) organised in folders, with immutable versions protected by a SHA-256 checksum, an approval "
              "circuit per document and retention policies. Use ls_qms for documents you write in the system and "
              "ls_document_management for documents you manage as files."),
        ("table", ["Menu", "Content"], [
            ["{{Quality Management ▸ Quality Policy / Procedures / Work Instructions / Quality Planning}}", "Structured controlled documents (ls_qms)"],
            ["{{Quality Management ▸ Quality Objectives}}, {{Quality Records}}", "Objectives with measurements; retained quality records"],
            ["{{Quality Management ▸ Reporting ▸ Procedures Due for Review}}", "Documents whose periodic review is due"],
            ["{{Documents ▸ Documents / Versions / My Approvals}}", "Controlled files (ls_document_management)"],
            ["{{Documents ▸ Configuration ▸ Folders / Retention Policies / Tags}}", "Structure and retention rules"],
        ]),
        ("table", ["Group", "Main rights"], [
            ["ls_qms: Viewer · User · Approver · Manager", "User writes and submits; Approver approves, rejects and publishes; Manager sets obsolete, reopens, disposes of records."],
            ["ls_document_management: Viewer · Editor · Approver · Manager", "Editor creates documents and versions; named approvers decide; only the Manager publishes and archives."],
        ]),
        ("flow", "qms_doc", "Lifecycle of an ls_qms controlled document (policy, SOP, work instruction, quality plan)."),
        ("flow", "dms_doc", "Lifecycle of a controlled file in ls_document_management."),
        ("shot", "ls_qms_sop__form", "A procedure in ls_qms: sections, status bar and approval buttons."),
    ],
    [
        ("p", "Deux modules portent la documentation maîtrisée. **ls_qms** contient les documents qualité structurés — "
              "politique qualité, SOP, instructions de travail et plans qualité — dont le contenu est saisi par rubriques, "
              "ainsi que les objectifs qualité et les enregistrements qualité. **ls_document_management** gère des "
              "*fichiers* maîtrisés (PDF, plans, formulaires) rangés dans des dossiers, avec des versions immuables "
              "protégées par une empreinte SHA-256, un circuit d'approbation par document et des politiques de "
              "conservation. Utilisez ls_qms pour les documents rédigés dans le système et ls_document_management pour "
              "les documents gérés comme fichiers."),
        ("table", ["Menu", "Contenu"], [
            ["{{Quality Management ▸ Quality Policy / Procedures / Work Instructions / Quality Planning}}", "Documents maîtrisés structurés (ls_qms)"],
            ["{{Quality Management ▸ Quality Objectives}}, {{Quality Records}}", "Objectifs et mesures ; enregistrements qualité conservés"],
            ["{{Quality Management ▸ Reporting ▸ Procedures Due for Review}}", "Documents dont la revue périodique est due"],
            ["{{Documents ▸ Documents / Versions / My Approvals}}", "Fichiers maîtrisés (ls_document_management)"],
            ["{{Documents ▸ Configuration ▸ Folders / Retention Policies / Tags}}", "Structure et règles de conservation"],
        ]),
        ("table", ["Groupe", "Droits principaux"], [
            ["ls_qms : Viewer · User · Approver · Manager", "User rédige et soumet ; Approver approuve, rejette et publie ; Manager rend obsolète, rouvre, détruit les enregistrements."],
            ["ls_document_management : Viewer · Editor · Approver · Manager", "Editor crée documents et versions ; les approbateurs désignés décident ; seul le Manager publie et archive."],
        ]),
        ("flow", "qms_doc", "Cycle de vie d'un document maîtrisé ls_qms (politique, SOP, instruction, plan qualité)."),
        ("flow", "dms_doc", "Cycle de vie d'un fichier maîtrisé dans ls_document_management."),
        ("shot", "ls_qms_sop__form", "Une procédure dans ls_qms : rubriques, barre d'état et boutons d'approbation."),
    ],
)

QA001 = sop(
    "SOP-QA-001", "ls_qms · ls_document_management",
    "Quality Management ▸ Procedures (and Quality Policy, Work Instructions, Quality Planning)",
    flows=[("qms_doc", tr("Lifecycle of a quality document in ls_qms.", "Cycle de vie d'un document qualité dans ls_qms."))],
    schematics=[("pyramid", tr("Where each document type sits in the hierarchy.", "Place de chaque type de document dans la hiérarchie."))],
    shots=[("ls_qms_sop__list", tr("Procedure register with status and next review date.", "Registre des procédures avec état et prochaine revue."))],
    related=["SOP-QA-002", "SOP-QA-003", "SOP-QA-012", "SOP-QA-030"],
    refs=["EU-GMP-4", "ISO-9001", "ISO-13485", "CFR-211-100", "EU-A11"],
    en=dict(
        title="Drafting, review, approval and publication of quality documents",
        owner="Head of Quality Assurance",
        objective="Ensure that every quality document (quality policy, SOP, work instruction, quality plan) is written to a common standard, reviewed and approved by competent people other than its author, and made effective in a controlled way, so that only approved, current instructions are used.",
        scope="All quality documents managed in ls_qms, and controlled files (forms, drawings, external documents) managed in ls_document_management. Excludes records, which follow SOP-QA-004.",
        roles=[("QMS User (author)", "Drafts the document, completes all mandatory sections, proposes reviewers, submits for review."),
               ("Reviewers (named on the document)", "Check technical content and consistency with other documents; return comments within the agreed time."),
               ("QMS Approver", "Approves or rejects with a reason; publishes the approved revision on its effective date."),
               ("QMS Manager", "Owns the document system, numbering and templates; resolves disputes; withdraws documents."),
               ("Document Manager (ls_document_management)", "Publishes and archives controlled files once all named approvers have approved.")],
        defs=[("Revision", "A numbered version of a document. Only one revision of a document may be published at a time."),
              ("Effective date", "Date from which the published revision applies. It cannot precede the approval date."),
              ("Reason for change", "Mandatory statement explaining why a new revision is created.")],
        steps=[("Check the need", "Search the register ({{Quality Management ▸ Procedures}}) to avoid duplicates. For a change to an existing document, use SOP-QA-002."),
               ("Create the draft", "Click [[New]]. Enter Title, Owning Department, Review Period (months; the default comes from the QMS parameter, 24 months at installation) and tick *Training Required* when users must be trained before applying the procedure. The reference and version are allocated by the system."),
               ("Write the content", "Complete Purpose, Scope, Definitions and Abbreviations, Responsibilities, Procedure and Reference Documents. For a work instruction, select the *Parent Procedure*; for a quality plan, add at least one control line; for the policy, write the policy statement."),
               ("Name the reviewers", "Add the reviewers who cover every affected function (production, QC, engineering, regulatory as relevant)."),
               ("Submit", "Click [[Submit for Review]]. The document moves to *Under Review* and its content is locked for the author."),
               ("Review", "Reviewers record comments in the chatter. Blocking comments lead the approver to [[Reject]] with a written reason; the document returns to Draft."),
               ("Approve", "A QMS Approver who is not the author clicks [[Approve]]. The approval date is recorded."),
               ("Plan the training", "If *Training Required* is ticked, launch SOP-QA-012 before the effective date."),
               ("Publish", "On the effective date the approver clicks [[Publish]]. The previous revision, if any, becomes *Obsolete* automatically."),
               ("Distribute", "Inform the users (chatter, e-mail, briefing). Withdraw any paper copy of the previous revision."),
               ("Controlled files", "For a file in ls_document_management: create the document in its folder, upload the file with [[New Version]], add at least one approver, [[Submit for Review]]; each approver decides in {{Documents ▸ My Approvals}}; the Document Manager then clicks [[Publish]].")],
        controls=["Purpose, scope and procedure of an SOP must be filled before it can be submitted.",
                  "The author of a document cannot approve it (segregation of duties).",
                  "Only one revision of a document may be published at a time; publishing retires the previous one.",
                  "The effective date cannot precede the approval date.",
                  "Published or obsolete content cannot be modified — a new revision is required.",
                  "Only draft documents can be deleted; others must be made obsolete.",
                  "A work instruction cannot be published while its parent procedure is not published.",
                  "ls_document_management: a document cannot be submitted without a version (file) and at least one approver; only a Document Manager can publish or archive; each version carries a SHA-256 checksum verified for integrity."],
        good=["Use one template per document type and keep the section headings of ls_qms.",
              "Choose reviewers by function, not by availability; two reviewers are usually enough.",
              "Set the effective date far enough ahead to complete training (SOP-QA-012).",
              "Write the reason for change even for the first revision (\"new procedure\").",
              "Quote the exact software buttons and menus in procedures that use the suite."],
        pitfalls=["Publishing before the users are trained.",
                  "Approving your own document through a second account — a data integrity breach.",
                  "Keeping uncontrolled copies (desktop, printouts) after a new revision is published.",
                  "Using the chatter to change content after approval: content is frozen, create a revision."],
        records=["The document revision with its approval and publication dates", "Chatter history of review comments", "Rejection reasons", "Training records (SOP-QA-012)"],
        kpis=["Median time from submission to approval", "Number of rejections per document", "Documents published without training completed (target 0)"],
        example="**Case.** The warehouse needs a procedure for temperature mapping. The QA officer creates *SOP – Temperature mapping of storage areas*, sets a 24-month review period and ticks *Training Required*. She names the warehouse manager and the validation engineer as reviewers and clicks [[Submit for Review]]. The validation engineer asks for the acceptance criterion to be stated in °C; the approver clicks [[Reject]] with this reason. After correction the document is resubmitted and approved by the Head of QA (not the author). Training sessions are held (SOP-QA-012); on 1 March the approver clicks [[Publish]]: the SOP becomes effective and its next review date is computed automatically (1 March two years later).",
    ),
    fr=dict(
        title="Rédaction, revue, approbation et publication des documents qualité",
        owner="Responsable assurance qualité",
        objective="Garantir que chaque document qualité (politique qualité, SOP, instruction de travail, plan qualité) est rédigé selon un standard commun, revu et approuvé par des personnes compétentes autres que son auteur, et rendu applicable de façon maîtrisée, afin que seules des instructions approuvées et en vigueur soient utilisées.",
        scope="Tous les documents qualité gérés dans ls_qms et les fichiers maîtrisés (formulaires, plans, documents externes) gérés dans ls_document_management. Les enregistrements relèvent de la SOP-QA-004.",
        roles=[("QMS User (rédacteur)", "Rédige le document, complète les rubriques obligatoires, propose les vérificateurs, soumet à la revue."),
               ("Vérificateurs (désignés sur le document)", "Vérifient le contenu technique et la cohérence avec les autres documents ; rendent leurs commentaires dans le délai convenu."),
               ("QMS Approver", "Approuve ou rejette avec motif ; publie la révision approuvée à sa date d'application."),
               ("QMS Manager", "Pilote le système documentaire, la numérotation et les modèles ; arbitre ; retire les documents."),
               ("Document Manager (ls_document_management)", "Publie et archive les fichiers maîtrisés une fois tous les approbateurs désignés d'accord.")],
        defs=[("Révision", "Version numérotée d'un document. Une seule révision d'un document peut être publiée à la fois."),
              ("Date d'application", "Date à partir de laquelle la révision publiée s'applique. Elle ne peut précéder la date d'approbation."),
              ("Motif de changement", "Explication obligatoire de la création d'une nouvelle révision.")],
        steps=[("Vérifier le besoin", "Rechercher dans le registre ({{Quality Management ▸ Procedures}}) pour éviter les doublons. Pour modifier un document existant, appliquer la SOP-QA-002."),
               ("Créer le brouillon", "Cliquer sur [[New]]. Saisir le titre (Title), le service propriétaire (Owning Department), la période de revue en mois (Review Period ; la valeur par défaut vient du paramètre QMS, 24 mois à l'installation) et cocher *Training Required* si les utilisateurs doivent être formés avant d'appliquer la procédure. Référence et version sont attribuées par le système."),
               ("Rédiger", "Compléter Purpose (objet), Scope (domaine), Definitions and Abbreviations, Responsibilities, Procedure et Reference Documents. Pour une instruction de travail, choisir la procédure parente (*Parent Procedure*) ; pour un plan qualité, ajouter au moins une ligne de contrôle ; pour la politique, rédiger l'énoncé de politique."),
               ("Désigner les vérificateurs", "Ajouter les vérificateurs couvrant chaque fonction concernée (production, CQ, ingénierie, affaires réglementaires selon le cas)."),
               ("Soumettre", "Cliquer sur [[Submit for Review]]. Le document passe *Under Review* et son contenu est verrouillé pour le rédacteur."),
               ("Revoir", "Les vérificateurs consignent leurs commentaires dans le fil de discussion. Un commentaire bloquant conduit l'approbateur à cliquer sur [[Reject]] avec un motif écrit ; le document revient en brouillon."),
               ("Approuver", "Un QMS Approver qui n'est pas l'auteur clique sur [[Approve]]. La date d'approbation est enregistrée."),
               ("Planifier la formation", "Si *Training Required* est coché, lancer la SOP-QA-012 avant la date d'application."),
               ("Publier", "À la date d'application, l'approbateur clique sur [[Publish]]. La révision précédente éventuelle devient automatiquement *Obsolete*."),
               ("Diffuser", "Informer les utilisateurs (fil de discussion, courriel, briefing). Retirer toute copie papier de la révision précédente."),
               ("Fichiers maîtrisés", "Pour un fichier dans ls_document_management : créer le document dans son dossier, charger le fichier avec [[New Version]], ajouter au moins un approbateur, [[Submit for Review]] ; chaque approbateur décide dans {{Documents ▸ My Approvals}} ; le Document Manager clique ensuite sur [[Publish]].")],
        controls=["Objet, domaine et mode opératoire d'une SOP doivent être remplis avant la soumission.",
                  "L'auteur d'un document ne peut pas l'approuver (séparation des tâches).",
                  "Une seule révision d'un document peut être publiée à la fois ; la publication retire la précédente.",
                  "La date d'application ne peut précéder la date d'approbation.",
                  "Le contenu publié ou obsolète ne peut plus être modifié — une nouvelle révision est nécessaire.",
                  "Seuls les brouillons peuvent être supprimés ; les autres documents doivent être rendus obsolètes.",
                  "Une instruction de travail ne peut être publiée tant que sa procédure parente ne l'est pas.",
                  "ls_document_management : pas de soumission sans version (fichier) ni au moins un approbateur ; seul un Document Manager publie ou archive ; chaque version porte une empreinte SHA-256 vérifiée."],
        good=["Un modèle par type de document, en conservant les rubriques de ls_qms.",
              "Choisir les vérificateurs par fonction, pas par disponibilité ; deux suffisent en général.",
              "Fixer la date d'application assez loin pour réaliser la formation (SOP-QA-012).",
              "Rédiger le motif de changement même pour la première révision (« nouvelle procédure »).",
              "Citer les boutons et menus exacts du logiciel dans les procédures qui utilisent la suite."],
        pitfalls=["Publier avant que les utilisateurs soient formés.",
                  "Approuver son propre document via un second compte — atteinte à l'intégrité des données.",
                  "Conserver des copies non maîtrisées (bureau, impressions) après publication d'une nouvelle révision.",
                  "Utiliser le fil de discussion pour modifier le contenu après approbation : le contenu est figé, créer une révision."],
        records=["La révision avec ses dates d'approbation et de publication", "Historique des commentaires de revue", "Motifs de rejet", "Enregistrements de formation (SOP-QA-012)"],
        kpis=["Délai médian entre soumission et approbation", "Nombre de rejets par document", "Documents publiés sans formation terminée (cible 0)"],
        example="**Cas.** L'entrepôt a besoin d'une procédure de cartographie de température. La chargée AQ crée *SOP – Cartographie en température des zones de stockage*, fixe une revue à 24 mois et coche *Training Required*. Elle désigne le responsable d'entrepôt et l'ingénieur validation comme vérificateurs et clique sur [[Submit for Review]]. L'ingénieur validation demande que le critère d'acceptation soit exprimé en °C ; l'approbateur clique sur [[Reject]] avec ce motif. Après correction, le document est resoumis et approuvé par la responsable AQ (qui n'en est pas l'auteur). Les sessions de formation ont lieu (SOP-QA-012) ; le 1er mars, l'approbateur clique sur [[Publish]] : la SOP entre en application et sa prochaine revue est calculée automatiquement (1er mars deux ans plus tard).",
    ),
)

QA002 = sop(
    "SOP-QA-002", "ls_qms · ls_document_management", "Quality Management ▸ Procedures ▸ New Revision / Set Obsolete",
    flows=[("dms_doc", tr("Lifecycle of a controlled file, including archiving.", "Cycle de vie d'un fichier maîtrisé, archivage compris."))],
    schematics=[("review_timeline", tr("A revision replaces the previous one, which becomes obsolete.", "Une révision remplace la précédente, qui devient obsolète."))],
    related=["SOP-QA-001", "SOP-QA-003", "SOP-QA-004", "SOP-QA-030"],
    refs=["EU-GMP-4", "ISO-13485", "CFR-211-180"],
    en=dict(
        title="Revision, withdrawal and archiving of documents",
        owner="QMS Manager",
        objective="Control changes to effective documents so that every change is justified, reviewed and approved, the previous revision is withdrawn from use at the right moment and remains retrievable for the retention period.",
        scope="Published documents of ls_qms and ls_document_management that must be changed, replaced or withdrawn.",
        roles=[("Document owner / QMS User", "Requests the revision, writes the reason for change and the new content."),
               ("QMS Approver", "Approves and publishes the new revision."),
               ("QMS Manager", "Withdraws (sets obsolete) documents that are no longer needed; checks references to them."),
               ("Document Manager", "Starts revisions and archives files in ls_document_management.")],
        defs=[("Obsolete", "A document that is no longer applicable. It remains readable for history but must not be used."),
              ("Archived (files)", "End state of a published controlled file; its retention period may start at archiving.")],
        steps=[("Decide the path", "Minor editorial change or substantive change? Substantive changes affecting product, process or validated state also require a change request (SOP-QA-030)."),
               ("Create the revision", "On the published document click [[New Revision]]. Enter the *Reason for Change* (mandatory). A new draft revision linked to the previous one is created; the current revision moves to *Under Revision* and remains the applicable revision until the new one is published."),
               ("Edit and route", "Edit the draft and route it through review and approval as in SOP-QA-001."),
               ("Publish", "Publishing the new revision retires the previous one to *Obsolete* automatically; its obsolete date is recorded."),
               ("Withdraw without replacement", "If the document is no longer needed, the QMS Manager clicks [[Set Obsolete]] after checking that no other published document refers to it (for a SOP, check its work instructions)."),
               ("Controlled files", "In ls_document_management, click [[Start Revision]] on a published document, add a new version with [[New Version]], then submit it for approval. To withdraw a file, the Document Manager clicks [[Archive]]."),
               ("Communicate", "Announce the change and its effective date; collect paper copies of the old revision.")],
        controls=["A reason for change is required to create a new revision.",
                  "Only one revision may be published; publishing retires the previous one.",
                  "Obsolete and published content cannot be edited.",
                  "Only draft documents can be deleted; published documents are made obsolete, never deleted.",
                  "ls_document_management: only published documents can enter revision or be archived; a published document cannot be deleted; versions are immutable."],
        good=["Summarise what changed in the reason for change (\"§5.3 temperature limit changed from 25 °C to 30 °C\").",
              "Check the documents that refer to the revised one; revise them together if necessary.",
              "Keep the effective date and the training of the new revision aligned (SOP-QA-012)."],
        pitfalls=["Making a substantive change without a change request.",
                  "Setting a SOP obsolete while its work instructions are still published.",
                  "Leaving the old revision printed at the workstation."],
        records=["Chain of revisions (Previous Revision / Following Revisions)", "Reason for change", "Obsolete date", "Archived file versions with checksums"],
        kpis=["Revisions per document per year", "Documents with overdue review", "Number of obsolete documents still referenced"],
        example="**Case.** An audit shows that the cleaning SOP still names a detergent that is no longer purchased. The owner opens the published SOP, clicks [[New Revision]] and writes: *\"§6.2 detergent X replaced by detergent Y (change CC-2026-014)\"*. The new draft is reviewed and approved. On publication, revision 3 becomes *Published* and revision 2 becomes *Obsolete* with today's date, and remains available for inspection.",
    ),
    fr=dict(
        title="Révision, mise en obsolescence et archivage des documents",
        owner="QMS Manager",
        objective="Maîtriser les modifications des documents en vigueur afin que chaque changement soit justifié, revu et approuvé, que la révision précédente soit retirée au bon moment et reste consultable pendant la durée de conservation.",
        scope="Documents publiés de ls_qms et de ls_document_management qui doivent être modifiés, remplacés ou retirés.",
        roles=[("Propriétaire / QMS User", "Demande la révision, rédige le motif de changement et le nouveau contenu."),
               ("QMS Approver", "Approuve et publie la nouvelle révision."),
               ("QMS Manager", "Retire (rend obsolètes) les documents devenus inutiles ; vérifie les renvois vers eux."),
               ("Document Manager", "Lance les révisions et archive les fichiers dans ls_document_management.")],
        defs=[("Obsolète", "Document qui ne s'applique plus. Il reste consultable pour l'historique mais ne doit pas être utilisé."),
              ("Archivé (fichiers)", "État final d'un fichier maîtrisé publié ; sa durée de conservation peut démarrer à l'archivage.")],
        steps=[("Choisir la voie", "Modification rédactionnelle mineure ou modification de fond ? Une modification de fond touchant le produit, le procédé ou l'état validé exige aussi une demande de changement (SOP-QA-030)."),
               ("Créer la révision", "Sur le document publié, cliquer sur [[New Revision]]. Saisir le motif (*Reason for Change*, obligatoire). Une nouvelle révision brouillon liée à la précédente est créée ; la révision courante passe à l'état *Under Revision* et reste la révision applicable jusqu'à la publication de la nouvelle."),
               ("Modifier et faire circuler", "Modifier le brouillon puis suivre la revue et l'approbation de la SOP-QA-001."),
               ("Publier", "La publication de la nouvelle révision fait passer automatiquement la précédente à *Obsolete* ; sa date d'obsolescence est enregistrée."),
               ("Retirer sans remplacement", "Si le document n'est plus nécessaire, le QMS Manager clique sur [[Set Obsolete]] après avoir vérifié qu'aucun autre document publié n'y renvoie (pour une SOP, vérifier ses instructions de travail)."),
               ("Fichiers maîtrisés", "Dans ls_document_management, cliquer sur [[Start Revision]] sur un document publié, ajouter une version avec [[New Version]], puis la soumettre à approbation. Pour retirer un fichier, le Document Manager clique sur [[Archive]]."),
               ("Communiquer", "Annoncer le changement et sa date d'application ; récupérer les copies papier de l'ancienne révision.")],
        controls=["Un motif de changement est exigé pour créer une révision.",
                  "Une seule révision publiée ; la publication retire la précédente.",
                  "Le contenu publié ou obsolète n'est pas modifiable.",
                  "Seuls les brouillons se suppriment ; un document publié est rendu obsolète, jamais supprimé.",
                  "ls_document_management : seuls les documents publiés peuvent entrer en révision ou être archivés ; un document publié ne peut être supprimé ; les versions sont immuables."],
        good=["Résumer ce qui change dans le motif (« §5.3 limite de température passée de 25 °C à 30 °C »).",
              "Vérifier les documents qui renvoient au document révisé ; les réviser ensemble si nécessaire.",
              "Aligner date d'application et formation de la nouvelle révision (SOP-QA-012)."],
        pitfalls=["Faire une modification de fond sans demande de changement.",
                  "Rendre obsolète une SOP dont les instructions de travail sont encore publiées.",
                  "Laisser l'ancienne révision imprimée au poste de travail."],
        records=["Chaîne des révisions (Previous Revision / Following Revisions)", "Motif de changement", "Date d'obsolescence", "Versions de fichiers archivées avec empreinte"],
        kpis=["Révisions par document et par an", "Documents en retard de revue", "Documents obsolètes encore référencés"],
        example="**Cas.** Un audit montre que la SOP de nettoyage cite un détergent qui n'est plus acheté. Le propriétaire ouvre la SOP publiée, clique sur [[New Revision]] et écrit : *« §6.2 détergent X remplacé par détergent Y (changement CC-2026-014) »*. Le brouillon est revu et approuvé. À la publication, la révision 3 devient *Published* et la révision 2 *Obsolete* à la date du jour ; elle reste disponible pour les inspections.",
    ),
)

QA003 = sop(
    "SOP-QA-003", "ls_qms", "Quality Management ▸ Reporting ▸ Procedures Due for Review",
    schematics=[("review_timeline", tr("Periodic review cycle computed from the effective date.", "Cycle de revue périodique calculé depuis la date d'application."))],
    related=["SOP-QA-001", "SOP-QA-002", "SOP-QA-004"],
    refs=["EU-GMP-4", "ISO-9001", "ISO-13485"],
    en=dict(
        title="Periodic review of documents",
        owner="QMS Manager",
        objective="Confirm at defined intervals that every effective document is still accurate, applicable and consistent with practice, regulations and other documents.",
        scope="All published ls_qms documents (policy, SOP, work instructions, quality plans) and controlled files whose owner defines a review.",
        roles=[("Document owner", "Performs the review and records its conclusion."),
               ("QMS Manager", "Monitors the list of documents due, escalates overdue reviews, reports the indicator to management review."),
               ("QMS Approver", "Approves the revision when the review concludes that a change is needed.")],
        defs=[("Review period", "Number of months between two reviews (field *Review Period (Months)*)."),
              ("Next review due", "Computed by the system: effective date + review period.")],
        steps=[("List the documents due", "Each month open {{Quality Management ▸ Reporting ▸ Procedures Due for Review}} and assign each document to its owner, with a due date."),
               ("Review the content", "The owner checks the document against current practice, recent deviations, CAPA, changes, audit findings and regulatory updates."),
               ("Conclude", "Either *no change needed* or *revision needed*. Record the conclusion as a quality record of type *Document Review Record* (SOP-QA-004) that refers to the document."),
               ("Revise if needed", "Create a new revision (SOP-QA-002). The review date restarts from the effective date of the new revision."),
               ("No change", "If no change is needed, the review period restarts only when a new revision becomes effective; to reset the next review date without content change, publish a revision whose reason for change states *\"periodic review — no change\"*, according to your policy."),
               ("Escalate", "Reviews overdue by more than one month are reported to the Head of QA and to management review.")],
        controls=["The next review date is computed from the effective date and the review period; the period cannot be negative.",
                  "Published content cannot be edited in place — any change goes through a new revision."],
        good=["Plan reviews in batches by process so related documents are reviewed together.",
              "Use the review to simplify: remove duplicated or unused documents.",
              "Decide in your document policy how a \"no change\" review is evidenced (review record only, or a new revision)."],
        pitfalls=["Signing off a review without reading the document against current practice.",
                  "Letting documents drift years past their review date."],
        records=["Quality record *Document Review Record* per review", "New revision when applicable"],
        kpis=["% of documents reviewed on time", "Number of documents overdue by more than 3 months (target 0)"],
        example="**Case.** In January, the report lists 12 procedures due. The QMS Manager assigns them. For SOP-QA-040 the owner finds that the acknowledgement time was shortened from 5 to 2 days by the complaint category configuration; she creates a new revision to align the text. For SOP-MET-001 no change is needed; she records a *Document Review Record* stating \"reviewed against CAPA-2025-031 and change CC-2025-044 — no change\".",
    ),
    fr=dict(
        title="Revue périodique des documents",
        owner="QMS Manager",
        objective="Confirmer à intervalles définis que chaque document en vigueur est toujours exact, applicable et cohérent avec la pratique, la réglementation et les autres documents.",
        scope="Tous les documents ls_qms publiés (politique, SOP, instructions, plans qualité) et les fichiers maîtrisés dont le propriétaire définit une revue.",
        roles=[("Propriétaire du document", "Réalise la revue et enregistre sa conclusion."),
               ("QMS Manager", "Suit la liste des documents dus, relance les revues en retard, présente l'indicateur en revue de direction."),
               ("QMS Approver", "Approuve la révision lorsque la revue conclut à un changement.")],
        defs=[("Période de revue", "Nombre de mois entre deux revues (champ *Review Period (Months)*)."),
              ("Prochaine revue", "Calculée par le système : date d'application + période de revue.")],
        steps=[("Lister les documents dus", "Chaque mois, ouvrir {{Quality Management ▸ Reporting ▸ Procedures Due for Review}} et attribuer chaque document à son propriétaire avec une échéance."),
               ("Revoir le contenu", "Le propriétaire compare le document à la pratique, aux déviations, CAPA, changements, constats d'audit et évolutions réglementaires récents."),
               ("Conclure", "Soit *pas de changement*, soit *révision nécessaire*. Consigner la conclusion dans un enregistrement qualité de type *Document Review Record* (SOP-QA-004) qui cite le document."),
               ("Réviser si besoin", "Créer une nouvelle révision (SOP-QA-002). La date de revue repart de la date d'application de la nouvelle révision."),
               ("Pas de changement", "Sans changement, la période de revue ne repart qu'à l'entrée en vigueur d'une nouvelle révision ; pour recaler la prochaine revue sans modifier le contenu, publier une révision dont le motif indique *« revue périodique — sans changement »*, selon votre politique."),
               ("Escalader", "Les revues en retard de plus d'un mois sont signalées à la responsable AQ et en revue de direction.")],
        controls=["La prochaine revue est calculée à partir de la date d'application et de la période ; la période ne peut être négative.",
                  "Le contenu publié n'est pas modifiable sur place — tout changement passe par une révision."],
        good=["Grouper les revues par processus pour revoir ensemble les documents liés.",
              "Profiter de la revue pour simplifier : supprimer les doublons et documents inutilisés.",
              "Décider dans la politique documentaire comment prouver une revue « sans changement » (enregistrement seul ou nouvelle révision)."],
        pitfalls=["Valider une revue sans confronter le document à la pratique.",
                  "Laisser des documents dépasser leur date de revue de plusieurs années."],
        records=["Enregistrement qualité *Document Review Record* par revue", "Nouvelle révision le cas échéant"],
        kpis=["% de documents revus dans les délais", "Documents en retard de plus de 3 mois (cible 0)"],
        example="**Cas.** En janvier, le rapport liste 12 procédures dues. Le QMS Manager les attribue. Pour la SOP-QA-040, la propriétaire constate que le délai d'accusé de réception a été ramené de 5 à 2 jours dans la configuration des catégories de réclamations ; elle crée une révision pour aligner le texte. Pour la SOP-MET-001, aucun changement : elle crée un *Document Review Record* indiquant « revue au regard de CAPA-2025-031 et CC-2025-044 — sans changement ».",
    ),
)

QA004 = sop(
    "SOP-QA-004", "ls_qms · ls_document_management", "Quality Management ▸ Quality Records · Documents ▸ Configuration ▸ Retention Policies",
    flows=[("qms_record", tr("Lifecycle of a quality record.", "Cycle de vie d'un enregistrement qualité."))],
    shots=[("ls_qms_quality_record__list", tr("Quality records with their retention date.", "Enregistrements qualité et leur date de conservation.")),
           ("ls_document_retention_policy__list", tr("Retention policies of controlled files.", "Politiques de conservation des fichiers maîtrisés."))],
    related=["SOP-QA-001", "SOP-DI-004"],
    refs=["EU-GMP-4", "CFR-211-180", "ISO-13485", "PICS-DI"],
    en=dict(
        title="Management and retention of quality records",
        owner="QMS Manager",
        objective="Ensure that quality records are complete, protected against unauthorised change, retained for the required period and disposed of only after that period, under control.",
        scope="Quality records of ls_qms (management review, meeting minutes, process verification, document review, objective review, customer feedback, internal communication, QMS change evaluation) and controlled files with a retention policy. Records produced by the other modules (batch records, deviations, calibrations…) are retained in their module and follow the same principles.",
        roles=[("QMS User", "Creates and completes the record; confirms it."),
               ("QMS Manager", "Sets retention periods, corrects confirmed records when justified (logged), archives and disposes of records."),
               ("Document Manager", "Maintains retention policies and legal holds of controlled files.")],
        defs=[("Retention period", "Minimum time a record must be kept (months). *Retain Until* is computed from the record date."),
              ("Legal hold", "Flag that suspends the end of retention of a controlled file (litigation, inspection)."),
              ("Disposal", "Controlled destruction of a record after its retention period.")],
        steps=[("Define retention rules", "The QMS Manager lists retention periods per record type from the regulations applicable to the products (for example batch-related records, medical device records) and configures them: *Retention Period (Months)* on quality records; in {{Documents ▸ Configuration ▸ Retention Policies}} the duration, unit, trigger (publication or archiving date), end-of-retention action (notify or archive) and advance notice."),
               ("Create the record", "In {{Quality Management ▸ Quality Records}} click [[New]], choose the *Record Type*, date, department, description, conclusion and the related policy, procedure, plan or objective. Attach supporting files."),
               ("Confirm", "When complete, click [[Confirm]]. From then on only a QMS Manager can correct it, and the correction is logged."),
               ("Archive", "When the record is no longer active, click [[Archive]]."),
               ("Monitor retention", "Use {{Quality Management ▸ Reporting ▸ Records Past Retention}} and the retention notices of ls_document_management."),
               ("Dispose", "After the *Retain Until* date and checking there is no legal hold, open inspection or litigation, the QMS Manager clicks [[Dispose]] and records the disposal decision.")],
        controls=["Only draft quality records can be deleted; others must be retained until the end of their retention period.",
                  "Confirmed records can only be corrected by a QMS Manager, and the correction is logged.",
                  "Only confirmed records can be archived; only archived records can be disposed of, and not before *Retain Until*.",
                  "Only a QMS Manager can dispose of records.",
                  "ls_document_management: retention duration limited to 200 years; legal hold available on documents."],
        good=["Base retention periods on the longest applicable requirement (product lifetime, market, contracts).",
              "Record the disposal decision itself as a quality record.",
              "Test periodically that archived records can still be read (see SOP-DI-004 for audit trail data)."],
        pitfalls=["Disposing of records needed for an ongoing investigation or litigation.",
                  "Keeping records in personal drives outside the controlled system."],
        records=["Quality records with state history", "Disposal decisions", "Retention policy configuration"],
        kpis=["Records past retention not yet processed", "Records confirmed more than 30 days after the activity"],
        example="**Case.** After the quarterly quality meeting, the secretary creates a quality record of type *Quality Meeting Minutes*, links it to the objective *Complaint closure time*, attaches the signed attendance list and clicks [[Confirm]]. The retention period is 120 months; *Retain Until* is computed automatically. Ten years later the record appears in *Records Past Retention*; the QMS Manager checks that no legal hold applies, clicks [[Archive]] then [[Dispose]].",
    ),
    fr=dict(
        title="Gestion et conservation des enregistrements qualité",
        owner="QMS Manager",
        objective="Garantir que les enregistrements qualité sont complets, protégés contre toute modification non autorisée, conservés pendant la durée requise et détruits seulement après cette durée, de façon maîtrisée.",
        scope="Enregistrements qualité de ls_qms (revue de direction, comptes rendus de réunion, vérification de procédé, revue documentaire, revue d'objectif, retour client, communication interne, évaluation de changement du SMQ) et fichiers maîtrisés dotés d'une politique de conservation. Les enregistrements produits par les autres modules (dossiers de lot, déviations, étalonnages…) sont conservés dans leur module selon les mêmes principes.",
        roles=[("QMS User", "Crée et complète l'enregistrement ; le confirme."),
               ("QMS Manager", "Fixe les durées de conservation, corrige les enregistrements confirmés si justifié (tracé), archive et détruit."),
               ("Document Manager", "Tient les politiques de conservation et les gels juridiques des fichiers maîtrisés.")],
        defs=[("Durée de conservation", "Temps minimal de conservation (mois). *Retain Until* est calculé depuis la date de l'enregistrement."),
              ("Gel juridique (Legal Hold)", "Indicateur qui suspend la fin de conservation d'un fichier (litige, inspection)."),
              ("Destruction", "Élimination maîtrisée d'un enregistrement après sa durée de conservation.")],
        steps=[("Définir les règles", "Le QMS Manager fixe les durées par type d'enregistrement d'après la réglementation applicable aux produits (par exemple dossiers de lot, dossiers de dispositifs médicaux) et les paramètre : *Retention Period (Months)* sur les enregistrements qualité ; dans {{Documents ▸ Configuration ▸ Retention Policies}}, durée, unité, déclencheur (date de publication ou d'archivage), action de fin (notifier ou archiver) et préavis."),
               ("Créer l'enregistrement", "Dans {{Quality Management ▸ Quality Records}}, cliquer sur [[New]], choisir le type (*Record Type*), la date, le service, la description, la conclusion et la politique, procédure, plan ou objectif lié. Joindre les pièces."),
               ("Confirmer", "Une fois complet, cliquer sur [[Confirm]]. Seul un QMS Manager peut ensuite le corriger, et la correction est tracée."),
               ("Archiver", "Quand l'enregistrement n'est plus actif, cliquer sur [[Archive]]."),
               ("Suivre la conservation", "Utiliser {{Quality Management ▸ Reporting ▸ Records Past Retention}} et les avis de fin de conservation de ls_document_management."),
               ("Détruire", "Après la date *Retain Until*, et après avoir vérifié l'absence de gel juridique, d'inspection ou de litige en cours, le QMS Manager clique sur [[Dispose]] et consigne la décision.")],
        controls=["Seuls les brouillons peuvent être supprimés ; les autres enregistrements sont conservés jusqu'à la fin de leur durée.",
                  "Un enregistrement confirmé n'est corrigible que par un QMS Manager, et la correction est tracée.",
                  "Seul un enregistrement confirmé peut être archivé ; seul un enregistrement archivé peut être détruit, et pas avant *Retain Until*.",
                  "Seul un QMS Manager peut détruire des enregistrements.",
                  "ls_document_management : durée de conservation limitée à 200 ans ; gel juridique disponible sur les documents."],
        good=["Fonder les durées sur l'exigence applicable la plus longue (durée de vie du produit, marché, contrats).",
              "Consigner la décision de destruction elle-même dans un enregistrement qualité.",
              "Vérifier périodiquement que les enregistrements archivés restent lisibles (voir SOP-DI-004 pour la piste d'audit)."],
        pitfalls=["Détruire des enregistrements nécessaires à une enquête ou un litige en cours.",
                  "Conserver des enregistrements sur des disques personnels hors du système maîtrisé."],
        records=["Enregistrements qualité avec historique d'état", "Décisions de destruction", "Paramétrage des politiques de conservation"],
        kpis=["Enregistrements échus non traités", "Enregistrements confirmés plus de 30 jours après l'activité"],
        example="**Cas.** Après la réunion qualité trimestrielle, la secrétaire crée un enregistrement de type *Quality Meeting Minutes*, le lie à l'objectif *Délai de clôture des réclamations*, joint la feuille d'émargement signée et clique sur [[Confirm]]. La durée est de 120 mois ; *Retain Until* est calculé automatiquement. Dix ans plus tard, l'enregistrement apparaît dans *Records Past Retention* ; le QMS Manager vérifie l'absence de gel juridique, clique sur [[Archive]] puis [[Dispose]].",
    ),
)

QA005 = sop(
    "SOP-QA-005", "ls_qms", "Quality Management ▸ Quality Objectives",
    flows=[("qms_objective", tr("Lifecycle of a quality objective.", "Cycle de vie d'un objectif qualité."))],
    shots=[("ls_qms_objective__form", tr("Quality objective with baseline, target and measurements.", "Objectif qualité avec valeur initiale, cible et mesures."))],
    related=["SOP-GEN-001", "SOP-GEN-002", "SOP-QA-004"],
    refs=["ISO-9001", "ISO-13485", "ICH-Q10"],
    en=dict(
        title="Quality objectives and measurement of their achievement",
        owner="Head of Quality / Management",
        objective="Translate the quality policy into measurable objectives, follow them with dated measurements and conclude on their achievement at the end of the period.",
        scope="All quality objectives of the company and its departments recorded in ls_qms.",
        roles=[("Top management", "Sets the objectives consistent with the quality policy and allocates resources."),
               ("Objective owner (*Responsible*)", "Records measurements, explains deviations from the trajectory, proposes actions."),
               ("QMS Manager", "Maintains the list of objectives, prepares the review for management review.")],
        defs=[("Direction", "*Increase*, *Decrease* or *Maintain*: the expected movement of the indicator."),
              ("Baseline / Target / Tolerance", "Starting value, value to reach, and accepted margin."),
              ("Performance status", "Computed: No Measurement, On Track, At Risk, Off Track, Target Reached.")],
        steps=[("Define", "In {{Quality Management ▸ Quality Objectives}} click [[New]]. Enter the objective, the related *Quality Policy*, department, responsible, start and target dates, direction, unit, baseline, target and tolerance."),
               ("Start", "Click [[Start]] at the beginning of the period."),
               ("Measure", "Add dated measurements at the planned frequency (monthly for example). The current value, achievement % and performance status are computed."),
               ("React", "When the status becomes *At Risk* or *Off Track*, the owner records the analysis in the chatter and, if the cause is systemic, raises a CAPA (SOP-QA-022)."),
               ("Close", "At the target date click [[Close as Achieved]] or [[Close as Not Achieved]]. Record the conclusion as a quality record of type *Quality Objective Review*."),
               ("Review", "Present all objectives in management review (SOP-GEN-001) and set the next period's objectives.")],
        controls=["For an *Increase* objective the target must be greater than the baseline; for *Decrease* it must be lower.",
                  "A measurement cannot be dated before the start date of the objective.",
                  "Only draft objectives can be started or deleted; others are cancelled.",
                  "An objective must be in progress to be closed."],
        good=["Use SMART objectives: one indicator, one number, one date, one owner.",
              "Limit the number of objectives so that each receives attention.",
              "Record the data source of each measurement in its note."],
        pitfalls=["Changing the target during the period to make it achievable — close and create a new objective instead.",
                  "Objectives without a link to the policy or to a real process risk."],
        records=["Objective with measurements and closure", "Quality Objective Review records", "Management review minutes"],
        kpis=["% of objectives achieved", "Objectives Off Track without action for more than one month"],
        example="**Case.** Objective *Reduce the median complaint closure time*: direction Decrease, unit days, baseline 48, target 30, tolerance 3, from January to December. Monthly measurements: 46, 44, 41… In June the value is 39 and the status turns *At Risk*; the owner notes that investigations wait for samples and raises CAPA-2026-022. In December the measurement is 29: the owner clicks [[Close as Achieved]].",
    ),
    fr=dict(
        title="Objectifs qualité et mesure de leur atteinte",
        owner="Direction / responsable qualité",
        objective="Traduire la politique qualité en objectifs mesurables, les suivre par des mesures datées et conclure sur leur atteinte en fin de période.",
        scope="Tous les objectifs qualité de l'entreprise et de ses services enregistrés dans ls_qms.",
        roles=[("Direction", "Fixe des objectifs cohérents avec la politique qualité et alloue les ressources."),
               ("Responsable de l'objectif (*Responsible*)", "Saisit les mesures, explique les écarts de trajectoire, propose des actions."),
               ("QMS Manager", "Tient la liste des objectifs, prépare la revue pour la revue de direction.")],
        defs=[("Sens (Direction)", "*Increase*, *Decrease* ou *Maintain* : évolution attendue de l'indicateur."),
              ("Valeur initiale / cible / tolérance", "Baseline, Target et Tolerance : point de départ, valeur à atteindre et marge admise."),
              ("Statut de performance", "Calculé : No Measurement, On Track, At Risk, Off Track, Target Reached.")],
        steps=[("Définir", "Dans {{Quality Management ▸ Quality Objectives}}, cliquer sur [[New]]. Saisir l'objectif, la politique qualité liée, le service, le responsable, les dates de début et de cible, le sens, l'unité, la valeur initiale, la cible et la tolérance."),
               ("Démarrer", "Cliquer sur [[Start]] en début de période."),
               ("Mesurer", "Ajouter des mesures datées à la fréquence prévue (mensuelle par exemple). La valeur courante, le % d'atteinte et le statut sont calculés."),
               ("Réagir", "Quand le statut passe *At Risk* ou *Off Track*, le responsable consigne son analyse dans le fil de discussion et, si la cause est systémique, ouvre une CAPA (SOP-QA-022)."),
               ("Clore", "À la date cible, cliquer sur [[Close as Achieved]] ou [[Close as Not Achieved]]. Consigner la conclusion dans un enregistrement *Quality Objective Review*."),
               ("Revoir", "Présenter l'ensemble des objectifs en revue de direction (SOP-GEN-001) et fixer ceux de la période suivante.")],
        controls=["Pour un objectif *Increase*, la cible doit dépasser la valeur initiale ; pour *Decrease*, elle doit lui être inférieure.",
                  "Une mesure ne peut être datée avant le début de l'objectif.",
                  "Seuls les objectifs brouillons peuvent être démarrés ou supprimés ; les autres sont annulés.",
                  "Un objectif doit être en cours pour être clos."],
        good=["Objectifs SMART : un indicateur, un chiffre, une date, un responsable.",
              "Limiter le nombre d'objectifs pour que chacun soit réellement suivi.",
              "Indiquer la source de données de chaque mesure dans sa note."],
        pitfalls=["Modifier la cible en cours de période pour la rendre atteignable — clore et créer un nouvel objectif.",
                  "Objectifs sans lien avec la politique ni avec un risque réel du processus."],
        records=["Objectif avec mesures et clôture", "Enregistrements Quality Objective Review", "Comptes rendus de revue de direction"],
        kpis=["% d'objectifs atteints", "Objectifs Off Track sans action depuis plus d'un mois"],
        example="**Cas.** Objectif *Réduire le délai médian de clôture des réclamations* : sens Decrease, unité jours, initiale 48, cible 30, tolérance 3, de janvier à décembre. Mesures mensuelles : 46, 44, 41… En juin la valeur est 39 et le statut passe *At Risk* ; le responsable note que les enquêtes attendent les échantillons et ouvre la CAPA-2026-022. En décembre la mesure est 29 : il clique sur [[Close as Achieved]].",
    ),
)

M_TRAIN = module(
    "mod-training", "ls_training", "Training", "Formation",
    [
        ("p", "ls_training manages a controlled course catalogue (Draft → Under Review → Approved → Obsolete), sessions "
              "with attendance and assessment scores, certifications issued automatically when a session closes, "
              "training requirements by job position, department or employee, a training matrix, and competency "
              "assessments that are distinct from attendance. Certification status (Valid, Expiring Soon, Expired, "
              "Revoked) is refreshed nightly and reminders are sent before expiry."),
        ("table", ["Menu", "Content"], [
            ["{{Training ▸ Configuration ▸ Courses / Competencies / Training Requirements}}", "Catalogue and rules"],
            ["{{Training ▸ Operations ▸ Sessions / Attendance / Certifications / Competency Assessments}}", "Delivery and evidence"],
            ["{{Training ▸ Operations ▸ Expiring and Expired}}", "Certifications to renew"],
            ["{{Training ▸ Reporting ▸ Training Matrix}}", "Employee × course compliance matrix"],
        ]),
        ("table", ["Group", "Main rights"], [
            ["Learner · Viewer", "Read own records / all records"],
            ["Trainer", "Runs sessions, records attendance and scores"],
            ["Manager", "Approves courses, manages requirements, revokes certifications"],
        ]),
        ("box", "warn", "Regulatory position stated by the module", "The module README states that ls_training does not implement 21 CFR Part 11 (no electronic signature, no field-level audit trail of its own). If training records are GxP records in your organisation, cover them with ls_audit_trail rules (SOP-DI-001) and state the approach in your validation."),
        ("schematic", "training", "The training loop."),
        ("flow", "training_session", "Lifecycle of a training session."),
        ("shot", "ls_training_course__list", "Course catalogue."),
    ],
    [
        ("p", "ls_training gère un catalogue de cours maîtrisé (Draft → Under Review → Approved → Obsolete), des sessions avec "
              "présence et note d'évaluation, des certifications émises automatiquement à la clôture de la session, des "
              "exigences de formation par poste, service ou salarié, une matrice de formation, et des évaluations de "
              "compétence distinctes de la simple présence. Le statut des certifications (Valid, Expiring Soon, Expired, "
              "Revoked) est recalculé chaque nuit et des rappels sont envoyés avant expiration."),
        ("table", ["Menu", "Contenu"], [
            ["{{Training ▸ Configuration ▸ Courses / Competencies / Training Requirements}}", "Catalogue et règles"],
            ["{{Training ▸ Operations ▸ Sessions / Attendance / Certifications / Competency Assessments}}", "Réalisation et preuves"],
            ["{{Training ▸ Operations ▸ Expiring and Expired}}", "Certifications à renouveler"],
            ["{{Training ▸ Reporting ▸ Training Matrix}}", "Matrice de conformité salarié × cours"],
        ]),
        ("table", ["Groupe", "Droits principaux"], [
            ["Learner · Viewer", "Lecture de ses propres enregistrements / de tous"],
            ["Trainer", "Anime les sessions, enregistre présence et notes"],
            ["Manager", "Approuve les cours, gère les exigences, révoque les certifications"],
        ]),
        ("box", "warn", "Position réglementaire affichée par le module", "Le README du module indique que ls_training n'implémente pas le 21 CFR Part 11 (pas de signature électronique ni de piste d'audit propre au niveau des champs). Si les enregistrements de formation sont des enregistrements GxP chez vous, couvrez-les par des règles ls_audit_trail (SOP-DI-001) et décrivez l'approche dans votre validation."),
        ("schematic", "training", "La boucle de formation."),
        ("flow", "training_session", "Cycle de vie d'une session de formation."),
        ("shot", "ls_training_course__list", "Catalogue des cours."),
    ],
)

QA010 = sop(
    "SOP-QA-010", "ls_training", "Training ▸ Configuration ▸ Courses",
    flows=[("training_course", tr("Lifecycle of a course.", "Cycle de vie d'un cours."))],
    shots=[("ls_training_course__form", tr("Course form: type, delivery mode, validity, pass score.", "Fiche cours : type, mode, validité, note de réussite."))],
    related=["SOP-QA-011", "SOP-QA-012", "SOP-QA-013"],
    refs=["EU-GMP-2", "CFR-211-25", "ISO-13485", "ISO-22716"],
    en=dict(
        title="Creation and approval of training courses",
        owner="Training Manager",
        objective="Ensure that every course used as evidence of qualification has approved content, learning objectives, a defined assessment rule and a validity period.",
        scope="All courses of the catalogue: induction, GMP/GxP, procedure/SOP, technical, health and safety, quality system and regulatory courses, whatever the delivery mode.",
        roles=[("Course author (Trainer)", "Writes the content and objectives, proposes the assessment and validity."),
               ("Subject-matter reviewer", "Checks technical accuracy."),
               ("Training Manager", "Approves the course, makes obsolete courses that are no longer valid.")],
        defs=[("Delivery mode", "Classroom, On-the-Job, Self-Study or External e-Learning (an e-Learning URL is then mandatory)."),
              ("Certification validity", "Months during which the certification stays valid; 0 means no expiry."),
              ("Pass score", "Score (%) to reach when the course requires an assessment.")],
        steps=[("Create", "In {{Training ▸ Configuration ▸ Courses}} click [[New]]. Enter name, code, version, course type, delivery mode, duration (hours), learning objectives and content."),
               ("Define assessment", "Tick *Requires Assessment* and set the pass score if knowledge must be tested (for example a written quiz for a critical SOP)."),
               ("Set validity", "Enter the certification validity in months according to the risk (for example 12 months for aseptic behaviour, 0 for a one-off induction module)."),
               ("Link competencies", "Link the competencies the course contributes to."),
               ("Submit and approve", "Click [[Submit for Review]]; the Training Manager checks and clicks [[Approve]]. Only approved courses can be scheduled."),
               ("Retire", "When the course is replaced, close or cancel its open sessions, then click [[Make Obsolete]].")],
        controls=["Duration must be greater than zero; the pass score must lie between 0 and 100; validity cannot be negative.",
                  "An External e-Learning course requires an e-Learning URL.",
                  "Only a draft course can be submitted; only a course under review can be approved; only an approved course can be made obsolete.",
                  "A course with open sessions cannot be made obsolete.",
                  "The course version in force is frozen onto every certification issued."],
        good=["For a SOP course, use the SOP reference as course code and its revision as course version.",
              "Write measurable learning objectives (\"The operator can perform a line clearance\").",
              "Prefer on-the-job training with competency assessment for practical skills."],
        pitfalls=["Using the same course for several SOP revisions without changing its version.",
                  "A pass score set so low that the assessment proves nothing."],
        records=["Approved course with version", "Course content"],
        kpis=["Courses under review for more than 30 days", "Courses without assessment for critical tasks"],
        example="**Case.** For SOP-PRD-002 *Line clearance*, the trainer creates course code *SOP-PRD-002*, version *3*, type *Procedure / SOP*, delivery *On-the-Job*, duration 1 h, with an assessment (pass score 100 %: the trainee must perform the clearance without error) and a 24-month validity. The Training Manager approves it.",
    ),
    fr=dict(
        title="Création et approbation des cours de formation",
        owner="Responsable formation",
        objective="Garantir que chaque cours servant de preuve de qualification a un contenu approuvé, des objectifs pédagogiques, une règle d'évaluation et une durée de validité définies.",
        scope="Tous les cours du catalogue : accueil, BPF/GxP, procédure/SOP, technique, hygiène-sécurité, système qualité et réglementaire, quel que soit le mode de délivrance.",
        roles=[("Auteur du cours (Trainer)", "Rédige le contenu et les objectifs, propose l'évaluation et la validité."),
               ("Vérificateur métier", "Vérifie l'exactitude technique."),
               ("Responsable formation (Manager)", "Approuve le cours, rend obsolètes les cours qui ne sont plus valables.")],
        defs=[("Mode de délivrance", "Classroom, On-the-Job, Self-Study ou External e-Learning (une URL est alors obligatoire)."),
              ("Validité de la certification", "Nombre de mois de validité ; 0 signifie sans expiration."),
              ("Note de réussite", "Score (%) à atteindre si le cours exige une évaluation.")],
        steps=[("Créer", "Dans {{Training ▸ Configuration ▸ Courses}}, cliquer sur [[New]]. Saisir nom, code, version, type de cours, mode, durée (heures), objectifs pédagogiques et contenu."),
               ("Définir l'évaluation", "Cocher *Requires Assessment* et fixer la note de réussite si les connaissances doivent être testées (par exemple un QCM pour une SOP critique)."),
               ("Fixer la validité", "Saisir la validité en mois selon le risque (par exemple 12 mois pour le comportement en zone aseptique, 0 pour un module d'accueil ponctuel)."),
               ("Relier les compétences", "Lier les compétences auxquelles le cours contribue."),
               ("Soumettre et approuver", "Cliquer sur [[Submit for Review]] ; le responsable formation vérifie et clique sur [[Approve]]. Seuls les cours approuvés peuvent être planifiés."),
               ("Retirer", "Quand le cours est remplacé, clore ou annuler ses sessions ouvertes, puis cliquer sur [[Make Obsolete]].")],
        controls=["La durée doit être positive ; la note de réussite comprise entre 0 et 100 ; la validité ne peut être négative.",
                  "Un cours External e-Learning exige une URL.",
                  "Seul un brouillon peut être soumis ; seul un cours en revue peut être approuvé ; seul un cours approuvé peut devenir obsolète.",
                  "Un cours ayant des sessions ouvertes ne peut être rendu obsolète.",
                  "La version du cours en vigueur est figée sur chaque certification émise."],
        good=["Pour un cours de SOP, utiliser la référence de la SOP comme code et sa révision comme version.",
              "Rédiger des objectifs mesurables (« L'opérateur sait réaliser un vide de ligne »).",
              "Préférer la formation au poste avec évaluation de compétence pour les gestes pratiques."],
        pitfalls=["Utiliser le même cours pour plusieurs révisions de SOP sans changer sa version.",
                  "Une note de réussite si basse que l'évaluation ne prouve rien."],
        records=["Cours approuvé avec sa version", "Contenu du cours"],
        kpis=["Cours en revue depuis plus de 30 jours", "Cours sans évaluation pour des tâches critiques"],
        example="**Cas.** Pour la SOP-PRD-002 *Vide de ligne*, le formateur crée le cours de code *SOP-PRD-002*, version *3*, type *Procedure / SOP*, mode *On-the-Job*, durée 1 h, avec évaluation (réussite 100 % : le stagiaire doit réaliser le vide de ligne sans erreur) et validité 24 mois. Le responsable formation l'approuve.",
    ),
)

QA011 = sop(
    "SOP-QA-011", "ls_training", "Training ▸ Operations ▸ Sessions",
    flows=[("training_session", tr("Lifecycle of a session.", "Cycle de vie d'une session.")),
           ("training_cert", tr("Statuses of a certification.", "Statuts d'une certification."))],
    shots=[("ls_training_session__form", tr("Session with attendees, outcomes and issued certifications.", "Session avec participants, résultats et certifications émises."))],
    related=["SOP-QA-010", "SOP-QA-013"],
    refs=["EU-GMP-2", "CFR-211-25", "ISO-13485"],
    en=dict(
        title="Session planning and issue of certifications",
        owner="Training Manager",
        objective="Plan and deliver training sessions so that attendance and assessment results are recorded as evidence and certifications are issued only to people who met the course rule.",
        scope="All sessions of approved courses, internal or external trainer. Externally delivered training may also be recorded as a manual certification.",
        roles=[("Training coordinator (Trainer)", "Creates sessions, registers employees, records attendance and scores, closes the session."),
               ("Trainer", "Delivers the session and assesses attendees."),
               ("Training Manager", "Supervises, revokes certifications when needed.")],
        defs=[("Outcome", "Computed from recorded evidence: presence and, when required, score ≥ pass mark. Absence yields *Pending*, not *Failed*."),
              ("Certification", "Append-only evidence issued at session closure; renewal creates a new record.")],
        steps=[("Create the session", "In {{Training ▸ Operations ▸ Sessions}} click [[New]], select the approved course, start and end, trainer (internal *or* external), location and maximum attendees."),
               ("Register", "Click [[Register Employees]]: select employees, a department, a job position or a training requirement; optionally exclude employees who already hold a valid certification."),
               ("Confirm", "Click [[Confirm]] once the list is final (at least one attendee)."),
               ("Deliver", "Click [[Start]] at the beginning; in the *Attendees* tab tick *Attended* for each person present and enter the assessment *Score*."),
               ("Close", "Click [[Close and Issue Certifications]]. Each attendee who meets the rule receives a certification carrying the course version; validity is computed from the course."),
               ("Handle absentees", "Absent employees remain *Pending*; register them in a later session."),
               ("Revoke if needed", "If a certification was issued wrongly, a Manager opens it and clicks [[Revoke]] with a documented reason. Certifications are never deleted.")],
        controls=["A session must end after it starts and cannot exceed its maximum attendees.",
                  "A session names either an internal or an external trainer, not both.",
                  "Only a draft session can be confirmed and it needs at least one attendee; only a confirmed session can start; only a session in progress can be closed.",
                  "A session cannot be closed while an attendee has no recorded outcome.",
                  "Attendance scores lie between 0 and 100; an employee of another company cannot attend.",
                  "Once closed, attendance evidence and the course, dates and trainer are frozen; the session can no longer be cancelled.",
                  "Certifications cannot be deleted; revocation needs a reason."],
        good=["Keep the signed attendance sheet of classroom sessions as an attachment.",
              "Record the score as soon as the assessment is corrected, not days later.",
              "For external training, attach the provider's certificate to the manual certification."],
        pitfalls=["Marking an employee attended because \"he read the SOP\" without assessment when the course requires one.",
                  "Closing the session before scores are entered."],
        records=["Session with attendance and scores", "Certifications (PDF Training Certificate)", "Individual Training Record (PDF per employee)"],
        kpis=["Sessions closed more than 5 days after the end", "Pass rate per course", "Certifications revoked"],
        example="**Case.** Session *SOP-PRD-002 v3 — 12 May* for the packaging team: 8 employees registered through the job position *Packaging operator*, 2 excluded because already certified. After the practical assessment, 7 score 100 %; one scores 80 % and fails. On [[Close and Issue Certifications]], 7 certifications valid 24 months are issued; the failed employee is registered in the next session.",
    ),
    fr=dict(
        title="Planification des sessions et émission des certifications",
        owner="Responsable formation",
        objective="Planifier et réaliser les sessions pour que présence et résultats d'évaluation soient enregistrés comme preuves, et que les certifications ne soient délivrées qu'aux personnes ayant satisfait à la règle du cours.",
        scope="Toutes les sessions des cours approuvés, formateur interne ou externe. Une formation suivie à l'extérieur peut aussi être enregistrée comme certification manuelle.",
        roles=[("Coordinateur formation (Trainer)", "Crée les sessions, inscrit les salariés, saisit présence et notes, clôt la session."),
               ("Formateur", "Anime la session et évalue les participants."),
               ("Responsable formation (Manager)", "Supervise, révoque les certifications si nécessaire.")],
        defs=[("Résultat", "Calculé à partir des preuves : présence et, si exigé, note ≥ seuil. Une absence donne *Pending*, pas *Failed*."),
              ("Certification", "Preuve en ajout seul émise à la clôture ; un renouvellement crée un nouvel enregistrement.")],
        steps=[("Créer la session", "Dans {{Training ▸ Operations ▸ Sessions}}, cliquer sur [[New]], choisir le cours approuvé, début et fin, formateur (interne *ou* externe), lieu et nombre maximal de participants."),
               ("Inscrire", "Cliquer sur [[Register Employees]] : choisir des salariés, un service, un poste ou une exigence de formation ; exclure éventuellement ceux qui ont déjà une certification valide."),
               ("Confirmer", "Cliquer sur [[Confirm]] quand la liste est définitive (au moins un participant)."),
               ("Réaliser", "Cliquer sur [[Start]] au début ; dans l'onglet des participants, cocher *Attended* pour chaque présent et saisir la note (*Score*)."),
               ("Clore", "Cliquer sur [[Close and Issue Certifications]]. Chaque participant qui satisfait à la règle reçoit une certification portant la version du cours ; la validité est calculée depuis le cours."),
               ("Gérer les absents", "Les absents restent *Pending* ; les inscrire à une session ultérieure."),
               ("Révoquer si besoin", "Si une certification a été émise à tort, un Manager l'ouvre et clique sur [[Revoke]] avec un motif documenté. Les certifications ne sont jamais supprimées.")],
        controls=["Une session doit finir après avoir commencé et ne peut dépasser son effectif maximal.",
                  "Une session désigne un formateur interne ou externe, pas les deux.",
                  "Seul un brouillon peut être confirmé, avec au moins un participant ; seule une session confirmée peut démarrer ; seule une session en cours peut être close.",
                  "Pas de clôture tant qu'un participant n'a pas de résultat enregistré.",
                  "Les notes sont comprises entre 0 et 100 ; un salarié d'une autre société ne peut participer.",
                  "Après clôture, les preuves de présence ainsi que cours, dates et formateur sont figés ; la session ne peut plus être annulée.",
                  "Les certifications ne se suppriment pas ; la révocation exige un motif."],
        good=["Joindre la feuille d'émargement signée des sessions en salle.",
              "Saisir la note dès la correction de l'évaluation, pas plusieurs jours après.",
              "Pour une formation externe, joindre l'attestation du prestataire à la certification manuelle."],
        pitfalls=["Marquer un salarié présent parce qu'« il a lu la SOP » sans évaluation alors que le cours en exige une.",
                  "Clore la session avant la saisie des notes."],
        records=["Session avec présences et notes", "Certifications (PDF Training Certificate)", "Dossier individuel de formation (PDF par salarié)"],
        kpis=["Sessions closes plus de 5 jours après la fin", "Taux de réussite par cours", "Certifications révoquées"],
        example="**Cas.** Session *SOP-PRD-002 v3 — 12 mai* pour l'équipe conditionnement : 8 salariés inscrits via le poste *Opérateur conditionnement*, 2 exclus car déjà certifiés. Après l'évaluation pratique, 7 obtiennent 100 % ; un obtient 80 % et échoue. À [[Close and Issue Certifications]], 7 certifications valables 24 mois sont émises ; le salarié en échec est inscrit à la session suivante.",
    ),
)

QA012 = sop(
    "SOP-QA-012", "ls_qms · ls_training", "Quality Management ▸ Procedures · Training ▸ Configuration ▸ Training Requirements",
    related=["SOP-QA-001", "SOP-QA-010", "SOP-QA-011", "SOP-QA-013"],
    refs=["EU-GMP-2", "EU-GMP-4", "CFR-211-25"],
    en=dict(
        title="Training linked to the publication of a new document",
        owner="QMS Manager with the Training Manager",
        objective="Ensure that nobody applies a new or revised procedure before being trained on it, and that the training evidence refers to the exact revision.",
        scope="Every ls_qms document with *Training Required* ticked, and every revision of such a document.",
        roles=[("Document author", "Ticks *Training Required*, identifies the target population and the training method."),
               ("Training Manager", "Creates or revises the course, the requirement and the sessions."),
               ("QMS Approver", "Publishes only when the training completion criterion is met."),
               ("Line managers", "Release their staff for training; do not assign untrained staff to the task.")],
        defs=[("Target population", "Job positions, departments or named employees who apply the document."),
              ("Completion criterion", "Proportion of the target population to be trained before publication (for example 100 % of the people on duty).")],
        steps=[("Flag the need", "In the draft document, tick *Training Required* and describe in the reason for change what is new."),
               ("Create or version the course", "On approval, the Training Manager creates the course (or a new version of it) with code = document reference, version = document revision (SOP-QA-010)."),
               ("Define the requirement", "In {{Training ▸ Configuration ▸ Training Requirements}} create the requirement: required course, job position / department / employee, *Mandatory*, and a grace period in days for newcomers."),
               ("Train", "Run sessions (SOP-QA-011). Use *Register Employees* by training requirement so nobody is forgotten."),
               ("Check completion", "Generate the matrix ({{Training ▸ Reporting ▸ Training Matrix}}) filtered on the course and check the gaps."),
               ("Publish", "The approver publishes the document once the completion criterion is met (SOP-QA-001) and records the training status in the chatter."),
               ("Catch up", "Employees absent at publication are trained before performing the task; line managers enforce it.")],
        controls=["There is no automatic link between a published document and a training course: the SOP flag *Training Required* is informative, and the course, requirement and sessions are created by people. This SOP is the control.",
                  "A training requirement must target an employee, a job position or a department, and cannot be duplicated.",
                  "Only approved courses can be scheduled; the course version is frozen on each certification."],
        good=["Use \"read and understand\" self-study with a short quiz only for minor revisions; use classroom or on-the-job training for substantive changes.",
              "Plan the effective date after the training capacity is known.",
              "Keep one course per SOP, versioned, rather than a new course per revision."],
        pitfalls=["Publishing on the approval date by default, before anyone is trained.",
                  "Forgetting night shifts and temporary staff in the target population."],
        records=["Course version", "Training requirement", "Certifications", "Training matrix extract attached to the publication note"],
        kpis=["% of target population trained at publication", "Tasks performed by untrained staff (from audits; target 0)"],
        example="**Case.** SOP-QA-020 revision 5 changes the deviation classification. The author ticks *Training Required*. After approval the Training Manager creates version 5 of course SOP-QA-020 and a requirement for the job positions *QA officer* and *Production supervisor*. Two sessions train 22 of 24 people. The matrix shows two people on leave; the approver publishes with the note \"22/24 trained, 2 on leave, trained on return before any deviation assessment\".",
    ),
    fr=dict(
        title="Formation liée à la publication d'un nouveau document",
        owner="QMS Manager avec le responsable formation",
        objective="Garantir que personne n'applique une procédure nouvelle ou révisée sans y avoir été formé, et que la preuve de formation désigne la révision exacte.",
        scope="Tout document ls_qms pour lequel *Training Required* est coché, et chaque révision d'un tel document.",
        roles=[("Rédacteur du document", "Coche *Training Required*, identifie la population cible et la méthode de formation."),
               ("Responsable formation", "Crée ou révise le cours, l'exigence et les sessions."),
               ("QMS Approver", "Ne publie que lorsque le critère de complétude de la formation est atteint."),
               ("Encadrement", "Libère le personnel pour la formation ; n'affecte pas de personnel non formé à la tâche.")],
        defs=[("Population cible", "Postes, services ou salariés nommés qui appliquent le document."),
              ("Critère de complétude", "Proportion de la population cible à former avant publication (par exemple 100 % du personnel en poste).")],
        steps=[("Signaler le besoin", "Dans le brouillon, cocher *Training Required* et décrire dans le motif de changement ce qui est nouveau."),
               ("Créer ou versionner le cours", "À l'approbation, le responsable formation crée le cours (ou une nouvelle version) avec code = référence du document, version = révision du document (SOP-QA-010)."),
               ("Définir l'exigence", "Dans {{Training ▸ Configuration ▸ Training Requirements}}, créer l'exigence : cours requis, poste / service / salarié, *Mandatory*, délai de grâce en jours pour les nouveaux arrivants."),
               ("Former", "Réaliser les sessions (SOP-QA-011). Utiliser *Register Employees* par exigence de formation pour n'oublier personne."),
               ("Vérifier la complétude", "Générer la matrice ({{Training ▸ Reporting ▸ Training Matrix}}) filtrée sur le cours et examiner les écarts."),
               ("Publier", "L'approbateur publie le document lorsque le critère est atteint (SOP-QA-001) et consigne l'état de la formation dans le fil de discussion."),
               ("Rattraper", "Les absents à la publication sont formés avant d'exécuter la tâche ; l'encadrement y veille.")],
        controls=["Il n'existe pas de lien automatique entre un document publié et un cours : l'indicateur *Training Required* de la SOP est informatif, et cours, exigence et sessions sont créés par des personnes. Cette SOP est le contrôle.",
                  "Une exigence de formation doit viser un salarié, un poste ou un service, et ne peut être dupliquée.",
                  "Seuls les cours approuvés se planifient ; la version du cours est figée sur chaque certification."],
        good=["Réserver l'autoformation « lu et compris » avec court QCM aux révisions mineures ; formation en salle ou au poste pour les changements de fond.",
              "Fixer la date d'application après avoir estimé la capacité de formation.",
              "Garder un cours par SOP, versionné, plutôt qu'un nouveau cours par révision."],
        pitfalls=["Publier par défaut le jour de l'approbation, avant toute formation.",
                  "Oublier les équipes de nuit et les intérimaires dans la population cible."],
        records=["Version du cours", "Exigence de formation", "Certifications", "Extrait de matrice joint à la note de publication"],
        kpis=["% de la population cible formée à la publication", "Tâches réalisées par du personnel non formé (audits ; cible 0)"],
        example="**Cas.** La révision 5 de la SOP-QA-020 modifie la classification des déviations. Le rédacteur coche *Training Required*. Après approbation, le responsable formation crée la version 5 du cours SOP-QA-020 et une exigence pour les postes *Chargé AQ* et *Chef d'équipe production*. Deux sessions forment 22 personnes sur 24. La matrice montre deux personnes en congé ; l'approbateur publie avec la note « 22/24 formés, 2 en congé, formés au retour avant toute évaluation de déviation ».",
    ),
)

QA013 = sop(
    "SOP-QA-013", "ls_training", "Training ▸ Reporting ▸ Training Matrix · Operations ▸ Competency Assessments",
    flows=[("training_cert", tr("Certification statuses refreshed nightly.", "Statuts de certification recalculés chaque nuit."))],
    schematics=[("training", tr("Requirement, certification, expiry and matrix.", "Exigence, certification, expiration et matrice."))],
    related=["SOP-QA-011", "SOP-QA-012", "SOP-DI-011"],
    refs=["EU-GMP-2", "CFR-211-25", "ISO-13485", "ISO-22716"],
    en=dict(
        title="Follow-up of qualifications and requalification",
        owner="Training Manager",
        objective="Know at any time who is qualified for which task, renew qualifications before they expire, and assess competence where attendance alone is not enough.",
        scope="All mandatory training requirements, certifications with an expiry, and competencies requiring periodic assessment.",
        roles=[("Training Manager", "Runs the matrix monthly, plans renewals, reports gaps."),
               ("Line manager / assessor", "Performs competency assessments of their staff (not of themselves)."),
               ("Employee", "Follows reminders and attends renewal sessions.")],
        defs=[("Matrix cell status", "Valid, Expiring Soon, Expired, Revoked or Not Trained for each employee × course."),
              ("Competency assessment", "Evidence that a person can do the job: named assessor, demonstrated level (Not Demonstrated, Developing, Proficient, Expert), evidence, confirmation lock.")],
        steps=[("Generate the matrix", "Monthly, open {{Training ▸ Reporting ▸ Training Matrix}}, click [[Generate Matrix]] and apply the *Gaps* filter."),
               ("Treat expiring certifications", "Use {{Training ▸ Operations ▸ Expiring and Expired}}; schedule renewal sessions before the expiry date. The system sends daily reminders within the warning window."),
               ("Act on expired or missing training", "The line manager removes the employee from the task until retrained; record the decision."),
               ("Assess competence", "In {{Training ▸ Operations ▸ Competency Assessments}} create the assessment: employee, competency, assessor, date, demonstrated level, evidence; set the next assessment date when the competency requires reassessment; click [[Confirm]]."),
               ("Report", "Report the compliance rate per department to management review.")],
        controls=["Certification status is computed from the expiry date and refreshed nightly; certifications are never deleted.",
                  "An employee cannot assess their own competency.",
                  "A competency assessment cannot be confirmed without evidence and cannot be modified or deleted once confirmed.",
                  "The next assessment date cannot precede the assessment date."],
        good=["Link critical access rights (e.g. batch release) to a valid qualification and review them together (SOP-IT-001).",
              "Use competency assessments for aseptic operators, analysts and auditors.",
              "Plan renewals in the annual training plan rather than waiting for reminders."],
        pitfalls=["Treating an expired certification as \"administrative\" and letting the employee keep working.",
                  "Line managers assessing competencies they have not observed."],
        records=["Training matrix extracts", "Certifications and renewals", "Competency assessments"],
        kpis=["Compliance rate (mandatory requirements met)", "Expired certifications of active staff (target 0)", "Competency reassessments overdue"],
        example="**Case.** The March matrix shows 3 *Expired* cells for the course *Aseptic gowning* in the filling team. The Training Manager informs the supervisor, who removes the three operators from Grade A/B work. A renewal session is held 4 days later; the new certifications are valid 12 months. In parallel, the supervisor confirms a competency assessment *Aseptic behaviour — Proficient* for each operator, based on an observed media fill.",
    ),
    fr=dict(
        title="Suivi des habilitations et requalification",
        owner="Responsable formation",
        objective="Savoir à tout moment qui est habilité à quelle tâche, renouveler les habilitations avant leur expiration et évaluer la compétence quand la présence ne suffit pas.",
        scope="Toutes les exigences de formation obligatoires, les certifications à durée limitée et les compétences soumises à réévaluation périodique.",
        roles=[("Responsable formation", "Génère la matrice chaque mois, planifie les renouvellements, signale les écarts."),
               ("Encadrant / évaluateur", "Réalise les évaluations de compétence de son personnel (pas les siennes)."),
               ("Salarié", "Tient compte des rappels et suit les sessions de renouvellement.")],
        defs=[("Statut d'une cellule de matrice", "Valid, Expiring Soon, Expired, Revoked ou Not Trained pour chaque salarié × cours."),
              ("Évaluation de compétence", "Preuve que la personne sait faire : évaluateur nommé, niveau démontré (Not Demonstrated, Developing, Proficient, Expert), preuve, verrouillage à la confirmation.")],
        steps=[("Générer la matrice", "Chaque mois, ouvrir {{Training ▸ Reporting ▸ Training Matrix}}, cliquer sur [[Generate Matrix]] et appliquer le filtre *Gaps*."),
               ("Traiter les certifications expirant", "Utiliser {{Training ▸ Operations ▸ Expiring and Expired}} ; planifier les sessions de renouvellement avant expiration. Le système envoie des rappels quotidiens dans la fenêtre d'alerte."),
               ("Agir sur les formations expirées ou manquantes", "L'encadrant retire le salarié de la tâche jusqu'à la nouvelle formation ; consigner la décision."),
               ("Évaluer la compétence", "Dans {{Training ▸ Operations ▸ Competency Assessments}}, créer l'évaluation : salarié, compétence, évaluateur, date, niveau démontré, preuve ; fixer la prochaine évaluation si la compétence l'exige ; cliquer sur [[Confirm]]."),
               ("Rendre compte", "Présenter le taux de conformité par service en revue de direction.")],
        controls=["Le statut des certifications est calculé depuis la date d'expiration et recalculé chaque nuit ; elles ne sont jamais supprimées.",
                  "Un salarié ne peut évaluer sa propre compétence.",
                  "Une évaluation ne peut être confirmée sans preuve et ne peut plus être modifiée ni supprimée une fois confirmée.",
                  "La prochaine évaluation ne peut précéder la date d'évaluation."],
        good=["Lier les droits d'accès critiques (ex. libération de lot) à une habilitation valide et les revoir ensemble (SOP-IT-001).",
              "Utiliser les évaluations de compétence pour opérateurs aseptiques, analystes et auditeurs.",
              "Planifier les renouvellements dans le plan annuel de formation plutôt que d'attendre les rappels."],
        pitfalls=["Considérer une certification expirée comme « administrative » et laisser le salarié travailler.",
                  "Des encadrants qui évaluent des compétences qu'ils n'ont pas observées."],
        records=["Extraits de matrice", "Certifications et renouvellements", "Évaluations de compétence"],
        kpis=["Taux de conformité (exigences obligatoires satisfaites)", "Certifications expirées de personnel actif (cible 0)", "Réévaluations de compétence en retard"],
        example="**Cas.** La matrice de mars montre 3 cellules *Expired* pour le cours *Habillage aseptique* dans l'équipe de remplissage. Le responsable formation prévient le chef d'équipe, qui retire les trois opérateurs des zones A/B. Une session de renouvellement a lieu 4 jours plus tard ; les nouvelles certifications sont valables 12 mois. En parallèle, le chef d'équipe confirme pour chacun une évaluation *Comportement aseptique — Proficient*, fondée sur une simulation de procédé observée.",
    ),
)

ITEMS = [P1, M_DOC, QA001, QA002, QA003, QA004, QA005, M_TRAIN, QA010, QA011, QA012, QA013]
