# -*- coding: utf-8 -*-
"""Part III (a) — Pharmaceutical (ls_pharma)."""
from .helpers import module, part, sop, tr

P3 = part(
    "III", "part3", "Industry modules", "Modules métier",
    "Procedures specific to each industry: pharmaceutical manufacturing, cosmetics, medical devices, medical "
    "plastics and the quality control laboratory.",
    "Les procédures propres à chaque métier : fabrication pharmaceutique, cosmétique, dispositifs médicaux, "
    "plastiques médicaux et laboratoire de contrôle qualité.",
    ["Pharmaceutical — ls_pharma", "Cosmetics — ls_cosmetics", "Medical devices — ls_medical_device",
     "Medical plastics — ls_medical_plastics", "Laboratory — ls_lab"],
    ["Pharmaceutique — ls_pharma", "Cosmétique — ls_cosmetics", "Dispositifs médicaux — ls_medical_device",
     "Plastiques médicaux — ls_medical_plastics", "Laboratoire — ls_lab"],
)

M_PH = module(
    "mod-pharma", "ls_pharma", "Pharmaceutical", "Pharmaceutique",
    [
        ("p", "**ls_pharma** covers pharmaceutical manufacturing records and their quality decisions: batches "
              "(bulk, packaging, finished product) with yield limits and expiry; batch production and control records "
              "with master record check, steps, in-process and laboratory controls, area inspections (line clearance), "
              "labelling reconciliation, samples and discrepancies; an append-only batch release decision taken by the "
              "quality unit; qualified materials (APIs and excipients); stability studies; GS1 serialisation and "
              "aggregation; and CTD dossiers. Its controls cite 21 CFR Part 211; deliveries of lots whose batch is not "
              "released are refused."),
        ("table", ["Menu", "Content"], [
            ["{{Pharmaceutical ▸ Batches ▸ Manufacturing Batches / Batch Records / Batch Release / Open Discrepancies}}", "Batches"],
            ["{{Pharmaceutical ▸ Materials ▸ APIs / Excipients / Pharmaceutical Products}}", "Materials"],
            ["{{Pharmaceutical ▸ Stability ▸ Stability Studies / Time Points / Stability Samples}}", "Stability"],
            ["{{Pharmaceutical ▸ Serialization ▸ Serial Numbers / Aggregation / Generate Serial Numbers}}", "Serialisation"],
            ["{{Pharmaceutical ▸ Regulatory ▸ CTD Dossiers}}", "Regulatory"],
        ]),
        ("table", ["Group", "Main rights"], [
            ["Pharmaceutical / Viewer · Production Operator", "Read; execute batch record steps"],
            ["Pharmaceutical / Production Manager", "Manages batches and records"],
            ["Pharmaceutical / Quality Assurance", "Reviews records, decides release"],
            ["Pharmaceutical / Regulatory Affairs", "CTD dossiers"],
            ["Pharmaceutical / Manager", "Configuration"],
        ]),
        ("box", "warn", "EU Qualified Person certification", "The batch release decision of ls_pharma is the quality unit decision described by 21 CFR 211.22 and 211.192. In the EU, certification by a Qualified Person (EU GMP Annex 16) is an additional legal act: state in SOP-QA-090 how and where the QP certifies (register, signature), since the module does not model it."),
        ("schematic", "batch_release", "Release gate of a batch."),
        ("flow", "batch", "Lifecycle of a batch."),
    ],
    [
        ("p", "**ls_pharma** couvre les enregistrements de fabrication pharmaceutique et leurs décisions qualité : lots "
              "(vrac, conditionnement, produit fini) avec limites de rendement et péremption ; dossiers de production et "
              "de contrôle du lot avec vérification du dossier maître, étapes, contrôles en cours et de laboratoire, "
              "inspections de zone (vide de ligne), réconciliation des étiquettes, échantillons et écarts ; décision de "
              "libération en ajout seul prise par l'unité qualité ; matières qualifiées (substances actives et "
              "excipients) ; études de stabilité ; sérialisation et agrégation GS1 ; dossiers CTD. Ses contrôles citent "
              "le 21 CFR Part 211 ; les livraisons de lots dont le lot de fabrication n'est pas libéré sont refusées."),
        ("table", ["Menu", "Contenu"], [
            ["{{Pharmaceutical ▸ Batches ▸ Manufacturing Batches / Batch Records / Batch Release / Open Discrepancies}}", "Lots"],
            ["{{Pharmaceutical ▸ Materials ▸ APIs / Excipients / Pharmaceutical Products}}", "Matières"],
            ["{{Pharmaceutical ▸ Stability ▸ Stability Studies / Time Points / Stability Samples}}", "Stabilité"],
            ["{{Pharmaceutical ▸ Serialization ▸ Serial Numbers / Aggregation / Generate Serial Numbers}}", "Sérialisation"],
            ["{{Pharmaceutical ▸ Regulatory ▸ CTD Dossiers}}", "Réglementaire"],
        ]),
        ("table", ["Groupe", "Droits principaux"], [
            ["Pharmaceutical / Viewer · Production Operator", "Lecture ; exécution des étapes du dossier de lot"],
            ["Pharmaceutical / Production Manager", "Gère lots et dossiers"],
            ["Pharmaceutical / Quality Assurance", "Revoit les dossiers, décide de la libération"],
            ["Pharmaceutical / Regulatory Affairs", "Dossiers CTD"],
            ["Pharmaceutical / Manager", "Paramétrage"],
        ]),
        ("box", "warn", "Certification par la personne qualifiée (UE)", "La décision de libération de ls_pharma est la décision de l'unité qualité décrite par les 21 CFR 211.22 et 211.192. Dans l'UE, la certification par la personne qualifiée (BPF UE annexe 16) est un acte juridique supplémentaire : préciser dans la SOP-QA-090 comment et où la PQ certifie (registre, signature), le module ne la modélisant pas."),
        ("schematic", "batch_release", "Jalon de libération d'un lot."),
        ("flow", "batch", "Cycle de vie d'un lot."),
    ],
)

PRD001 = sop(
    "SOP-PRD-001", "ls_pharma", "Pharmaceutical ▸ Batches ▸ Manufacturing Batches / Batch Records",
    flows=[("batch_record", tr("Lifecycle of a batch production and control record.", "Cycle de vie d'un dossier de production et de contrôle."))],
    related=["SOP-PRD-002", "SOP-QA-090", "SOP-QA-020"],
    refs=["CFR-211-188", "CFR-211-192", "EU-GMP-4", "EU-GMP-5", "ICH-Q7"],
    en=dict(
        title="Issue and execution of the batch record",
        owner="Production Manager",
        objective="Issue for each batch a production and control record reproduced from the approved master record and checked, and execute it contemporaneously so that every significant step is dated, attributed and, where required, checked by a second person.",
        scope="Manufacturing and packaging/labelling batch records of all pharmaceutical batches (bulk, packaging, finished product).",
        roles=[("Production Manager", "Creates the batch and issues the record."),
               ("Checker (second person)", "Checks the reproduction of the master record; checks significant steps and component charges."),
               ("Production Operators", "Execute steps and record values."),
               ("QA", "Is informed of discrepancies; reviews the record (SOP-QA-090).")],
        defs=[("Master record", "Approved master production and control record; referenced by number and version on each batch record."),
              ("Significant step", "Step requiring identification of the person performing it and of the person checking it.")],
        steps=[("Create the batch", "In {{Manufacturing Batches}} click [[New]]: reference, batch type, product, lot, manufacturing order, BOM, site, planned quantity, theoretical yield, yield limits, shelf life."),
               ("Issue the record", "Add a batch record: record type (Manufacturing or Packaging and Labelling), master record reference and version; add steps, controls, planned samples and labelling items as defined in the master record."),
               ("Check the reproduction", "A second person compares the issued record with the master and records *Master Record Checked By / On*."),
               ("Start", "Click [[Start Production]] on the batch and [[Start Execution]] on the record."),
               ("Execute steps", "For each step line of the record, perform the step, record the value, the date performed and the performer, then click [[Done]] on the line; for significant or automated steps, record the checker (*Checked or Supervised By*). A step that does not apply is set to *Not Applicable* with a remark."),
               ("Components", "Record each component charge (lot, quantity, assay) and have it verified by a second person."),
               ("Controls", "Record in-process and laboratory control results against their limits."),
               ("Discrepancies", "Record any discrepancy immediately (classification, description) and click [[Start Investigation]]; major events also go through SOP-QA-020."),
               ("Complete", "Click [[Complete Execution]] when all steps are done or not applicable; record actual yield and click [[Complete Manufacturing]] on the batch."),
               ("Submit", "Click [[Submit for Review]] on the record; place the batch in quarantine ([[Place in Quarantine]]) pending QA review.")],
        controls=["Execution cannot start until the reproduction of the master record has been checked, dated and attributed.",
                  "A step cannot be completed without a date and the person who performed it; automated steps need the checker; *not applicable* needs a remark.",
                  "A component charged and verified by the same user is refused (21 CFR 211.101(d)).",
                  "The record cannot complete while steps remain open, and cannot be submitted/approved with open discrepancies; closing a discrepancy needs investigation, conclusion and follow-up.",
                  "Manufacturing cannot be declared complete without actual yield; a batch without batch record cannot proceed.",
                  "Expiry after manufacturing date; production end after start; minimum yield ≤ maximum; non-draft batches and records cannot be deleted."],
        good=["Record at the time of the operation; never pre-fill or back-date.",
              "Keep the printed master record page references in the step instructions.",
              "Record discrepancies even when \"corrected immediately\"."],
        pitfalls=["The same person charging and verifying components to save time.",
                  "Steps marked done at the end of the shift."],
        records=["Batch and batch production and control record with steps, controls, samples, discrepancies"],
        kpis=["Right-first-time records (no discrepancy)", "Records submitted within 24 h of completion"],
        example="**Case.** Batch 26T018 of *Tablets 10 mg*: manufacturing record issued from master MR-TAB10 v7, checked by the shift supervisor. The operator performs step 5 *Dry granulation, 12 min* (value 12 min, done 08:42); the component *API lot A2210, 5.012 kg* is charged by the operator and verified by a second operator. An IPC LOD result is within limits. At the end, actual yield 98.6 % (limits 96–101 %); record submitted for review and batch placed in quarantine.",
    ),
    fr=dict(
        title="Émission et exécution du dossier de lot",
        owner="Responsable production",
        objective="Émettre pour chaque lot un dossier de production et de contrôle reproduit à partir du dossier maître approuvé et vérifié, et l'exécuter en temps réel pour que chaque étape significative soit datée, attribuée et, si nécessaire, vérifiée par une seconde personne.",
        scope="Dossiers de fabrication et de conditionnement/étiquetage de tous les lots pharmaceutiques (vrac, conditionnement, produit fini).",
        roles=[("Responsable production", "Crée le lot et émet le dossier."),
               ("Vérificateur (seconde personne)", "Vérifie la reproduction du dossier maître ; vérifie les étapes significatives et les pesées de composants."),
               ("Opérateurs de production", "Exécutent les étapes et saisissent les valeurs."),
               ("AQ", "Est informée des écarts ; revoit le dossier (SOP-QA-090).")],
        defs=[("Dossier maître", "Dossier maître de production et de contrôle approuvé ; cité par numéro et version sur chaque dossier de lot."),
              ("Étape significative", "Étape exigeant l'identification de l'exécutant et du vérificateur.")],
        steps=[("Créer le lot", "Dans {{Manufacturing Batches}}, cliquer sur [[New]] : référence, type, produit, lot, ordre de fabrication, nomenclature, site, quantité prévue, rendement théorique, limites de rendement, durée de validité."),
               ("Émettre le dossier", "Ajouter un dossier : type (Manufacturing ou Packaging and Labelling), référence et version du dossier maître ; ajouter étapes, contrôles, échantillons prévus et articles d'étiquetage définis par le dossier maître."),
               ("Vérifier la reproduction", "Une seconde personne compare le dossier émis au dossier maître et renseigne *Master Record Checked By / On*."),
               ("Démarrer", "Cliquer sur [[Start Production]] sur le lot et [[Start Execution]] sur le dossier."),
               ("Exécuter les étapes", "Pour chaque ligne d'étape du dossier, exécuter l'étape, saisir la valeur, la date et l'exécutant, puis cliquer sur [[Done]] sur la ligne ; pour les étapes significatives ou automatisées, saisir le vérificateur (*Checked or Supervised By*). Une étape qui ne s'applique pas passe à *Not Applicable* avec une remarque."),
               ("Composants", "Enregistrer chaque pesée/charge (lot, quantité, titre) et la faire vérifier par une seconde personne."),
               ("Contrôles", "Saisir les résultats des contrôles en cours et de laboratoire au regard de leurs limites."),
               ("Écarts", "Enregistrer immédiatement tout écart (classification, description) et cliquer sur [[Start Investigation]] ; les événements majeurs passent aussi par la SOP-QA-020."),
               ("Terminer", "Cliquer sur [[Complete Execution]] quand toutes les étapes sont faites ou sans objet ; saisir le rendement réel et cliquer sur [[Complete Manufacturing]] sur le lot."),
               ("Soumettre", "Cliquer sur [[Submit for Review]] sur le dossier ; placer le lot en quarantaine ([[Place in Quarantine]]) en attente de la revue AQ.")],
        controls=["L'exécution ne peut démarrer tant que la reproduction du dossier maître n'a pas été vérifiée, datée et attribuée.",
                  "Une étape ne se termine pas sans date ni exécutant ; les étapes automatisées exigent le vérificateur ; *sans objet* exige une remarque.",
                  "Une charge de composant saisie et vérifiée par le même utilisateur est refusée (21 CFR 211.101(d)).",
                  "Le dossier ne se termine pas avec des étapes ouvertes et ne se soumet/approuve pas avec des écarts ouverts ; clore un écart exige investigation, conclusion et suivi.",
                  "La fabrication ne peut être déclarée terminée sans rendement réel ; un lot sans dossier ne peut avancer.",
                  "Péremption après fabrication ; fin après début ; rendement minimal ≤ maximal ; lots et dossiers non brouillons non supprimables."],
        good=["Enregistrer au moment de l'opération ; ne jamais pré-remplir ni antidater.",
              "Garder dans les instructions des étapes les renvois aux pages du dossier maître.",
              "Enregistrer les écarts même « corrigés immédiatement »."],
        pitfalls=["La même personne qui charge et vérifie les composants pour gagner du temps.",
                  "Des étapes marquées faites en fin de poste."],
        records=["Lot et dossier de production et de contrôle avec étapes, contrôles, échantillons, écarts"],
        kpis=["Dossiers bons du premier coup (sans écart)", "Dossiers soumis sous 24 h après la fin"],
        example="**Cas.** Lot 26T018 de *Comprimés 10 mg* : dossier de fabrication émis depuis le maître MR-TAB10 v7, vérifié par le chef d'équipe. L'opérateur exécute l'étape 5 *Granulation sèche, 12 min* (valeur 12 min, faite à 8 h 42) ; le composant *substance active lot A2210, 5,012 kg* est chargé par l'opérateur et vérifié par un second opérateur. Un contrôle de perte à la dessiccation est conforme. À la fin, rendement réel 98,6 % (limites 96–101 %) ; dossier soumis à la revue et lot mis en quarantaine.",
    ),
)

PRD002 = sop(
    "SOP-PRD-002", "ls_pharma", "Pharmaceutical ▸ Batches ▸ Batch Records (Area Inspections, Labelling Control)",
    related=["SOP-PRD-001", "SOP-QA-090"],
    refs=["CFR-211-130", "EU-GMP-5", "CFR-211-188"],
    en=dict(
        title="Line clearance and label reconciliation",
        owner="Packaging Manager",
        objective="Prevent mix-ups by verifying that lines and areas are free of previous materials before and after use, and reconcile the quantities of printed labelling materials issued, used, returned and destroyed.",
        scope="All packaging and labelling operations, and manufacturing areas at product changeover.",
        roles=[("Operator", "Performs the area inspection and label counts."),
               ("Verifier", "Verifies the inspection (not the same person)."),
               ("Packaging supervisor", "Investigates reconciliation differences.")],
        defs=[("Area inspection (line clearance)", "Documented check, before or after use, that no material, document or label of the previous product remains."),
              ("Reconciliation", "Issued − used − returned − destroyed; the difference must be within the tolerance.")],
        steps=[("Before use", "Add an area inspection: moment *Before Use*, area or line, previous product, performed on/by; record *Pass* or *Fail* with findings; a second person records *Verified By*."),
               ("Fail", "If the inspection fails, describe the findings, clean again, repeat the inspection; do not start."),
               ("Issue labelling", "Add each labelling item (label, leaflet, carton) with its version and code, and the quantity issued."),
               ("Reconcile", "At the end, record used, returned and destroyed; the difference is computed; tick *Reconciled* when within tolerance and record who reconciled."),
               ("Out of tolerance", "Record a discrepancy on the batch record and investigate (missing labels may be on another product)."),
               ("After use", "Perform and verify an inspection *After Use*.")],
        controls=["A failed area inspection requires recorded findings.",
                  "The inspection cannot be verified by the person who performed it.",
                  "Labelling quantities cannot be negative; unreconciled labels are counted on the record and shown to QA at review."],
        good=["Use a checklist of places to inspect (under conveyors, reject bins, printers).",
              "Destroy excess coded labels and record their destruction."],
        pitfalls=["Signing the clearance of a line you did not inspect.",
                  "Rounding reconciliation differences to zero."],
        records=["Area inspections with verification", "Labelling reconciliation"],
        kpis=["Failed clearances", "Batches with unreconciled labels at review"],
        example="**Case.** Before packaging batch 26T018, the operator inspects line PK-2 (previous product *Capsules 20 mg*): one leaflet of the previous product found under the feeder → *Fail*, findings recorded, line re-cleaned, second inspection *Pass*, verified by the supervisor. Labels: issued 12 500, used 12 180, returned 300, destroyed 20 → difference 0, reconciled.",
    ),
    fr=dict(
        title="Vide de ligne et réconciliation des étiquettes",
        owner="Responsable conditionnement",
        objective="Prévenir les mélanges en vérifiant que lignes et zones sont exemptes des matières précédentes avant et après utilisation, et réconcilier les quantités d'articles imprimés émis, utilisés, retournés et détruits.",
        scope="Toutes les opérations de conditionnement et d'étiquetage, et les zones de fabrication lors des changements de produit.",
        roles=[("Opérateur", "Réalise l'inspection de zone et les comptages."),
               ("Vérificateur", "Vérifie l'inspection (pas la même personne)."),
               ("Chef d'équipe conditionnement", "Investigue les écarts de réconciliation.")],
        defs=[("Inspection de zone (vide de ligne)", "Contrôle documenté, avant ou après utilisation, qu'aucune matière, document ou étiquette du produit précédent ne subsiste."),
              ("Réconciliation", "Émis − utilisé − retourné − détruit ; la différence doit rester dans la tolérance.")],
        steps=[("Avant utilisation", "Ajouter une inspection : moment *Before Use*, zone ou ligne, produit précédent, date et auteur ; saisir *Pass* ou *Fail* avec constats ; une seconde personne renseigne *Verified By*."),
               ("Échec", "En cas d'échec, décrire les constats, renettoyer, refaire l'inspection ; ne pas démarrer."),
               ("Émettre les articles", "Ajouter chaque article (étiquette, notice, étui) avec version et code, et la quantité émise."),
               ("Réconcilier", "En fin d'opération, saisir utilisé, retourné et détruit ; la différence est calculée ; cocher *Reconciled* si elle est dans la tolérance et indiquer qui a réconcilié."),
               ("Hors tolérance", "Enregistrer un écart sur le dossier de lot et investiguer (des étiquettes manquantes peuvent se trouver sur un autre produit)."),
               ("Après utilisation", "Réaliser et faire vérifier une inspection *After Use*.")],
        controls=["Une inspection en échec exige des constats.",
                  "L'inspection ne peut être vérifiée par la personne qui l'a réalisée.",
                  "Les quantités ne peuvent être négatives ; les étiquettes non réconciliées sont comptées sur le dossier et visibles par l'AQ à la revue."],
        good=["Utiliser une liste des endroits à inspecter (sous les convoyeurs, bacs de rejet, imprimantes).",
              "Détruire les étiquettes codées excédentaires et consigner la destruction."],
        pitfalls=["Signer le vide de ligne d'une ligne que l'on n'a pas inspectée.",
                  "Arrondir à zéro les écarts de réconciliation."],
        records=["Inspections de zone vérifiées", "Réconciliation de l'étiquetage"],
        kpis=["Vides de ligne en échec", "Lots avec étiquettes non réconciliées à la revue"],
        example="**Cas.** Avant le conditionnement du lot 26T018, l'opérateur inspecte la ligne PK-2 (produit précédent *Gélules 20 mg*) : une notice du produit précédent trouvée sous l'alimentateur → *Fail*, constat enregistré, ligne renettoyée, seconde inspection *Pass*, vérifiée par le chef d'équipe. Étiquettes : émises 12 500, utilisées 12 180, retournées 300, détruites 20 → différence 0, réconciliées.",
    ),
)

QA090 = sop(
    "SOP-QA-090", "ls_pharma", "Pharmaceutical ▸ Batches ▸ Batch Records / Batch Release",
    flows=[("batch", tr("Batch lifecycle up to release.", "Cycle de vie du lot jusqu'à la libération."))],
    schematics=[("batch_release", tr("What the release decision checks.", "Ce que vérifie la décision de libération."))],
    related=["SOP-PRD-001", "SOP-PRD-002", "SOP-QC-012", "SOP-QA-021", "SOP-DI-002"],
    refs=["CFR-211-22", "CFR-211-192", "EU-A16", "EU-GMP-1", "ICH-Q7"],
    en=dict(
        title="Batch record review and batch release by the quality unit",
        owner="Head of Quality Assurance",
        objective="Release a batch for distribution only after an independent quality unit has reviewed and approved its production and control records, confirmed that every discrepancy is investigated and closed, and verified the release checklist.",
        scope="All pharmaceutical batches made or packaged on site, before distribution.",
        roles=[("QA reviewer", "Reviews and approves or rejects each batch record."),
               ("Release authority (QA; QP in the EU)", "Takes and records the release decision; cannot be the manufacturer of the batch."),
               ("Production", "Answers review questions and completes records returned for completion.")],
        defs=[("Release checklist", "Batch records reviewed and approved; discrepancies investigated and closed; yield within limits; component charge-in verified by a second person; laboratory results conform; labelling reconciled; reserve samples retained; covered by the stability programme."),
              ("Release decision", "Append-only record: Released for Distribution or Rejected, with statement, date, decider and integrity digest.")],
        steps=[("Review the record", "Open the submitted record: steps, controls (non-conforming controls counter), area inspections, labelling reconciliation (unreconciled counter), samples, discrepancies (open counter), audit trail extract where available (SOP-DI-002)."),
               ("Decide on the record", "Click [[Approve]] with the review conclusion, [[Reject]] with a written conclusion, or [[Return for Completion]] if entries are missing."),
               ("Check laboratory results", "Confirm that the QC results of the batch are approved (SOP-QC-012) and that no OOS investigation is open."),
               ("Submit the batch", "Click [[Submit for QA Review]] on the batch."),
               ("Decide", "Click [[Record Release Decision]]: decision, statement, and tick each checklist item after verifying it. The decision is recorded as an append-only release decision with an integrity digest."),
               ("EU QP certification", "Where applicable, the QP certifies the batch in the QP register according to Annex 16, referencing the release decision."),
               ("Distribution", "Once released, deliveries of the lot are allowed; a rejected batch is handled as rejected material."),
               ("Verify integrity", "Use [[Verify Integrity]] on a release decision during audits.")],
        controls=["A batch record cannot be reviewed by the user who executed it; rejection needs a written conclusion; approval is refused with open discrepancies; closed records are frozen.",
                  "A release decision can only be recorded while the batch is under QA review, once per batch, and not by the person who manufactured it.",
                  "Release is refused when checklist items are not confirmed, when a batch record is not approved, when yield is outside limits without an investigation reference, or without an expiry date.",
                  "Release decisions are append-only: cannot be modified, duplicated or deleted.",
                  "Deliveries of lots whose batch is not released are refused (stock move line control)."],
        good=["Review by exception using the counters (open discrepancies, non-conforming controls, unreconciled labels) but read the whole record for critical steps.",
              "Record the reasoning in the decision statement, especially for released batches with closed deviations."],
        pitfalls=["Ticking the checklist without evidence.",
                  "Releasing before the laboratory results are approved."],
        records=["Approved batch records", "Release decision with checklist and digest", "QP register (EU)"],
        kpis=["Release lead time", "Batch records returned for completion", "Batches rejected"],
        example="**Case.** QA reviews batch 26T018: two records, 0 open discrepancies, 0 non-conforming controls, labels reconciled; yield 98.6 % within 96–101 %; QC results approved. The QA officer (not involved in manufacturing) records *Released for Distribution* with all checklist items ticked. The QP certifies it in the register the same day; the lot can be shipped.",
    ),
    fr=dict(
        title="Revue du dossier de lot et libération des lots par l'unité qualité",
        owner="Responsable assurance qualité",
        objective="Ne libérer un lot pour distribution qu'après qu'une unité qualité indépendante a revu et approuvé ses dossiers de production et de contrôle, confirmé que chaque écart est investigué et clos, et vérifié la liste de libération.",
        scope="Tous les lots pharmaceutiques fabriqués ou conditionnés sur le site, avant distribution.",
        roles=[("Vérificateur AQ", "Revoit et approuve ou rejette chaque dossier de lot."),
               ("Autorité de libération (AQ ; PQ dans l'UE)", "Prend et enregistre la décision ; ne peut être le fabricant du lot."),
               ("Production", "Répond aux questions de revue et complète les dossiers renvoyés.")],
        defs=[("Liste de libération", "Dossiers revus et approuvés ; écarts investigués et clos ; rendement dans les limites ; charges de composants vérifiées par une seconde personne ; résultats de laboratoire conformes ; étiquetage réconcilié ; échantillons de référence conservés ; lot couvert par le programme de stabilité."),
              ("Décision de libération", "Enregistrement en ajout seul : Released for Distribution ou Rejected, avec déclaration, date, décideur et empreinte d'intégrité.")],
        steps=[("Revoir le dossier", "Ouvrir le dossier soumis : étapes, contrôles (compteur des non-conformes), inspections de zone, réconciliation (compteur des non réconciliés), échantillons, écarts (compteur des ouverts), extrait de piste d'audit si disponible (SOP-DI-002)."),
               ("Statuer sur le dossier", "Cliquer sur [[Approve]] avec la conclusion de revue, [[Reject]] avec une conclusion écrite, ou [[Return for Completion]] si des saisies manquent."),
               ("Vérifier le laboratoire", "Confirmer que les résultats CQ du lot sont approuvés (SOP-QC-012) et qu'aucune enquête OOS n'est ouverte."),
               ("Soumettre le lot", "Cliquer sur [[Submit for QA Review]] sur le lot."),
               ("Décider", "Cliquer sur [[Record Release Decision]] : décision, déclaration, et cocher chaque point de la liste après l'avoir vérifié. La décision est enregistrée en ajout seul avec une empreinte d'intégrité."),
               ("Certification PQ (UE)", "Le cas échéant, la PQ certifie le lot dans le registre selon l'annexe 16, en citant la décision de libération."),
               ("Distribution", "Une fois libéré, les livraisons du lot sont permises ; un lot rejeté est traité comme matière refusée."),
               ("Vérifier l'intégrité", "Utiliser [[Verify Integrity]] sur une décision lors des audits.")],
        controls=["Un dossier ne peut être revu par l'utilisateur qui l'a exécuté ; un rejet exige une conclusion écrite ; l'approbation est refusée avec des écarts ouverts ; un dossier clos est figé.",
                  "Une décision ne s'enregistre que si le lot est en revue AQ, une seule fois par lot, et pas par la personne qui l'a fabriqué.",
                  "La libération est refusée si des points de la liste ne sont pas confirmés, si un dossier n'est pas approuvé, si le rendement est hors limites sans référence d'enquête, ou sans date de péremption.",
                  "Les décisions sont en ajout seul : ni modifiables, ni duplicables, ni supprimables.",
                  "Les livraisons de lots dont le lot de fabrication n'est pas libéré sont refusées (contrôle sur les lignes de mouvement de stock)."],
        good=["Revoir par exception grâce aux compteurs (écarts ouverts, contrôles non conformes, étiquettes non réconciliées) mais lire intégralement les étapes critiques.",
              "Écrire le raisonnement dans la déclaration, surtout pour les lots libérés avec déviations closes."],
        pitfalls=["Cocher la liste sans preuve.",
                  "Libérer avant l'approbation des résultats de laboratoire."],
        records=["Dossiers de lot approuvés", "Décision de libération avec liste et empreinte", "Registre de la PQ (UE)"],
        kpis=["Délai de libération", "Dossiers renvoyés pour complément", "Lots rejetés"],
        example="**Cas.** L'AQ revoit le lot 26T018 : deux dossiers, 0 écart ouvert, 0 contrôle non conforme, étiquettes réconciliées ; rendement 98,6 % dans 96–101 % ; résultats CQ approuvés. La chargée AQ (non impliquée dans la fabrication) enregistre *Released for Distribution* avec tous les points cochés. La PQ certifie le lot au registre le jour même ; le lot peut être expédié.",
    ),
)

QC001 = sop(
    "SOP-QC-001", "ls_pharma", "Pharmaceutical ▸ Materials ▸ APIs / Excipients",
    flows=[("material", tr("States of a pharmaceutical material.", "États d'une matière pharmaceutique."))],
    related=["SOP-QA-070", "SOP-QC-010"],
    refs=["ICH-Q7", "EU-GMP-5", "CFR-211-84"],
    en=dict(
        title="Qualification of active substances and excipients",
        owner="QC Manager with QA",
        objective="Maintain master data of active substances and excipients that are qualified before use: specification basis, approved manufacturers, retest period, storage, and specific requirements (animal origin, controlled substances).",
        scope="All APIs and excipients used in manufacturing.",
        roles=[("QC / QA", "Qualify, restrict or make obsolete materials."),
               ("Purchasing", "Buys only from approved manufacturers (see SOP-QA-070 / 073).")],
        defs=[("Potency basis", "As Is, Anhydrous, Dried or Active Moiety basis; label assay must be positive."),
              ("TSE/BSE statement", "Required reference for materials of animal origin.")],
        steps=[("Create", "In {{Materials ▸ APIs}} or {{Excipients}} click [[New]]: name, internal code, inventory item, pharmacopoeia and monograph, CAS number, approved manufacturers, retest period, storage condition; for APIs: INN, active moiety, potency basis, label assay, controlled substance and schedule, sterile; for excipients: function, novel excipient, maximum daily intake, label declaration."),
               ("Animal origin", "Tick *Of Animal Origin* and record the TSE/BSE statement reference."),
               ("Qualify", "When the supplier is approved and the specification is in place, click [[Qualify]]."),
               ("Restrict", "Click [[Restrict]] to limit use (e.g. pending an investigation); [[Declare Obsolete]] when no longer used.")],
        controls=["A controlled substance cannot be qualified until its schedule is recorded; a material of animal origin cannot be qualified without its TSE/BSE statement reference.",
                  "Label assay > 0; retest period and maximum daily intake non-negative.",
                  "An obsolete material cannot return to draft; a qualified material cannot be qualified twice."],
        good=["Keep the approved manufacturer list identical to the supplier qualification scope."],
        pitfalls=["Using a new manufacturer's material under an old qualification."],
        records=["Material master data with state history"],
        kpis=["Materials used while not qualified (target 0)"],
        example="**Case.** Gelatin (excipient, function *Coating Agent*) is of bovine origin: the TSE statement reference *EDQM CEP R1-CEP 2000-xxx* is recorded before [[Qualify]] is accepted.",
    ),
    fr=dict(
        title="Qualification des principes actifs et des excipients",
        owner="Responsable CQ avec l'AQ",
        objective="Tenir des données de base des substances actives et excipients qualifiés avant usage : base de spécification, fabricants approuvés, délai de recontrôle, conservation, exigences particulières (origine animale, substances contrôlées).",
        scope="Toutes les substances actives et tous les excipients utilisés en fabrication.",
        roles=[("CQ / AQ", "Qualifient, restreignent ou rendent obsolètes les matières."),
               ("Achats", "N'achètent qu'auprès des fabricants approuvés (voir SOP-QA-070 / 073).")],
        defs=[("Base de teneur", "As Is, Anhydrous, Dried ou Active Moiety ; le titre déclaré doit être positif."),
              ("Déclaration EST/ESB", "Référence exigée pour les matières d'origine animale.")],
        steps=[("Créer", "Dans {{Materials ▸ APIs}} ou {{Excipients}}, cliquer sur [[New]] : nom, code interne, article de stock, pharmacopée et monographie, numéro CAS, fabricants approuvés, délai de recontrôle, conditions de conservation ; pour une substance active : DCI, fraction active, base de teneur, titre déclaré, substance contrôlée et tableau, stérile ; pour un excipient : fonction, excipient nouveau, apport journalier maximal, déclaration à l'étiquetage."),
               ("Origine animale", "Cocher *Of Animal Origin* et saisir la référence de la déclaration EST/ESB."),
               ("Qualifier", "Quand le fournisseur est approuvé et la spécification en place, cliquer sur [[Qualify]]."),
               ("Restreindre", "Cliquer sur [[Restrict]] pour limiter l'usage (ex. enquête en cours) ; [[Declare Obsolete]] quand la matière n'est plus utilisée.")],
        controls=["Une substance contrôlée ne se qualifie pas sans son tableau ; une matière d'origine animale ne se qualifie pas sans la référence de déclaration EST/ESB.",
                  "Titre déclaré > 0 ; délai de recontrôle et apport journalier maximal positifs.",
                  "Une matière obsolète ne revient pas en brouillon ; une matière qualifiée ne se qualifie pas deux fois."],
        good=["Garder la liste des fabricants approuvés identique au périmètre de qualification fournisseur."],
        pitfalls=["Utiliser la matière d'un nouveau fabricant sous une ancienne qualification."],
        records=["Données de base avec historique d'état"],
        kpis=["Matières utilisées non qualifiées (cible 0)"],
        example="**Cas.** La gélatine (excipient, fonction *Coating Agent*) est d'origine bovine : la référence de déclaration EST *CEP EDQM R1-CEP 2000-xxx* est saisie avant que [[Qualify]] soit accepté.",
    ),
)

QC002 = sop(
    "SOP-QC-002", "ls_pharma", "Pharmaceutical ▸ Stability",
    flows=[("stability", tr("Lifecycle of a stability study.", "Cycle de vie d'une étude de stabilité."))],
    related=["SOP-QC-014", "SOP-QA-090"],
    refs=["ICH-Q1A", "CFR-211-166", "EU-GMP-6"],
    en=dict(
        title="Stability programme",
        owner="QC Manager",
        objective="Run registration, ongoing, follow-up and post-change stability studies according to approved protocols, pull and test samples on time, and use the results to support shelf life and storage conditions.",
        scope="Stability studies of finished products and intermediates managed in ls_pharma. Laboratory-side sample testing may be managed in ls_lab (SOP-QC-014).",
        roles=[("Stability coordinator", "Creates studies, generates schedules, pulls samples."),
               ("Analysts", "Test and record results."),
               ("QC Manager", "Concludes studies and proposes shelf life.")],
        defs=[("Storage condition", "Long term, intermediate, accelerated or other (temperature, humidity and tolerance)."),
              ("Time point", "Month of a study at a condition; scheduled date derived from study start.")],
        steps=[("Create", "In {{Stability Studies}} click [[New]]: title, study type, product, batch, protocol reference, packaging configuration, start, planned duration, storage conditions."),
               ("Schedule", "Click [[Generate Schedule]] to create time points per condition; review scheduled dates."),
               ("Start", "Click [[Start Study]]; place samples in storage (stability samples)."),
               ("Pull and test", "At each time point click [[Pull Samples]], test, record results, then [[Mark Tested]] and [[Complete]]. A time point not pulled is recorded with [[Mark Missed]] and a remark."),
               ("Out of specification", "Handle non-conforming results through an OOS investigation (SOP-QC-013); significant change is recorded on the study."),
               ("Conclude", "When all time points are final, write the conclusion (proposed shelf life, storage) and click [[Complete Study]]; [[Terminate Study]] with justification if stopped early.")],
        controls=["Time points can only be generated in draft or scheduled studies, and require at least one storage condition; a study needs time points to start.",
                  "A time point cannot be tested before its samples are pulled; tested requires results; missed requires a remark.",
                  "Completion requires every time point in a final state and a conclusion (21 CFR 211.166); termination requires a justification.",
                  "Samples cannot be allocated to another study's time point or stored under a different condition; discarding requires a remark."],
        good=["Enrol at least one batch per year per product and strength in the ongoing programme.",
              "Watch overdue time points weekly."],
        pitfalls=["Pulling samples late without recording the actual date."],
        records=["Study, time points, samples, results, conclusion"],
        kpis=["Time points pulled on time", "Studies with significant change"],
        example="**Case.** Ongoing stability of batch 26T018: long term 25 °C/60 % RH and accelerated 40 °C/75 % RH, planned 36 months; time points generated at 0, 3, 6, 9, 12, 18, 24, 36 months. At 6 months accelerated, dissolution is out of specification → OOS investigation opened; the study continues.",
    ),
    fr=dict(
        title="Programme de stabilité",
        owner="Responsable CQ",
        objective="Mener les études de stabilité d'enregistrement, en continu, de suivi et après changement selon des protocoles approuvés, sortir et analyser les échantillons à temps, et utiliser les résultats pour justifier durée de validité et conditions de conservation.",
        scope="Études de stabilité des produits finis et intermédiaires gérées dans ls_pharma. L'analyse des échantillons côté laboratoire peut être gérée dans ls_lab (SOP-QC-014).",
        roles=[("Coordinateur stabilité", "Crée les études, génère les calendriers, sort les échantillons."),
               ("Analystes", "Analysent et saisissent les résultats."),
               ("Responsable CQ", "Conclut les études et propose la durée de validité.")],
        defs=[("Condition de conservation", "Long terme, intermédiaire, accélérée ou autre (température, humidité et tolérance)."),
              ("Point de contrôle", "Mois d'une étude à une condition ; date prévue déduite du début de l'étude.")],
        steps=[("Créer", "Dans {{Stability Studies}}, cliquer sur [[New]] : titre, type d'étude, produit, lot, référence du protocole, conditionnement, début, durée prévue, conditions."),
               ("Planifier", "Cliquer sur [[Generate Schedule]] pour créer les points par condition ; vérifier les dates."),
               ("Démarrer", "Cliquer sur [[Start Study]] ; placer les échantillons en stockage."),
               ("Sortir et analyser", "À chaque point, cliquer sur [[Pull Samples]], analyser, saisir les résultats, puis [[Mark Tested]] et [[Complete]]. Un point non sorti est enregistré avec [[Mark Missed]] et une remarque."),
               ("Hors spécification", "Traiter les résultats non conformes par une enquête OOS (SOP-QC-013) ; le changement significatif est consigné sur l'étude."),
               ("Conclure", "Quand tous les points sont finaux, rédiger la conclusion (durée de validité proposée, conservation) et cliquer sur [[Complete Study]] ; [[Terminate Study]] avec justification en cas d'arrêt anticipé.")],
        controls=["Les points ne se génèrent qu'en brouillon ou planifié et exigent au moins une condition ; une étude sans point ne démarre pas.",
                  "Un point ne s'analyse pas avant la sortie de ses échantillons ; « analysé » exige des résultats ; « manqué » exige une remarque.",
                  "La fin exige tous les points finaux et une conclusion (21 CFR 211.166) ; l'arrêt exige une justification.",
                  "Un échantillon ne peut être affecté au point d'une autre étude ni stocké dans une autre condition ; l'élimination exige une remarque."],
        good=["Inscrire au moins un lot par an, par produit et dosage, au programme continu.",
              "Surveiller chaque semaine les points en retard."],
        pitfalls=["Sortir les échantillons en retard sans enregistrer la date réelle."],
        records=["Étude, points, échantillons, résultats, conclusion"],
        kpis=["Points sortis à temps", "Études avec changement significatif"],
        example="**Cas.** Stabilité continue du lot 26T018 : long terme 25 °C/60 % HR et accélérée 40 °C/75 % HR, 36 mois prévus ; points à 0, 3, 6, 9, 12, 18, 24, 36 mois. À 6 mois en accéléré, la dissolution est hors spécification → enquête OOS ouverte ; l'étude continue.",
    ),
)

PRD003 = sop(
    "SOP-PRD-003", "ls_pharma", "Pharmaceutical ▸ Serialization",
    flows=[("serial", tr("States of a serialised unit.", "États d'une unité sérialisée."))],
    schematics=[("serial", tr("Serialisation and aggregation hierarchy.", "Hiérarchie de sérialisation et d'agrégation."))],
    related=["SOP-PRD-001", "SOP-QA-090"],
    refs=["FMD", "GS1"],
    en=dict(
        title="GS1 serialisation and aggregation",
        owner="Packaging Manager with IT",
        objective="Assign a unique identifier to each saleable unit, commission it only for released packaging, aggregate units into containers with SSCC codes, and keep the status of each identifier accurate until it leaves the company.",
        scope="Products flagged as requiring serialisation. Connection to national verification systems (e.g. EU hub) is outside the module and must be described separately.",
        roles=[("Packaging operator", "Generates, commissions and aggregates."),
               ("Packaging Manager", "Decommissions with reason; supervises."),
               ("IT / serialisation partner", "Exchanges data with the repository system.")],
        defs=[("Unique identifier", "GTIN-14 product code + serial number + batch + expiry (+ national reimbursement number when required)."),
              ("SSCC", "18-digit Serial Shipping Container Code with modulo-10 check digit; built from the company GS1 prefix and extension digit set in company settings."),
              ("Commissioned / Decommissioned", "Active in the supply chain / withdrawn (with reason); other terminal states: destroyed, sampled, returned.")],
        steps=[("Configure", "Set the GS1 company prefix, SSCC extension digit and serial length in {{Configuration ▸ Company Settings}}; enter the GTIN-14 on each serialised product."),
               ("Generate", "Use {{Serialization ▸ Generate Serial Numbers}} for the batch."),
               ("Commission", "Click [[Commission]] on units actually printed and verified on the line."),
               ("Aggregate", "Create containers (bundle, case, pallet) with their SSCC; add units or child containers; click [[Pack]]."),
               ("Ship", "Click [[Mark Shipped]] on containers and units shipped."),
               ("Correct", "Use [[Disaggregate]] on a packed (not shipped) container to rework; [[Decommission]] units damaged, sampled or destroyed with a reason.")],
        controls=["GTIN-14 and SSCC formats and check digits are validated; serialised products must carry a product code.",
                  "Commissioned units cannot be deleted (decommission instead) and their identifier can no longer change; terminal states are final.",
                  "Only generated units can be commissioned; units must be commissioned before shipping; containers cannot be packed empty or with uncommissioned units, cannot contain themselves, and cannot be disaggregated once shipped."],
        good=["Reconcile generated, commissioned and decommissioned counts per batch at batch record review.",
              "Keep the rework of aggregated cases under supervision."],
        pitfalls=["Commissioning the full range generated instead of the units actually printed."],
        records=["Serial numbers with status history", "Aggregation hierarchy"],
        kpis=["Decommissioned units per batch", "Aggregation errors"],
        example="**Case.** Batch 26T018 of 12 000 boxes: 12 100 serials generated, 12 000 commissioned; 20 boxes per case (600 cases) and 40 cases per pallet (15 pallets), each with an SSCC. Two damaged boxes are decommissioned with the reason *damaged on line*; their case is disaggregated and repacked.",
    ),
    fr=dict(
        title="Sérialisation GS1 et agrégation",
        owner="Responsable conditionnement avec l'informatique",
        objective="Attribuer un identifiant unique à chaque unité de vente, ne l'activer que pour un conditionnement réalisé, agréger les unités dans des contenants codés SSCC, et tenir exact le statut de chaque identifiant jusqu'à sa sortie de l'entreprise.",
        scope="Produits marqués comme soumis à sérialisation. La connexion aux systèmes nationaux de vérification (ex. hub UE) est hors du module et doit être décrite à part.",
        roles=[("Opérateur conditionnement", "Génère, active et agrège."),
               ("Responsable conditionnement", "Désactive avec motif ; supervise."),
               ("Informatique / partenaire de sérialisation", "Échange les données avec le système de répertoires.")],
        defs=[("Identifiant unique", "Code produit GTIN-14 + numéro de série + lot + péremption (+ numéro national de remboursement si exigé)."),
              ("SSCC", "Code de 18 chiffres avec clé modulo 10 ; construit à partir du préfixe GS1 de l'entreprise et du chiffre d'extension paramétrés sur la société."),
              ("Activé / désactivé", "Actif dans la chaîne / retiré (avec motif) ; autres états finaux : détruit, échantillonné, retourné.")],
        steps=[("Paramétrer", "Saisir le préfixe GS1, le chiffre d'extension SSCC et la longueur des séries dans {{Configuration ▸ Company Settings}} ; saisir le GTIN-14 sur chaque produit sérialisé."),
               ("Générer", "Utiliser {{Serialization ▸ Generate Serial Numbers}} pour le lot."),
               ("Activer", "Cliquer sur [[Commission]] sur les unités réellement imprimées et vérifiées sur la ligne."),
               ("Agréger", "Créer les contenants (fardeau, carton, palette) avec leur SSCC ; ajouter unités ou contenants enfants ; cliquer sur [[Pack]]."),
               ("Expédier", "Cliquer sur [[Mark Shipped]] sur les contenants et unités expédiés."),
               ("Corriger", "Utiliser [[Disaggregate]] sur un contenant conditionné (non expédié) pour le reprendre ; [[Decommission]] les unités abîmées, prélevées ou détruites avec un motif.")],
        controls=["Formats et clés de contrôle GTIN-14 et SSCC sont vérifiés ; un produit sérialisé doit porter un code produit.",
                  "Une unité activée ne se supprime pas (la désactiver) et son identifiant ne change plus ; les états finaux sont définitifs.",
                  "Seule une unité générée s'active ; activation obligatoire avant expédition ; un contenant ne se conditionne ni vide ni avec des unités non activées, ne se contient pas lui-même et ne se désagrège plus une fois expédié."],
        good=["Réconcilier par lot les nombres générés, activés et désactivés lors de la revue du dossier.",
              "Superviser la reprise des cartons agrégés."],
        pitfalls=["Activer toute la plage générée au lieu des unités réellement imprimées."],
        records=["Numéros de série et historique d'état", "Hiérarchie d'agrégation"],
        kpis=["Unités désactivées par lot", "Erreurs d'agrégation"],
        example="**Cas.** Lot 26T018 de 12 000 boîtes : 12 100 séries générées, 12 000 activées ; 20 boîtes par carton (600 cartons) et 40 cartons par palette (15 palettes), chacun avec un SSCC. Deux boîtes abîmées sont désactivées avec le motif *abîmées sur ligne* ; leur carton est désagrégé et reconditionné.",
    ),
)

RA001 = sop(
    "SOP-RA-001", "ls_pharma", "Pharmaceutical ▸ Regulatory ▸ CTD Dossiers",
    flows=[("ctd", tr("Lifecycle of a CTD dossier.", "Cycle de vie d'un dossier CTD."))],
    schematics=[("ctd", tr("CTD structure.", "Structure du CTD."))],
    related=["SOP-QA-030", "SOP-RA-010"],
    refs=["ICH-M4"],
    en=dict(
        title="Preparation of the CTD dossier (Common Technical Document)",
        owner="Regulatory Affairs Manager",
        objective="Plan and track the preparation of marketing authorisation dossiers section by section, record submission, deficiencies and decision, and keep evidence of each section's source document.",
        scope="New applications, variations, renewals and transfers prepared in CTD format. The module tracks status and references; it does not compile or publish eCTD sequences.",
        roles=[("Regulatory Affairs Manager", "Owns the dossier and its planning."),
               ("Section owners", "Prepare sections and provide document references."),
               ("Management", "Approves submission.")],
        defs=[("Section", "CTD module (1 to 5), number and title, owner, due date, document reference, status."),
              ("Deficiency", "Question or objection received from the authority on a submitted dossier.")],
        steps=[("Create", "In {{CTD Dossiers}} click [[New]]: title, product, dossier type, authority, contact, MA holder, version."),
               ("Load the structure", "Click [[Start Preparation]] then [[Load CTD Structure]] to copy the template sections (configured in {{Configuration ▸ CTD Section Template}})."),
               ("Prepare sections", "Assign owners and due dates; each owner clicks [[Start Preparation]] on the section, then [[Mark Ready]] with the document reference."),
               ("Ready", "When all sections are ready click [[Mark Ready]] on the dossier."),
               ("Submit", "After internal approval and submission through the authority's channel, click [[Record Submission]] with the date."),
               ("Deficiencies", "On receipt of questions click [[Record Deficiency]]; set the affected sections to deficiency with a description; answer and mark them ready again."),
               ("Decision", "Click [[Record Approval]] with the authorisation number and decision date, or [[Withdraw]].")],
        controls=["A section cannot be declared ready without a document reference; a section in deficiency must describe it; template sections cannot belong to a dossier.",
                  "The template can only be loaded in preparation; the dossier can only be marked ready when all sections are ready; submission requires *ready*.",
                  "A deficiency can only be recorded on a submitted dossier; approval requires the authorisation number; decision date ≥ submission date; submitted dossiers cannot be deleted."],
        good=["Link each variation dossier to its change request (SOP-QA-030).",
              "Use the document reference of the controlled document (ls_document_management number and version)."],
        pitfalls=["Sections marked ready with drafts as document reference."],
        records=["Dossier with sections, submission, deficiencies and decision"],
        kpis=["Sections late vs due date", "Deficiency cycles per dossier"],
        example="**Case.** Variation for a new API manufacturer (CC-2026-021 follow-up): dossier type *Variation*; only sections 1.x, 2.3, 3.2.S.2 and 3.2.S.4 apply; owners assigned; all ready in 6 weeks; submission recorded; one deficiency on 3.2.S.4 answered; approval recorded with the authority's decision number.",
    ),
    fr=dict(
        title="Préparation du dossier CTD (Common Technical Document, document technique commun)",
        owner="Responsable affaires réglementaires",
        objective="Planifier et suivre la préparation des dossiers d'AMM section par section, enregistrer dépôt, questions et décision, et garder la preuve du document source de chaque section.",
        scope="Demandes initiales, variations, renouvellements et transferts préparés au format CTD. Le module suit statuts et références ; il ne compile ni ne publie de séquences eCTD.",
        roles=[("Responsable affaires réglementaires", "Porte le dossier et sa planification."),
               ("Responsables de section", "Préparent les sections et fournissent les références documentaires."),
               ("Direction", "Approuve le dépôt.")],
        defs=[("Section", "Module CTD (1 à 5), numéro et titre, responsable, échéance, référence documentaire, statut."),
              ("Objection (deficiency)", "Question ou objection de l'autorité sur un dossier déposé.")],
        steps=[("Créer", "Dans {{CTD Dossiers}}, cliquer sur [[New]] : titre, produit, type, autorité, contact, titulaire, version."),
               ("Charger la structure", "Cliquer sur [[Start Preparation]] puis [[Load CTD Structure]] pour copier les sections modèles (paramétrées dans {{Configuration ▸ CTD Section Template}})."),
               ("Préparer les sections", "Attribuer responsables et échéances ; chaque responsable clique sur [[Start Preparation]] sur sa section, puis [[Mark Ready]] avec la référence documentaire."),
               ("Prêt", "Quand toutes les sections sont prêtes, cliquer sur [[Mark Ready]] sur le dossier."),
               ("Déposer", "Après approbation interne et dépôt par le canal de l'autorité, cliquer sur [[Record Submission]] avec la date."),
               ("Objections", "À réception des questions, cliquer sur [[Record Deficiency]] ; passer les sections concernées en objection avec description ; répondre et les remettre prêtes."),
               ("Décision", "Cliquer sur [[Record Approval]] avec le numéro d'autorisation et la date, ou [[Withdraw]].")],
        controls=["Une section ne se déclare prête qu'avec une référence documentaire ; une section en objection doit la décrire ; une section modèle n'appartient pas à un dossier.",
                  "Le modèle ne se charge qu'en préparation ; le dossier n'est prêt que si toutes les sections le sont ; le dépôt exige l'état prêt.",
                  "Une objection ne s'enregistre que sur un dossier déposé ; l'approbation exige le numéro d'autorisation ; date de décision ≥ date de dépôt ; un dossier déposé ne se supprime pas."],
        good=["Relier chaque dossier de variation à sa demande de changement (SOP-QA-030).",
              "Utiliser comme référence le numéro et la version du document maîtrisé (ls_document_management)."],
        pitfalls=["Des sections déclarées prêtes avec des brouillons comme référence."],
        records=["Dossier avec sections, dépôt, objections et décision"],
        kpis=["Sections en retard", "Cycles de questions par dossier"],
        example="**Cas.** Variation pour un nouveau fabricant de substance active (suite de CC-2026-021) : type *Variation* ; seules les sections 1.x, 2.3, 3.2.S.2 et 3.2.S.4 s'appliquent ; responsables désignés ; toutes prêtes en 6 semaines ; dépôt enregistré ; une question sur 3.2.S.4 traitée ; approbation enregistrée avec le numéro de décision de l'autorité.",
    ),
)

ITEMS = [P3, M_PH, PRD001, PRD002, QA090, QC001, QC002, PRD003, RA001]
