# -*- coding: utf-8 -*-
"""Part IV (regulatory affairs), Part V (OCA modules), Part VI (procedures not covered)."""
from .helpers import module, part, sop, tr

P4 = part(
    "IV", "part4", "Regulatory affairs", "Affaires réglementaires",
    "Regulatory intelligence for import and export. Only phase 1 of ls_import_export (the cited provision registry "
    "and regulatory questions) exists; import-export operations (authorisations, customs, banking) are later phases "
    "and are not covered.",
    "Veille réglementaire pour l'import et l'export. Seule la phase 1 de ls_import_export (registre des textes cités "
    "et questions réglementaires) existe ; les opérations d'import-export (autorisations, douane, banque) relèvent "
    "des phases suivantes et ne sont pas couvertes.",
    ["Import-export (phase 1) — ls_import_export"], ["Import-export (phase 1) — ls_import_export"],
)

M_IE = module(
    "mod-ie", "ls_import_export", "Import-export compliance (phase 1)", "Conformité import-export (phase 1)",
    [
        ("p", "**ls_import_export** is built on a *Truth Protocol*: the module asserts no regulatory requirement that is "
              "not first recorded as a cited provision with a source, an effective date and an in-force status. The "
              "registry ships **empty**; every provision is entered by a person who read the source. Expected but "
              "unverified rules are recorded as **regulatory questions** for a qualified adviser. A compliance "
              "requirement cannot exist without at least one cited provision. Phase 1 is non-behavioural: it does not "
              "yet block purchases, sales or shipments."),
        ("table", ["Menu", "Content"], [
            ["{{Import & Export Compliance ▸ Registry ▸ Provisions / Compliance Requirements / Regulatory Questions}}", "Registry"],
        ]),
        ("table", ["Group", "Main rights"], [
            ["Viewer · User · Officer · Manager", "From read-only to registry maintenance and approval"],
        ]),
        ("flow", "provision", "Statuses of a provision."),
    ],
    [
        ("p", "**ls_import_export** repose sur un *protocole de vérité* : le module n'affirme aucune exigence "
              "réglementaire qui n'ait d'abord été enregistrée comme disposition citée, avec source, date d'effet et "
              "statut en vigueur. Le registre est livré **vide** ; chaque disposition est saisie par une personne qui a lu "
              "la source. Les règles attendues mais non vérifiées sont enregistrées comme **questions réglementaires** "
              "pour un conseil qualifié. Une exigence de conformité ne peut exister sans au moins une disposition citée. "
              "La phase 1 n'agit pas sur les opérations : elle ne bloque encore ni achats, ni ventes, ni expéditions."),
        ("table", ["Menu", "Contenu"], [
            ["{{Import & Export Compliance ▸ Registry ▸ Provisions / Compliance Requirements / Regulatory Questions}}", "Registre"],
        ]),
        ("table", ["Groupe", "Droits principaux"], [
            ["Viewer · User · Officer · Manager", "De la lecture seule à la tenue et l'approbation du registre"],
        ]),
        ("flow", "provision", "Statuts d'une disposition."),
    ],
)

RA010 = sop(
    "SOP-RA-010", "ls_import_export", "Import & Export Compliance ▸ Registry ▸ Provisions / Compliance Requirements",
    flows=[("provision", tr("Statuses of a provision.", "Statuts d'une disposition."))],
    related=["SOP-RA-011", "SOP-COS-006", "SOP-COS-007"],
    refs=[],
    en=dict(
        title="Regulatory watch: register of cited texts",
        owner="Regulatory Affairs Manager (import-export)",
        objective="Maintain a registry of the legal and regulatory provisions that govern regulated imports and exports, each cited from its official source with effective date and status, and derive compliance requirements only from cited provisions.",
        scope="Algerian and international texts applicable to the import and export of medicinal products, medical devices and cosmetics (e.g. pharmaceutical agency, ministry, customs, central bank, foreign trade rules), as selected by Regulatory Affairs.",
        roles=[("Regulatory Officer", "Reads the source, records provisions and citations."),
               ("Regulatory Affairs Manager", "Validates entries and requirements; decides on status changes.")],
        defs=[("Provision", "Legal text or article recorded with source, effective date and status: In Force, Amended, Repealed, Under Review."),
              ("Compliance requirement", "Operational obligation derived from one or more cited provisions.")],
        steps=[("Monitor sources", "Define the official sources to monitor (official journal, agency websites, customs notes) and the frequency (e.g. weekly)."),
               ("Record a provision", "In {{Registry ▸ Provisions}} create the provision with its official reference, title, source, effective date and status; add citations (article, exact wording or summary with reference)."),
               ("Derive requirements", "In {{Compliance Requirements}} create the requirement and cite at least one provision."),
               ("Update", "When a text is amended or repealed, change the status and create the new provision; review the requirements citing it."),
               ("Open questions", "When a rule is expected but not verified, record a regulatory question (SOP-RA-011) instead of a requirement.")],
        controls=["A compliance requirement must cite at least one provision; the last cited provision cannot be removed.",
                  "The registry contains nothing that has not been entered by a person — there is no pre-loaded law."],
        good=["Record the date on which the source was consulted.",
              "Never paraphrase a legal obligation without the citation next to it."],
        pitfalls=["Entering requirements from memory or from a consultant's slide without the text."],
        records=["Provisions with citations", "Requirements with cited provisions"],
        kpis=["Provisions under review for more than 30 days", "Requirements whose provisions were amended"],
        example="**Case.** The officer reads a newly published executive decree on the import of medical devices, records it as a provision *In Force* from its effective date with citations of the articles on prior import authorisation, and creates the requirement *\"Import programme approval before first import of the year\"* citing those articles.",
    ),
    fr=dict(
        title="Veille réglementaire : registre des textes cités",
        owner="Responsable affaires réglementaires (import-export)",
        objective="Tenir un registre des dispositions légales et réglementaires qui régissent les importations et exportations réglementées, chacune citée depuis sa source officielle avec date d'effet et statut, et ne déduire d'exigences de conformité que de dispositions citées.",
        scope="Textes algériens et internationaux applicables à l'import et l'export de médicaments, dispositifs médicaux et cosmétiques (ex. agence pharmaceutique, ministère, douanes, banque centrale, commerce extérieur), selon la sélection des affaires réglementaires.",
        roles=[("Chargé réglementaire", "Lit la source, enregistre dispositions et citations."),
               ("Responsable affaires réglementaires", "Valide entrées et exigences ; décide des changements de statut.")],
        defs=[("Disposition", "Texte ou article enregistré avec source, date d'effet et statut : In Force, Amended, Repealed, Under Review."),
              ("Exigence de conformité", "Obligation opérationnelle déduite d'une ou plusieurs dispositions citées.")],
        steps=[("Surveiller les sources", "Définir les sources officielles à surveiller (journal officiel, sites des agences, notes des douanes) et la fréquence (ex. hebdomadaire)."),
               ("Enregistrer une disposition", "Dans {{Registry ▸ Provisions}}, créer la disposition avec sa référence officielle, titre, source, date d'effet et statut ; ajouter les citations (article, texte exact ou résumé avec référence)."),
               ("Déduire les exigences", "Dans {{Compliance Requirements}}, créer l'exigence et citer au moins une disposition."),
               ("Mettre à jour", "Quand un texte est modifié ou abrogé, changer son statut et créer la nouvelle disposition ; revoir les exigences qui le citent."),
               ("Questions ouvertes", "Quand une règle est attendue mais non vérifiée, enregistrer une question réglementaire (SOP-RA-011) au lieu d'une exigence.")],
        controls=["Une exigence de conformité doit citer au moins une disposition ; la dernière disposition citée ne peut être retirée.",
                  "Le registre ne contient rien qui n'ait été saisi par une personne — aucun texte n'est préchargé."],
        good=["Noter la date de consultation de la source.",
              "Ne jamais reformuler une obligation légale sans la citation à côté."],
        pitfalls=["Saisir des exigences de mémoire ou d'après la présentation d'un consultant, sans le texte."],
        records=["Dispositions avec citations", "Exigences avec dispositions citées"],
        kpis=["Dispositions en revue depuis plus de 30 jours", "Exigences dont les dispositions ont été modifiées"],
        example="**Cas.** Le chargé lit un décret exécutif nouvellement publié sur l'importation des dispositifs médicaux, l'enregistre comme disposition *In Force* à sa date d'effet avec la citation des articles relatifs à l'autorisation préalable d'importation, et crée l'exigence *« Approbation du programme d'importation avant la première importation de l'année »* citant ces articles.",
    ),
)

RA011 = sop(
    "SOP-RA-011", "ls_import_export", "Import & Export Compliance ▸ Registry ▸ Regulatory Questions",
    flows=[("question", tr("Statuses of a regulatory question.", "Statuts d'une question réglementaire."))],
    related=["SOP-RA-010", "SOP-COS-007"],
    refs=[],
    en=dict(
        title="Handling open regulatory questions",
        owner="Regulatory Affairs Manager",
        objective="Record, assign and answer regulatory questions whose answer is not verified, so that no rule is assumed or guessed and each answer is traceable to a source or a qualified adviser.",
        scope="Questions about import-export rules, and more generally any regulatory point where the applicable requirement is uncertain.",
        roles=[("Any user", "Raises a question with context."),
               ("Regulatory Affairs Manager", "Assigns, obtains the answer (authority, lawyer, consultant), records it."),
               ("Management", "Decides how to operate while the question is open.")],
        defs=[("Status", "Open, Answered, Will Not Answer.")],
        steps=[("Raise", "In {{Regulatory Questions}} create the question: precise wording, context, products concerned, urgency."),
               ("Assign", "Assign it to a responsible person and a due date."),
               ("Answer", "Obtain the answer from an authoritative source; record the answer, its source (letter, meeting minutes, legal opinion) and date; set *Answered*. If a provision results, record it (SOP-RA-010)."),
               ("Decline", "If the question will not be pursued, set *Will Not Answer* with the reason."),
               ("Interim decision", "While open, record the interim operating decision taken by management (e.g. the most conservative interpretation).")],
        controls=["Statuses are limited to Open, Answered and Will Not Answer."],
        good=["Prefer written answers from authorities; keep minutes of oral answers."],
        pitfalls=["Treating an informal answer as a legal requirement without recording its source."],
        records=["Questions with answers and sources"],
        kpis=["Open questions older than 60 days"],
        example="**Case.** Question: *\"Does a change of the importer's storage site require a new import authorisation for cosmetics?\"* — assigned to the regulatory manager; answer received by letter from the competent directorate after 3 weeks; recorded with the letter reference; the provision cited in the letter is added to the registry.",
    ),
    fr=dict(
        title="Traitement des questions réglementaires ouvertes",
        owner="Responsable affaires réglementaires",
        objective="Enregistrer, attribuer et traiter les questions réglementaires dont la réponse n'est pas vérifiée, pour qu'aucune règle ne soit supposée ni devinée et que chaque réponse soit rattachée à une source ou à un conseil qualifié.",
        scope="Questions sur les règles d'import-export et, plus largement, tout point réglementaire dont l'exigence applicable est incertaine.",
        roles=[("Tout utilisateur", "Pose une question avec son contexte."),
               ("Responsable affaires réglementaires", "Attribue, obtient la réponse (autorité, avocat, consultant), l'enregistre."),
               ("Direction", "Décide du mode de fonctionnement tant que la question est ouverte.")],
        defs=[("Statut", "Open, Answered, Will Not Answer.")],
        steps=[("Poser", "Dans {{Regulatory Questions}}, créer la question : formulation précise, contexte, produits concernés, urgence."),
               ("Attribuer", "L'attribuer à un responsable avec une échéance."),
               ("Répondre", "Obtenir la réponse d'une source faisant autorité ; enregistrer la réponse, sa source (courrier, compte rendu, avis juridique) et sa date ; passer *Answered*. Si une disposition en découle, l'enregistrer (SOP-RA-010)."),
               ("Refuser", "Si la question n'est pas poursuivie, passer *Will Not Answer* avec le motif."),
               ("Décision provisoire", "Tant qu'elle est ouverte, consigner la décision de fonctionnement prise par la direction (ex. l'interprétation la plus prudente).")],
        controls=["Les statuts se limitent à Open, Answered et Will Not Answer."],
        good=["Préférer des réponses écrites des autorités ; consigner les réponses orales dans un compte rendu."],
        pitfalls=["Traiter une réponse informelle comme une exigence légale sans enregistrer sa source."],
        records=["Questions avec réponses et sources"],
        kpis=["Questions ouvertes depuis plus de 60 jours"],
        example="**Cas.** Question : *« Un changement de site de stockage de l'importateur exige-t-il une nouvelle autorisation d'importation pour les cosmétiques ? »* — attribuée au responsable réglementaire ; réponse reçue par courrier de la direction compétente après 3 semaines ; enregistrée avec la référence du courrier ; la disposition citée dans le courrier est ajoutée au registre.",
    ),
)

P5 = part(
    "V", "part5", "Procedures supported by OCA modules", "Procédures apportées par les modules OCA",
    "Procedures supported by community (OCA) modules present in the repository. Before relying on them, note the "
    "installation findings reported in the annex *Known limitations*: on a fresh Odoo 19.0 database, auditlog, "
    "base_user_role, mgmtsystem_kpi and mgmtsystem_review (through its dependency base_external_dbsource) failed to "
    "install because of view references renamed from *tree* to *list*. Screenshots are therefore given only for "
    "maintenance_plan, maintenance_equipment_certification and quality_control_oca, which installed.",
    "Procédures outillées par des modules communautaires (OCA) présents dans le dépôt. Avant de s'y appuyer, tenir "
    "compte des constats d'installation de l'annexe *Limites constatées* : sur une base Odoo 19.0 neuve, auditlog, "
    "base_user_role, mgmtsystem_kpi et mgmtsystem_review (via sa dépendance base_external_dbsource) échouaient à "
    "l'installation à cause de références de vues renommées de *tree* en *list*. Des captures ne sont donc données "
    "que pour maintenance_plan, maintenance_equipment_certification et quality_control_oca, qui se sont installés.",
    ["Management review — mgmtsystem_review", "Quality indicators — mgmtsystem_kpi", "Preventive maintenance — maintenance_plan",
     "Equipment certificates — maintenance_equipment_certification", "Roles and access review — base_user_role",
     "Technical audit log — auditlog", "Generic inspections — quality_control_oca"],
    ["Revue de direction — mgmtsystem_review", "Indicateurs qualité — mgmtsystem_kpi", "Maintenance préventive — maintenance_plan",
     "Certificats des équipements — maintenance_equipment_certification", "Rôles et revue des droits — base_user_role",
     "Journal d'audit technique — auditlog", "Contrôles d'inspection — quality_control_oca"],
)

GEN001 = sop(
    "SOP-GEN-001", "mgmtsystem_review", "Management Systems ▸ Management System ▸ Reviews",
    schematics=[("pdca", tr("Management review closes the quality cycle.", "La revue de direction boucle le cycle qualité."))],
    related=["SOP-QA-005", "SOP-GEN-002", "SOP-QA-062", "SOP-EM-005"],
    refs=["ISO-9001", "ISO-13485", "ICH-Q10", "EU-GMP-1"],
    en=dict(
        title="Management review",
        owner="General Manager with the Head of Quality",
        objective="Review at planned intervals the suitability, adequacy and effectiveness of the quality system and decide on improvements and resources.",
        scope="The whole quality management system, at least once a year (more often in the first years or after major changes).",
        roles=[("Top management", "Chairs the review, takes decisions."),
               ("Head of Quality", "Prepares inputs, records the review."),
               ("Process owners", "Present their indicators and actions.")],
        defs=[("Inputs", "Status of previous actions; changes; customer feedback and complaints; process performance and product conformity; nonconformities and CAPA; audit results; monitoring results; supplier performance; risks and opportunities; adequacy of resources; new regulatory requirements."),
              ("Outputs", "Decisions on improvement, changes to the QMS, and resource needs.")],
        steps=[("Prepare inputs", "Collect from the suite: objectives (SOP-QA-005), CAPA status (ls_capa), deviations and complaints trends, audit results (ls_audit), supplier ratings, EM trends, risk profile, training compliance, recalls, validation status."),
               ("Create the review", "In the management review record (mgmtsystem_review): name, date, participants, policy, changes; update the KPI history with the dedicated button (KPIs from mgmtsystem_kpi)."),
               ("Hold the meeting", "Discuss each input; record decisions and actions as review lines."),
               ("Conclude and close", "Write the conclusion; close the review."),
               ("Follow up", "Turn decisions into CAPA, changes or objectives with owners and dates; report their status at the next review."),
               ("Alternative", "If mgmtsystem_review is not installed (see limitations), record the review as a quality record of type *Management Review* in ls_qms (SOP-QA-004), with the minutes attached.")],
        controls=["The review record has states Open and Closed; closed reviews keep their KPI history snapshot."],
        good=["Send the input pack one week before the meeting.",
              "Record decisions as verifiable actions, not as intentions."],
        pitfalls=["A review reduced to a slide presentation without decisions."],
        records=["Management review record or quality record with minutes", "Actions arising"],
        kpis=["Actions from the last review completed on time"],
        example="**Case.** Annual review 2027: inputs from 14 audits, 62 deviations, 11 CAPA overdue, EM trends stable except corridor C. Decisions: add one QA reviewer (resource), revise the deviation classification SOP (change CC-2028-002), new objective on CAPA timeliness. Recorded, closed, actions assigned.",
    ),
    fr=dict(
        title="Revue de direction",
        owner="Directeur général avec le responsable qualité",
        objective="Revoir à intervalles planifiés la pertinence, l'adéquation et l'efficacité du système qualité et décider des améliorations et ressources.",
        scope="L'ensemble du système de management de la qualité, au moins une fois par an (plus souvent les premières années ou après des changements majeurs).",
        roles=[("Direction", "Préside la revue, décide."),
               ("Responsable qualité", "Prépare les éléments d'entrée, consigne la revue."),
               ("Pilotes de processus", "Présentent indicateurs et actions.")],
        defs=[("Éléments d'entrée", "État des actions précédentes ; changements ; retours clients et réclamations ; performance des processus et conformité des produits ; non-conformités et CAPA ; résultats d'audit ; résultats de surveillance ; performance des fournisseurs ; risques et opportunités ; adéquation des ressources ; nouvelles exigences réglementaires."),
              ("Éléments de sortie", "Décisions d'amélioration, changements du SMQ, besoins en ressources.")],
        steps=[("Préparer les entrées", "Rassembler depuis la suite : objectifs (SOP-QA-005), état des CAPA (ls_capa), tendances des déviations et réclamations, résultats d'audit (ls_audit), notes fournisseurs, tendances EM, profil de risque, conformité de la formation, rappels, statut de validation."),
               ("Créer la revue", "Dans l'enregistrement de revue (mgmtsystem_review) : nom, date, participants, politique, changements ; mettre à jour l'historique des KPI avec le bouton dédié (KPI de mgmtsystem_kpi)."),
               ("Tenir la réunion", "Examiner chaque entrée ; consigner décisions et actions en lignes de revue."),
               ("Conclure et clore", "Rédiger la conclusion ; clore la revue."),
               ("Suivre", "Traduire les décisions en CAPA, changements ou objectifs avec responsables et échéances ; en rendre compte à la revue suivante."),
               ("Alternative", "Si mgmtsystem_review n'est pas installé (voir limites), consigner la revue comme enregistrement qualité de type *Management Review* dans ls_qms (SOP-QA-004), compte rendu joint.")],
        controls=["La revue a les états Open et Closed ; une revue close conserve son instantané d'historique des KPI."],
        good=["Envoyer le dossier d'entrée une semaine avant la réunion.",
              "Consigner les décisions comme des actions vérifiables, pas comme des intentions."],
        pitfalls=["Une revue réduite à une présentation sans décision."],
        records=["Revue de direction ou enregistrement qualité avec compte rendu", "Actions décidées"],
        kpis=["Actions de la dernière revue réalisées à temps"],
        example="**Cas.** Revue annuelle 2027 : entrées issues de 14 audits, 62 déviations, 11 CAPA en retard, tendances EM stables sauf le couloir C. Décisions : un vérificateur AQ supplémentaire (ressource), révision de la SOP de classification des déviations (CC-2028-002), nouvel objectif sur les délais CAPA. Consignée, close, actions attribuées.",
    ),
)

GEN002 = sop(
    "SOP-GEN-002", "mgmtsystem_kpi", "Management Systems ▸ KPI",
    related=["SOP-QA-005", "SOP-GEN-001"],
    refs=["ISO-9001", "ICH-Q10"],
    en=dict(
        title="Quality indicators (KPI)",
        owner="Head of Quality",
        objective="Define a small set of quality indicators with clear formulas, sources, frequencies and thresholds, and review them regularly.",
        scope="Indicators of the quality system and GMP processes (e.g. deviation closure time, CAPA on time, complaint rate, right-first-time batches, OOS rate, EM excursions, training compliance, supplier rating).",
        roles=[("Head of Quality", "Owns the KPI list."),
               ("Process owners", "Provide values and comment trends.")],
        defs=[("KPI", "Indicator computed periodically from a defined source, with thresholds (green/amber/red)."),
              ("KPI history", "Stored values over time, snapshotted into management reviews.")],
        steps=[("Define", "For each indicator write: name, formula, data source (menu or report of the suite), frequency, owner, thresholds, direction."),
               ("Configure", "Create the KPI in mgmtsystem_kpi (based on the OCA *kpi* module) with its computation and thresholds; or, if the module is not available, follow it as a quality objective with measurements in ls_qms (SOP-QA-005)."),
               ("Collect", "Compute or enter values at the defined frequency; check the source data."),
               ("Review", "Monthly in the quality meeting; quarterly and annually in management review (SOP-GEN-001).")],
        controls=["Indicator computation and history are managed by the kpi / mgmtsystem_kpi modules; check the installation limits before relying on them."],
        good=["Prefer indicators computed from system data rather than typed by hand.",
              "Pair each lagging indicator (e.g. complaints) with a leading one (e.g. CAPA on time)."],
        pitfalls=["Too many indicators, none of them acted upon."],
        records=["KPI definitions and history"],
        kpis=["KPIs out of threshold without action"],
        example="**Case.** KPI *CAPA closed on time (%)* = CAPA closed ≤ due date / CAPA closed, monthly, source {{Quality ▸ CAPA ▸ CAPA Records}}, green ≥ 90 %, red < 75 %. In March: 71 % → red; discussed in the quality meeting; action: weekly CAPA review.",
    ),
    fr=dict(
        title="Indicateurs qualité (KPI)",
        owner="Responsable qualité",
        objective="Définir un petit nombre d'indicateurs qualité avec formules, sources, fréquences et seuils clairs, et les revoir régulièrement.",
        scope="Indicateurs du système qualité et des processus BPF (ex. délai de clôture des déviations, CAPA dans les délais, taux de réclamations, lots bons du premier coup, taux d'OOS, excursions EM, conformité de la formation, note des fournisseurs).",
        roles=[("Responsable qualité", "Porte la liste des KPI."),
               ("Pilotes de processus", "Fournissent les valeurs et commentent les tendances.")],
        defs=[("KPI", "Indicateur calculé périodiquement depuis une source définie, avec seuils (vert/orange/rouge)."),
              ("Historique des KPI", "Valeurs conservées dans le temps, reprises dans les revues de direction.")],
        steps=[("Définir", "Pour chaque indicateur : nom, formule, source de données (menu ou rapport de la suite), fréquence, responsable, seuils, sens."),
               ("Paramétrer", "Créer le KPI dans mgmtsystem_kpi (fondé sur le module OCA *kpi*) avec son calcul et ses seuils ; ou, si le module n'est pas disponible, le suivre comme objectif qualité avec mesures dans ls_qms (SOP-QA-005)."),
               ("Recueillir", "Calculer ou saisir les valeurs à la fréquence définie ; vérifier les données sources."),
               ("Revoir", "Chaque mois en réunion qualité ; chaque trimestre et chaque année en revue de direction (SOP-GEN-001).")],
        controls=["Le calcul et l'historique des indicateurs sont gérés par les modules kpi / mgmtsystem_kpi ; vérifier les limites d'installation avant de s'y fier."],
        good=["Préférer des indicateurs calculés depuis les données du système plutôt que saisis à la main.",
              "Associer à chaque indicateur de résultat (ex. réclamations) un indicateur avancé (ex. CAPA dans les délais)."],
        pitfalls=["Trop d'indicateurs, aucun suivi d'action."],
        records=["Définitions et historique des KPI"],
        kpis=["KPI hors seuil sans action"],
        example="**Cas.** KPI *CAPA closes dans les délais (%)* = CAPA closes ≤ échéance / CAPA closes, mensuel, source {{Quality ▸ CAPA ▸ CAPA Records}}, vert ≥ 90 %, rouge < 75 %. En mars : 71 % → rouge ; discuté en réunion qualité ; action : revue hebdomadaire des CAPA.",
    ),
)

GEN003 = sop(
    "SOP-GEN-003", "maintenance_plan", "Maintenance ▸ Maintenance ▸ Maintenance Plans",
    shots=[("maintenance_plan__list", tr("Preventive maintenance plans (maintenance_plan).", "Plans de maintenance préventive (maintenance_plan)."))],
    related=["SOP-MET-001", "SOP-MP-002", "SOP-VAL-005"],
    refs=["EU-GMP-3", "CFR-211-68", "ISO-13485"],
    en=dict(
        title="Preventive maintenance of equipment",
        owner="Maintenance Manager",
        objective="Maintain GMP equipment at planned intervals so that it remains in its qualified state, and record every intervention.",
        scope="Production, utility and laboratory equipment registered in Odoo Maintenance. Moulds follow SOP-MP-002; measuring instruments follow SOP-MET-002.",
        roles=[("Maintenance Manager", "Defines plans and kinds of maintenance."),
               ("Technicians", "Perform maintenance requests and record work done."),
               ("QA", "Is informed of interventions that may affect the qualified state.")],
        defs=[("Maintenance plan", "Per equipment: kind, interval and interval step, duration, start date, planning horizon, instructions (PDF, slide or text); generates maintenance requests; next maintenance date computed.")],
        steps=[("Create plans", "On each equipment add maintenance plans: kind, interval (e.g. 3 months), duration, start date, horizon, instructions."),
               ("Execute", "Perform the generated maintenance requests; record the work done and parts replaced; close the request."),
               ("Assess impact", "When an intervention may affect the qualified state (e.g. replacement of a critical part), raise a change request (SOP-QA-030) or a revalidation (SOP-VAL-005) before release to production."),
               ("Review", "Review overdue requests weekly; adjust intervals with failure history.")],
        controls=["Next maintenance dates are computed from the plan interval; requests are generated within the planning horizon."],
        good=["Attach the GMP-relevant instructions (cleaning after maintenance, line clearance) to the plan."],
        pitfalls=["Equipment returned to production after intervention without QA being informed."],
        records=["Maintenance plans and requests with work done"],
        kpis=["Preventive maintenance done on time (%)", "Corrective interventions per equipment"],
        example="**Case.** Tablet press TP-02: plan *Preventive — 3 months*, 4 h, instructions PDF; the request of June is done: turret cleaned, punches inspected; no part replaced → no revalidation needed; request closed.",
    ),
    fr=dict(
        title="Maintenance préventive des équipements",
        owner="Responsable maintenance",
        objective="Entretenir les équipements BPF à intervalles planifiés pour qu'ils restent dans leur état qualifié, et enregistrer chaque intervention.",
        scope="Équipements de production, d'utilités et de laboratoire enregistrés dans Odoo Maintenance. Les moules suivent la SOP-MP-002 ; les instruments de mesure la SOP-MET-002.",
        roles=[("Responsable maintenance", "Définit les plans et types de maintenance."),
               ("Techniciens", "Réalisent les demandes de maintenance et consignent le travail."),
               ("AQ", "Est informée des interventions pouvant affecter l'état qualifié.")],
        defs=[("Plan de maintenance", "Par équipement : type, intervalle et pas, durée, date de début, horizon de planification, instructions (PDF, diapositive ou texte) ; génère les demandes de maintenance ; prochaine date calculée.")],
        steps=[("Créer les plans", "Sur chaque équipement, ajouter les plans : type, intervalle (ex. 3 mois), durée, date de début, horizon, instructions."),
               ("Réaliser", "Réaliser les demandes générées ; consigner le travail et les pièces remplacées ; clore la demande."),
               ("Évaluer l'impact", "Quand une intervention peut affecter l'état qualifié (ex. remplacement d'une pièce critique), ouvrir une demande de changement (SOP-QA-030) ou une revalidation (SOP-VAL-005) avant la remise en production."),
               ("Revoir", "Revoir chaque semaine les demandes en retard ; ajuster les intervalles selon l'historique de pannes.")],
        controls=["Les prochaines dates sont calculées depuis l'intervalle du plan ; les demandes sont générées dans l'horizon de planification."],
        good=["Joindre au plan les instructions BPF (nettoyage après intervention, vide de ligne)."],
        pitfalls=["Un équipement remis en production après intervention sans information de l'AQ."],
        records=["Plans et demandes de maintenance avec travaux réalisés"],
        kpis=["Maintenance préventive réalisée à temps (%)", "Interventions correctives par équipement"],
        example="**Cas.** Presse à comprimés TP-02 : plan *Préventif — 3 mois*, 4 h, instructions en PDF ; la demande de juin est réalisée : tourelle nettoyée, poinçons inspectés ; aucune pièce remplacée → pas de revalidation ; demande close.",
    ),
)

GEN004 = sop(
    "SOP-GEN-004", "maintenance_equipment_certification", "Maintenance ▸ Configuration ▸ Certificates / Certificate Reminder Rules",
    related=["SOP-GEN-003", "SOP-MET-004"],
    refs=["EU-GMP-3"],
    en=dict(
        title="Regulatory certificates of equipment",
        owner="Maintenance Manager / EHS",
        objective="Keep the regulatory certificates of equipment (pressure vessels, lifting equipment, electrical installations, etc.) current, with reminders before renewal dates.",
        scope="Equipment subject to statutory inspections or certifications.",
        roles=[("Maintenance Manager", "Records certificates and renewals."),
               ("EHS", "Defines which equipment needs which certificate.")],
        defs=[("Certificate", "Name, certificate number, date, renewal date, file, notes, linked equipment."),
              ("Reminder rule", "Number of days before renewal at which a reminder is sent (activated in settings).")],
        steps=[("Configure reminders", "Enable certificate expiration notifications in the settings and create reminder rules (e.g. 60 and 15 days before)."),
               ("Record", "On the equipment add each certificate with number, date, renewal date and file."),
               ("Renew", "Schedule the inspection before the renewal date; record the new certificate; archive the old one."),
               ("Stop use", "If a certificate expires, stop using the equipment until renewed.")],
        controls=["Reminders are sent according to the rules when notifications are enabled."],
        good=["Keep inspection reports with their certificate."],
        pitfalls=["Relying on the inspection body to remind you."],
        records=["Equipment certificates with files"],
        kpis=["Expired certificates of equipment in use (target 0)"],
        example="**Case.** Autoclave AC-02 pressure vessel certificate renewed every 24 months; reminders at 60 and 15 days; the inspection is performed 3 weeks before the renewal date and the new certificate attached.",
    ),
    fr=dict(
        title="Certificats réglementaires des équipements",
        owner="Responsable maintenance / HSE",
        objective="Tenir à jour les certificats réglementaires des équipements (appareils à pression, appareils de levage, installations électriques, etc.), avec rappels avant les dates de renouvellement.",
        scope="Équipements soumis à des vérifications ou certifications réglementaires.",
        roles=[("Responsable maintenance", "Enregistre certificats et renouvellements."),
               ("HSE", "Définit quels équipements exigent quels certificats.")],
        defs=[("Certificat", "Nom, numéro, date, date de renouvellement, fichier, notes, équipement lié."),
              ("Règle de rappel", "Nombre de jours avant renouvellement auquel un rappel est envoyé (activé dans les paramètres).")],
        steps=[("Paramétrer les rappels", "Activer les notifications d'expiration dans les paramètres et créer les règles (ex. 60 et 15 jours avant)."),
               ("Enregistrer", "Sur l'équipement, ajouter chaque certificat avec numéro, date, date de renouvellement et fichier."),
               ("Renouveler", "Programmer la vérification avant la date de renouvellement ; enregistrer le nouveau certificat ; archiver l'ancien."),
               ("Arrêter l'usage", "Si un certificat expire, cesser d'utiliser l'équipement jusqu'au renouvellement.")],
        controls=["Les rappels sont envoyés selon les règles quand les notifications sont activées."],
        good=["Conserver les rapports de vérification avec leur certificat."],
        pitfalls=["Compter sur l'organisme de contrôle pour les rappels."],
        records=["Certificats des équipements avec fichiers"],
        kpis=["Certificats expirés d'équipements en service (cible 0)"],
        example="**Cas.** Le certificat d'appareil à pression de l'autoclave AC-02 est renouvelé tous les 24 mois ; rappels à 60 et 15 jours ; la vérification a lieu 3 semaines avant l'échéance et le nouveau certificat est joint.",
    ),
)

IT001 = sop(
    "SOP-IT-001", "base_user_role", "Settings ▸ Users & Companies ▸ Roles",
    related=["SOP-DI-011", "SOP-QA-013"],
    refs=["EU-A11", "CFR-11", "PICS-DI"],
    en=dict(
        title="Role-based access management and periodic review of access rights",
        owner="System Owner with IT",
        objective="Grant access rights through documented roles matching job functions and the segregation of duties of the SOPs, and review them periodically.",
        scope="All users of the Odoo installation, all LS module groups and standard Odoo groups.",
        roles=[("System Owner", "Defines roles, approves access requests, performs the periodic review."),
               ("IT administrator", "Implements approved changes; never grants rights without approval."),
               ("Line managers", "Request access and removal for their staff.")],
        defs=[("Role", "Named set of groups (base_user_role) assigned to users, optionally with *From* and *To* dates."),
              ("Access matrix", "Document listing, per job function, the roles and the LS groups granted.")],
        steps=[("Design roles", "Build roles from the responsibilities tables of the SOPs (e.g. *QA officer* = Deviation Investigator + CAPA Coordinator + Document Approver + Laboratory Reviewer…). Check that no role combines incompatible duties (e.g. batch manufacturer and release authority)."),
               ("Request and approve", "Access requests are made by the line manager and approved by the System Owner; record them (ticket or quality record)."),
               ("Assign", "Assign roles to users with dates when temporary (holidays, projects). Without base_user_role (see limitations), assign groups directly and keep the access matrix as the reference."),
               ("Link to training", "Grant critical roles only to users with valid qualifications (SOP-QA-013)."),
               ("Remove", "Remove access the day a person leaves or changes job."),
               ("Review", "Every 6 months (critical systems) export users and groups, compare with the matrix and HR list, correct differences, record the review.")],
        controls=["Role lines can be limited in time (From/To); each LS module enforces its own group checks and segregation-of-duties rules regardless of the role mechanism."],
        good=["Give administrators separate personal accounts for administration and for business use.",
              "Keep at least two people per critical approval role."],
        pitfalls=["Granting *Manager* groups to everyone to avoid access errors — this defeats segregation of duties."],
        records=["Access matrix", "Access requests and approvals", "Periodic review records"],
        kpis=["Differences found at review", "Leavers with active accounts (target 0)"],
        example="**Case.** Semi-annual review: 142 active users; 3 leavers still active (disabled the same day), 2 users with Deviation Manager who changed jobs (removed), 1 missing Laboratory Reviewer backup (granted after training). Review recorded as a quality record.",
    ),
    fr=dict(
        title="Gestion des accès par rôles et revue périodique des droits",
        owner="Propriétaire du système avec l'informatique",
        objective="Attribuer les droits d'accès par des rôles documentés correspondant aux fonctions et à la séparation des tâches des SOP, et les revoir périodiquement.",
        scope="Tous les utilisateurs de l'installation Odoo, tous les groupes des modules LS et les groupes Odoo standard.",
        roles=[("Propriétaire du système", "Définit les rôles, approuve les demandes d'accès, réalise la revue périodique."),
               ("Administrateur informatique", "Met en œuvre les changements approuvés ; n'accorde jamais de droits sans approbation."),
               ("Encadrement", "Demande les ouvertures et retraits pour son personnel.")],
        defs=[("Rôle", "Ensemble nommé de groupes (base_user_role) attribué aux utilisateurs, éventuellement avec des dates *From* et *To*."),
              ("Matrice d'accès", "Document listant, par fonction, les rôles et groupes LS accordés.")],
        steps=[("Concevoir les rôles", "Construire les rôles à partir des tableaux de responsabilités des SOP (ex. *Chargé AQ* = Deviation Investigator + CAPA Coordinator + Document Approver + Laboratory Reviewer…). Vérifier qu'aucun rôle ne cumule des tâches incompatibles (ex. fabricant du lot et autorité de libération)."),
               ("Demander et approuver", "L'encadrement demande, le propriétaire du système approuve ; conserver la trace (ticket ou enregistrement qualité)."),
               ("Attribuer", "Attribuer les rôles aux utilisateurs, avec dates si temporaires (congés, projets). Sans base_user_role (voir limites), attribuer les groupes directement et garder la matrice comme référence."),
               ("Lier à la formation", "N'attribuer les rôles critiques qu'aux utilisateurs disposant d'habilitations valides (SOP-QA-013)."),
               ("Retirer", "Retirer les accès le jour du départ ou du changement de poste."),
               ("Revoir", "Tous les 6 mois (systèmes critiques), exporter utilisateurs et groupes, comparer à la matrice et à la liste RH, corriger les écarts, consigner la revue.")],
        controls=["Les lignes de rôle peuvent être limitées dans le temps (From/To) ; chaque module LS applique ses propres contrôles de groupes et de séparation des tâches, quel que soit le mécanisme de rôles."],
        good=["Donner aux administrateurs des comptes personnels distincts pour l'administration et pour l'usage métier.",
              "Garder au moins deux personnes par rôle d'approbation critique."],
        pitfalls=["Donner les groupes *Manager* à tous pour éviter les erreurs d'accès — cela annule la séparation des tâches."],
        records=["Matrice d'accès", "Demandes et approbations d'accès", "Revues périodiques"],
        kpis=["Écarts trouvés à la revue", "Partants avec compte actif (cible 0)"],
        example="**Cas.** Revue semestrielle : 142 utilisateurs actifs ; 3 partants encore actifs (désactivés le jour même), 2 utilisateurs Deviation Manager ayant changé de poste (retirés), 1 suppléant Laboratory Reviewer manquant (accordé après formation). Revue consignée en enregistrement qualité.",
    ),
)

IT002 = sop(
    "SOP-IT-002", "auditlog", "Settings ▸ Technical ▸ Audit ▸ Rules / Logs (menu defined by the module)",
    related=["SOP-DI-001", "SOP-DI-002"],
    refs=["EU-A11", "PICS-DI"],
    en=dict(
        title="Technical audit log",
        owner="IT administrator with the System Owner",
        objective="Use the OCA auditlog module, where installed, to log technical operations (including reads, sessions and HTTP requests) useful for security investigations, and keep it distinct from the GxP audit trail.",
        scope="Technical and security logging of selected models. GxP record changes are covered by ls_audit_trail (SOP-DI-001 to 004).",
        roles=[("IT administrator", "Configures rules and investigates security events."),
               ("System Owner / QA", "Approves the scope and reviews findings.")],
        defs=[("auditlog rule", "Model with log_read, log_write, log_create, log_unlink options, log type (full or fast), capture of the record."),
              ("Difference with ls_audit_trail", "auditlog entries are not hash-chained; ls_audit_trail provides tamper-evidence, verification and evidence packs.")],
        steps=[("Decide the need", "Define which technical events must be logged (e.g. reads of personal data, access to configuration) and why ls_audit_trail does not cover them."),
               ("Configure", "Create rules for the selected models and subscribe them; keep reads logging limited (volume)."),
               ("Review", "Review the logs during security investigations and periodically for administrator activity."),
               ("Retain and purge", "Define retention and purge the logs by the module's scheduled action according to the IT policy.")],
        controls=["At the time of writing, auditlog failed to install on a fresh Odoo 19.0 database (view reference *view_auditlog_http_request_tree* not found). Fix and validate the module before relying on this SOP."],
        good=["Do not duplicate GxP auditing in two tools with different rules — use ls_audit_trail for GxP."],
        pitfalls=["Logging reads on large models, degrading performance."],
        records=["auditlog rules", "Investigation extracts"],
        kpis=["Security investigations using the log"],
        example="**Case.** Reads of the HR employee model are logged to support investigations of personal data access; changes to GxP records remain in ls_audit_trail.",
    ),
    fr=dict(
        title="Journal d'audit technique",
        owner="Administrateur informatique avec le propriétaire du système",
        objective="Utiliser le module OCA auditlog, lorsqu'il est installé, pour journaliser des opérations techniques (y compris lectures, sessions et requêtes HTTP) utiles aux enquêtes de sécurité, en le distinguant de la piste d'audit GxP.",
        scope="Journalisation technique et de sécurité de modèles choisis. Les modifications des enregistrements GxP relèvent de ls_audit_trail (SOP-DI-001 à 004).",
        roles=[("Administrateur informatique", "Paramètre les règles et investigue les événements de sécurité."),
               ("Propriétaire du système / AQ", "Approuvent le périmètre et revoient les constats.")],
        defs=[("Règle auditlog", "Modèle avec options log_read, log_write, log_create, log_unlink, type de journal (complet ou rapide), capture de l'enregistrement."),
              ("Différence avec ls_audit_trail", "Les entrées auditlog ne sont pas chaînées ; ls_audit_trail apporte l'infalsifiabilité, la vérification et les dossiers de preuves.")],
        steps=[("Décider du besoin", "Définir quels événements techniques journaliser (ex. lectures de données personnelles, accès au paramétrage) et pourquoi ls_audit_trail ne les couvre pas."),
               ("Paramétrer", "Créer les règles pour les modèles choisis et les activer ; limiter la journalisation des lectures (volume)."),
               ("Revoir", "Revoir les journaux lors des enquêtes de sécurité et périodiquement pour l'activité des administrateurs."),
               ("Conserver et purger", "Définir la conservation et purger les journaux par l'action planifiée du module selon la politique informatique.")],
        controls=["Lors de la rédaction, auditlog échouait à l'installation sur une base Odoo 19.0 neuve (référence de vue *view_auditlog_http_request_tree* introuvable). Corriger et valider le module avant de s'appuyer sur cette SOP."],
        good=["Ne pas dupliquer l'audit GxP dans deux outils aux règles différentes — utiliser ls_audit_trail pour le GxP."],
        pitfalls=["Journaliser les lectures de gros modèles et dégrader les performances."],
        records=["Règles auditlog", "Extraits d'enquête"],
        kpis=["Enquêtes de sécurité utilisant le journal"],
        example="**Cas.** Les lectures du modèle salarié RH sont journalisées pour les enquêtes sur l'accès aux données personnelles ; les modifications des enregistrements GxP restent dans ls_audit_trail.",
    ),
)

QC020 = sop(
    "SOP-QC-020", "quality_control_oca", "Quality Control ▸ Inspections ▸ Inspections · Tests ▸ Tests",
    shots=[("qc_test__list", tr("Inspection test definitions (quality_control_oca).", "Définitions d'essais d'inspection (quality_control_oca)."))],
    related=["SOP-QC-011", "SOP-QA-070"],
    refs=["ISO-13485", "CFR-211-84", "EU-GMP-5"],
    en=dict(
        title="Generic inspection controls, for example at reception",
        owner="QC Manager",
        objective="Perform simple, questionnaire-based inspections (e.g. visual and documentary checks at reception) with recorded answers and a pass/fail outcome, where a full laboratory sample is not needed.",
        scope="Incoming visual/identity checks, packaging inspections and other attribute inspections. Analytical testing is managed in ls_lab.",
        roles=[("Inspector", "Performs the inspection and records answers."),
               ("Supervisor", "Approves inspections waiting for approval.")],
        defs=[("Test", "Set of questions (qualitative with allowed values, or quantitative with min/max)."),
              ("Inspection states", "Plan, Draft, Ready, Waiting supervisor approval, Quality success, Quality failed, Canceled.")],
        steps=[("Define tests", "In {{Quality Control ▸ Tests ▸ Tests}} create the test and its questions with acceptable values or ranges; group tests by category."),
               ("Create the inspection", "Create an inspection for the object (e.g. the product/lot received) and select the test. Note: automatic creation on receipts requires a stock integration module that is not present in the repository — inspections are created manually."),
               ("Record answers", "Answer each question; the outcome is computed; confirm the inspection."),
               ("Approve", "Inspections requiring approval go to *Waiting supervisor approval*; the supervisor approves."),
               ("Act on failure", "A failed inspection leads to quarantine and a deviation or supplier complaint.")],
        controls=["The inspection outcome (success) is computed from the answers against the defined values or ranges."],
        good=["Keep tests short and specific to the material category."],
        pitfalls=["Using generic inspections for analytical tests that need method, specification and review (use ls_lab)."],
        records=["Inspections with answers and outcome"],
        kpis=["Failed inspections per supplier"],
        example="**Case.** Reception of printed cartons: test *Carton — reception* with 6 questions (supplier label present, quantity matches, artwork version, colour vs standard, no damage, CoC present). One carton lot has artwork version 3 instead of 4 → *Quality failed*, lot quarantined, supplier complaint opened.",
    ),
    fr=dict(
        title="Contrôles d'inspection génériques, par exemple à la réception",
        owner="Responsable CQ",
        objective="Réaliser des inspections simples fondées sur un questionnaire (ex. contrôles visuels et documentaires à réception), avec réponses enregistrées et résultat conforme/non conforme, lorsqu'un échantillon de laboratoire complet n'est pas nécessaire.",
        scope="Contrôles visuels/d'identité à réception, inspections de conditionnement et autres contrôles par attributs. Les analyses relèvent de ls_lab.",
        roles=[("Inspecteur", "Réalise l'inspection et enregistre les réponses."),
               ("Superviseur", "Approuve les inspections en attente d'approbation.")],
        defs=[("Test", "Ensemble de questions (qualitatives avec valeurs admises, ou quantitatives avec min/max)."),
              ("États d'inspection", "Plan, Draft, Ready, Waiting supervisor approval, Quality success, Quality failed, Canceled.")],
        steps=[("Définir les tests", "Dans {{Quality Control ▸ Tests ▸ Tests}}, créer le test et ses questions avec valeurs ou plages acceptables ; grouper les tests par catégorie."),
               ("Créer l'inspection", "Créer une inspection pour l'objet (ex. produit/lot reçu) et choisir le test. Remarque : la création automatique sur les réceptions exige un module d'intégration stock absent du dépôt — les inspections sont créées manuellement."),
               ("Répondre", "Répondre à chaque question ; le résultat est calculé ; confirmer l'inspection."),
               ("Approuver", "Les inspections soumises à approbation passent *Waiting supervisor approval* ; le superviseur approuve."),
               ("Agir sur un échec", "Une inspection en échec conduit à la quarantaine et à une déviation ou une réclamation fournisseur.")],
        controls=["Le résultat de l'inspection (succès) est calculé à partir des réponses selon les valeurs ou plages définies."],
        good=["Garder des tests courts et propres à la catégorie de matière."],
        pitfalls=["Utiliser les inspections génériques pour des analyses qui exigent méthode, spécification et revue (utiliser ls_lab)."],
        records=["Inspections avec réponses et résultat"],
        kpis=["Inspections en échec par fournisseur"],
        example="**Cas.** Réception d'étuis imprimés : test *Étui — réception* à 6 questions (étiquette fournisseur, quantité, version de maquette, couleur vs standard, absence de dommage, certificat de conformité). Un lot porte la maquette version 3 au lieu de 4 → *Quality failed*, lot en quarantaine, réclamation fournisseur ouverte.",
    ),
)

UNCOVERED = {
    "kind": "chapter", "id": "part6",
    "en": {"title": "Part VI — Procedures needed but not covered by the suite", "blocks": [
        ("p", "These procedures depend on infrastructure and organisation, not on the modules. They are nevertheless "
              "required by GMP and data integrity guidance (EU GMP Annex 11, PIC/S PI 041-1) for the suite to be used "
              "in a regulated way. Each outline below lists what the SOP must contain; the content must be written with "
              "IT and the hosting provider."),
        ("table", ["Proposed code", "Procedure", "What it must contain"], [
            ["SOP-IT-010", "Backup and restore", "Scope (database, filestore, configuration), frequency and retention, encryption, off-site copy, restore test at defined intervals with evidence (restore to a test environment and verification of records, audit trail chain and signature chain — SOP-DI-002, SOP-DI-012), responsibilities."],
            ["SOP-IT-011", "Business continuity and disaster recovery", "Recovery time and recovery point objectives per process, fallback on paper (forms, later transcription and verification), crisis roles, periodic exercise, return to normal."],
            ["SOP-IT-012", "IT incident management", "Detection, classification (including data integrity impact), escalation to QA, investigation, link to deviation/CAPA, communication, closure."],
            ["SOP-IT-013", "Physical security of servers", "Location, access control and logs, environment (power, temperature, fire), visitor rules, cloud provider controls when hosted."],
            ["SOP-IT-014", "Qualification of the hosting", "Supplier assessment of the hosting/cloud provider (SOP-QA-070), service agreement, infrastructure qualification (IQ), security certifications, change notification."],
            ["SOP-VAL-010", "Validation of the suite itself (IQ, OQ, PQ of the system)", "User requirements, supplier assessment of the modules, risk-based test strategy (SOP-VAL-006), installation qualification of Odoo and modules (versions, installation log without errors), operational qualification of the controls listed in this handbook, performance qualification with real data and users, traceability matrix, report, periodic review and change control of upgrades."],
        ]),
        ("box", "note", "Why these matter here", "Several controls of the suite depend on the database (append-only triggers, hash chains, scheduled integrity checks). A restore, a migration or a server change can therefore affect regulated evidence: backup/restore and validation procedures must include the verification of the audit trail and signature chains after any restore."),
    ]},
    "fr": {"title": "Partie VI — Procédures nécessaires mais non couvertes par la suite", "blocks": [
        ("p", "Ces procédures dépendent de l'infrastructure et de l'organisation, pas des modules. Elles sont pourtant "
              "exigées par les BPF et les guides d'intégrité des données (BPF UE annexe 11, PIC/S PI 041-1) pour que la "
              "suite soit utilisée de façon conforme. Chaque trame ci-dessous liste ce que la SOP doit contenir ; le "
              "contenu est à rédiger avec l'informatique et l'hébergeur."),
        ("table", ["Code proposé", "Procédure", "Contenu attendu"], [
            ["SOP-IT-010", "Sauvegarde et restauration", "Périmètre (base, fichiers, configuration), fréquence et conservation, chiffrement, copie hors site, test de restauration à intervalles définis avec preuve (restauration sur un environnement de test et vérification des enregistrements, de la chaîne de piste d'audit et de la chaîne de signatures — SOP-DI-002, SOP-DI-012), responsabilités."],
            ["SOP-IT-011", "Plan de continuité et reprise après sinistre", "Objectifs de durée et de point de reprise par processus, mode dégradé papier (formulaires, retranscription et vérification ultérieures), rôles de crise, exercice périodique, retour à la normale."],
            ["SOP-IT-012", "Gestion des incidents informatiques", "Détection, classification (dont impact sur l'intégrité des données), escalade à l'AQ, investigation, lien avec déviation/CAPA, communication, clôture."],
            ["SOP-IT-013", "Sécurité physique des serveurs", "Emplacement, contrôle et journal des accès, environnement (électricité, température, incendie), règles pour les visiteurs, contrôles du fournisseur cloud en cas d'hébergement."],
            ["SOP-IT-014", "Qualification de l'hébergement", "Évaluation fournisseur de l'hébergeur/fournisseur cloud (SOP-QA-070), contrat de service, qualification de l'infrastructure (QI), certifications de sécurité, notification des changements."],
            ["SOP-VAL-010", "Validation de la suite elle-même (IQ, OQ, PQ du système)", "Besoins utilisateurs, évaluation fournisseur des modules, stratégie de test fondée sur le risque (SOP-VAL-006), qualification d'installation d'Odoo et des modules (versions, journal d'installation sans erreur), qualification opérationnelle des contrôles listés dans ce manuel, qualification de performance avec données et utilisateurs réels, matrice de traçabilité, rapport, revue périodique et maîtrise des changements des mises à jour."],
        ]),
        ("box", "note", "Pourquoi c'est important ici", "Plusieurs contrôles de la suite reposent sur la base de données (déclencheurs d'ajout seul, chaînes d'empreintes, vérifications planifiées). Une restauration, une migration ou un changement de serveur peut donc affecter des preuves réglementées : les procédures de sauvegarde/restauration et de validation doivent inclure la vérification des chaînes de piste d'audit et de signatures après toute restauration."),
    ]},
}

ITEMS = [P4, M_IE, RA010, RA011, P5, GEN001, GEN002, GEN003, GEN004, IT001, IT002, QC020, UNCOVERED]
