# -*- coding: utf-8 -*-
"""Part I (b) — Deviations and CAPA, change control, complaints."""
from .helpers import module, sop, tr

M_DEV = module(
    "mod-dev", "ls_deviation · ls_capa", "Deviations and CAPA", "Déviations et CAPA",
    [
        ("p", "**ls_deviation** records departures from approved instructions or specifications: classification "
              "(type, category, severity), impact assessment, immediate actions, investigations with a root cause "
              "analysis method, product dispositions and closure. Every state change is written in an append-only "
              "*Transition Log*. **ls_capa** manages corrective and preventive actions from any source (audit, "
              "deviation, complaint, inspection, management review, risk assessment…): impact assessment, root cause "
              "analyses (Five Whys, Ishikawa, FMEA), actions (optionally turned into project tasks), effectiveness "
              "checks and closure."),
        ("table", ["Menu", "Content"], [
            ["{{Quality Management ▸ Deviations ▸ All Deviations / My Deviations}}", "Deviation records"],
            ["{{Quality Management ▸ Deviations ▸ Immediate Actions / Investigations / Product Dispositions}}", "Sub-records"],
            ["{{Quality Management ▸ Reporting ▸ Deviation Analysis / Transition Log}}", "Analysis and audit trail of transitions"],
            ["{{Quality ▸ CAPA ▸ CAPA Records / Root Cause Analyses / Actions / Effectiveness Verification}}", "CAPA records"],
            ["Settings: closure target (days) per severity", "Configured per company (default 30 days for minor, major and critical)"],
        ]),
        ("table", ["Group", "Main rights"], [
            ["Deviation: Viewer · Reporter · Investigator · Manager", "Reporter declares; Investigator assesses and investigates; Manager approves dispositions, closes, and alone may edit closed records."],
            ["CAPA: Viewer · Investigator · Coordinator · Manager", "Investigator performs analyses and actions; Coordinator drives the record; Manager closes."],
        ]),
        ("flow", "deviation", "Lifecycle of a deviation."),
        ("flow", "capa", "Lifecycle of a CAPA record."),
        ("shot", "ls_deviation__form", "Deviation form: classification, chronology, subject, status bar."),
    ],
    [
        ("p", "**ls_deviation** enregistre les écarts aux instructions ou spécifications approuvées : classification (type, "
              "catégorie, gravité), évaluation d'impact, actions immédiates, investigations avec méthode d'analyse des "
              "causes, dispositions du produit et clôture. Chaque changement d'état est écrit dans un journal des "
              "transitions (*Transition Log*) en ajout seul. **ls_capa** gère les actions correctives et préventives de "
              "toute origine (audit, déviation, réclamation, inspection, revue de direction, analyse de risque…) : "
              "évaluation d'impact, analyses de causes (5 Pourquoi, Ishikawa, AMDE), actions (éventuellement converties en "
              "tâches de projet), vérifications d'efficacité et clôture."),
        ("table", ["Menu", "Contenu"], [
            ["{{Quality Management ▸ Deviations ▸ All Deviations / My Deviations}}", "Déviations"],
            ["{{Quality Management ▸ Deviations ▸ Immediate Actions / Investigations / Product Dispositions}}", "Sous-enregistrements"],
            ["{{Quality Management ▸ Reporting ▸ Deviation Analysis / Transition Log}}", "Analyse et traçabilité des transitions"],
            ["{{Quality ▸ CAPA ▸ CAPA Records / Root Cause Analyses / Actions / Effectiveness Verification}}", "CAPA"],
            ["Paramètres : délai de clôture (jours) par gravité", "Par société (30 jours par défaut pour mineure, majeure et critique)"],
        ]),
        ("table", ["Groupe", "Droits principaux"], [
            ["Deviation : Viewer · Reporter · Investigator · Manager", "Reporter déclare ; Investigator évalue et enquête ; Manager approuve les dispositions, clôt, et seul peut modifier une déviation close."],
            ["CAPA : Viewer · Investigator · Coordinator · Manager", "Investigator réalise analyses et actions ; Coordinator pilote la CAPA ; Manager clôt."],
        ]),
        ("flow", "deviation", "Cycle de vie d'une déviation."),
        ("flow", "capa", "Cycle de vie d'une CAPA."),
        ("shot", "ls_deviation__form", "Fiche déviation : classification, chronologie, objet, barre d'état."),
    ],
)

QA020 = sop(
    "SOP-QA-020", "ls_deviation", "Quality Management ▸ Deviations ▸ All Deviations",
    flows=[("deviation", tr("Deviation lifecycle; this SOP covers Reported → Assessed.", "Cycle de vie d'une déviation ; cette SOP couvre Reported → Assessed."))],
    shots=[("ls_deviation__list", tr("Deviation register with severity and overdue flag.", "Registre des déviations avec gravité et retard."))],
    related=["SOP-QA-021", "SOP-QA-022", "SOP-QA-030"],
    refs=["EU-GMP-1", "EU-GMP-5", "CFR-211-100", "CFR-211-192", "ICH-Q10", "ICH-Q9"],
    en=dict(
        title="Reporting, assessment and classification of deviations",
        owner="Head of Quality Assurance",
        objective="Make sure that every departure from an approved procedure, specification or condition is reported without delay, contained, and classified by QA on the basis of a documented impact assessment.",
        scope="Unplanned deviations and planned deviations (temporary departures approved in advance) in production, quality control, warehouse, engineering and utilities.",
        roles=[("Any employee (Deviation Reporter)", "Reports the event immediately and takes safe immediate actions."),
               ("Supervisor", "Checks the report on the same shift, completes immediate actions."),
               ("Deviation Investigator / QA", "Documents the impact assessment, sets the severity, assigns the investigator."),
               ("Deviation Manager (QA)", "Confirms the classification; decides on planned deviations.")],
        defs=[("Deviation", "Departure from an approved instruction, specification or established standard."),
              ("Planned deviation", "Departure approved before execution; it requires a justification recorded beforehand."),
              ("Severity", "Minor, Major or Critical, according to the potential impact on patient safety, product quality, regulatory compliance and validated state.")],
        steps=[("Contain", "Stop or secure the activity if needed; segregate the material concerned."),
               ("Report", "In {{Quality Management ▸ Deviations}} click [[New]]. Enter title, description, deviation type, category, occurrence and detection dates, product, lots, manufacturing order, equipment, location and quantity affected. For a planned deviation, tick *Planned Deviation* and write the justification before execution."),
               ("Record immediate actions", "Add each immediate action (containment, segregation, notification) with its owner; mark it done with completion evidence."),
               ("Assess the impact", "QA completes the impact questions (patient safety, product quality, regulatory, validation, other batches) and the impact assessment text."),
               ("Classify", "Set the severity and assign the investigator and QA reviewer. The target closure date is proposed from the company setting for that severity."),
               ("Complete the assessment", "Click [[Complete Assessment]]. The state becomes *Assessed* and the transition is logged."),
               ("Send back if incomplete", "QA uses [[Send Back]] when the report is not usable, with an explanation in the chatter."),
               ("Extend if necessary", "A target date can only be extended with [[Extend Target Date]] and a rationale.")],
        controls=["Occurrence date ≤ detection date ≤ recording date.",
                  "A planned deviation requires a justification recorded before execution.",
                  "An affected quantity requires a product.",
                  "Assessment requires a severity, a documented impact assessment and an assigned investigator.",
                  "An immediate action cannot be marked done without completion evidence.",
                  "A deviation that progressed beyond *Reported* cannot be deleted — only cancelled with a reason.",
                  "Every transition is recorded in the append-only Transition Log (cannot be edited or deleted)."],
        good=["Report within the shift; a late deviation report is itself a finding.",
              "Describe facts (what, where, when, how much), not opinions or blame.",
              "Classify on the potential impact, not on the likely outcome of the investigation.",
              "Check the list of open deviations at the daily production meeting."],
        pitfalls=["Correcting the situation and \"forgetting\" the report.",
                  "Grouping unrelated events in one deviation.",
                  "Downgrading severity to meet the closure target."],
        records=["Deviation record with transition log", "Immediate actions with evidence", "Impact assessment"],
        kpis=["Time from occurrence to report", "Deviations by type/category (trend)", "% classified within 2 working days"],
        example="**Case.** During filling, an operator sees that the room differential pressure alarm had been active for 40 minutes. The supervisor stops filling, quarantines the 1 200 units filled in that period and reports deviation DEV/2026/00017: type *Environmental Excursion*, category *Production*, product and lot filled. Immediate actions: quarantine (done, evidence: quarantine label photo) and notification of QA (done). QA assesses a potential impact on product quality and on other batches, sets severity *Major*, assigns the investigator and clicks [[Complete Assessment]].",
    ),
    fr=dict(
        title="Déclaration, évaluation et classification des déviations",
        owner="Responsable assurance qualité",
        objective="Faire en sorte que tout écart à une procédure, spécification ou condition approuvée soit déclaré sans délai, maîtrisé, et classé par l'AQ sur la base d'une évaluation d'impact documentée.",
        scope="Déviations non planifiées et déviations planifiées (écarts temporaires approuvés à l'avance) en production, contrôle qualité, magasin, maintenance et utilités.",
        roles=[("Tout salarié (Deviation Reporter)", "Déclare l'événement immédiatement et prend les actions immédiates sûres."),
               ("Chef d'équipe", "Vérifie la déclaration dans le poste, complète les actions immédiates."),
               ("Deviation Investigator / AQ", "Documente l'évaluation d'impact, fixe la gravité, désigne l'enquêteur."),
               ("Deviation Manager (AQ)", "Confirme la classification ; décide des déviations planifiées.")],
        defs=[("Déviation", "Écart par rapport à une instruction, une spécification ou un standard approuvé."),
              ("Déviation planifiée", "Écart approuvé avant exécution ; exige une justification enregistrée au préalable."),
              ("Gravité", "Minor, Major ou Critical, selon l'impact potentiel sur la sécurité du patient, la qualité du produit, la conformité réglementaire et l'état validé.")],
        steps=[("Maîtriser", "Arrêter ou sécuriser l'activité si nécessaire ; isoler la matière concernée."),
               ("Déclarer", "Dans {{Quality Management ▸ Deviations}}, cliquer sur [[New]]. Saisir titre, description, type, catégorie, dates de survenue et de détection, produit, lots, ordre de fabrication, équipement, emplacement et quantité concernée. Pour une déviation planifiée, cocher *Planned Deviation* et rédiger la justification avant exécution."),
               ("Enregistrer les actions immédiates", "Ajouter chaque action immédiate (confinement, isolement, information) avec son responsable ; la marquer faite avec la preuve de réalisation."),
               ("Évaluer l'impact", "L'AQ renseigne les questions d'impact (sécurité patient, qualité produit, réglementaire, validation, autres lots) et le texte d'évaluation."),
               ("Classer", "Fixer la gravité, désigner l'enquêteur et le vérificateur AQ. La date cible de clôture est proposée selon le paramètre société pour cette gravité."),
               ("Terminer l'évaluation", "Cliquer sur [[Complete Assessment]]. L'état devient *Assessed* et la transition est journalisée."),
               ("Renvoyer si incomplet", "L'AQ utilise [[Send Back]] si la déclaration est inexploitable, avec une explication dans le fil de discussion."),
               ("Prolonger si nécessaire", "Une date cible ne se prolonge qu'avec [[Extend Target Date]] et une justification.")],
        controls=["Date de survenue ≤ date de détection ≤ date d'enregistrement.",
                  "Une déviation planifiée exige une justification enregistrée avant exécution.",
                  "Une quantité concernée exige un produit.",
                  "L'évaluation exige une gravité, une évaluation d'impact documentée et un enquêteur désigné.",
                  "Une action immédiate ne peut être marquée faite sans preuve de réalisation.",
                  "Une déviation au-delà de *Reported* ne peut être supprimée — seulement annulée avec motif.",
                  "Chaque transition est enregistrée dans le journal des transitions en ajout seul (ni modifiable ni supprimable)."],
        good=["Déclarer dans le poste ; une déclaration tardive est en soi un constat.",
              "Décrire les faits (quoi, où, quand, combien), pas des opinions ni des reproches.",
              "Classer selon l'impact potentiel, pas selon l'issue probable de l'enquête.",
              "Passer en revue les déviations ouvertes à la réunion de production quotidienne."],
        pitfalls=["Corriger la situation et « oublier » la déclaration.",
                  "Regrouper des événements sans lien dans une même déviation.",
                  "Baisser la gravité pour tenir le délai de clôture."],
        records=["Déviation avec journal des transitions", "Actions immédiates avec preuves", "Évaluation d'impact"],
        kpis=["Délai survenue → déclaration", "Déviations par type/catégorie (tendance)", "% classées en 2 jours ouvrés"],
        example="**Cas.** Pendant le remplissage, un opérateur constate que l'alarme de pression différentielle de la salle est active depuis 40 minutes. Le chef d'équipe arrête le remplissage, met en quarantaine les 1 200 unités remplies pendant cette période et déclare la déviation DEV/2026/00017 : type *Environmental Excursion*, catégorie *Production*, produit et lot rempli. Actions immédiates : quarantaine (faite, preuve : photo de l'étiquette) et information de l'AQ (faite). L'AQ évalue un impact potentiel sur la qualité et sur d'autres lots, fixe la gravité *Major*, désigne l'enquêteur et clique sur [[Complete Assessment]].",
    ),
)

QA021 = sop(
    "SOP-QA-021", "ls_deviation", "Quality Management ▸ Deviations ▸ Investigations / Product Dispositions",
    flows=[("deviation", tr("This SOP covers Assessed → Closed.", "Cette SOP couvre Assessed → Closed."))],
    schematics=[("ishikawa", tr("Ishikawa diagram used during investigation.", "Diagramme d'Ishikawa utilisé en investigation."))],
    related=["SOP-QA-020", "SOP-QA-022", "SOP-QA-090"],
    refs=["CFR-211-192", "EU-GMP-1", "EU-GMP-5", "ICH-Q9", "ICH-Q10"],
    en=dict(
        title="Investigation, extension to other batches and product disposition",
        owner="Head of Quality Assurance",
        objective="Find the root cause of each deviation, determine whether other batches or products are affected, decide on the fate of the affected product, and close with a written conclusion and follow-up.",
        scope="All assessed deviations. Complaint and laboratory OOS investigations follow SOP-QA-040 and SOP-QC-013.",
        roles=[("Assigned investigator", "Leads the investigation, records findings, contributing factors and root cause."),
               ("QA reviewer", "Challenges the investigation, checks the extension to other batches."),
               ("Deviation Manager", "Approves or rejects product dispositions; closes the deviation.")],
        defs=[("Extension rationale", "Documented reasoning on whether other batches, products or equipment are affected (required by 21 CFR 211.192)."),
              ("Disposition", "Decision on the affected quantity: Use As Is, Rework, Reprocess, Quarantine, Reject, Destroy, Return to Supplier.")],
        steps=[("Open the investigation", "Add an investigation record: subject, RCA method (from {{Configuration ▸ Root Cause Analysis Methods}}), investigator, start date. Click [[Start]]."),
               ("Start the phase", "On the deviation click [[Start Investigation]] (at least one investigation record must exist)."),
               ("Investigate", "Collect facts (batch record, logbooks, EM data, interviews), apply the method (5 Whys, Ishikawa…), record findings, contributing factors and root cause; tick *Root Cause Determined* when confirmed."),
               ("Complete", "Click [[Complete]] on the investigation (findings and root cause required)."),
               ("Extend", "Write the *Other Batches Evaluated* / extension rationale: which other lots, products or equipment could be affected and why they are or are not."),
               ("Propose dispositions", "For each affected lot add a disposition: product, lot, quantity, decision and justification. Click [[Proceed to Disposition]]."),
               ("Approve dispositions", "The Deviation Manager clicks [[Approve]] or [[Reject]] on each disposition."),
               ("Decide on CAPA", "If a systemic cause exists click [[Require CAPA]] and open the CAPA in ls_capa (SOP-QA-022); otherwise record the rationale for no CAPA."),
               ("Close", "Click [[Close Deviation]]: enter the conclusion, the follow-up, the CAPA decision and CAPA reference, and the QA reviewer.")],
        controls=["The investigation phase needs at least one investigation record.",
                  "An investigation cannot be completed without findings and a recorded root cause; completion date ≥ start date.",
                  "Disposition requires all investigations completed and an extension rationale; if an impact was assessed, at least one disposition is required.",
                  "Only a Deviation Manager can approve or reject a disposition; the lot must belong to the product.",
                  "Closure is refused while an immediate action is open or a disposition is still draft; a CAPA reference is mandatory when CAPA is required.",
                  "A closed or cancelled deviation can only be modified by a Deviation Manager."],
        good=["Distinguish the direct cause from the root cause; ask \"why\" until you reach a process or system cause.",
              "Human error is rarely a root cause: look for what made the error possible.",
              "Base the extension on data (same equipment, same material lot, same period).",
              "Close within the target; if not possible, extend formally with a reason."],
        pitfalls=["\"Operator retrained\" as the only action for a systemic cause.",
                  "Releasing product before the disposition is approved.",
                  "Closing with \"no impact\" without evidence."],
        records=["Investigation records", "Dispositions with approval", "Conclusion, follow-up, CAPA reference", "Transition log"],
        kpis=["Median time to closure by severity", "% closed within target", "Recurrence of the same root cause"],
        example="**Case (continued from SOP-QA-020).** The investigator uses Ishikawa: the alarm was not escalated because the BMS pager had been muted after a maintenance intervention (method + machine). Root cause: no procedure to restore alarm routing after maintenance. Extension: two earlier batches filled in the same room since the maintenance are reviewed; their EM data are within limits — no impact. Disposition for the 1 200 units: *Reject*, approved by the Deviation Manager. CAPA required (restore-after-maintenance checklist); CAPA-2026-031 opened and referenced at closure.",
    ),
    fr=dict(
        title="Investigation, extension aux autres lots et disposition du produit",
        owner="Responsable assurance qualité",
        objective="Trouver la cause racine de chaque déviation, déterminer si d'autres lots ou produits sont touchés, décider du devenir du produit concerné, et clore avec une conclusion écrite et un suivi.",
        scope="Toutes les déviations évaluées. Les enquêtes réclamation et OOS suivent les SOP-QA-040 et SOP-QC-013.",
        roles=[("Enquêteur désigné", "Conduit l'investigation, consigne constats, facteurs contributifs et cause racine."),
               ("Vérificateur AQ", "Challenge l'investigation, vérifie l'extension aux autres lots."),
               ("Deviation Manager", "Approuve ou rejette les dispositions ; clôt la déviation.")],
        defs=[("Justification d'extension", "Raisonnement documenté sur l'atteinte éventuelle d'autres lots, produits ou équipements (exigée par le 21 CFR 211.192)."),
              ("Disposition", "Décision sur la quantité concernée : Use As Is, Rework, Reprocess, Quarantine, Reject, Destroy, Return to Supplier.")],
        steps=[("Ouvrir l'investigation", "Ajouter un enregistrement d'investigation : objet, méthode d'analyse (paramétrée dans {{Configuration ▸ Root Cause Analysis Methods}}), enquêteur, date de début. Cliquer sur [[Start]]."),
               ("Démarrer la phase", "Sur la déviation, cliquer sur [[Start Investigation]] (au moins une investigation doit exister)."),
               ("Enquêter", "Recueillir les faits (dossier de lot, cahiers de route, données EM, entretiens), appliquer la méthode (5 Pourquoi, Ishikawa…), consigner constats, facteurs contributifs et cause racine ; cocher *Root Cause Determined* une fois confirmée."),
               ("Terminer", "Cliquer sur [[Complete]] sur l'investigation (constats et cause racine obligatoires)."),
               ("Étendre", "Rédiger la justification d'extension (*Other Batches Evaluated*) : quels autres lots, produits ou équipements pourraient être touchés et pourquoi ils le sont ou non."),
               ("Proposer les dispositions", "Pour chaque lot concerné, ajouter une disposition : produit, lot, quantité, décision et justification. Cliquer sur [[Proceed to Disposition]]."),
               ("Approuver les dispositions", "Le Deviation Manager clique sur [[Approve]] ou [[Reject]] sur chaque disposition."),
               ("Décider de la CAPA", "En cas de cause systémique, cliquer sur [[Require CAPA]] et ouvrir la CAPA dans ls_capa (SOP-QA-022) ; sinon consigner la justification de l'absence de CAPA."),
               ("Clore", "Cliquer sur [[Close Deviation]] : saisir la conclusion, le suivi, la décision et la référence CAPA, et le vérificateur AQ.")],
        controls=["La phase d'investigation exige au moins une investigation.",
                  "Une investigation ne peut être terminée sans constats ni cause racine ; date de fin ≥ date de début.",
                  "La disposition exige toutes les investigations terminées et une justification d'extension ; si un impact a été évalué, au moins une disposition est exigée.",
                  "Seul un Deviation Manager approuve ou rejette une disposition ; le lot doit appartenir au produit.",
                  "La clôture est refusée tant qu'une action immédiate est ouverte ou qu'une disposition est en brouillon ; la référence CAPA est obligatoire si une CAPA est requise.",
                  "Une déviation close ou annulée n'est modifiable que par un Deviation Manager."],
        good=["Distinguer cause directe et cause racine ; demander « pourquoi » jusqu'à une cause de processus ou de système.",
              "L'erreur humaine est rarement une cause racine : chercher ce qui l'a rendue possible.",
              "Fonder l'extension sur des données (même équipement, même lot de matière, même période).",
              "Clore dans le délai ; sinon prolonger formellement avec un motif."],
        pitfalls=["« Opérateur reformé » comme seule action pour une cause systémique.",
                  "Libérer le produit avant l'approbation de la disposition.",
                  "Clore avec « pas d'impact » sans preuve."],
        records=["Investigations", "Dispositions approuvées", "Conclusion, suivi, référence CAPA", "Journal des transitions"],
        kpis=["Délai médian de clôture par gravité", "% clôturées dans le délai", "Récurrence d'une même cause racine"],
        example="**Cas (suite de la SOP-QA-020).** L'enquêteur applique Ishikawa : l'alarme n'a pas été transmise car le renvoi d'alarme de la GTC avait été coupé lors d'une maintenance (méthode + machine). Cause racine : aucune procédure de rétablissement du renvoi d'alarme après maintenance. Extension : deux lots antérieurs remplis dans la même salle depuis la maintenance sont revus ; leurs données EM sont conformes — pas d'impact. Disposition des 1 200 unités : *Reject*, approuvée par le Deviation Manager. CAPA requise (liste de contrôle de remise en service) ; CAPA-2026-031 ouverte et référencée à la clôture.",
    ),
)

QA022 = sop(
    "SOP-QA-022", "ls_capa", "Quality ▸ CAPA ▸ CAPA Records",
    flows=[("capa", tr("CAPA lifecycle with its gates.", "Cycle de vie CAPA et ses jalons."))],
    schematics=[("handoffs", tr("Sources feeding the CAPA system.", "Sources qui alimentent le système CAPA."))],
    shots=[("ls_capa_issue__form", tr("CAPA record form.", "Fiche CAPA."))],
    related=["SOP-QA-021", "SOP-QA-023", "SOP-QA-030", "SOP-QA-040", "SOP-QA-053"],
    refs=["ICH-Q10", "ISO-13485", "ISO-9001", "EU-GMP-1", "CFR-820"],
    en=dict(
        title="CAPA management from identification to closure",
        owner="CAPA Manager (QA)",
        objective="Eliminate the causes of detected or potential nonconformities by a structured process: identify, assess, analyse root causes, plan and implement actions, verify effectiveness, close.",
        scope="Corrective and preventive actions from internal and external audits, inspections, deviations, complaints, nonconformities, management review, risk assessments, environmental monitoring, suppliers and change control.",
        roles=[("Initiator (any user)", "Identifies the need and creates the record with its source reference."),
               ("CAPA Owner / Coordinator", "Drives the CAPA through its stages and meets the due date."),
               ("CAPA Investigator", "Performs root cause analyses and actions."),
               ("CAPA Manager", "Checks each gate, closes the CAPA.")],
        defs=[("Correction", "Immediate fix of the nonconformity (recorded as *Immediate Action / Correction*)."),
              ("Corrective action", "Action on the cause to prevent recurrence."),
              ("Preventive action", "Action on the cause of a potential nonconformity to prevent occurrence.")],
        steps=[("Identify", "In {{Quality ▸ CAPA ▸ CAPA Records}} click [[New]]: title, description, source (e.g. *Deviation*) and *Source Reference* (e.g. DEV/2026/00017), type (corrective, preventive or both), severity, priority, category, owner and due date."),
               ("Assess", "Document the impact assessment (product quality, regulatory, patient/user safety) and the correction already taken. Click [[Assess]]."),
               ("Investigate", "Click [[Start Investigation]]. Add one or more root cause analyses (Five Whys, Ishikawa, FMEA or other method), each with a root cause statement; mark the primary root cause; click [[Confirm]] on each."),
               ("Plan actions", "Click [[Plan Actions]]. Add actions: type, description, root cause addressed, responsible, planned completion date. Use [[Create Task]] to follow an action in a project."),
               ("Execute", "Click [[Start Execution]]. Each responsible clicks [[Start]] then [[Mark Done]] with completion evidence. Cancelled actions need a reason."),
               ("Complete", "When all actions are done or cancelled, click [[Complete]]."),
               ("Verify effectiveness", "Plan and perform effectiveness checks (SOP-QA-023); when at least one concludes *Effective* and all are done, click [[Verify Effectiveness]]."),
               ("Close", "Click [[Close CAPA]], write the closure summary. Write the CAPA reference back into the source record (deviation, complaint, audit finding).")],
        controls=["Each transition is only allowed from the expected status.",
                  "Assessment requires a documented impact assessment.",
                  "Action planning requires at least one confirmed root cause analysis.",
                  "Execution requires at least one planned action; completion requires all actions done or cancelled.",
                  "An action cannot be completed without evidence nor cancelled without a reason; a completed action cannot be cancelled.",
                  "Verification requires every effectiveness check completed and at least one *Effective*.",
                  "Closure requires a closure summary; due date ≥ identification date.",
                  "A CAPA beyond *Identified* cannot be deleted — it is archived.",
                  "Five Whys needs at least the first Why; Ishikawa needs a category; FMEA ratings are 1–10; a confirmed root cause cannot be reset once execution started."],
        good=["Size the CAPA to the risk: not every deviation needs a CAPA, but every recurring cause does.",
              "One action, one owner, one date, one piece of evidence.",
              "Check that the action addresses the confirmed root cause (link *Root Cause Addressed*).",
              "Review overdue CAPAs weekly in the quality meeting."],
        pitfalls=["Closing on completion of actions without effectiveness verification.",
                  "Extending due dates repeatedly without escalation.",
                  "Opening a CAPA without writing its reference back into the source record — the link is manual."],
        records=["CAPA record with root causes, actions, evidence, effectiveness checks and closure summary"],
        kpis=["Overdue CAPAs", "Median time to closure", "% of CAPAs verified effective at first check", "Recurring root causes"],
        example="**Case.** CAPA-2026-031, source *Deviation*, reference DEV/2026/00017, type corrective, severity major, due in 60 days. Impact assessment documented; Five Whys analysis confirmed: *no restore-after-maintenance step for alarm routing*. Actions: (1) add a restore checklist to the maintenance work order template — engineering, 30 days; (2) train maintenance technicians — 45 days; (3) weekly automatic alarm routing test — IT, 45 days. Each action is closed with evidence (new template, training certificates, test report). Effectiveness check planned at +3 months: *no alarm routing failure after 12 maintenance interventions*.",
    ),
    fr=dict(
        title="Gestion des CAPA, de l'identification à la clôture",
        owner="CAPA Manager (AQ)",
        objective="Éliminer les causes de non-conformités détectées ou potentielles par un processus structuré : identifier, évaluer, analyser les causes racines, planifier et réaliser les actions, vérifier l'efficacité, clore.",
        scope="Actions correctives et préventives issues des audits internes et externes, inspections, déviations, réclamations, non-conformités, revue de direction, analyses de risque, surveillance de l'environnement, fournisseurs et maîtrise des changements.",
        roles=[("Initiateur (tout utilisateur)", "Identifie le besoin et crée la CAPA avec la référence de sa source."),
               ("Responsable CAPA / Coordinator", "Fait avancer la CAPA et tient l'échéance."),
               ("CAPA Investigator", "Réalise analyses de causes et actions."),
               ("CAPA Manager", "Vérifie chaque jalon, clôt la CAPA.")],
        defs=[("Correction", "Traitement immédiat de la non-conformité (champ *Immediate Action / Correction*)."),
              ("Action corrective", "Action sur la cause pour éviter la récurrence."),
              ("Action préventive", "Action sur la cause d'une non-conformité potentielle pour éviter qu'elle survienne.")],
        steps=[("Identifier", "Dans {{Quality ▸ CAPA ▸ CAPA Records}}, cliquer sur [[New]] : titre, description, source (ex. *Deviation*) et *Source Reference* (ex. DEV/2026/00017), type (corrective, préventive ou les deux), gravité, priorité, catégorie, responsable et échéance."),
               ("Évaluer", "Documenter l'évaluation d'impact (qualité produit, réglementaire, sécurité patient/utilisateur) et la correction déjà réalisée. Cliquer sur [[Assess]]."),
               ("Analyser", "Cliquer sur [[Start Investigation]]. Ajouter une ou plusieurs analyses de causes (5 Pourquoi, Ishikawa, AMDE ou autre méthode), chacune avec son énoncé de cause racine ; marquer la cause principale ; cliquer sur [[Confirm]] pour chacune."),
               ("Planifier", "Cliquer sur [[Plan Actions]]. Ajouter les actions : type, description, cause traitée, responsable, date prévue. [[Create Task]] permet de suivre une action dans un projet."),
               ("Réaliser", "Cliquer sur [[Start Execution]]. Chaque responsable clique sur [[Start]] puis [[Mark Done]] avec la preuve de réalisation. Une action annulée exige un motif."),
               ("Terminer", "Quand toutes les actions sont faites ou annulées, cliquer sur [[Complete]]."),
               ("Vérifier l'efficacité", "Planifier et réaliser les vérifications (SOP-QA-023) ; quand au moins une conclut *Effective* et que toutes sont terminées, cliquer sur [[Verify Effectiveness]]."),
               ("Clore", "Cliquer sur [[Close CAPA]] et rédiger le résumé de clôture. Reporter la référence CAPA dans l'enregistrement source (déviation, réclamation, constat d'audit).")],
        controls=["Chaque transition n'est permise que depuis l'état attendu.",
                  "L'évaluation exige une évaluation d'impact documentée.",
                  "La planification exige au moins une analyse de cause confirmée.",
                  "L'exécution exige au moins une action planifiée ; la complétion exige toutes les actions faites ou annulées.",
                  "Une action ne peut être terminée sans preuve ni annulée sans motif ; une action terminée ne peut être annulée.",
                  "La vérification exige toutes les vérifications d'efficacité terminées et au moins une *Effective*.",
                  "La clôture exige un résumé ; échéance ≥ date d'identification.",
                  "Une CAPA au-delà de *Identified* ne peut être supprimée — elle est archivée.",
                  "5 Pourquoi : au moins le premier Pourquoi ; Ishikawa : une catégorie ; AMDE : cotations 1 à 10 ; une cause confirmée ne peut plus être réinitialisée une fois l'exécution démarrée."],
        good=["Proportionner la CAPA au risque : toute déviation n'appelle pas une CAPA, mais toute cause récurrente oui.",
              "Une action, un responsable, une date, une preuve.",
              "Vérifier que l'action traite la cause confirmée (lien *Root Cause Addressed*).",
              "Revoir les CAPA en retard chaque semaine en réunion qualité."],
        pitfalls=["Clore à la fin des actions sans vérifier l'efficacité.",
                  "Repousser les échéances sans escalade.",
                  "Ouvrir une CAPA sans reporter sa référence dans l'enregistrement source — le lien est manuel."],
        records=["CAPA avec causes, actions, preuves, vérifications d'efficacité et résumé de clôture"],
        kpis=["CAPA en retard", "Délai médian de clôture", "% de CAPA efficaces à la première vérification", "Causes racines récurrentes"],
        example="**Cas.** CAPA-2026-031, source *Deviation*, référence DEV/2026/00017, corrective, majeure, échéance 60 jours. Évaluation d'impact documentée ; analyse 5 Pourquoi confirmée : *pas d'étape de rétablissement du renvoi d'alarme après maintenance*. Actions : (1) ajouter une liste de contrôle au modèle d'ordre de travail — maintenance, 30 jours ; (2) former les techniciens — 45 jours ; (3) test hebdomadaire automatique du renvoi d'alarme — informatique, 45 jours. Chaque action est close avec sa preuve (nouveau modèle, certifications, rapport de test). Vérification d'efficacité planifiée à +3 mois : *aucune défaillance de renvoi d'alarme après 12 interventions*.",
    ),
)

QA023 = sop(
    "SOP-QA-023", "ls_capa", "Quality ▸ CAPA ▸ Effectiveness Verification",
    flows=[("capa_eff", tr("Lifecycle of an effectiveness check.", "Cycle de vie d'une vérification d'efficacité."))],
    related=["SOP-QA-022", "SOP-QA-031"],
    refs=["ICH-Q10", "ISO-13485", "ISO-9001"],
    en=dict(
        title="Verification of CAPA effectiveness",
        owner="CAPA Manager (QA)",
        objective="Prove, with objective data collected after implementation, that the CAPA actions eliminated or reduced the cause, and trigger a new CAPA when they did not.",
        scope="Every CAPA before its verification and closure.",
        roles=[("CAPA Owner", "Defines the method and acceptance criteria when planning actions."),
               ("Verifier", "Collects the data at the planned date and concludes; ideally independent of the action owner."),
               ("CAPA Manager", "Accepts the conclusion; raises a follow-up CAPA when not effective.")],
        defs=[("Verification method", "Data Review, Follow-up Audit, Process Monitoring, Retesting, Training Verification or Other Documented Method."),
              ("Acceptance criteria", "Measurable condition that proves effectiveness (e.g. \"zero recurrence in 3 months\").")],
        steps=[("Define", "In the CAPA, add an effectiveness check: method, acceptance criteria, planned verification date (not before the identification date), verifier."),
               ("Plan", "Click [[Plan]] once the actions are implemented; the check appears in {{Quality ▸ CAPA ▸ Effectiveness Verification}}."),
               ("Collect data", "At the planned date, collect the data defined by the method over the whole observation period."),
               ("Conclude", "Record the conclusion and click [[Conclude Effective]] or [[Conclude Not Effective]]."),
               ("Not effective", "Click [[Raise Follow-up CAPA]]: a new CAPA is created and linked; the root cause analysis must be revisited."),
               ("Verify the CAPA", "Return to the CAPA and click [[Verify Effectiveness]], then close (SOP-QA-022).")],
        controls=["Only draft checks can be planned; a check cannot be planned before the CAPA identification date.",
                  "A check cannot be completed while its result is *Pending* or without a conclusion.",
                  "A follow-up CAPA can only be raised from a check concluded *Not Effective*, and only once.",
                  "The CAPA cannot be verified until every check is completed and at least one is *Effective*."],
        good=["Set the criteria before implementation, so that they are not tailored to the results.",
              "Choose an observation period long enough to see recurrence (number of batches, audits, interventions).",
              "Training alone is verified by observing the task, not by the attendance list."],
        pitfalls=["\"Actions completed\" used as effectiveness evidence.",
                  "Verification by the person who implemented the action, without a second look."],
        records=["Effectiveness checks with data, conclusion and date", "Follow-up CAPA when applicable"],
        kpis=["% effective at first verification", "Follow-up CAPAs raised", "Checks overdue"],
        example="**Case.** For CAPA-2026-031 the check is: method *Process Monitoring*, criterion *\"alarm routing verified operational after 100 % of maintenance interventions over 3 months, minimum 10 interventions\"*. At +3 months the verifier reviews 12 work orders: all carry the completed restore checklist and the weekly routing tests passed. She clicks [[Conclude Effective]]; the CAPA owner clicks [[Verify Effectiveness]] and closes the CAPA.",
    ),
    fr=dict(
        title="Vérification de l'efficacité des CAPA",
        owner="CAPA Manager (AQ)",
        objective="Démontrer par des données objectives recueillies après la mise en œuvre que les actions CAPA ont supprimé ou réduit la cause, et déclencher une nouvelle CAPA dans le cas contraire.",
        scope="Toute CAPA avant sa vérification et sa clôture.",
        roles=[("Responsable CAPA", "Définit la méthode et les critères d'acceptation lors de la planification."),
               ("Vérificateur", "Recueille les données à la date prévue et conclut ; idéalement indépendant du responsable de l'action."),
               ("CAPA Manager", "Accepte la conclusion ; ouvre une CAPA de suivi si inefficace.")],
        defs=[("Méthode de vérification", "Data Review, Follow-up Audit, Process Monitoring, Retesting, Training Verification ou Other Documented Method."),
              ("Critère d'acceptation", "Condition mesurable prouvant l'efficacité (ex. « aucune récurrence en 3 mois »).")],
        steps=[("Définir", "Dans la CAPA, ajouter une vérification : méthode, critère d'acceptation, date prévue (pas avant la date d'identification), vérificateur."),
               ("Planifier", "Cliquer sur [[Plan]] une fois les actions mises en œuvre ; la vérification apparaît dans {{Quality ▸ CAPA ▸ Effectiveness Verification}}."),
               ("Recueillir", "À la date prévue, recueillir les données définies par la méthode sur toute la période d'observation."),
               ("Conclure", "Saisir la conclusion et cliquer sur [[Conclude Effective]] ou [[Conclude Not Effective]]."),
               ("Inefficace", "Cliquer sur [[Raise Follow-up CAPA]] : une nouvelle CAPA est créée et liée ; l'analyse de cause doit être reprise."),
               ("Vérifier la CAPA", "Revenir sur la CAPA et cliquer sur [[Verify Effectiveness]], puis clore (SOP-QA-022).")],
        controls=["Seule une vérification brouillon peut être planifiée ; pas avant la date d'identification de la CAPA.",
                  "Pas de clôture d'une vérification au résultat *Pending* ou sans conclusion.",
                  "Une CAPA de suivi ne peut naître que d'une vérification *Not Effective*, et une seule fois.",
                  "La CAPA ne peut être vérifiée que si toutes les vérifications sont terminées et au moins une *Effective*."],
        good=["Fixer les critères avant la mise en œuvre, pour qu'ils ne soient pas taillés sur les résultats.",
              "Choisir une période d'observation assez longue pour voir une récurrence (nombre de lots, d'audits, d'interventions).",
              "Une formation se vérifie en observant la tâche, pas avec la feuille de présence."],
        pitfalls=["Utiliser « actions terminées » comme preuve d'efficacité.",
                  "Vérification par la personne qui a mis en œuvre l'action, sans second regard."],
        records=["Vérifications avec données, conclusion et date", "CAPA de suivi le cas échéant"],
        kpis=["% efficaces à la première vérification", "CAPA de suivi ouvertes", "Vérifications en retard"],
        example="**Cas.** Pour la CAPA-2026-031 : méthode *Process Monitoring*, critère *« renvoi d'alarme vérifié opérationnel après 100 % des interventions sur 3 mois, au moins 10 interventions »*. À +3 mois, la vérificatrice revoit 12 ordres de travail : tous portent la liste de contrôle remplie et les tests hebdomadaires sont conformes. Elle clique sur [[Conclude Effective]] ; le responsable clique sur [[Verify Effectiveness]] et clôt la CAPA.",
    ),
)

M_CC = module(
    "mod-cc", "ls_change_control", "Change control", "Maîtrise des changements",
    [
        ("p", "**ls_change_control** manages change requests from draft to closure: classification (minor, major, "
              "critical), permanent or temporary change, impact areas with an impact assessment per area, approvals "
              "generated from the category's approval templates, implementation actions with evidence, and "
              "effectiveness verifications. The request is approved automatically once every assessment is completed "
              "and every approval is favourable; any rejection rejects the request."),
        ("table", ["Menu", "Content"], [
            ["{{Change Control ▸ Change Requests ▸ All / My Change Requests / Impact Assessments}}", "Requests and assessments"],
            ["{{Change Control ▸ Approvals ▸ My Approvals}}", "Decisions waiting for the connected user"],
            ["{{Change Control ▸ Execution ▸ Implementation Actions / Effectiveness Verifications}}", "Execution"],
            ["{{Change Control ▸ Configuration ▸ Change Categories / Impact Areas / Settings}}", "Categories, approval templates, delays"],
        ]),
        ("table", ["Group", "Main rights"], [
            ["Viewer · Requester", "Read; create and submit requests"],
            ["Approver", "Record approval decisions assigned to them"],
            ["Change Control Manager", "Drives the workflow, starts assessment and implementation, closes, rejects, cancels"],
        ]),
        ("flow", "change", "Lifecycle of a change request."),
        ("shot", "ls_change_control_request__form", "Change request form."),
    ],
    [
        ("p", "**ls_change_control** gère les demandes de changement du brouillon à la clôture : classification (mineur, "
              "majeur, critique), changement permanent ou temporaire, domaines d'impact avec une évaluation par domaine, "
              "approbations générées à partir des modèles de la catégorie, actions de mise en œuvre avec preuves et "
              "vérifications d'efficacité. La demande est approuvée automatiquement dès que toutes les évaluations sont "
              "terminées et toutes les approbations favorables ; un seul refus rejette la demande."),
        ("table", ["Menu", "Contenu"], [
            ["{{Change Control ▸ Change Requests ▸ All / My Change Requests / Impact Assessments}}", "Demandes et évaluations"],
            ["{{Change Control ▸ Approvals ▸ My Approvals}}", "Décisions attendues de l'utilisateur connecté"],
            ["{{Change Control ▸ Execution ▸ Implementation Actions / Effectiveness Verifications}}", "Mise en œuvre"],
            ["{{Change Control ▸ Configuration ▸ Change Categories / Impact Areas / Settings}}", "Catégories, modèles d'approbation, délais"],
        ]),
        ("table", ["Groupe", "Droits principaux"], [
            ["Viewer · Requester", "Lecture ; création et soumission de demandes"],
            ["Approver", "Enregistre les décisions qui lui sont attribuées"],
            ["Change Control Manager", "Pilote le workflow, lance évaluation et mise en œuvre, clôt, rejette, annule"],
        ]),
        ("flow", "change", "Cycle de vie d'une demande de changement."),
        ("shot", "ls_change_control_request__form", "Fiche demande de changement."),
    ],
)

QA030 = sop(
    "SOP-QA-030", "ls_change_control", "Change Control ▸ Change Requests",
    flows=[("change", tr("This SOP covers Draft → Approved.", "Cette SOP couvre Draft → Approved."))],
    shots=[("ls_change_control_request__list", tr("Change request register.", "Registre des demandes de changement."))],
    related=["SOP-QA-031", "SOP-QA-002", "SOP-QA-060", "SOP-VAL-005"],
    refs=["ICH-Q10", "EU-A15", "ISO-13485", "EU-GMP-1", "EU-A11"],
    en=dict(
        title="Change request and impact assessment",
        owner="Change Control Manager",
        objective="Ensure that any change that may affect product quality, the validated state, regulatory compliance or safety is proposed, justified, assessed by every affected function and approved before implementation.",
        scope="Changes to products, processes, equipment, facilities, utilities, materials and suppliers, specifications, test methods, computerised systems and quality documents with a substantive effect. Temporary changes are included.",
        roles=[("Requester", "Describes the current situation, the proposed change and its justification; submits."),
               ("Change Control Manager", "Screens the request, completes classification and impact areas, starts the assessment, arbitrates."),
               ("Assessors (per impact area)", "Assess the impact of their area and describe the required actions."),
               ("Approvers", "Approve or reject, with a comment when rejecting.")],
        defs=[("Classification", "Minor, Major or Critical."),
              ("Temporary change", "Change limited in time; it must declare its end date."),
              ("Regulatory impact", "No Regulatory Action, Notification to the Authority, Variation of the Marketing Authorisation, Prior Approval Required.")],
        steps=[("Create", "In {{Change Control ▸ Change Requests}} click [[New]]: title, category, permanent/temporary (end date if temporary), classification, priority, current situation, proposed change, justification, requested target date."),
               ("Declare impacts", "Tick the impact flags (GMP, product quality, regulatory, revalidation, training, document update, customer notification) and select the impact areas; reference the risk assessment if one exists (SOP-QA-060)."),
               ("Submit", "Click [[Submit for Review]]. The content is frozen for the requester."),
               ("Screen", "The Change Control Manager checks completeness; if incomplete, [[Return to Draft]] with a comment."),
               ("Start the assessment", "Click [[Start Impact Assessment]]: the system generates one assessment per impact area and the approvals defined by the category, and notifies the approvers."),
               ("Assess", "Each assessor opens {{Change Requests ▸ Impact Assessments}}, sets the impact level (No Impact, Low, Medium, High), writes the assessment and, where there is an impact, the required actions; clicks [[Complete Assessment]]."),
               ("Decide", "Each approver opens {{Approvals ▸ My Approvals}} and clicks [[Approve]] or [[Reject]] (a comment is required to reject)."),
               ("Approval", "When all assessments are completed and all approvals favourable, the request becomes *Approved* automatically and a planned implementation date is proposed from the category delay. A single rejection rejects the request.")],
        controls=["Once submitted, the request content is frozen; only a Change Control Manager may modify it — a change of the change itself requires a new request.",
                  "Workflow fields (dates, states, deciders) cannot be written directly.",
                  "A temporary change must declare an end date; a permanent change must not.",
                  "Assessments and decisions can only be recorded while the request is in *Impact Assessment*; only the assigned assessor/approver (or the manager for assessments) may record them.",
                  "A written assessment is required; if an impact is declared the required actions must be described.",
                  "A rejection requires a comment; decided approvals cannot be modified or deleted.",
                  "A submitted request cannot be deleted; requester and manager must be internal users."],
        good=["Describe the change so that a person who was not in the meeting understands it.",
              "Involve regulatory affairs early: a variation can take months.",
              "Use a risk assessment for major and critical changes.",
              "Link documents to revise, validations to perform and training to deliver as implementation actions."],
        pitfalls=["Implementing before approval (\"it was urgent\").",
                  "Approving without reading the assessments.",
                  "Using a temporary change that becomes permanent without a new request."],
        records=["Change request with assessments, approvals and dates", "Referenced risk assessment"],
        kpis=["Time from submission to approval", "Changes implemented before approval (target 0)", "Temporary changes past their end date"],
        example="**Case.** Engineering proposes to replace the tablet press punches with a new supplier's tooling. Request CC-2026-021: category *Equipment*, permanent, classification *Major*, regulatory impact *No Regulatory Action* (equivalent design), requires revalidation and document update. Impact areas: Production, Quality Control, Validation, Purchasing. The manager clicks [[Start Impact Assessment]]; four assessments and three approvals are generated. Validation assesses *High* impact (OQ of the press with new tooling). All approve; the request becomes *Approved*.",
    ),
    fr=dict(
        title="Demande de changement et évaluation d'impact",
        owner="Change Control Manager",
        objective="Garantir que tout changement susceptible d'affecter la qualité du produit, l'état validé, la conformité réglementaire ou la sécurité est proposé, justifié, évalué par chaque fonction concernée et approuvé avant sa mise en œuvre.",
        scope="Changements de produits, procédés, équipements, locaux, utilités, matières et fournisseurs, spécifications, méthodes d'analyse, systèmes informatisés et documents qualité ayant un effet de fond. Les changements temporaires sont inclus.",
        roles=[("Demandeur (Requester)", "Décrit la situation actuelle, le changement proposé et sa justification ; soumet."),
               ("Change Control Manager", "Examine la demande, complète classification et domaines d'impact, lance l'évaluation, arbitre."),
               ("Évaluateurs (par domaine)", "Évaluent l'impact dans leur domaine et décrivent les actions nécessaires."),
               ("Approbateurs", "Approuvent ou rejettent, avec commentaire en cas de rejet.")],
        defs=[("Classification", "Minor, Major ou Critical."),
              ("Changement temporaire", "Changement limité dans le temps ; il doit déclarer sa date de fin."),
              ("Impact réglementaire", "No Regulatory Action, Notification to the Authority, Variation of the Marketing Authorisation, Prior Approval Required.")],
        steps=[("Créer", "Dans {{Change Control ▸ Change Requests}}, cliquer sur [[New]] : titre, catégorie, permanent/temporaire (date de fin si temporaire), classification, priorité, situation actuelle, changement proposé, justification, date cible souhaitée."),
               ("Déclarer les impacts", "Cocher les indicateurs d'impact (BPF, qualité produit, réglementaire, revalidation, formation, mise à jour documentaire, information client) et choisir les domaines d'impact ; citer l'analyse de risque s'il en existe une (SOP-QA-060)."),
               ("Soumettre", "Cliquer sur [[Submit for Review]]. Le contenu est figé pour le demandeur."),
               ("Examiner", "Le Change Control Manager vérifie la complétude ; si incomplet, [[Return to Draft]] avec un commentaire."),
               ("Lancer l'évaluation", "Cliquer sur [[Start Impact Assessment]] : le système génère une évaluation par domaine d'impact et les approbations prévues par la catégorie, et prévient les approbateurs."),
               ("Évaluer", "Chaque évaluateur ouvre {{Change Requests ▸ Impact Assessments}}, fixe le niveau (No Impact, Low, Medium, High), rédige l'évaluation et, en cas d'impact, les actions nécessaires ; clique sur [[Complete Assessment]]."),
               ("Décider", "Chaque approbateur ouvre {{Approvals ▸ My Approvals}} et clique sur [[Approve]] ou [[Reject]] (commentaire obligatoire pour rejeter)."),
               ("Approbation", "Quand toutes les évaluations sont terminées et toutes les approbations favorables, la demande passe automatiquement *Approved* et une date de mise en œuvre est proposée selon le délai de la catégorie. Un seul rejet rejette la demande.")],
        controls=["Après soumission, le contenu est figé ; seul un Change Control Manager peut le modifier — changer le changement lui-même exige une nouvelle demande.",
                  "Les champs gérés par le workflow (dates, états, décideurs) ne sont pas modifiables directement.",
                  "Un changement temporaire doit déclarer une date de fin ; un changement permanent ne le doit pas.",
                  "Évaluations et décisions ne s'enregistrent que dans l'état *Impact Assessment*, par l'évaluateur/approbateur désigné (ou le manager pour les évaluations).",
                  "Une évaluation écrite est exigée ; en cas d'impact, les actions nécessaires doivent être décrites.",
                  "Un rejet exige un commentaire ; une approbation décidée n'est ni modifiable ni supprimable.",
                  "Une demande soumise ne peut être supprimée ; demandeur et manager doivent être des utilisateurs internes."],
        good=["Décrire le changement pour qu'une personne absente de la réunion le comprenne.",
              "Associer tôt les affaires réglementaires : une variation peut prendre des mois.",
              "Réaliser une analyse de risque pour les changements majeurs et critiques.",
              "Traduire documents à réviser, validations à mener et formations à dispenser en actions de mise en œuvre."],
        pitfalls=["Mettre en œuvre avant approbation (« c'était urgent »).",
                  "Approuver sans lire les évaluations.",
                  "Un changement temporaire qui devient permanent sans nouvelle demande."],
        records=["Demande avec évaluations, approbations et dates", "Analyse de risque référencée"],
        kpis=["Délai soumission → approbation", "Changements mis en œuvre avant approbation (cible 0)", "Changements temporaires échus"],
        example="**Cas.** L'ingénierie propose de remplacer les poinçons de la presse à comprimés par l'outillage d'un nouveau fournisseur. Demande CC-2026-021 : catégorie *Equipment*, permanent, *Major*, impact réglementaire *No Regulatory Action* (conception équivalente), revalidation et mise à jour documentaire requises. Domaines : Production, Contrôle qualité, Validation, Achats. Le manager clique sur [[Start Impact Assessment]] ; quatre évaluations et trois approbations sont générées. La validation évalue un impact *High* (QO de la presse avec le nouvel outillage). Tous approuvent ; la demande passe *Approved*.",
    ),
)

QA031 = sop(
    "SOP-QA-031", "ls_change_control", "Change Control ▸ Execution",
    flows=[("change", tr("This SOP covers Approved → Closed.", "Cette SOP couvre Approved → Closed."))],
    related=["SOP-QA-030", "SOP-QA-023", "SOP-VAL-005", "SOP-QA-012"],
    refs=["ICH-Q10", "EU-A15", "ISO-13485"],
    en=dict(
        title="Approval, implementation and verification of changes",
        owner="Change Control Manager",
        objective="Implement approved changes as planned, with evidence for each action, verify that the change achieved its purpose without adverse effect, and close the request formally.",
        scope="All approved change requests.",
        roles=[("Action owners", "Perform the implementation actions and record evidence."),
               ("Change Control Manager", "Starts implementation, declares the change verified, closes; cancels actions when justified."),
               ("Verifier", "Performs the effectiveness verification against the acceptance criteria.")],
        defs=[("Implementation action", "Task with an owner and an evidence reference (e.g. document revision, validation report, training record)."),
              ("Effectiveness verification", "Check planned on the request with a method and acceptance criteria; required when the category demands it.")],
        steps=[("Plan the actions", "On the approved request add implementation actions (owner, description, due date) derived from the assessments: document revisions, validation, training, supplier notification, regulatory filing."),
               ("Start implementation", "The manager clicks [[Start Implementation]] (at least one action is required)."),
               ("Execute", "Each owner clicks [[Start]] then [[Mark as Done]] with the evidence reference. Only the manager can cancel an action ([[Cancel Action]]), with a reason."),
               ("Verify effectiveness", "At the planned date the verifier records the verification result and conclusion and clicks [[Conclude: Effective]] or [[Conclude: Not Effective]] (the latter requires a follow-up reference, e.g. a new change request or CAPA)."),
               ("Declare verified", "When all actions are closed and verifications complete, the manager clicks [[Declare Verified]]."),
               ("Close", "Click [[Close]] and write the closure statement (what was changed, effective date, evidence)."),
               ("Temporary change", "At the end date, verify the return to the original state and record it before closing.")],
        controls=["Implementation actions can only be executed once the change is approved; only the owner or the manager may update an action.",
                  "An action cannot be closed without an evidence reference; cancellation requires a reason and the manager role; a started action cannot be deleted.",
                  "Verifications can only be completed during *Implementation*; a conclusion is required; *Not Effective* requires a follow-up.",
                  "Verification of the request is refused while blocking items remain; closure requires a closure statement.",
                  "A category requiring effectiveness verification must define a verification delay (on the category or the company)."],
        good=["Do not declare the change effective on the day of implementation: allow a representative period.",
              "Keep the evidence reference precise (document number and revision, report number).",
              "Close the loop with training (SOP-QA-012) and revalidation (SOP-VAL-005)."],
        pitfalls=["Actions closed with \"done\" and no evidence.",
                  "Leaving requests in *Implementation* for months after the change is in use."],
        records=["Implementation actions with evidence", "Effectiveness verifications", "Closure statement"],
        kpis=["Actions overdue", "Requests closed within planned date", "% of changes needing a follow-up"],
        example="**Case (continued).** CC-2026-021 actions: (1) OQ of the press with new tooling — report VAL-OQ-2026-008; (2) revise SOP-PRD-014 rev 4; (3) train operators. After 10 batches the verifier checks tablet weight, hardness and friability trends: all within control limits → [[Conclude: Effective]]. The manager clicks [[Declare Verified]] then [[Close]].",
    ),
    fr=dict(
        title="Approbation, mise en œuvre et vérification des changements",
        owner="Change Control Manager",
        objective="Mettre en œuvre les changements approuvés comme prévu, avec une preuve pour chaque action, vérifier que le changement a atteint son but sans effet indésirable, et clore formellement la demande.",
        scope="Toutes les demandes de changement approuvées.",
        roles=[("Responsables d'action", "Réalisent les actions de mise en œuvre et enregistrent la preuve."),
               ("Change Control Manager", "Lance la mise en œuvre, déclare le changement vérifié, clôt ; annule des actions si justifié."),
               ("Vérificateur", "Réalise la vérification d'efficacité selon les critères d'acceptation.")],
        defs=[("Action de mise en œuvre", "Tâche avec responsable et référence de preuve (révision de document, rapport de validation, enregistrement de formation)."),
              ("Vérification d'efficacité", "Contrôle planifié sur la demande avec méthode et critères ; obligatoire si la catégorie l'exige.")],
        steps=[("Planifier les actions", "Sur la demande approuvée, ajouter les actions (responsable, description, échéance) issues des évaluations : révisions documentaires, validation, formation, information fournisseur, dépôt réglementaire."),
               ("Lancer", "Le manager clique sur [[Start Implementation]] (au moins une action exigée)."),
               ("Réaliser", "Chaque responsable clique sur [[Start]] puis [[Mark as Done]] avec la référence de preuve. Seul le manager peut annuler une action ([[Cancel Action]]), avec motif."),
               ("Vérifier l'efficacité", "À la date prévue, le vérificateur saisit le résultat et la conclusion, puis clique sur [[Conclude: Effective]] ou [[Conclude: Not Effective]] (ce dernier exige une référence de suivi, ex. nouvelle demande ou CAPA)."),
               ("Déclarer vérifié", "Quand toutes les actions sont closes et les vérifications terminées, le manager clique sur [[Declare Verified]]."),
               ("Clore", "Cliquer sur [[Close]] et rédiger la déclaration de clôture (ce qui a changé, date d'effet, preuves)."),
               ("Changement temporaire", "À la date de fin, vérifier le retour à l'état initial et le consigner avant clôture.")],
        controls=["Les actions ne s'exécutent qu'une fois le changement approuvé ; seul le responsable ou le manager peut mettre à jour une action.",
                  "Une action ne se clôt pas sans référence de preuve ; l'annulation exige un motif et le rôle manager ; une action démarrée ne peut être supprimée.",
                  "Les vérifications ne se terminent qu'en *Implementation* ; une conclusion est exigée ; *Not Effective* impose un suivi.",
                  "La vérification de la demande est refusée tant qu'il reste des points bloquants ; la clôture exige une déclaration.",
                  "Une catégorie exigeant une vérification d'efficacité doit définir un délai (sur la catégorie ou la société)."],
        good=["Ne pas déclarer le changement efficace le jour de sa mise en œuvre : prévoir une période représentative.",
              "Référence de preuve précise (numéro et révision du document, numéro de rapport).",
              "Boucler avec la formation (SOP-QA-012) et la revalidation (SOP-VAL-005)."],
        pitfalls=["Actions closes avec « fait » sans preuve.",
                  "Des demandes laissées en *Implementation* des mois après l'utilisation du changement."],
        records=["Actions de mise en œuvre avec preuves", "Vérifications d'efficacité", "Déclaration de clôture"],
        kpis=["Actions en retard", "Demandes closes à la date prévue", "% de changements nécessitant un suivi"],
        example="**Cas (suite).** Actions de CC-2026-021 : (1) QO de la presse avec le nouvel outillage — rapport VAL-OQ-2026-008 ; (2) révision de la SOP-PRD-014 rév. 4 ; (3) formation des opérateurs. Après 10 lots, le vérificateur examine les tendances de masse, dureté et friabilité : toutes dans les limites de maîtrise → [[Conclude: Effective]]. Le manager clique sur [[Declare Verified]] puis [[Close]].",
    ),
)

M_CMP = module(
    "mod-complaint", "ls_complaint", "Complaints", "Réclamations",
    [
        ("p", "**ls_complaint** records product quality complaints from any channel, with product, lot and sample, "
              "assessment, investigations (several methodologies, approval by a different user), resolutions, "
              "adverse events with reportability assessment, and closure. Complaint categories carry target times "
              "for acknowledgement, investigation and closure, and the reporting deadline for adverse events."),
        ("table", ["Menu", "Content"], [
            ["{{Complaints ▸ Complaint Handling ▸ All / My Complaints / Investigations / Resolutions}}", "Complaint handling"],
            ["{{Complaints ▸ Vigilance ▸ Adverse Events}}", "Adverse events and authority reports"],
            ["{{Complaints ▸ Configuration ▸ Complaint Categories}}", "Target days and reporting deadline"],
            ["{{Complaints ▸ Reporting ▸ Complaint Analysis}}", "Trending"],
        ]),
        ("table", ["Group", "Main rights"], [
            ["Complaint Viewer · Investigator · Reviewer · Manager", "Investigator investigates; Reviewer approves investigations; Manager closes and cancels."],
        ]),
        ("flow", "complaint", "Lifecycle of a complaint."),
        ("shot", "ls_complaint__form", "Complaint form."),
    ],
    [
        ("p", "**ls_complaint** enregistre les réclamations qualité produit quel que soit le canal, avec produit, lot et "
              "échantillon, évaluation, investigations (plusieurs méthodes, approbation par un autre utilisateur), "
              "résolutions, événements indésirables avec évaluation de la déclarabilité, et clôture. Les catégories "
              "portent les délais cibles d'accusé de réception, d'investigation et de clôture, ainsi que le délai de "
              "déclaration des événements indésirables."),
        ("table", ["Menu", "Contenu"], [
            ["{{Complaints ▸ Complaint Handling ▸ All / My Complaints / Investigations / Resolutions}}", "Traitement des réclamations"],
            ["{{Complaints ▸ Vigilance ▸ Adverse Events}}", "Événements indésirables et déclarations"],
            ["{{Complaints ▸ Configuration ▸ Complaint Categories}}", "Délais cibles et délai de déclaration"],
            ["{{Complaints ▸ Reporting ▸ Complaint Analysis}}", "Analyse de tendance"],
        ]),
        ("table", ["Groupe", "Droits principaux"], [
            ["Complaint Viewer · Investigator · Reviewer · Manager", "Investigator enquête ; Reviewer approuve les investigations ; Manager clôt et annule."],
        ]),
        ("flow", "complaint", "Cycle de vie d'une réclamation."),
        ("shot", "ls_complaint__form", "Fiche réclamation."),
    ],
)

QA040 = sop(
    "SOP-QA-040", "ls_complaint", "Complaints ▸ Complaint Handling",
    flows=[("complaint", tr("Complaint lifecycle.", "Cycle de vie d'une réclamation."))],
    shots=[("ls_complaint__list", tr("Complaint register.", "Registre des réclamations."))],
    related=["SOP-QA-041", "SOP-QA-022", "SOP-QA-081"],
    refs=["EU-GMP-8", "CFR-211-198", "ISO-13485", "ISO-22716", "COS-23"],
    en=dict(
        title="Reception, assessment and investigation of complaints",
        owner="Complaint Manager (QA)",
        objective="Register every complaint, acknowledge it on time, assess its seriousness, investigate the cause when justified, respond to the complainant and feed the CAPA and recall processes.",
        scope="Product quality complaints received from patients, consumers, healthcare professionals, customers, distributors, pharmacies, hospitals, authorities or internal sources, for all products of the company.",
        roles=[("Receiver (any employee)", "Forwards the complaint to QA the same day; creates the record if trained."),
               ("Complaint Investigator", "Assesses and investigates, requests the sample, writes conclusions."),
               ("Complaint Reviewer", "Approves or rejects investigations (not their own)."),
               ("Complaint Manager", "Decides on waiver of investigation and CAPA, closes the complaint.")],
        defs=[("Complaint", "Any written, electronic or oral communication alleging a deficiency of a product after release."),
              ("Waiver of investigation", "Documented decision not to investigate (e.g. identical complaint already investigated).")],
        steps=[("Register", "In {{Complaints ▸ Complaint Handling}} click [[New]]: receipt date, channel, received by, complainant and type, subject and description, product, lot, quantity, market, sample availability."),
               ("Acknowledge", "Contact the complainant within the category's acknowledgement target; record *Customer Notified* and the date."),
               ("Assess", "Click [[Start Assessment]]; set category, complaint type, severity, potential safety and regulatory impact, assessment summary. If an adverse event is involved, create it (SOP-QA-041)."),
               ("Investigate or waive", "Click [[Start Investigation]] and add an investigation (investigator, methodology, plan). Or click [[Waive Investigation]] with a justification."),
               ("Investigate", "Examine the sample, the retained samples, batch record, other complaints on the same lot; record the summary, root cause category and description, conclusion (Confirmed, Not Confirmed, Inconclusive) and the batch impact. Click [[Complete]]; a reviewer clicks [[Approve]]."),
               ("CAPA", "If a CAPA is needed click [[CAPA Required]], open the CAPA (SOP-QA-022) and record its reference."),
               ("Resolve", "Click [[Start Resolution]]; add resolutions (reply letter, replacement, credit) and mark them done with evidence."),
               ("Close", "Click [[Close]] with a closure summary. Consider a recall (SOP-QA-081) if the investigation shows a risk for other units on the market.")],
        controls=["Receipt date not in the future; occurrence date ≤ receipt date; expiry date ≥ manufacturing date; the lot must belong to the product.",
                  "A product must be identified before leaving the *Received* state.",
                  "A description is mandatory when the channel or type is *Other*.",
                  "Investigation: completion date ≥ start date; mandatory fields checked at completion; root cause description required unless *Not Determined*; the approver must differ from the investigator; a rejection needs a reason.",
                  "Resolution requires completion evidence; cancellation requires a reason.",
                  "Closure requires a closure summary; cancellation requires a reason; a complaint that left *Received* cannot be deleted."],
        good=["Record the complainant's words verbatim in the description.",
              "Ask for the sample and the lot number at first contact.",
              "Search for complaints on the same lot before concluding.",
              "Treat suspected falsified products as urgent and inform the authority according to local rules."],
        pitfalls=["Closing \"not confirmed\" without examining a sample or retained sample.",
                  "Missing the reportability assessment when health is involved."],
        records=["Complaint record, investigations with approval, resolutions, closure summary", "Correspondence with the complainant"],
        kpis=["Acknowledgement within target", "Median closure time", "Complaints per million units per product", "% confirmed"],
        example="**Case.** A pharmacy reports by phone that a blister of lot 24B117 contains one broken tablet. The receiver registers the complaint (channel *Phone*, complainant type *Pharmacy*, type *Product Quality Defect*). QA acknowledges within 2 days, assesses severity *Minor*, starts an investigation (methodology *Batch Record Review*): no event recorded, IPC hardness within limits, 2 similar complaints in 12 months across 3 lots → not systemic. Conclusion *Complaint Confirmed*, root cause *Transport or Storage* (crushed box visible on the photo). Resolution: replacement and letter. Closed in 18 days.",
    ),
    fr=dict(
        title="Réception, évaluation et investigation des réclamations",
        owner="Complaint Manager (AQ)",
        objective="Enregistrer chaque réclamation, en accuser réception dans les délais, en évaluer la gravité, en rechercher la cause lorsque c'est justifié, répondre au réclamant et alimenter les processus CAPA et rappel.",
        scope="Réclamations qualité produit reçues de patients, consommateurs, professionnels de santé, clients, distributeurs, pharmacies, hôpitaux, autorités ou sources internes, pour tous les produits de l'entreprise.",
        roles=[("Récepteur (tout salarié)", "Transmet la réclamation à l'AQ le jour même ; crée l'enregistrement s'il est formé."),
               ("Complaint Investigator", "Évalue et enquête, demande l'échantillon, rédige les conclusions."),
               ("Complaint Reviewer", "Approuve ou rejette les investigations (pas les siennes)."),
               ("Complaint Manager", "Décide de la dispense d'investigation et de la CAPA, clôt la réclamation.")],
        defs=[("Réclamation", "Toute communication écrite, électronique ou orale alléguant un défaut d'un produit après sa libération."),
              ("Dispense d'investigation", "Décision documentée de ne pas enquêter (ex. réclamation identique déjà investiguée).")],
        steps=[("Enregistrer", "Dans {{Complaints ▸ Complaint Handling}}, cliquer sur [[New]] : date de réception, canal, reçu par, réclamant et son type, objet et description, produit, lot, quantité, marché, disponibilité de l'échantillon."),
               ("Accuser réception", "Contacter le réclamant dans le délai cible de la catégorie ; renseigner *Customer Notified* et la date."),
               ("Évaluer", "Cliquer sur [[Start Assessment]] ; fixer catégorie, type, gravité, impact potentiel sécurité et réglementaire, synthèse. En cas d'événement indésirable, le créer (SOP-QA-041)."),
               ("Enquêter ou dispenser", "Cliquer sur [[Start Investigation]] et ajouter une investigation (enquêteur, méthode, plan). Ou cliquer sur [[Waive Investigation]] avec justification."),
               ("Enquêter", "Examiner l'échantillon, les échantillons de référence, le dossier de lot, les autres réclamations du lot ; consigner la synthèse, la catégorie et la description de la cause, la conclusion (Confirmed, Not Confirmed, Inconclusive) et l'impact lot. Cliquer sur [[Complete]] ; un vérificateur clique sur [[Approve]]."),
               ("CAPA", "Si une CAPA est nécessaire, cliquer sur [[CAPA Required]], ouvrir la CAPA (SOP-QA-022) et saisir sa référence."),
               ("Résoudre", "Cliquer sur [[Start Resolution]] ; ajouter les résolutions (courrier de réponse, remplacement, avoir) et les marquer faites avec preuve."),
               ("Clore", "Cliquer sur [[Close]] avec une synthèse de clôture. Envisager un rappel (SOP-QA-081) si l'enquête montre un risque pour d'autres unités sur le marché.")],
        controls=["Date de réception non future ; survenue ≤ réception ; péremption ≥ fabrication ; le lot doit appartenir au produit.",
                  "Un produit doit être identifié avant de quitter l'état *Received*.",
                  "Une description est obligatoire quand le canal ou le type est *Other*.",
                  "Investigation : date de fin ≥ début ; champs obligatoires contrôlés à la fin ; description de cause exigée sauf *Not Determined* ; l'approbateur doit différer de l'enquêteur ; un rejet exige un motif.",
                  "Une résolution exige une preuve ; son annulation un motif.",
                  "La clôture exige une synthèse ; l'annulation un motif ; une réclamation sortie de *Received* ne peut être supprimée."],
        good=["Consigner mot pour mot les propos du réclamant.",
              "Demander l'échantillon et le numéro de lot dès le premier contact.",
              "Rechercher les réclamations sur le même lot avant de conclure.",
              "Traiter les suspicions de falsification en urgence et informer l'autorité selon les règles locales."],
        pitfalls=["Conclure « non confirmée » sans examiner d'échantillon ni échantillon de référence.",
                  "Oublier l'évaluation de déclarabilité quand la santé est en jeu."],
        records=["Réclamation, investigations approuvées, résolutions, synthèse de clôture", "Correspondance avec le réclamant"],
        kpis=["Accusés de réception dans le délai", "Délai médian de clôture", "Réclamations par million d'unités par produit", "% confirmées"],
        example="**Cas.** Une pharmacie signale par téléphone qu'un blister du lot 24B117 contient un comprimé cassé. Le récepteur enregistre la réclamation (canal *Phone*, réclamant *Pharmacy*, type *Product Quality Defect*). L'AQ accuse réception en 2 jours, fixe la gravité *Minor*, ouvre une investigation (méthode *Batch Record Review*) : aucun événement consigné, dureté en cours de fabrication conforme, 2 réclamations similaires en 12 mois sur 3 lots → non systémique. Conclusion *Complaint Confirmed*, cause *Transport or Storage* (boîte écrasée visible sur la photo). Résolution : remplacement et courrier. Clôture en 18 jours.",
    ),
)

QA041 = sop(
    "SOP-QA-041", "ls_complaint", "Complaints ▸ Vigilance ▸ Adverse Events",
    flows=[("adverse_event", tr("Lifecycle of an adverse event.", "Cycle de vie d'un événement indésirable."))],
    related=["SOP-QA-040", "SOP-MD-007"],
    refs=["MDR-VIG", "CFR-803", "GVP-VI", "COS-23", "ISO-13485"],
    en=dict(
        title="Adverse events: reportability assessment and reporting deadlines",
        owner="Vigilance officer / Complaint Manager",
        objective="Identify, among complaints, the events that must be reported to a competent authority, assess reportability and causality in a documented way, and submit within the legal deadline.",
        scope="Adverse events and incidents linked to complaints for medicinal products, medical devices and cosmetics. Pharmacovigilance systems for medicinal products may be managed in a dedicated tool; this SOP then covers the hand-over.",
        roles=[("Complaint Investigator", "Creates the adverse event from the complaint and collects facts."),
               ("Vigilance officer", "Assesses seriousness, causality and reportability; submits the report."),
               ("Complaint Manager", "Configures the reporting deadlines per category; supervises timeliness.")],
        defs=[("Awareness date", "Date when the company first became aware of the event; the reporting clock starts from it."),
              ("Report due date", "Computed: awareness date + reporting deadline (days) configured on the complaint category."),
              ("Causality", "Certain, Probable, Possible, Unlikely, Unrelated, Not Assessable.")],
        steps=[("Configure deadlines", "For each complaint category set *Adverse Event Reporting Deadline (days)* according to the applicable rule. A single deadline per category: create separate categories when deadlines differ by seriousness (for example, for medical devices under the MDR: 2, 10 or 15 days depending on the case; for US medical device reporting: 30 calendar days, or 5 work days in defined cases; for EU pharmacovigilance: 15 days for serious and 90 days for non-serious reactions)."),
               ("Create", "From the complaint, add an adverse event: awareness date, event date, description, seriousness and criteria, outcome, subject pseudonym, age range, sex."),
               ("Assess", "Record causality and its rationale, *Reportable to Authority*, the reportability rationale and the competent authority. Click [[Assess]]."),
               ("Submit", "Prepare and send the report through the authority's channel before the due date; record the submission date, the authority acknowledgement reference and who submitted; click [[Record Submission]]."),
               ("Follow up", "Record follow-up information; tick *Follow Up Required* when a follow-up report is due."),
               ("Close", "Click [[Close]] with closure notes.")],
        controls=["Awareness date not in the future; event date ≤ awareness date.",
                  "Reportability rationale mandatory once assessed; causality assessment mandatory.",
                  "A reportable event requires the competent authority; a non-reportable event cannot record a submission.",
                  "The authority acknowledgement reference is mandatory at submission.",
                  "Closed events cannot be modified; non-draft events cannot be deleted."],
        good=["Assess reportability on the day of awareness; when in doubt, report.",
              "Use pseudonyms — never store the patient's name in the complaint system.",
              "Monitor the overdue filter daily."],
        pitfalls=["Starting the clock at the date QA received the complaint instead of the first awareness in the company.",
                  "One category used for all seriousness levels with a single, inappropriate deadline."],
        records=["Adverse event with assessment, submission and acknowledgement"],
        kpis=["% of reportable events submitted on time (target 100 %)", "Median time from awareness to assessment"],
        example="**Case.** A hospital reports that a catheter tip detached during use, without injury. Awareness 3 March. The vigilance officer assesses seriousness *Serious* (could have led to serious deterioration), causality *Probable*, reportable to the national competent authority. The category *Medical device — serious incident* has a 15-day deadline: the report is due 18 March. It is submitted on 12 March; the authority's reference is recorded; a follow-up report is planned after the investigation.",
    ),
    fr=dict(
        title="Événements indésirables : évaluation de la déclarabilité et délais de déclaration",
        owner="Responsable vigilance / Complaint Manager",
        objective="Identifier, parmi les réclamations, les événements à déclarer à une autorité compétente, évaluer la déclarabilité et l'imputabilité de manière documentée, et déclarer dans le délai légal.",
        scope="Événements indésirables et incidents liés aux réclamations pour médicaments, dispositifs médicaux et cosmétiques. La pharmacovigilance des médicaments peut être gérée dans un outil dédié ; cette SOP couvre alors le passage de relais.",
        roles=[("Complaint Investigator", "Crée l'événement depuis la réclamation et recueille les faits."),
               ("Responsable vigilance", "Évalue gravité, imputabilité et déclarabilité ; déclare."),
               ("Complaint Manager", "Paramètre les délais par catégorie ; surveille le respect des délais.")],
        defs=[("Date de connaissance (Awareness date)", "Date à laquelle l'entreprise a eu connaissance de l'événement ; le délai court à partir d'elle."),
              ("Échéance de déclaration", "Calculée : date de connaissance + délai (jours) paramétré sur la catégorie."),
              ("Imputabilité (Causality)", "Certain, Probable, Possible, Unlikely, Unrelated, Not Assessable.")],
        steps=[("Paramétrer les délais", "Pour chaque catégorie de réclamation, fixer *Adverse Event Reporting Deadline (days)* selon la règle applicable. Un seul délai par catégorie : créer des catégories distinctes quand les délais varient selon la gravité (par exemple pour les dispositifs médicaux sous MDR : 2, 10 ou 15 jours selon le cas ; pour la déclaration américaine des dispositifs : 30 jours calendaires, ou 5 jours ouvrés dans les cas prévus ; en pharmacovigilance UE : 15 jours pour les effets graves et 90 jours pour les non graves)."),
               ("Créer", "Depuis la réclamation, ajouter un événement : date de connaissance, date de survenue, description, gravité et critères, évolution, pseudonyme du sujet, tranche d'âge, sexe."),
               ("Évaluer", "Renseigner l'imputabilité et sa justification, *Reportable to Authority*, la justification de déclarabilité et l'autorité compétente. Cliquer sur [[Assess]]."),
               ("Déclarer", "Préparer et envoyer la déclaration par le canal de l'autorité avant l'échéance ; saisir la date d'envoi, la référence d'accusé de l'autorité et le déclarant ; cliquer sur [[Record Submission]]."),
               ("Suivre", "Consigner les informations de suivi ; cocher *Follow Up Required* si un rapport de suivi est dû."),
               ("Clore", "Cliquer sur [[Close]] avec des notes de clôture.")],
        controls=["Date de connaissance non future ; date de survenue ≤ date de connaissance.",
                  "Justification de déclarabilité obligatoire après évaluation ; imputabilité obligatoire.",
                  "Un événement déclarable exige l'autorité compétente ; un événement non déclarable ne peut enregistrer d'envoi.",
                  "La référence d'accusé de l'autorité est obligatoire à l'envoi.",
                  "Un événement clos n'est plus modifiable ; seul un brouillon peut être supprimé."],
        good=["Évaluer la déclarabilité le jour même ; en cas de doute, déclarer.",
              "Utiliser des pseudonymes — jamais le nom du patient dans le système de réclamations.",
              "Surveiller chaque jour le filtre des retards."],
        pitfalls=["Faire courir le délai depuis la réception par l'AQ au lieu de la première connaissance dans l'entreprise.",
                  "Une seule catégorie pour toutes les gravités avec un délai unique inadapté."],
        records=["Événement avec évaluation, déclaration et accusé de réception"],
        kpis=["% d'événements déclarables déclarés dans le délai (cible 100 %)", "Délai médian connaissance → évaluation"],
        example="**Cas.** Un hôpital signale le détachement de l'extrémité d'un cathéter pendant l'utilisation, sans blessure. Connaissance le 3 mars. Le responsable vigilance évalue la gravité *Serious* (aurait pu entraîner une dégradation grave), l'imputabilité *Probable*, déclarable à l'autorité nationale. La catégorie *Dispositif médical — incident grave* a un délai de 15 jours : échéance le 18 mars. La déclaration part le 12 mars ; la référence de l'autorité est saisie ; un rapport de suivi est prévu après l'enquête.",
    ),
)

ITEMS = [M_DEV, QA020, QA021, QA022, QA023, M_CC, QA030, QA031, M_CMP, QA040, QA041]
