# -*- coding: utf-8 -*-
"""Regulatory and normative references cited by the SOP sheets.

Only texts whose existence, title and scope are well established are listed.
Chapter- or article-level citations are used where the exact paragraph could
not be confirmed. Each organisation must check the version in force before
approving its SOPs.
"""


def R(en, fr=None):
    return {"en": en, "fr": fr or en}


REFS = {
    # EU GMP (EudraLex Volume 4)
    "EU-GMP-1": R("EudraLex Vol. 4, EU GMP Part I, Chapter 1 — Pharmaceutical Quality System",
                  "EudraLex vol. 4, BPF UE partie I, chapitre 1 — Système qualité pharmaceutique"),
    "EU-GMP-2": R("EudraLex Vol. 4, EU GMP Part I, Chapter 2 — Personnel",
                  "EudraLex vol. 4, BPF UE partie I, chapitre 2 — Personnel"),
    "EU-GMP-3": R("EudraLex Vol. 4, EU GMP Part I, Chapter 3 — Premises and Equipment",
                  "EudraLex vol. 4, BPF UE partie I, chapitre 3 — Locaux et matériel"),
    "EU-GMP-4": R("EudraLex Vol. 4, EU GMP Part I, Chapter 4 — Documentation",
                  "EudraLex vol. 4, BPF UE partie I, chapitre 4 — Documentation"),
    "EU-GMP-5": R("EudraLex Vol. 4, EU GMP Part I, Chapter 5 — Production",
                  "EudraLex vol. 4, BPF UE partie I, chapitre 5 — Production"),
    "EU-GMP-6": R("EudraLex Vol. 4, EU GMP Part I, Chapter 6 — Quality Control",
                  "EudraLex vol. 4, BPF UE partie I, chapitre 6 — Contrôle de la qualité"),
    "EU-GMP-7": R("EudraLex Vol. 4, EU GMP Part I, Chapter 7 — Outsourced Activities",
                  "EudraLex vol. 4, BPF UE partie I, chapitre 7 — Activités externalisées"),
    "EU-GMP-8": R("EudraLex Vol. 4, EU GMP Part I, Chapter 8 — Complaints and Product Recall",
                  "EudraLex vol. 4, BPF UE partie I, chapitre 8 — Réclamations et rappels de produits"),
    "EU-GMP-9": R("EudraLex Vol. 4, EU GMP Part I, Chapter 9 — Self Inspection",
                  "EudraLex vol. 4, BPF UE partie I, chapitre 9 — Auto-inspection"),
    "EU-A1": R("EU GMP Annex 1 (2022) — Manufacture of Sterile Medicinal Products",
               "BPF UE annexe 1 (2022) — Fabrication des médicaments stériles"),
    "EU-A11": R("EU GMP Annex 11 — Computerised Systems (check the revision in force)",
                "BPF UE annexe 11 — Systèmes informatisés (vérifier la révision en vigueur)"),
    "EU-A15": R("EU GMP Annex 15 (2015) — Qualification and Validation",
                "BPF UE annexe 15 (2015) — Qualification et validation"),
    "EU-A16": R("EU GMP Annex 16 — Certification by a Qualified Person and Batch Release",
                "BPF UE annexe 16 — Certification par une personne qualifiée et libération des lots"),
    # US
    "CFR-11": R("21 CFR Part 11 — Electronic Records; Electronic Signatures",
                "21 CFR Part 11 — Enregistrements et signatures électroniques"),
    "CFR-211": R("21 CFR Part 211 — Current Good Manufacturing Practice for Finished Pharmaceuticals",
                 "21 CFR Part 211 — BPF en vigueur pour les produits pharmaceutiques finis"),
    "CFR-211-22": R("21 CFR 211.22 — Responsibilities of the quality control unit",
                    "21 CFR 211.22 — Responsabilités de l'unité de contrôle qualité"),
    "CFR-211-25": R("21 CFR 211.25 — Personnel qualifications", "21 CFR 211.25 — Qualification du personnel"),
    "CFR-211-68": R("21 CFR 211.68 — Automatic, mechanical and electronic equipment",
                    "21 CFR 211.68 — Équipements automatiques, mécaniques et électroniques"),
    "CFR-211-84": R("21 CFR 211.84 — Testing and approval or rejection of components",
                    "21 CFR 211.84 — Contrôle et acceptation ou refus des composants"),
    "CFR-211-100": R("21 CFR 211.100 — Written procedures; deviations",
                     "21 CFR 211.100 — Procédures écrites ; déviations"),
    "CFR-211-160": R("21 CFR 211.160 to 211.176 — Laboratory controls",
                     "21 CFR 211.160 à 211.176 — Contrôles de laboratoire"),
    "CFR-211-166": R("21 CFR 211.166 — Stability testing", "21 CFR 211.166 — Essais de stabilité"),
    "CFR-211-180": R("21 CFR 211.180 to 211.198 — Records and reports",
                     "21 CFR 211.180 à 211.198 — Enregistrements et rapports"),
    "CFR-211-188": R("21 CFR 211.186 and 211.188 — Master and batch production and control records",
                     "21 CFR 211.186 et 211.188 — Dossiers maîtres et dossiers de lot"),
    "CFR-211-192": R("21 CFR 211.192 — Production record review", "21 CFR 211.192 — Revue des dossiers de production"),
    "CFR-211-198": R("21 CFR 211.198 — Complaint files", "21 CFR 211.198 — Dossiers de réclamations"),
    "CFR-211-130": R("21 CFR 211.122 to 211.137 — Packaging and labelling control",
                     "21 CFR 211.122 à 211.137 — Contrôle du conditionnement et de l'étiquetage"),
    "CFR-7": R("21 CFR Part 7, Subpart C — Recalls (7.40 to 7.59)",
               "21 CFR Part 7, sous-partie C — Rappels (7.40 à 7.59)"),
    "CFR-820": R("21 CFR Part 820 — Quality Management System Regulation (incorporates ISO 13485:2016 by reference; applicable since 2 February 2026)",
                 "21 CFR Part 820 — Quality Management System Regulation (intègre l'ISO 13485:2016 par référence ; applicable depuis le 2 février 2026)"),
    "CFR-803": R("21 CFR Part 803 — Medical Device Reporting", "21 CFR Part 803 — Déclaration des incidents liés aux dispositifs médicaux"),
    "FDA-OOS": R("FDA Guidance — Investigating Out-of-Specification (OOS) Test Results for Pharmaceutical Production (Revision 1, 2022)",
                 "Guide FDA — Investigating Out-of-Specification (OOS) Test Results for Pharmaceutical Production (révision 1, 2022)"),
    "FDA-PV": R("FDA Guidance — Process Validation: General Principles and Practices (2011)",
                "Guide FDA — Process Validation: General Principles and Practices (2011)"),
    "FDA-DI": R("FDA Guidance — Data Integrity and Compliance With Drug CGMP, Questions and Answers (2018)",
                "Guide FDA — Data Integrity and Compliance With Drug CGMP, questions-réponses (2018)"),
    # ICH
    "ICH-Q1A": R("ICH Q1A(R2) — Stability Testing of New Drug Substances and Products",
                 "ICH Q1A(R2) — Essais de stabilité des nouvelles substances et nouveaux produits"),
    "ICH-Q2": R("ICH Q2(R2) — Validation of Analytical Procedures", "ICH Q2(R2) — Validation des procédures analytiques"),
    "ICH-Q7": R("ICH Q7 — Good Manufacturing Practice for Active Pharmaceutical Ingredients",
                "ICH Q7 — Bonnes pratiques de fabrication des substances actives"),
    "ICH-Q9": R("ICH Q9(R1) — Quality Risk Management", "ICH Q9(R1) — Gestion du risque qualité"),
    "ICH-Q10": R("ICH Q10 — Pharmaceutical Quality System", "ICH Q10 — Système qualité pharmaceutique"),
    "ICH-M4": R("ICH M4 — Organisation of the Common Technical Document", "ICH M4 — Organisation du document technique commun (CTD)"),
    # ISO / IEC
    "ISO-9001": R("ISO 9001:2015 — Quality management systems — Requirements",
                  "ISO 9001:2015 — Systèmes de management de la qualité — Exigences"),
    "ISO-13485": R("ISO 13485:2016 — Medical devices — Quality management systems",
                   "ISO 13485:2016 — Dispositifs médicaux — Systèmes de management de la qualité"),
    "ISO-14971": R("ISO 14971:2019 — Medical devices — Application of risk management",
                   "ISO 14971:2019 — Dispositifs médicaux — Application de la gestion des risques"),
    "ISO-19011": R("ISO 19011:2018 — Guidelines for auditing management systems",
                   "ISO 19011:2018 — Lignes directrices pour l'audit des systèmes de management"),
    "ISO-22716": R("ISO 22716:2007 — Cosmetics — Good Manufacturing Practices",
                   "ISO 22716:2007 — Cosmétiques — Bonnes pratiques de fabrication"),
    "ISO-17025": R("ISO/IEC 17025:2017 — Competence of testing and calibration laboratories",
                   "ISO/IEC 17025:2017 — Compétence des laboratoires d'étalonnages et d'essais"),
    "ISO-14644": R("ISO 14644-1:2015 — Cleanrooms — Classification of air cleanliness by particle concentration",
                   "ISO 14644-1:2015 — Salles propres — Classification de la propreté particulaire de l'air"),
    "ISO-10012": R("ISO 10012:2003 — Measurement management systems", "ISO 10012:2003 — Systèmes de management de la mesure"),
    "ISO-31000": R("ISO 31000:2018 — Risk management — Guidelines", "ISO 31000:2018 — Management du risque — Lignes directrices"),
    "IEC-60812": R("IEC 60812:2018 — Failure modes and effects analysis (FMEA and FMECA)",
                   "IEC 60812:2018 — Analyse des modes de défaillance et de leurs effets (AMDE et AMDEC)"),
    "ISO-15378": R("ISO 15378:2017 — Primary packaging materials for medicinal products",
                   "ISO 15378:2017 — Articles d'emballage primaire pour médicaments"),
    "ISO-10993": R("ISO 10993-1 — Biological evaluation of medical devices", "ISO 10993-1 — Évaluation biologique des dispositifs médicaux"),
    # EU product legislation
    "MDR": R("Regulation (EU) 2017/745 on medical devices (MDR)", "Règlement (UE) 2017/745 relatif aux dispositifs médicaux (MDR)"),
    "MDR-UDI": R("MDR Article 27 and Annex VI — Unique Device Identification", "MDR article 27 et annexe VI — Identification unique des dispositifs"),
    "MDR-CE": R("MDR Articles 20 and 52, Annexes IX to XI — CE marking and conformity assessment",
                "MDR articles 20 et 52, annexes IX à XI — Marquage CE et évaluation de la conformité"),
    "MDR-CLIN": R("MDR Article 61 and Annex XIV — Clinical evaluation and PMCF",
                  "MDR article 61 et annexe XIV — Évaluation clinique et SCAC (PMCF)"),
    "MDR-TD": R("MDR Annexes II and III — Technical documentation", "MDR annexes II et III — Documentation technique"),
    "MDR-PMS": R("MDR Articles 83 to 86 and Annex III — Post-market surveillance, PMS report and PSUR",
                 "MDR articles 83 à 86 et annexe III — Surveillance après commercialisation, rapport SAC et PSUR"),
    "MDR-VIG": R("MDR Articles 87 to 92 — Vigilance", "MDR articles 87 à 92 — Vigilance"),
    "COS": R("Regulation (EC) No 1223/2009 on cosmetic products", "Règlement (CE) n° 1223/2009 relatif aux produits cosmétiques"),
    "COS-10": R("Regulation (EC) No 1223/2009, Article 10 and Annex I — Safety assessment (CPSR)",
                "Règlement (CE) n° 1223/2009, article 10 et annexe I — Évaluation de la sécurité (RSPC/CPSR)"),
    "COS-11": R("Regulation (EC) No 1223/2009, Article 11 — Product information file",
                "Règlement (CE) n° 1223/2009, article 11 — Dossier d'information sur le produit"),
    "COS-14": R("Regulation (EC) No 1223/2009, Article 14 and Annexes II to VI — Restrictions",
                "Règlement (CE) n° 1223/2009, article 14 et annexes II à VI — Restrictions"),
    "COS-19": R("Regulation (EC) No 1223/2009, Article 19 — Labelling", "Règlement (CE) n° 1223/2009, article 19 — Étiquetage"),
    "COS-20": R("Regulation (EC) No 1223/2009, Article 20, and Regulation (EU) No 655/2013 — Claims and common criteria",
                "Règlement (CE) n° 1223/2009, article 20, et règlement (UE) n° 655/2013 — Allégations et critères communs"),
    "COS-23": R("Regulation (EC) No 1223/2009, Article 23 — Serious undesirable effects",
                "Règlement (CE) n° 1223/2009, article 23 — Effets indésirables graves"),
    "DZ-COS": R("Algeria — Executive Decree No. 97-37 of 14 January 1997, as amended by Executive Decree No. 10-114 of 18 April 2010 (as cited in ls_cosmetics; to be verified by Regulatory Affairs)",
                "Algérie — Décret exécutif n° 97-37 du 14 janvier 1997, modifié par le décret exécutif n° 10-114 du 18 avril 2010 (tel que cité dans ls_cosmetics ; à vérifier par les affaires réglementaires)"),
    "FMD": R("Commission Delegated Regulation (EU) 2016/161 — Safety features on medicinal product packaging",
             "Règlement délégué (UE) 2016/161 — Dispositifs de sécurité sur l'emballage des médicaments"),
    "GS1": R("GS1 General Specifications (GTIN, SSCC, check digit)", "Spécifications générales GS1 (GTIN, SSCC, clé de contrôle)"),
    # data integrity / CSV
    "PICS-DI": R("PIC/S PI 041-1 — Good Practices for Data Management and Integrity in Regulated GMP/GDP Environments (2021)",
                 "PIC/S PI 041-1 — Bonnes pratiques de gestion et d'intégrité des données en environnement BPF/BPD (2021)"),
    "MHRA-DI": R("MHRA — GxP Data Integrity Guidance and Definitions (2018)", "MHRA — GxP Data Integrity Guidance and Definitions (2018)"),
    "GAMP5": R("ISPE GAMP 5 Guide, Second Edition (2022) — A Risk-Based Approach to Compliant GxP Computerized Systems",
               "Guide ISPE GAMP 5, deuxième édition (2022) — Approche fondée sur les risques des systèmes informatisés GxP"),
    "GHTF-PV": R("GHTF/SG3/N99-10:2004 — Quality Management Systems — Process Validation Guidance",
                 "GHTF/SG3/N99-10:2004 — Systèmes de management de la qualité — Guide de validation des procédés"),
    "GVP-VI": R("EMA Good Pharmacovigilance Practices, Module VI — Management and reporting of adverse reactions",
                "EMA, Bonnes pratiques de pharmacovigilance, module VI — Gestion et déclaration des effets indésirables"),
}
