{
    "name": "LSS Audit Probe (test-only)",
    "summary": "Runtime probes for the 2026-09-24 independent audit. Test code only; never install in production.",
    "version": "19.0.1.0.0",
    "license": "LGPL-3",
    "author": "Independent audit",
    "category": "Hidden/Tests",
    "depends": [
        "stock",
        "sale_stock",
        "purchase",
        "mrp",
        "hr",
        "ls_audit_trail",
        "ls_recall",
        "ls_pharma",
        "ls_supplier_qualification",
        "ls_document_management",
        "ls_qms",
        "ls_electronic_signature",
        "ls_lab",
    ],
    "data": [],
    "installable": True,
    "application": False,
}
