# Part of the Life Sciences Suite. See LICENSE file for full copyright
# and licensing details.
"""Tests of the risk register model."""

from dateutil.relativedelta import relativedelta

from psycopg2 import errors as pg_errors

from odoo import fields
from odoo.exceptions import AccessError, UserError, ValidationError
from odoo.tests.common import tagged

from .common import RiskCommon


@tagged("post_install", "-at_install")
class TestRiskRegister(RiskCommon):
    """Verify numbering, lifecycle gating and derived evaluation fields."""

    def test_sequence_assigned(self):
        """A new risk receives a reference from the sequence."""
        risk = self._make_risk()
        self.assertTrue(risk.name.startswith("RISK/"))
        self.assertNotEqual(risk.name, "/")

    def test_display_name_includes_reference(self):
        """The display name combines the reference and the title."""
        risk = self._make_risk(title="Contamination")
        self.assertEqual(risk.display_name, f"{risk.name} - Contamination")

    def test_default_matrix_applied(self):
        """A risk created without a matrix adopts the company default."""
        risk = self.env["ls.risk.register"].with_user(self.user_analyst).create(
            {"title": "Defaulted", "risk_type": "process"}
        )
        self.assertEqual(risk.matrix_id, self.matrix)

    def test_initial_state_is_draft(self):
        """A new risk starts in draft with no evaluation."""
        risk = self._make_risk()
        self.assertEqual(risk.state, "draft")
        self.assertFalse(risk.current_risk_level)
        self.assertFalse(risk.current_acceptability)

    def test_evaluation_follows_approved_assessment(self):
        """The current evaluation comes from the approved assessment."""
        risk = self._make_risk()
        self._approved_assessment(risk, severity=3, probability=3)
        self.assertEqual(risk.current_risk_level, "very_high")
        self.assertEqual(risk.current_acceptability, "not_acceptable")
        self.assertEqual(risk.assessment_count, 1)

    def test_draft_assessment_ignored_in_evaluation(self):
        """A draft assessment does not change the current evaluation."""
        risk = self._make_risk()
        self._make_assessment(risk, severity=3, probability=3)
        self.assertFalse(risk.current_risk_level)

    def test_initial_and_current_diverge(self):
        """The initial evaluation is preserved after a residual assessment."""
        risk = self._make_risk()
        self._approved_assessment(risk, severity=3, probability=3)
        residual = self._make_assessment(
            risk, severity=1, probability=1, assessment_type="residual"
        )
        residual.with_user(self.user_analyst).action_confirm()
        residual.with_user(self.user_manager).action_approve()
        self.assertEqual(risk.initial_risk_level, "very_high")
        # The current level is the level of the residual cell (1, 1) of the
        # fixture matrix, as generated by the matrix itself.
        self.assertEqual(
            risk.current_risk_level, self.matrix.get_cell(1, 1).risk_level
        )
        self.assertNotEqual(risk.current_risk_level, risk.initial_risk_level)

    def test_start_assessment_requires_initial(self):
        """A risk cannot leave draft without an approved initial assessment."""
        risk = self._make_risk()
        with self.assertRaises(UserError):
            risk.action_start_assessment()

    def test_start_assessment_sets_review_date(self):
        """Leaving draft sets the next review date from the interval."""
        risk = self._make_risk()
        self._approved_assessment(risk)
        risk.action_start_assessment()
        self.assertEqual(risk.state, "assessed")
        expected = fields.Date.context_today(risk) + relativedelta(
            months=risk.review_interval_months
        )
        self.assertEqual(risk.next_review_date, expected)

    def test_monitoring_requires_completeness(self):
        """Monitoring requires the completeness confirmation."""
        risk = self._make_risk()
        self._approved_assessment(risk)
        risk.action_start_assessment()
        risk.action_start_risk_control()
        with self.assertRaises(UserError):
            risk.with_user(self.user_manager).action_start_monitoring()

    def test_completeness_requires_verified_measures(self):
        """Completeness cannot be confirmed while measures are unverified."""
        risk = self._make_risk()
        self._approved_assessment(risk)
        risk.action_start_assessment()
        risk.action_start_risk_control()
        self.env["ls.risk.mitigation"].create(
            {
                "risk_id": risk.id,
                "title": "Pending measure",
                "description": "Not yet verified.",
                "control_option": "protective_measure",
                "responsible_id": self.user_analyst.id,
            }
        )
        with self.assertRaises(UserError):
            risk.with_user(self.user_manager).action_confirm_control_completeness()

    def test_completeness_requires_manager_role(self):
        """An analyst cannot confirm completeness through the ORM."""
        risk = self._make_risk()
        self._approved_assessment(risk)
        risk.action_start_assessment()
        risk.action_start_risk_control()
        with self.assertRaises(AccessError):
            risk.with_user(self.user_analyst).action_confirm_control_completeness()

    def test_monitoring_requires_residual_decision(self):
        """A risk needing control cannot be monitored without acceptance."""
        risk = self._make_risk()
        self._approved_assessment(risk, severity=3, probability=1)
        self.assertEqual(risk.current_acceptability, "acceptable_with_control")
        risk.action_start_assessment()
        risk.action_start_risk_control()
        risk.with_user(self.user_manager).action_confirm_control_completeness()
        with self.assertRaises(UserError):
            risk.with_user(self.user_manager).action_start_monitoring()

    def test_monitoring_allowed_when_acceptable(self):
        """An acceptable risk reaches monitoring without an acceptance."""
        risk = self._make_risk()
        self._approved_assessment(risk, severity=1, probability=1)
        self.assertEqual(risk.current_acceptability, "acceptable")
        risk.action_start_assessment()
        risk.action_start_risk_control()
        risk.with_user(self.user_manager).action_confirm_control_completeness()
        risk.with_user(self.user_manager).action_start_monitoring()
        self.assertEqual(risk.state, "monitoring")
        self.assertTrue(risk.last_review_date)

    def test_requires_residual_decision_without_assessment(self):
        """A risk with no approved assessment always needs a decision."""
        risk = self._make_risk()
        self.assertTrue(risk._requires_residual_decision())

    def test_unlink_blocked_after_assessment(self):
        """An assessed risk cannot be deleted."""
        risk = self._make_risk()
        self._approved_assessment(risk)
        risk.action_start_assessment()
        with self.assertRaises(UserError):
            risk.unlink()

    def test_unlink_allowed_in_draft(self):
        """A draft risk can be deleted."""
        risk = self._make_risk()
        risk.unlink()
        self.assertFalse(risk.exists())

    def test_copy_resets_workflow(self):
        """Duplicating a risk resets its reference and state."""
        risk = self._make_risk()
        self._approved_assessment(risk)
        risk.action_start_assessment()
        copy = risk.copy()
        self.assertEqual(copy.state, "draft")
        self.assertNotEqual(copy.name, risk.name)
        self.assertFalse(copy.assessment_ids)

    def test_review_overdue_flag(self):
        """An open risk past its review date is flagged overdue."""
        risk = self._make_risk()
        self._approved_assessment(risk)
        risk.action_start_assessment()
        risk.next_review_date = fields.Date.context_today(risk) - relativedelta(days=1)
        self.assertTrue(risk.review_overdue)

    def test_review_not_overdue_when_closed(self):
        """A closed risk is never flagged overdue."""
        risk = self._make_risk()
        self._approved_assessment(risk)
        risk.action_start_assessment()
        risk.next_review_date = fields.Date.context_today(risk) - relativedelta(days=1)
        risk.state = "closed"
        self.assertFalse(risk.review_overdue)

    def test_cron_notifies_overdue(self):
        """The scheduled action reports the number of overdue risks."""
        risk = self._make_risk()
        self._approved_assessment(risk)
        risk.action_start_assessment()
        risk.next_review_date = fields.Date.context_today(risk) - relativedelta(days=5)
        count = self.env["ls.risk.register"]._cron_notify_review_due()
        self.assertGreaterEqual(count, 1)

    def test_cron_ignores_current_risks(self):
        """The scheduled action ignores risks whose review is not due."""
        risk = self._make_risk()
        self._approved_assessment(risk)
        risk.action_start_assessment()
        risk.next_review_date = fields.Date.context_today(risk) + relativedelta(days=30)
        self.env["ls.risk.register"].search([]).write(
            {"next_review_date": fields.Date.context_today(risk) + relativedelta(days=30)}
        )
        self.assertEqual(self.env["ls.risk.register"]._cron_notify_review_due(), 0)

    def test_matrix_company_mismatch_rejected(self):
        """A risk cannot use a matrix from another company.

        The record is created with ``sudo`` so that the test exercises the
        Python constraint rather than an access error raised earlier by the
        multi-company record rule.
        """
        other = self._build_matrix(self.env, self.other_company, "MIS-3X3")
        with self.assertRaises(ValidationError):
            self.env["ls.risk.register"].sudo().create(
                {
                    "title": "Cross-company matrix",
                    "risk_type": "process",
                    "company_id": self.company.id,
                    "matrix_id": other.id,
                    "owner_id": self.user_analyst.id,
                }
            )

    def test_category_company_mismatch_rejected(self):
        """A risk cannot use a category from another company."""
        foreign_category = self.env["ls.risk.category"].sudo().create(
            {
                "name": "Foreign",
                "code": "FGN",
                "company_id": self.other_company.id,
            }
        )
        with self.assertRaises(ValidationError):
            self.env["ls.risk.register"].sudo().create(
                {
                    "title": "Cross-company category",
                    "risk_type": "process",
                    "company_id": self.company.id,
                    "category_id": foreign_category.id,
                    "matrix_id": self.matrix.id,
                    "owner_id": self.user_analyst.id,
                }
            )

    def test_review_interval_must_be_positive(self):
        """A non-positive review interval is rejected."""
        risk = self._make_risk()
        with self.assertRaises(pg_errors.CheckViolation):
            risk.review_interval_months = 0
            self.env.flush_all()

    def test_linked_record_requires_both_parts(self):
        """The technical link needs both a model and a record identifier."""
        risk = self._make_risk()
        model = self.env["ir.model"].search([("model", "=", "res.partner")], limit=1)
        with self.assertRaises(ValidationError):
            risk.linked_model_id = model

    def test_open_linked_record_requires_link(self):
        """Opening an absent linked record raises a user error."""
        risk = self._make_risk()
        with self.assertRaises(UserError):
            risk.action_open_linked_record()

    def test_reset_to_draft_requires_cancelled(self):
        """Only a cancelled risk can be reset to draft."""
        risk = self._make_risk()
        with self.assertRaises(UserError):
            risk.with_user(self.user_manager).action_reset_to_draft()
