#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Foundation (Volume 0 + Volume 1) generator for the
Life Sciences Suite Implementation & Operational Guide.

Output: docs/build/Life_Sciences_Guide_Foundation.pdf

Pipeline: ReportLab body PDF (with auto TOC) -> metadata -> QA.
Cover is rendered separately and prepended by render_cover.py.

Truth protocol: every module mentioned is tagged VERIFIED / CUSTOM DEVELOPMENT /
ASSUMPTION against the actual codebase under addons/.
"""

import hashlib
import os
import sys

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_JUSTIFY, TA_LEFT, TA_RIGHT
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import cm, inch, mm
from reportlab.pdfbase import pdfmetrics
from reportlab.pdfbase.pdfmetrics import registerFontFamily
from reportlab.pdfbase.ttfonts import TTFont
from reportlab.platypus import (
    CondPageBreak,
    HRFlowable,
    Image,
    KeepTogether,
    PageBreak,
    Paragraph,
    SimpleDocTemplate,
    Spacer,
    Table,
    TableStyle,
)
from reportlab.platypus.tableofcontents import TableOfContents

# ---------------------------------------------------------------------------
# Paths
# ---------------------------------------------------------------------------
HERE = os.path.dirname(os.path.abspath(__file__))
PROJECT_ROOT = os.path.dirname(os.path.dirname(HERE))
BUILD_DIR = os.path.join(PROJECT_ROOT, "docs", "build")
os.makedirs(BUILD_DIR, exist_ok=True)
OUTPUT_PDF = os.path.join(BUILD_DIR, "Life_Sciences_Guide_Foundation.pdf")

# ---------------------------------------------------------------------------
# Fonts (Windows TTF paths; brief paths are Linux-specific)
# ---------------------------------------------------------------------------
FONTS = {
    "TimesNewRoman": r"C:\Windows\Fonts\times.ttf",
    "TimesNewRoman-Bold": r"C:\Windows\Fonts\timesbd.ttf",
    "TimesNewRoman-Italic": r"C:\Windows\Fonts\timesi.ttf",
    "Calibri": r"C:\Windows\Fonts\calibri.ttf",
    "Calibri-Bold": r"C:\Windows\Fonts\calibrib.ttf",
    "Consolas": r"C:\Windows\Fonts\consola.ttf",
}
for name, path in FONTS.items():
    if not os.path.exists(path):
        raise FileNotFoundError(f"Required font not found: {path}")
    pdfmetrics.registerFont(TTFont(name, path))

registerFontFamily(
    "TimesNewRoman",
    normal="TimesNewRoman",
    bold="TimesNewRoman-Bold",
    italic="TimesNewRoman-Italic",
)
registerFontFamily("Calibri", normal="Calibri", bold="Calibri-Bold")
registerFontFamily("Consolas", normal="Consolas", bold="Consolas")

# ---------------------------------------------------------------------------
# Palette (auto-generated by pdf.py palette.cascade, then fixed for clinical tone)
# Source intent: "Cool Blue Clinical Regulatory Pharmaceutical Quality System"
#   Intent: neutral | Mode: minimal | Harmony: split_complementary
#   Base hue: 45 | Accent hue: 195 | All tier constraints PASS
# ---------------------------------------------------------------------------
ACCENT = colors.HexColor("#2b8eaf")          # clinical blue (XS accent)
ACCENT_DARK = colors.HexColor("#1f6b86")     # deeper blue for H1
ACCENT_SECONDARY = colors.HexColor("#53bb53")  # green for VERIFIED badges
TEXT_PRIMARY = colors.HexColor("#1a1a18")
TEXT_MUTED = colors.HexColor("#8b8981")
BG_PAGE = colors.HexColor("#f2f2f0")
BG_SURFACE = colors.HexColor("#eeedec")      # card bg / odd rows
BG_STRIPE = colors.HexColor("#f3f2f1")
BORDER = colors.HexColor("#d2ccbd")

# Truth-protocol semantic colors
BADGE_VERIFIED_BG = colors.HexColor("#e6f4ea")
BADGE_VERIFIED_FG = colors.HexColor("#1e7e34")
BADGE_CUSTOM_BG = colors.HexColor("#fff4e5")
BADGE_CUSTOM_FG = colors.HexColor("#b06a00")
BADGE_ASSUMPTION_BG = colors.HexColor("#eef1f6")
BADGE_ASSUMPTION_FG = colors.HexColor("#3a5a8a")

# ---------------------------------------------------------------------------
# Page geometry
# ---------------------------------------------------------------------------
PAGE_W, PAGE_H = A4
LEFT_M = RIGHT_M = 2.0 * cm
TOP_M = 2.2 * cm
BOTTOM_M = 2.0 * cm
CONTENT_W = PAGE_W - LEFT_M - RIGHT_M

# ---------------------------------------------------------------------------
# Styles
# ---------------------------------------------------------------------------
BODY_FONT = "TimesNewRoman"
BODY_FONT_B = "TimesNewRoman-Bold"
HEAD_FONT = "Calibri"
HEAD_FONT_B = "Calibri-Bold"
MONO_FONT = "Consolas"

ss = getSampleStyleSheet()

style_body = ParagraphStyle(
    "Body", parent=ss["Normal"], fontName=BODY_FONT, fontSize=10.5,
    leading=15.5, alignment=TA_JUSTIFY, textColor=TEXT_PRIMARY,
    spaceAfter=6,
)
style_body_left = ParagraphStyle("BodyLeft", parent=style_body, alignment=TA_LEFT)
style_bullet = ParagraphStyle(
    "Bullet", parent=style_body, leftIndent=16, bulletIndent=4, spaceAfter=3,
    alignment=TA_LEFT,
)
style_callout = ParagraphStyle(
    "Callout", parent=style_body, fontSize=9.5, leading=14,
    leftIndent=10, rightIndent=6, textColor=TEXT_PRIMARY, alignment=TA_LEFT,
)
style_h1 = ParagraphStyle(
    "H1", fontName=HEAD_FONT_B, fontSize=20, leading=26, textColor=ACCENT_DARK,
    spaceBefore=10, spaceAfter=4, alignment=TA_LEFT,
)
style_h1_kicker = ParagraphStyle(
    "H1Kicker", fontName=HEAD_FONT_B, fontSize=9, leading=12,
    textColor=ACCENT, alignment=TA_LEFT, spaceAfter=2,
)
style_h2 = ParagraphStyle(
    "H2", fontName=HEAD_FONT_B, fontSize=14, leading=19, textColor=ACCENT_DARK,
    spaceBefore=14, spaceAfter=5, alignment=TA_LEFT,
)
style_h3 = ParagraphStyle(
    "H3", fontName=HEAD_FONT_B, fontSize=11.5, leading=16, textColor=TEXT_PRIMARY,
    spaceBefore=10, spaceAfter=3, alignment=TA_LEFT,
)
style_kicker = ParagraphStyle(
    "Kicker", fontName=HEAD_FONT_B, fontSize=8.5, leading=11,
    textColor=TEXT_MUTED, alignment=TA_LEFT, spaceAfter=2,
)
style_caption = ParagraphStyle(
    "Caption", fontName=BODY_FONT, fontSize=8.5, leading=11,
    textColor=TEXT_MUTED, alignment=TA_CENTER, spaceBefore=3, spaceAfter=10,
)
style_table_h = ParagraphStyle(
    "TblH", fontName=HEAD_FONT_B, fontSize=9.5, leading=12,
    textColor=colors.white, alignment=TA_LEFT,
)
style_table_h_c = ParagraphStyle("TblHC", parent=style_table_h, alignment=TA_CENTER)
style_table = ParagraphStyle(
    "Tbl", fontName=BODY_FONT, fontSize=9, leading=12.5,
    textColor=TEXT_PRIMARY, alignment=TA_LEFT,
)
style_table_c = ParagraphStyle("TblC", parent=style_table, alignment=TA_CENTER)
style_mono = ParagraphStyle(
    "Mono", fontName=MONO_FONT, fontSize=8.5, leading=12, textColor=TEXT_PRIMARY,
    leftIndent=8, alignment=TA_LEFT,
)
style_quote = ParagraphStyle(
    "Quote", parent=style_body, fontName="TimesNewRoman-Italic",
    leftIndent=18, rightIndent=12, textColor=TEXT_MUTED,
    borderColor=ACCENT, borderWidth=0, spaceBefore=4, spaceAfter=8,
)

# TOC level styles
toc_l0 = ParagraphStyle("TOC0", fontName=HEAD_FONT_B, fontSize=11, leading=16,
                        leftIndent=0, textColor=ACCENT_DARK, spaceBefore=4)
toc_l1 = ParagraphStyle("TOC1", fontName=BODY_FONT, fontSize=10, leading=14,
                        leftIndent=18, textColor=TEXT_PRIMARY)
toc_l2 = ParagraphStyle("TOC2", fontName=BODY_FONT, fontSize=9.5, leading=13,
                        leftIndent=34, textColor=TEXT_MUTED)

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
_bookmark_seq = 0


def _key(text):
    global _bookmark_seq
    _bookmark_seq += 1
    return "h_%s" % hashlib.md5((text + str(_bookmark_seq)).encode()).hexdigest()[:10]


def h1(text, story, level=0, kicker=None):
    """Major heading. Adds optional kicker line, accent rule, TOC bookmark."""
    key = _key(text)
    flow = []
    if kicker:
        flow.append(Paragraph(kicker.upper(), style_h1_kicker))
    p = Paragraph('<a name="%s"/>%s' % (key, text), style_h1)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    flow.append(p)
    flow.append(HRFlowable(width="100%", thickness=1.2, color=ACCENT,
                           spaceBefore=2, spaceAfter=8))
    story.extend(flow)


def h2(text, story, level=1):
    key = _key(text)
    p = Paragraph('<a name="%s"/>%s' % (key, text), style_h2)
    p.bookmark_name = text
    p.bookmark_level = level
    p.bookmark_text = text
    p.bookmark_key = key
    story.append(CondPageBreak(60))
    story.append(p)


def h3(text, story):
    story.append(CondPageBreak(40))
    story.append(Paragraph(text, style_h3))


def para(text, story, style=None):
    story.append(Paragraph(text, style or style_body))


def bullets(items, story, style=None):
    st = style or style_bullet
    for it in items:
        story.append(Paragraph(it, st, bulletText="•"))


def numbered(items, story):
    for i, it in enumerate(items, 1):
        story.append(Paragraph(it, style_bullet, bulletText="%d." % i))


def spacer(h, story):
    story.append(Spacer(1, h))


def badge(text, kind="verified"):
    """Inline truth-protocol badge as a small table cell."""
    bg = {"verified": BADGE_VERIFIED_BG, "custom": BADGE_CUSTOM_BG,
          "assumption": BADGE_ASSUMPTION_BG}[kind]
    fg = {"verified": BADGE_VERIFIED_FG, "custom": BADGE_CUSTOM_FG,
          "assumption": BADGE_ASSUMPTION_FG}[kind]
    st = ParagraphStyle("badge", fontName=HEAD_FONT_B, fontSize=7.5, leading=10,
                        textColor=fg, alignment=TA_CENTER)
    t = Table([[Paragraph(text, st)]], colWidths=[None])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), bg),
        ("BOX", (0, 0), (-1, -1), 0.5, fg),
        ("TOPPADDING", (0, 0), (-1, -1), 2),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 2),
        ("LEFTPADDING", (0, 0), (-1, -1), 4),
        ("RIGHTPADDING", (0, 0), (-1, -1), 4),
    ]))
    return t


def module_status_row(status, module_hint, story):
    """A one-row status banner at the top of a step."""
    kind = {"VERIFIED": "verified", "CUSTOM DEVELOPMENT": "custom",
            "ASSUMPTION": "assumption", "ARCHITECTURAL RECOMMENDATION": "custom"}[status]
    label = Paragraph("<b>Module status</b>", style_kicker)
    cell_status = badge(status, kind)
    cell_hint = Paragraph(module_hint, style_callout)
    t = Table([[label, cell_status, cell_hint]],
              colWidths=[CONTENT_W * 0.16, CONTENT_W * 0.26, CONTENT_W * 0.58])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BG_STRIPE),
        ("BOX", (0, 0), (-1, -1), 0.4, BORDER),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
        ("LEFTPADDING", (0, 0), (-1, -1), 8),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(t)
    spacer(8, story)


def std_table(header, rows, col_ratios, caption=None, header_align="left"):
    """Build a standard styled table with Paragraph cells."""
    hstyle = style_table_h_c if header_align == "center" else style_table_h
    data = [[Paragraph(c, hstyle) for c in header]]
    for row in rows:
        data.append([Paragraph(str(c), style_table) for c in row])
    col_widths = [r * CONTENT_W for r in col_ratios]
    t = Table(data, colWidths=col_widths, hAlign="CENTER", repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    for i in range(1, len(data)):
        bg = colors.white if i % 2 == 1 else BG_SURFACE
        style.append(("BACKGROUND", (0, i), (-1, i), bg))
    t.setStyle(TableStyle(style))
    return t


def section_meta_table(rows, story):
    """Two-column metadata table (Field | Value) for step header blocks."""
    data = [[Paragraph("<b>Attribute</b>", style_table_h),
             Paragraph("<b>Value</b>", style_table_h)]]
    for k, v in rows:
        data.append([Paragraph(k, style_table), Paragraph(v, style_table)])
    t = Table(data, colWidths=[CONTENT_W * 0.28, CONTENT_W * 0.72],
              hAlign="CENTER", repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT_DARK),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    for i in range(1, len(data)):
        bg = colors.white if i % 2 == 1 else BG_SURFACE
        style.append(("BACKGROUND", (0, i), (-1, i), bg))
    t.setStyle(TableStyle(style))
    story.append(t)
    spacer(8, story)


def callout(title, body_html, story, kind="info"):
    """Side-bordered callout box."""
    color_map = {"info": ACCENT, "warn": colors.HexColor("#b06a00"),
                 "reg": ACCENT_DARK, "custom": BADGE_CUSTOM_FG}
    bar = color_map.get(kind, ACCENT)
    title_st = ParagraphStyle("coT", fontName=HEAD_FONT_B, fontSize=9.5,
                              leading=12, textColor=bar, spaceAfter=3)
    inner = [Paragraph(title.upper(), title_st),
             Paragraph(body_html, style_callout)]
    t = Table([[inner]], colWidths=[CONTENT_W])
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, -1), BG_STRIPE),
        ("LINEBEFORE", (0, 0), (0, -1), 3, bar),
        ("BOX", (0, 0), (-1, -1), 0.3, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 10),
        ("RIGHTPADDING", (0, 0), (-1, -1), 8),
        ("TOPPADDING", (0, 0), (-1, -1), 6),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 6),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
    ]))
    story.append(t)
    spacer(8, story)


def reg_callout(text, story):
    """Regulatory citation callout."""
    callout("Regulatory note", text, story, kind="reg")


def verified_note(text, story):
    callout("Verified against codebase", text, story, kind="info")


def custom_note(text, story):
    callout("Custom development / not in codebase", text, story, kind="custom")


def two_col_kv(rows, story, ratios=(0.30, 0.70)):
    """Field-by-field explanation table: Field | Explanation."""
    data = [[Paragraph("<b>Field</b>", style_table_h),
             Paragraph("<b>Explanation</b>", style_table_h)]]
    for k, v in rows:
        data.append([Paragraph(k, style_table), Paragraph(v, style_table)])
    cw = [r * CONTENT_W for r in ratios]
    t = Table(data, colWidths=cw, hAlign="CENTER", repeatRows=1)
    style = [
        ("BACKGROUND", (0, 0), (-1, 0), ACCENT),
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("GRID", (0, 0), (-1, -1), 0.4, BORDER),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
        ("RIGHTPADDING", (0, 0), (-1, -1), 6),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
    ]
    for i in range(1, len(data)):
        bg = colors.white if i % 2 == 1 else BG_SURFACE
        style.append(("BACKGROUND", (0, i), (-1, i), bg))
    t.setStyle(TableStyle(style))
    story.append(t)
    spacer(8, story)


# ---------------------------------------------------------------------------
# Doc template with TOC + running header/footer
# ---------------------------------------------------------------------------
class GuideDocTemplate(SimpleDocTemplate):
    def afterFlowable(self, flowable):
        if hasattr(flowable, "bookmark_name"):
            level = getattr(flowable, "bookmark_level", 0)
            text = getattr(flowable, "bookmark_text", "")
            key = getattr(flowable, "bookmark_key", "")
            self.notify("TOCEntry", (level, text, self.page, key))


def _header_footer(canvas, doc):
    canvas.saveState()
    # Header
    canvas.setFont(BODY_FONT, 7.5)
    canvas.setFillColor(TEXT_MUTED)
    canvas.drawString(LEFT_M, PAGE_H - 1.3 * cm,
                      "Life Sciences Suite — Implementation & Operational Guide")
    canvas.drawRightString(PAGE_W - RIGHT_M, PAGE_H - 1.3 * cm,
                           "Foundation (Volume 0–1)")
    canvas.setStrokeColor(BORDER)
    canvas.setLineWidth(0.4)
    canvas.line(LEFT_M, PAGE_H - 1.5 * cm, PAGE_W - RIGHT_M, PAGE_H - 1.5 * cm)
    # Footer
    canvas.drawString(LEFT_M, 1.2 * cm, "Odoo 19 Community · AGPL-3 · v1.0 (Draft)")
    canvas.drawRightString(PAGE_W - RIGHT_M, 1.2 * cm, "Page %d" % doc.page)
    canvas.line(LEFT_M, 1.5 * cm, PAGE_W - RIGHT_M, 1.5 * cm)
    canvas.restoreState()


# ---------------------------------------------------------------------------
# COVER (separate HTML/Playwright per brief; here a clean ReportLab cover page
# is used as fallback because Playwright is not installed in this environment.
# The cover is deliberately restrained: title block + meta, no decoration.)
# ---------------------------------------------------------------------------
def build_cover(story):
    spacer(4.0 * cm, story)
    kicker = ParagraphStyle("ck", fontName=HEAD_FONT_B, fontSize=10, leading=14,
                            textColor=ACCENT, alignment=TA_LEFT, spaceAfter=6)
    title = ParagraphStyle("ct", fontName=HEAD_FONT_B, fontSize=30, leading=36,
                           textColor=ACCENT_DARK, alignment=TA_LEFT, spaceAfter=8)
    subtitle = ParagraphStyle("cst", fontName=BODY_FONT, fontSize=14, leading=20,
                              textColor=TEXT_PRIMARY, alignment=TA_LEFT, spaceAfter=20)
    meta = ParagraphStyle("cm", fontName=BODY_FONT, fontSize=10, leading=15,
                          textColor=TEXT_MUTED, alignment=TA_LEFT)
    story.append(Paragraph("IMPLEMENTATION & OPERATIONAL GUIDE", kicker))
    story.append(HRFlowable(width="35%", thickness=2, color=ACCENT,
                            spaceBefore=0, spaceAfter=14, hAlign="LEFT"))
    story.append(Paragraph("Life Sciences Suite", title))
    story.append(Paragraph("Foundation — Volume 0 & Volume 1", subtitle))
    story.append(Paragraph(
        "A greenfield implementation and validation guide for the complete "
        "Life Sciences Suite running on <b>Odoo 19 Community Edition</b>, "
        "covering pharmaceutical, medical device, medical plastics, cosmetics "
        "and laboratory operations under GMP, ISO and regulatory frameworks.",
        style_body_left))
    spacer(1.2 * cm, story)
    rows = [
        ["Document", "Foundation (Volume 0 + Volume 1)"],
        ["Edition", "1.0 (Draft for review)"],
        ["Date", "August 2026"],
        ["Platform", "Odoo 19.0 Community Edition · PostgreSQL 16 · Docker"],
        ["License", "LGPLv3 (Odoo Community) · AGPL-3 (OCA & Life Sciences modules)"],
        ["Classification", "Confidential — Enterprise Architecture Document"],
        ["Truth protocol", "VERIFIED / ASSUMPTION / ARCHITECTURAL RECOMMENDATION / CUSTOM DEVELOPMENT"],
    ]
    data = [[Paragraph("<b>%s</b>" % k, style_table), Paragraph(v, style_table)]
            for k, v in rows]
    t = Table(data, colWidths=[CONTENT_W * 0.25, CONTENT_W * 0.75], hAlign="LEFT")
    t.setStyle(TableStyle([
        ("VALIGN", (0, 0), (-1, -1), "TOP"),
        ("LINEBELOW", (0, 0), (-1, -1), 0.3, BORDER),
        ("LINEABOVE", (0, 0), (-1, 0), 0.6, ACCENT),
        ("TOPPADDING", (0, 0), (-1, -1), 5),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 5),
        ("LEFTPADDING", (0, 0), (-1, -1), 0),
    ]))
    story.append(t)
    spacer(1.5 * cm, story)
    story.append(HRFlowable(width="100%", thickness=0.6, color=BORDER,
                            spaceBefore=0, spaceAfter=6))
    story.append(Paragraph(
        "This document is not a substitute for regulatory or legal advice. "
        "Software alone does not guarantee regulatory compliance. See the "
        "Truth Protocol and Regulatory Disclaimer in Volume 0.",
        ParagraphStyle("disc", fontName="TimesNewRoman-Italic", fontSize=8.5,
                       leading=12, textColor=TEXT_MUTED, alignment=TA_LEFT)))
    story.append(PageBreak())


# ===========================================================================
# CONTENT
# ===========================================================================
story = []

# ---- COVER ----------------------------------------------------------------
build_cover(story)

# ---- TABLE OF CONTENTS ----------------------------------------------------
toc_title = ParagraphStyle("tocT", fontName=HEAD_FONT_B, fontSize=22, leading=28,
                           textColor=ACCENT_DARK, spaceAfter=4)
toc_kicker = ParagraphStyle("tocK", fontName=HEAD_FONT_B, fontSize=9,
                            textColor=ACCENT, spaceAfter=2)
story.append(Paragraph("NAVIGATION", toc_kicker))
story.append(Paragraph("Table of Contents", toc_title))
story.append(HRFlowable(width="100%", thickness=1.2, color=ACCENT,
                        spaceBefore=2, spaceAfter=14))
toc = TableOfContents()
toc.levelStyles = [toc_l0, toc_l1, toc_l2]
story.append(toc)
story.append(PageBreak())


# ===========================================================================
# VOLUME 0 — FRONT MATTER
# ===========================================================================
h1("Volume 0 — Front Matter & How to Use This Guide", story, kicker="Volume 0")

h2("0.1 Document Purpose", story)
para(
    "This guide is the operational and validation reference for the Life Sciences "
    "Suite, an ERP solution built on <b>Odoo 19 Community Edition</b> for "
    "organisations operating in pharmaceutical manufacturing, medical devices, "
    "medical plastics, cosmetics and laboratories. It is written so that a new "
    "company can configure the system from an empty database through to "
    "commercial production, in the correct chronological order, without skipping "
    "mandatory prerequisites.", story)
para(
    "The guide targets ERP consultants, system integrators, validation teams, "
    "QA departments, regulatory affairs, auditors, IT departments and production "
    "managers. It is structured to be comparable in quality and depth to "
    "validated pharmaceutical ERP implementation documentation produced by major "
    "consulting and software houses.", story)

h2("0.2 Source of Truth", story)
para("The primary references for this guide are, in order of precedence:", story)
numbered([
    "<b>The supplied Life Sciences Suite Functional Specification</b> "
    "(v1.0, July 2026) — the authoritative functional reference.",
    "<b>The supplied Life Sciences Suite Architecture document</b> — the "
    "four-layer architecture model (Native Odoo → OCA → Life Sciences Core → "
    "Industry).",
    "<b>The actual codebase</b> under <font name='Consolas'>addons/</font> in "
    "the project root — module manifests, models, security files, record rules "
    "and demo data. Where the code differs from a summary, the code is truth.",
    "<b>Odoo 19 Community</b> documentation and the <b>OCA</b> official "
    "repositories at <font name='Consolas'>https://github.com/OCA</font>.",
    "<b>Official regulations only</b> — cited inline wherever a regulatory "
    "claim is made.",
], story)

verified_note(
    "The codebase at <font name='Consolas'>D:\\Docker\\odoo19Claude_ls-docker</font> "
    "contains 442 addon folders. Of these, <b>17 Life Sciences Core modules</b> "
    "(<font name='Consolas'>ls_*</font>) and <b>1 Industry module</b> "
    "(<font name='Consolas'>ls_pharma</font>) are present with complete manifests, "
    "security files, record rules, views, reports, wizards, demo data and cron "
    "jobs at version <font name='Consolas'>19.0.1.0.0</font>. Four industry "
    "modules specified in the Functional Specification are <b>not present</b> in "
    "the codebase: <font name='Consolas'>ls_medical_device</font>, "
    "<font name='Consolas'>ls_medical_plastics</font>, "
    "<font name='Consolas'>ls_cosmetics</font> and "
    "<font name='Consolas'>ls_lab</font>. These are documented as Architectural "
    "Recommendations / Custom Development.", story)

h2("0.3 Truth Protocol (Mandatory)", story)
para(
    "This guide obeys a strict truth protocol. Nothing is invented. No regulation, "
    "ISO clause, FDA requirement, ANPP requirement, WHO GMP requirement or Odoo "
    "feature is fabricated. Where information cannot be verified, the guide writes "
    "exactly:", story)
story.append(Paragraph(
    '<i>"This information could not be verified from official documentation."</i>',
    style_quote))
para("Every statement is labelled with one of four provenance tags:", story)
two_col_kv([
    ("VERIFIED",
     "Confirmed against the codebase (module manifests, model source, security "
     "files) or against an official regulation cited inline. Installable and "
     "operational as described."),
    ("ASSUMPTION",
     "A reasonable inference not contradicting any verified source, but not "
     "directly confirmed. Treat as a starting point for validation, not as fact."),
    ("ARCHITECTURAL RECOMMENDATION",
     "A design proposal from the Functional Specification or this guide that has "
     "no corresponding installed module. Describes intent and target state, not "
     "current capability."),
    ("CUSTOM DEVELOPMENT",
     "Functionality specified but absent from the codebase. Must be designed, "
     "built, validated and maintained before it can be used in a regulated "
     "environment."),
], story)
para(
    "Every regulatory statement indicates its source. If a statement cannot be "
    "mapped to an official regulation it is never presented as mandatory.", story)

h2("0.4 Regulatory Disclaimer", story)
callout(
    "Compliance is not a software property",
    "The Life Sciences Suite is designed to support the implementation of "
    "processes aligned with applicable regulatory frameworks. Software alone "
    "does not guarantee regulatory compliance. Compliance depends on "
    "organisational procedures and policies, system validation (per FDA 21 CFR "
    "Part 11, EU GMP Annex 11, or applicable guidance), staff training and "
    "competency, the quality management system, and ongoing monitoring and "
    "continuous improvement. <b>No module in this suite is certified as "
    "&#8220;compliant&#8221; with any regulatory framework unless explicitly stated "
    "with verified evidence from the relevant regulatory authority.</b> The "
    "regulatory mappings in this guide indicate which processes a module "
    "<i>supports</i>; they do not imply certification.",
    story, kind="reg")
para(
    "Specific verification gaps acknowledged in this guide include: precise ANPP "
    "(Algeria) clause numbers, the full Odoo 19 Community module manifest set, "
    "and the feature sets of certain OCA repositories. Where such gaps exist, "
    "the guide states <i>&#8220;This information could not be verified from "
    "official documentation.&#8221;</i> rather than inventing detail.", story)

h2("0.5 Regulatory Frameworks Referenced", story)
para(
    "Where applicable, implementation steps are mapped to the following official "
    "frameworks. Only clauses that can be verified are cited. The list reflects "
    "the Functional Specification §3.1.", story)
std_table(
    ["Framework", "Applicability", "Key focus areas"],
    [
        ["ANPP Requirements (Algeria)", "Pharmaceuticals",
         "Manufacturing authorisation, GMP compliance, CTD dossier submission, "
         "product traceability, packaging compliance"],
        ["Algerian GMP (BPF)", "Pharmaceuticals",
         "Good manufacturing practices recognised by ANPP"],
        ["WHO GMP Guidance", "Pharmaceuticals", "WHO GMP guidelines"],
        ["EU GMP (incl. Annex 1, 11, 15)", "Pharmaceuticals",
         "Sterile manufacture, computerised systems, qualification & validation"],
        ["FDA 21 CFR Part 11", "All (US)", "Electronic records & signatures, audit trails"],
        ["FDA 21 CFR Part 210 / 211", "Pharmaceuticals",
         "cGMP for finished pharmaceuticals"],
        ["FDA 21 CFR Part 820", "Medical devices", "Quality system regulation"],
        ["ISO 9001:2015", "All industries", "Quality management systems"],
        ["ISO 13485:2016", "Medical devices", "QMS for medical devices"],
        ["ISO 14971:2019", "Medical devices", "Risk management"],
        ["ISO 15378:2017", "Medical plastics", "GMP for primary packaging materials"],
        ["ISO 22716:2007", "Cosmetics", "GMP guidelines for cosmetics"],
        ["ICH Q7 / Q9", "Pharmaceuticals", "GMP for APIs; quality risk management"],
        ["GS1 Standards", "All", "Barcoding, serialization, traceability"],
        ["EU MDR 2017/745", "Medical devices", "Medical Device Regulation"],
        ["EU Cosmetics Regulation 1223/2009", "Cosmetics", "Cosmetic product regulation"],
    ],
    col_ratios=[0.30, 0.20, 0.50])
story.append(Paragraph(
    "Table 0.1 — Regulatory frameworks referenced in this guide (Functional "
    "Specification §3.1). S = the suite supports implementation of processes "
    "aligned with the framework; it does not imply certification.", style_caption))

h2("0.6 How This Guide Is Structured", story)
para(
    "The guide follows a realistic greenfield pharmaceutical implementation "
    "sequence. The full work is delivered in volumes; this Foundation document "
    "contains Volume 0 (front matter) and Volume 1 (platform foundation, Steps "
    "1–7). Each implementation step uses a consistent section template:", story)
std_table(
    ["#", "Section", "Purpose"],
    [
        ["1–5", "Identity, objective, context, rationale, regulatory context",
         "Establish <i>what</i> the step does and <i>why</i> it is required."],
        ["6–7", "Applicable industries, required modules",
         "Scope and the Native / OCA / Life Sciences modules involved, with "
         "module-status badges."],
        ["8–13", "Dependencies, prerequisites, actors, roles, master data",
         "What must exist beforehand and who performs the step."],
        ["14–18", "Menus, navigation, configuration, field-by-field, rules",
         "Operational detail: where to click, what each field means, business rules."],
        ["19–25", "Workflow, states, approvals, signatures, audit, notifications",
         "How records move through their lifecycle and how they are controlled."],
        ["26–32", "Documents, records, reports, KPIs, dashboards, integration, data model",
         "Outputs, measurement, and technical integration."],
        ["33–38", "Security groups, record rules, access rights, validation/blocking rules",
         "How the step is secured and constrained."],
        ["39–46", "Mistakes, best practices, risk, failure modes, CAPA, change control, deviation",
         "Quality and risk dimensions."],
        ["47–54", "Testing, UAT, IQ/OQ/PQ, CSV, evidence, inspection evidence",
         "Validation evidence for the step."],
        ["55–57", "Backup, disaster recovery, references",
         "Continuity and source citations."],
    ],
    col_ratios=[0.10, 0.40, 0.50])
story.append(Paragraph(
    "Table 0.2 — Section template applied to each implementation step (condensed "
    "from the 57-section master template).", style_caption))

h2("0.7 Two-Tier Treatment", story)
para(
    "A literal application of all sections to every step would produce repetitive "
    "material of little operational value. This guide therefore uses two tiers:", story)
bullets([
    "<b>Tier A — Master Configuration Steps</b> (the steps in the implementation "
    "order) receive the full section treatment wherever the section is "
    "meaningful. Sections that genuinely do not apply (for example "
    "&#8220;Generated Documents&#8221; for the Users step) are explicitly marked "
    "N/A rather than padded.",
    "<b>Tier B — Cross-Cutting Reference</b> topics (FDA 21 CFR Part 11 controls, "
    "ALCOA+ data integrity, GS1 serialization, integration architecture, CSV "
    "strategy) are covered once, comprehensively, in dedicated reference volumes "
    "and cross-referenced from individual steps.",
], story)

h2("0.8 Edition & Revision Control", story)
two_col_kv([
    ("Document version", "1.0 (Draft for review)"),
    ("Issued", "August 2026"),
    ("Supersedes", "None (initial issue)"),
    ("Next review", "Upon completion of validation activities or material "
                    "change to the configured system"),
    ("Owner", "Life Sciences Suite Architecture Team"),
    ("Change control", "Material changes to this guide are themselves subject "
                       "to change control (see Volume 2, Step 15) once the QMS "
                       "is operational."),
], story)

story.append(PageBreak())


# ===========================================================================
# VOLUME 1 — FOUNDATION & ARCHITECTURE
# ===========================================================================
h1("Volume 1 — Foundation & Architecture", story, kicker="Volume 1")
para(
    "Volume 1 establishes the platform on which every subsequent module depends. "
    "It begins with an empty database and proceeds through native and OCA module "
    "baseline, company/site/location topology, users, the security architecture, "
    "and the two cross-cutting controls — electronic signatures and audit trail — "
    "that every later GxP record relies upon. No step in Volume 2 or beyond may "
    "be started before the corresponding prerequisite in this volume is complete.",
    story)

# ---- Architecture overview ------------------------------------------------
h2("1.1 Four-Layer Architecture", story)
para(
    "The Life Sciences Suite is organised in four layers, each building on the "
    "one below. This model is taken from the supplied Architecture document and "
    "is confirmed by the module manifests in the codebase.", story)
std_table(
    ["Layer", "Description", "Verified example (codebase)"],
    [
        ["Layer 1 — Native Odoo 19",
         "Core Odoo Community modules (base, sale, purchase, stock, mrp, "
         "account, hr, project, maintenance). Foundation ERP capability.",
         "Present (Odoo 19 image, <font name='Consolas'>odoo:19</font>)"],
        ["Layer 2 — OCA",
         "Odoo Community Association modules extending manufacturing, logistics, "
         "quality, audit logging and workflow.",
         "<font name='Consolas'>mgmtsystem</font>, <font name='Consolas'>document_page</font>, "
         "<font name='Consolas'>quality_control_oca</font>, <font name='Consolas'>auditlog</font>"],
        ["Layer 3 — Life Sciences Core",
         "Custom QMS / GxP modules: QMS, CAPA, deviations, change control, "
         "document management, training, validation, calibration, supplier "
         "qualification, complaint, recall, e-signatures, audit trail, risk, "
         "environmental monitoring.",
         "<font name='Consolas'>ls_qms</font>, <font name='Consolas'>ls_capa</font>, "
         "<font name='Consolas'>ls_audit_trail</font> (17 present)"],
        ["Layer 4 — Industry",
         "Sector-specific extensions: pharmaceutical, medical device, medical "
         "plastics, cosmetics, laboratory.",
         "<font name='Consolas'>ls_pharma</font> present; "
         "<font name='Consolas'>ls_medical_device</font>, "
         "<font name='Consolas'>ls_medical_plastics</font>, "
         "<font name='Consolas'>ls_cosmetics</font>, "
         "<font name='Consolas'>ls_lab</font> NOT present"],
    ],
    col_ratios=[0.20, 0.45, 0.35])
story.append(Paragraph(
    "Table 1.1 — Four-layer architecture, verified against the codebase.", style_caption))

h2("1.2 Deployment Topology", story)
verified_note(
    "The project ships as a Docker Compose stack: an <font name='Consolas'>odoo:19</font> "
    "application container built from a local Dockerfile, a "
    "<font name='Consolas'>postgres:16</font> database container with a healthcheck, "
    "and named volumes for the configuration, addons, Odoo filestore and logs. "
    "The application listens internally on port 8069 and is published on host "
    "port 8071. Addons under <font name='Consolas'>./addons</font> are mounted at "
    "<font name='Consolas'>/mnt/extra-addons</font> and declared via "
    "<font name='Consolas'>addons_path</font> in <font name='Consolas'>odoo.conf</font>.",
    story)
two_col_kv([
    ("Database", "PostgreSQL 16 (container <font name='Consolas'>odoo19Claude_ls-db</font>)"),
    ("Application", "Odoo 19 Community (container <font name='Consolas'>odoo19Claude_ls</font>)"),
    ("Host port", "8071 → container 8069"),
    ("Addons path", "<font name='Consolas'>/mnt/extra-addons</font> (mounted from <font name='Consolas'>./addons</font>)"),
    ("Master password", "Stored as a PBKDF2-SHA512 hash in <font name='Consolas'>config/odoo.conf</font>"),
    ("Filestore", "<font name='Consolas'>./odoo-data</font> (mounted at <font name='Consolas'>/var/lib/odoo</font>)"),
    ("Logs", "<font name='Consolas'>./logs</font> (mounted at <font name='Consolas'>/var/log/odoo</font>)"),
], story)

reg_callout(
    "For a GxP system, the deployment topology itself is part of the validated "
    "state. The Infrastructure Qualification (IQ) for the platform — containers, "
    "database, network, backups — must be documented and version-controlled "
    "before any application-level validation begins. This is addressed in Step 1.",
    story)


# ===========================================================================
# STEP 1 — Empty-database initialization
# ===========================================================================
story.append(PageBreak())
h1("Step 1 — Empty-Database Initialization", story, kicker="Step 1 · Tier A")
module_status_row("VERIFIED",
                  "Native Odoo platform (no custom module). Verified against "
                  "<font name='Consolas'>docker-compose.yml</font>, "
                  "<font name='Consolas'>Dockerfile</font> and "
                  "<font name='Consolas'>config/odoo.conf</font>.", story)

h2("1. Business Objective", story)
para(
    "Bring the application and database containers online from a clean state and "
    "create the first (empty) Odoo database, so that all subsequent configuration "
    "has a known, reproducible starting point.", story)

h2("2. Business Context", story)
para(
    "The ERP starts with an empty database. Nothing exists. This step is the "
    "single source of truth for the platform: every later step assumes the "
    "database created here. Skipping or improvising it (for example by cloning a "
    "demo database) makes the validated state unverifiable and must not be done "
    "in a regulated environment.", story)

h2("3. Why this step is required", story)
bullets([
    "Establishes a reproducible, traceable platform baseline.",
    "Records the exact Odoo, PostgreSQL and module versions that will enter "
    "validation.",
    "Produces the first evidence (database manager screen, installed module "
    "list) for the Installation Qualification (IQ) of the platform.",
    "Separates <b>infrastructure</b> qualification from <b>application</b> "
    "configuration, which is a GAMP 5 expectation for category 5 (custom) and "
    "category 4 (configured) software.",
], story)

h2("6. Regulatory Context", story)
reg_callout(
    "GAMP 5 (2nd ed.) recommends a risk-based, life-cycle approach to computerised "
    "system validation, beginning with a documented and reproducible installed "
    "system. EU GMP Annex 11 §4 (Validation) and Annex 15 (Qualification and "
    "Validation) require that the system be qualified before use. This step "
    "produces the platform-level qualification evidence; module-level IQ/OQ/PQ "
    "follow in later steps.", story)

h2("7. Applicable Industries", story)
para("All industries: Pharmaceutical, Medical Devices, Medical Plastics, "
     "Cosmetics, Laboratories.", story)

h2("8. Required Modules", story)
two_col_kv([
    ("Native Odoo", "<font name='Consolas'>base</font> (installed automatically with "
                    "the first database). No other module is required at this point."),
    ("OCA", "None."),
    ("Life Sciences", "None."),
], story)

h2("10. Prerequisites", story)
numbered([
    "Docker Engine and Docker Compose are installed on the host.",
    "Host ports 8071 (application) and 5432 (database, if exposed) are free.",
    "The project directory <font name='Consolas'>D:\\Docker\\odoo19Claude_ls-docker</font> "
    "is intact, with <font name='Consolas'>docker-compose.yml</font>, "
    "<font name='Consolas'>Dockerfile</font>, <font name='Consolas'>config/odoo.conf</font> "
    "and the <font name='Consolas'>addons/</font> tree.",
    "A backup destination for the PostgreSQL volume is identified (see §55).",
], story)

h2("11. Actors", story)
two_col_kv([
    ("Administrator", "Builds and starts the stack; creates the database."),
    ("IT / Infrastructure", "Owns the host, Docker, network and backups."),
    ("Validation", "Witnesses and records the platform IQ evidence."),
], story)

h2("16. Configuration Parameters", story)
para(
    "The platform is configured through three files. Their effective values, "
    "verified from the codebase, are:", story)
std_table(
    ["File", "Parameter", "Verified value", "Purpose"],
    [
        ["docker-compose.yml", "db image", "postgres:16", "Database engine"],
        ["docker-compose.yml", "db POSTGRES_USER", "odoo", "Database role"],
        ["docker-compose.yml", "odoo build", "odoo:19 (local Dockerfile)", "Application image"],
        ["docker-compose.yml", "odoo ports", "8071:8069", "Host → container port"],
        ["docker-compose.yml", "odoo volumes", "addons → /mnt/extra-addons", "Custom addons mount"],
        ["odoo.conf", "addons_path", "/mnt/extra-addons", "Where Odoo finds custom modules"],
        ["odoo.conf", "db_host / db_port", "db / 5432", "Database connection"],
        ["odoo.conf", "admin_passwd", "PBKDF2-SHA512 hash", "Database manager password"],
        ["odoo.conf", "list_db", "True", "Allow database listing (tighten for production)"],
        ["odoo.conf", "proxy_mode", "False", "Disable X-Forwarded-* handling (set True behind a reverse proxy)"],
    ],
    col_ratios=[0.16, 0.20, 0.30, 0.34])
story.append(Paragraph("Table 1.2 — Platform configuration, verified from the codebase.", style_caption))

callout("Production hardening (ARCHITECTURAL RECOMMENDATION)",
    "For a production GxP deployment, set <font name='Consolas'>list_db = False</font> "
    "(suppresses the database selector), terminate TLS at a reverse proxy and set "
    "<font name='Consolas'>proxy_mode = True</font>, restrict the database "
    "container to the application network only, and enable point-in-time backups "
    "for PostgreSQL. These are infrastructure decisions that must be captured in "
    "the platform IQ before validation sign-off.", story, kind="custom")

h2("19. Workflow", story)
para("The end-to-end sequence to bring the platform online and create the empty database:", story)
numbered([
    "<b>Build & start:</b> from the project root, run "
    "<font name='Consolas'>docker compose up -d --build</font>. The Postgres "
    "container becomes healthy; the Odoo container starts and waits for it.",
    "<b>Reach the database manager:</b> open "
    "<font name='Consolas'>http://<host>:8071/web/database/manager</font>.",
    "<b>Create the database:</b> choose <i>Create Database</i>, enter the "
    "database name, the master password (matching the hash in "
    "<font name='Consolas'>odoo.conf</font>), the administrator password, "
    "language and country. <b>Do not</b> load demo data for a validated system.",
    "<b>Confirm the baseline:</b> log in as admin; the installed module list "
    "contains only <font name='Consolas'>base</font>. This is the empty-database "
    "baseline.",
    "<b>Record evidence:</b> capture the database manager screen, the installed "
    "module list, the Odoo and PostgreSQL versions, and the image digests. "
    "These form the first IQ artefacts.",
], story)

h2("39. Common Mistakes", story)
bullets([
    "<b>Loading demo data</b> in a database intended for validation. Demo data "
    "pollutes master data and audit trails. Always create without demo data.",
    "<b>Cloning a dev database</b> into the validation environment. The provenance "
    "of every record must be traceable; clones break this.",
    "<b>Exposing <font name='Consolas'>list_db = True</font></b> in production — "
    "leaks the database list and the create/restore/delete controls.",
    "<b>Reusing the default admin password</b> from <font name='Consolas'>odoo.conf</font>. "
    "Rotate it immediately after database creation and record the rotation.",
], story)

h2("40. Best Practices", story)
bullets([
    "Tag the exact image digests in the IQ pack so the platform can be rebuilt "
    "byte-for-byte.",
    "Keep <font name='Consolas'>odoo.conf</font>, <font name='Consolas'>docker-compose.yml</font> "
    "and the Dockerfile under version control; treat changes as platform "
    "change-control events.",
    "Run the database and application clocks from the same NTP source. Timestamp "
    "integrity underpins every audit trail in the suite.",
], story)

h2("47–51. Testing & Validation (Platform IQ)", story)
para(
    "The platform Installation Qualification establishes that the system is "
    "installed correctly and is reproducible. The minimum evidence set:", story)
std_table(
    ["IQ Item", "Evidence", "Pass criterion"],
    [
        ["Containers running", "<font name='Consolas'>docker compose ps</font> output",
         "Both containers Up; db healthy"],
        ["Database reachable", "<font name='Consolas'>pg_isready -U odoo</font>",
         "Returns 'accepting connections'"],
        ["Application reachable", "HTTP 200 on /web/login",
         "Login page renders"],
        ["Empty baseline", "Installed modules list",
         "Only <font name='Consolas'>base</font> present"],
        ["Versions recorded", "Odoo & PostgreSQL version strings",
         "Recorded in IQ pack"],
        ["Clocks synchronised", "Container date output vs. NTP",
         "Drift < 1 s"],
    ],
    col_ratios=[0.26, 0.40, 0.34])
story.append(Paragraph("Table 1.3 — Platform IQ evidence set.", style_caption))

h2("55. Backup Strategy", story)
para(
    "Before any further configuration, establish the platform backup: a "
    "PostgreSQL logical backup (<font name='Consolas'>pg_dump</font>) of the "
    "fresh empty database plus a copy of the filestore and "
    "<font name='Consolas'>addons/</font> tree. This proves the restore path "
    "works while the system is trivially small. See Volume 6 for the full "
    "backup & disaster-recovery strategy.", story)

h2("57. References", story)
bullets([
    "Supplied Architecture document, §1–4.",
    "Supplied Functional Specification §4 (Architecture Overview), §5 (Native modules).",
    "<font name='Consolas'>docker-compose.yml</font>, <font name='Consolas'>Dockerfile</font>, "
    "<font name='Consolas'>config/odoo.conf</font> (codebase).",
    "GAMP 5, 2nd edition (ISPE) — life-cycle & risk-based validation.",
    "EU GMP Annex 11 §4 (Validation); Annex 15 (Qualification and Validation).",
], story)


# ===========================================================================
# STEP 2 — Native module baseline
# ===========================================================================
story.append(PageBreak())
h1("Step 2 — Native Module Baseline Install", story, kicker="Step 2 · Tier A")
module_status_row("VERIFIED",
                  "Native Odoo 19 Community modules. Dependency order per "
                  "Functional Specification §15.1.", story)

h2("1. Business Objective", story)
para(
    "Install the Layer 1 native modules in dependency order, so that the ERP "
    "foundation (sales, purchase, inventory, manufacturing, accounting, HR, "
    "projects, maintenance) is present and the OCA and Life Sciences layers can "
    "be installed on top.", story)

h2("3. Why this step is required", story)
para(
    "Every OCA and Life Sciences module depends on one or more native modules "
    "(see the dependency matrix, Functional Specification §15). Installing native "
    "modules out of order produces broken or partially-installed dependencies "
    "that surface later as obscure errors during validation.", story)

h2("8. Required Modules & Dependency Order", story)
para(
    "Install in this order, derived from Functional Specification §15.1:", story)
std_table(
    ["Order", "Module", "Depends on", "Life-sciences relevance"],
    [
        ["1", "<font name='Consolas'>base</font>", "—", "Mandatory foundation (already installed in Step 1)"],
        ["2", "<font name='Consolas'>product</font>", "base", "Materials, APIs, finished products"],
        ["3", "<font name='Consolas'>stock</font>", "base, product", "Raw materials, WIP, finished goods"],
        ["4", "<font name='Consolas'>mrp</font>", "base, product, stock", "Production planning & execution"],
        ["5", "<font name='Consolas'>quality</font>", "base, stock (mrp optional)", "QC inspections, quality alerts"],
        ["6", "<font name='Consolas'>purchase</font>", "base, product, account, stock", "Raw material & supplier management"],
        ["7", "<font name='Consolas'>sale</font>", "base, product, account, stock", "Customer order management"],
        ["8", "<font name='Consolas'>account</font>", "base, product", "Financial management"],
        ["9", "<font name='Consolas'>hr</font>", "base", "Personnel records (employees, departments)"],
        ["10", "<font name='Consolas'>project</font>", "base", "Validation projects, CAPA tasks"],
        ["11", "<font name='Consolas'>maintenance</font>", "base, hr", "Equipment records & maintenance"],
    ],
    col_ratios=[0.07, 0.16, 0.27, 0.50])
story.append(Paragraph(
    "Table 1.4 — Native module install order (Functional Specification §15.1).", style_caption))

verified_note(
    "The native <font name='Consolas'>quality</font> module folder is <b>not</b> "
    "present in the project <font name='Consolas'>addons/</font> tree; it is part "
    "of the Odoo 19 Community core image and is installed from there. The OCA "
    "module <font name='Consolas'>quality_control_oca</font> is present in "
    "<font name='Consolas'>addons/</font> and is addressed in the OCA selection "
    "chapter (§1.3).", story)

h2("14. Menus & 15. Navigation", story)
para(
    "After installation, the main menu gains the installed applications. From "
    "<font name='Consolas'>Apps</font> → search the technical name → click "
    "<i>Install</i>. Confirm each install completes without warnings in "
    "<font name='Consolas'>Settings → Technical → Modules</font>.", story)

h2("18. Business Rules", story)
bullets([
    "Install <font name='Consolas'>account</font> before <font name='Consolas'>sale</font> "
    "and <font name='Consolas'>purchase</font> — both depend on it.",
    "Install <font name='Consolas'>hr</font> before "
    "<font name='Consolas'>maintenance</font> — maintenance equipment references "
    "employees and departments.",
    "Do not install <font name='Consolas'>mrp</font> before "
    "<font name='Consolas'>stock</font>.",
], story)

h2("39. Common Mistakes", story)
bullets([
    "Installing all native modules at once via the Apps menu without checking "
    "dependencies — leads to partial installs.",
    "Installing Enterprise-only modules (<font name='Consolas'>documents</font>, "
    "<font name='Consolas'>approvals</font>, AI features) which are <b>not</b> "
    "available in Community Edition. The Functional Specification §5.1 notes "
    "these are Enterprise-only.",
], story)

h2("47–51. Testing & Validation", story)
para(
    "For each native module, capture: install timestamp, version, and a smoke "
    "test (open the module's main menu, create one record of the primary model, "
    "delete it). This is the module-level IQ foundation that the OCA and Life "
    "Sciences layers inherit.", story)

h2("57. References", story)
bullets([
    "Functional Specification §5 (Native modules), §15.1 (Layer 1 dependency matrix).",
    "Odoo 19 Community documentation — module manifests and dependencies.",
], story)


# ===========================================================================
# 1.3 OCA Module Selection
# ===========================================================================
story.append(PageBreak())
h1("1.3 OCA Module Selection & Deployment", story, kicker="Chapter · Tier B reference", level=0)
para(
    "Layer 2 selects OCA modules that strengthen the platform where native Odoo "
    "Community is thin: management-system documentation, controlled pages, "
    "quality control points, audit logging and maintenance extensions. This "
    "chapter inventories what is <b>verified present</b> in the codebase and "
    "recommends a baseline set. OCA modules are AGPL-3 unless otherwise noted.",
    story)

h2("Verified OCA families present", story)
verified_note(
    "The following OCA families are present under <font name='Consolas'>addons/</font> "
    "and are directly relevant to the Life Sciences Suite:", story)
std_table(
    ["OCA family / module", "Purpose", "Replaces / extends"],
    [
        ["mgmtsystem (+ action, audit, nonconformity, review, kpi, manual, "
         "quality, risk, hazard, etc.)",
         "ISO/IEC/BS management-system framework: actions, nonconformities, "
         "audits, management reviews, KPIs, manuals.",
         "Provides a standards-based backbone alongside the custom ls_* QMS."],
        ["document_page (+ access_group, approval, procedure, work_instruction, "
         "quality_manual, etc.)",
         "Controlled wiki-style pages with versioning, approval and access "
         "groups.",
         "Useful for quality manual, SOPs, work instructions pre- "
         "<font name='Consolas'>ls_document_management</font>."],
        ["quality_control_oca",
         "Quality control points, inspections and alerts (OCA equivalent of "
         "the native quality module).",
         "In-process QC inspections integrated with stock and mrp."],
        ["auditlog",
         "Generic field-level audit logging (rules per model).",
         "Complementary to <font name='Consolas'>ls_audit_trail</font>; see §1.6 "
         "Step 7 for the division of responsibility."],
        ["base_maintenance + maintenance_*",
         "Equipment categories, certifications, tags, maintenance plans, "
         "timesheets, request links to purchase/repair.",
         "Extends native maintenance for calibration & equipment "
         "qualification (Step 17, 24)."],
        ["helpdesk_mgmt (+ fieldservice, rating, activity)",
         "Helpdesk / ticket management.",
         "Possible front-end for complaint receipt (Step 31) if configured."],
    ],
    col_ratios=[0.30, 0.40, 0.30])
story.append(Paragraph(
    "Table 1.5 — OCA modules verified present and relevant to the suite.", style_caption))

h2("Recommended baseline", story)
para(
    "For a pharmaceutical greenfield, install the following OCA baseline before "
    "the Life Sciences Core layer. Each is justified and tagged:", story)
two_col_kv([
    ("mgmtsystem + mgmtsystem_nonconformity + mgmtsystem_action",
     "Provides the nonconformity / action backbone. The ls_capa module can "
     "integrate with or supersede this depending on configuration choice. "
     "<b>Decision required</b>: adopt OCA mgmtsystem as the QMS backbone, or "
     "the custom ls_qms/ls_capa. See Volume 2."),
    ("document_page + document_page_approval",
     "Controlled document pages with approval workflow. Useful for the Quality "
     "Manual and early SOPs while ls_document_management is being validated."),
    ("quality_control_oca",
     "In-process quality control points. Pairs with ls_pharma batch records "
     "(Step 26)."),
    ("base_maintenance + maintenance_plan + maintenance_equipment_certification",
     "Equipment and preventive-maintenance foundation for calibration "
     "(Step 17) and equipment qualification (Step 24)."),
    ("auditlog",
     "Generic audit log; retained as a defence-in-depth alongside "
     "ls_audit_trail (Step 7)."),
], story)

callout("Verification gap — ASSUMPTION",
    "The Functional Specification §6.7 states that the OCA module lists for "
    "<font name='Consolas'>account-analytic</font>, <font name='Consolas'>crm</font> "
    "and <font name='Consolas'>agreement</font> could not be fully verified from "
    "official documentation. Before relying on any OCA module in a validated "
    "process, confirm its manifest, license and Odoo 19 compatibility directly "
    "in the OCA repository.", story, kind="custom")

h2("57. References", story)
bullets([
    "Functional Specification §6 (OCA modules), §15.2 (Layer 2 dependency matrix).",
    "OCA repositories: <font name='Consolas'>https://github.com/OCA</font>.",
], story)


# ===========================================================================
# STEP 3 — Company / Sites / Locations
# ===========================================================================
story.append(PageBreak())
h1("Step 3 — Company, Sites, Plants, Buildings, Cleanrooms, Warehouses, Locations",
   story, kicker="Step 3 · Tier A")
module_status_row("VERIFIED",
                  "Native <font name='Consolas'>base</font> (res.company) and "
                  "<font name='Consolas'>stock</font> (stock.warehouse, "
                  "stock.location). Cleanroom grades are represented via location "
                  "structure and naming.", story)

h2("1. Business Objective", story)
para(
    "Model the physical and organisational topology of the company: legal "
    "entities, sites, plants, buildings, cleanrooms, warehouses and storage "
    "locations. This topology is the substrate for inventory, manufacturing, "
    "quality, environmental monitoring and traceability.", story)

h2("6. Regulatory Context", story)
reg_callout(
    "EU GMP Annex 1 (manufacture of sterile medicinal products) classifies "
    "cleanroom environments by grade (A/B/C/D). EU GMP Part I §3 (Premises) "
    "requires premises to be located, designed, constructed and maintained to "
    "suit the operations. The location hierarchy in Odoo is the system's "
    "representation of these premises and must correspond to the site master "
    "plan and environmental classification drawings.", story)

h2("16. Configuration Parameters & 17. Field-by-field", story)
para(
    "The topology is built from three native objects. Recommended mapping:", story)
std_table(
    ["Physical / organisational concept", "Odoo object", "Notes"],
    [
        ["Legal entity", "<font name='Consolas'>res.company</font>",
         "One per legal entity. Multi-company if applicable."],
        ["Site / Plant", "<font name='Consolas'>stock.warehouse</font>",
         "A warehouse represents a physical site/plant. One company may own several."],
        ["Building / area", "<font name='Consolas'>stock.location</font> (type: internal)",
         "Top-level internal locations under the warehouse."],
        ["Cleanroom (grade A/B/C/D)", "<font name='Consolas'>stock.location</font> (internal)",
         "Model each grade as a distinct location; encode the grade in the name "
         "(e.g. <font name='Consolas'>CR-3/Grade-B</font>)."],
        ["Storage location / bin", "<font name='Consolas'>stock.location</font> (internal)",
         "Leaf locations for quants."],
        ["Quarantine / hold", "<font name='Consolas'>stock.location</font> (internal, separate)",
         "Physically or logically segregated; used for QA hold, recall hold."],
        ["Supplier / customer / transit", "<font name='Consolas'>stock.location</font> (partner/transient)",
         "Native location types."],
    ],
    col_ratios=[0.32, 0.30, 0.38])
story.append(Paragraph("Table 1.6 — Topology mapping.", style_caption))

two_col_kv([
    ("res.company — name", "Legal entity name (e.g. the manufacturing company)."),
    ("res.company — currency", "Base currency; multi-currency configured in account."),
    ("res.company — parent_id", "Parent company, for group structure."),
    ("stock.warehouse — name / code", "Site/plant name and short code (e.g. PLT01)."),
    ("stock.warehouse — company_id", "Owning legal entity."),
    ("stock.location — name", "Location full name; encode building/grade/bin."),
    ("stock.location — location_id", "Parent location → builds the hierarchy."),
    ("stock.location — usage", "internal / view / supplier / customer / transient / inventory / production."),
    ("stock.location — company_id", "Owning company (for multi-company isolation)."),
    ("stock.location — active", "Archive (not delete) decommissioned locations to preserve history."),
], story)

h2("18. Business Rules", story)
bullets([
    "Cleanroom grades are represented by location, not by a dedicated model. "
    "Enforce a naming convention so environmental monitoring "
    "(<font name='Consolas'>ls_environmental_monitoring</font>, Step 19) can "
    "reference locations unambiguously.",
    "Quarantine locations must be segregated from released-goods locations to "
    "support batch hold/release (Step 28).",
    "Decommissioned premises are archived, never deleted — deletion destroys "
    "historical traceability.",
], story)

h2("40. Best Practices", story)
bullets([
    "Mirror the site master plan and classification drawings exactly; the "
    "location tree is the system's authoritative site model.",
    "Use view-type locations to group buildings/floors; keep stock quants only "
    "on leaf internal locations.",
    "Record the mapping (location → physical room → GMP grade) in a controlled "
    "document; it is inspection evidence.",
], story)

h2("57. References", story)
bullets([
    "Functional Specification §5.2.4 (Inventory / stock), §5.2.1 (base).",
    "EU GMP Annex 1 (sterile manufacture) and Part I §3 (Premises).",
], story)


# ===========================================================================
# STEP 4 — Departments & Users
# ===========================================================================
story.append(PageBreak())
h1("Step 4 — Departments & Users", story, kicker="Step 4 · Tier A")
module_status_row("VERIFIED",
                  "Native <font name='Consolas'>hr</font> (hr.department, "
                  "hr.employee, hr.job) and <font name='Consolas'>base</font> "
                  "(res.users, res.groups).", story)

h2("1. Business Objective", story)
para(
    "Create the organisational structure (departments, jobs, employees) and the "
    "user accounts that will operate the system, each linked to an employee. "
    "This step provides the actors referenced by every later workflow.", story)

h2("16–17. Fields", story)
two_col_kv([
    ("hr.department — name / parent_id", "Department and its parent (org tree)."),
    ("hr.department — manager_id", "Department head (employee)."),
    ("hr.employee — name / user_id", "Employee and the linked login user "
                                     "(one user per employee in a regulated system)."),
    ("hr.employee — department_id / job_id", "Assignment to department and role."),
    ("hr.employee — work_email / work_phone", "Contact details used by notifications."),
    ("res.users — login", "Unique login; recommend employee-style naming."),
    ("res.users — email", "Used for password reset and notifications."),
    ("res.users — groups_id", "Security groups; assigned in Step 5."),
    ("res.users — company_ids / company_id", "Allowed and default companies."),
    ("res.users — share", "False for internal users; True for portal/external."),
], story)

h2("18. Business Rules", story)
bullets([
    "One user per employee. Shared logins destroy attribution and break ALCOA+ "
    "(see Volume 6).",
    "Deactivate, never delete, leavers — deletion orphans audit trails and "
    "signatures.",
    "Internal users only for GxP operations; portal/external users for "
    "non-GxP access.",
], story)

h2("39. Common Mistakes", story)
bullets([
    "Reusing a generic <font name='Consolas'>qa</font> / "
    "<font name='Consolas'>admin</font> login across a team.",
    "Granting Administrator rights broadly. Reserve "
    "<font name='Consolas'>Settings</font> access to a small, named "
    "administrator group.",
], story)

h2("57. References", story)
bullets([
    "Functional Specification §5.2.8 (Employees / hr), §5.2.1 (base).",
    "ALCOA+ data-integrity principles — see Volume 6.",
], story)


# ===========================================================================
# STEP 5 — Security Architecture
# ===========================================================================
story.append(PageBreak())
h1("Step 5 — Security Architecture: Groups, Roles, Access Rights, Record Rules",
   story, kicker="Step 5 · Tier A")
module_status_row("VERIFIED",
                  "Native <font name='Consolas'>base</font> (res.groups, "
                  "ir.model.access, ir.rule). Odoo 19 uses the new "
                  "<font name='Consolas'>res.groups.privilege</font> model "
                  "(verified in ls_signature_groups.xml).", story)

h2("1. Business Objective", story)
para(
    "Define a least-privilege security architecture: who can read, write, create "
    "and delete each object, scoped by company and by record rule. This is the "
    "control foundation for segregation of duties and for ALCOA+ attribution.",
    story)

h2("6. Regulatory Context", story)
reg_callout(
    "FDA 21 CFR Part 11 §11.10(d) and §11.300 require controls over access, "
    "including authority checks ensuring that only authorised individuals can "
    "use the system, electronically sign, or access records. EU GMP Annex 11 §7 "
    "(Data Security) requires access control. Segregation of duties is a "
    "general GMP expectation (e.g. batch release independent of production).", story)

h2("17. Field-by-field — the four security mechanisms", story)
std_table(
    ["Mechanism", "Object", "Purpose"],
    [
        ["User groups (roles)", "<font name='Consolas'>res.groups</font>",
         "Bundles of access. Users gain access by membership. Odoo 19 groups "
         "reference a <font name='Consolas'>res.groups.privilege</font> "
         "category."],
        ["Model access rights", "<font name='Consolas'>ir.model.access.csv</font>",
         "Per-group CRUD (read/write/create/unlink) on each model."],
        ["Record rules", "<font name='Consolas'>ir.rule</font>",
         "Row-level filters (e.g. restrict to the user's company)."],
        ["View-level restrictions", "view attributes, menu visibility",
         "Hide fields/menus/actions from unauthorised groups."],
    ],
    col_ratios=[0.24, 0.30, 0.46])
story.append(Paragraph("Table 1.7 — The four security mechanisms.", style_caption))

verified_note(
    "Odoo 19 changed <font name='Consolas'>res.groups.category_id</font> to "
    "<font name='Consolas'>res.groups.privilege_id</font>, pointing at the new "
    "<font name='Consolas'>res.groups.privilege</font> model. This is confirmed "
    "in the codebase: <font name='Consolas'>ls_electronic_signature/security/"
    "ls_signature_groups.xml</font> declares a "
    "<font name='Consolas'>module_category_life_sciences</font> and a "
    "<font name='Consolas'>privilege_ls_signature</font>, then groups reference "
    "the privilege. <b>The audit_trail module deliberately does not assign a "
    "category</b>, with a comment that the field name &#8220;could not be "
    "verified for Odoo 19 from official documentation&#8221; — it relies on "
    "group name and <font name='Consolas'>implied_ids</font> only. This is an "
    "ASSUMPTION-level gap to watch during upgrade.", story)

h2("32. Security Groups & 33. Record Rules — design pattern", story)
para(
    "Each Life Sciences module follows the same pattern, verified in the code:", story)
bullets([
    "A module category under <b>Life Sciences</b> groups the module's roles.",
    "Role groups are ordered by privilege and chained with "
    "<font name='Consolas'>implied_ids</font> so each higher role implies the "
    "lower (e.g. Manager → Auditor → Viewer → Signer).",
    "Record rules scope records to the user's company (multi-company isolation).",
    "Audit/signature evidence groups are <b>read-only by design</b> so auditors "
    "cannot alter the evidence they audit (segregation of duties).",
], story)

h2("40. Best Practices", story)
bullets([
    "Document the role-to-user mapping in the QMS; it is inspection evidence.",
    "Run periodic access reviews (a native or scheduled action) and record the "
    "review.",
    "Reserve Administrator for infrastructure work; day-to-day QA/QC/Production "
    "work uses named functional roles.",
], story)

h2("57. References", story)
bullets([
    "FDA 21 CFR Part 11 §11.10, §11.300; EU GMP Annex 11 §7.",
    "Functional Specification §7.x (per-module Security Groups).",
    "<font name='Consolas'>ls_electronic_signature/security/ls_signature_groups.xml</font>, "
    "<font name='Consolas'>ls_audit_trail/security/ls_audit_trail_groups.xml</font>.",
], story)


# ===========================================================================
# STEP 6 — Electronic Signatures
# ===========================================================================
story.append(PageBreak())
h1("Step 6 — Electronic Signatures", story, kicker="Step 6 · Tier A")
module_status_row("VERIFIED",
                  "<font name='Consolas'>ls_electronic_signature</font> v19.0.1.0.0, "
                  "AGPL-3, status Beta. Manifest and models verified in the "
                  "codebase. Depends on base, mail.", story)

h2("1. Business Objective", story)
para(
    "Provide electronic signature capability with signature manifestations, "
    "signature/record linking, and identification-code-and-password controls, "
    "to support FDA 21 CFR Part 11 electronic signature requirements.", story)

h2("6. Regulatory Context", story)
reg_callout(
    "<b>FDA 21 CFR Part 11</b> is the primary driver: §11.50 (signature "
    "manifestations — the signed record must show the printed name, the date "
    "and time, and the <i>meaning</i> of the signature); §11.70 (signature / "
    "record linking — signatures must be inextricably linked to their record); "
    "§11.200 (two distinct identification-code components for non-biometric "
    "signatures); §11.300 (controls for identification codes/passwords, "
    "including detection of unauthorised use). EU GMP Annex 11 §2.4-2.5 "
    "expects equivalent controls for electronic signatures.", story)

h2("8. Required Modules", story)
two_col_kv([
    ("Native Odoo", "<font name='Consolas'>base</font>, <font name='Consolas'>mail</font>"),
    ("OCA", "None."),
    ("Life Sciences", "<font name='Consolas'>ls_electronic_signature</font> "
                      "(VERIFIED present, Beta)."),
], story)

h2("12. Roles and Permissions (verified)", story)
verified_note(
    "The module declares five roles under the <b>Life Sciences</b> category and "
    "the <b>Electronic Signatures</b> privilege, chained by "
    "<font name='Consolas'>implied_ids</font>. The source comments cite 21 CFR "
    "11.300(d) for the Security Unit role.", story)
std_table(
    ["Role", "Implies", "Verified purpose (from source comments)"],
    [
        ["Signer", "—",
         "May execute electronic signatures and see their own signature history."],
        ["Viewer", "Signer",
         "May read every signature record of the accessible companies."],
        ["Auditor", "Viewer",
         "Read-only access to signatures, attempts, sessions and integrity "
         "checks. <b>Read-only by design</b> so an auditor can never alter the "
         "evidence being audited."],
        ["Manager", "Auditor",
         "Configures meanings and policies. Holds <b>no</b> write/delete right "
         "over signature records."],
        ["Security Unit", "Auditor",
         "Receives immediate notification of attempted unauthorised use of an "
         "identification code or password, as required by 21 CFR 11.300(d)."],
    ],
    col_ratios=[0.16, 0.14, 0.70])
story.append(Paragraph("Table 1.8 — Electronic signature roles (verified in source).", style_caption))

h2("13. Required Master Data", story)
bullets([
    "<b>Signature Meanings</b> — the controlled vocabulary of meanings (e.g. "
    "AUTHORED, REVIEWED, APPROVED, REJECTED), per 21 CFR 11.50(a)(3).",
    "<b>Signature Policies</b> — rules binding meanings to models/groups.",
    "<b>Users</b> with the Signer role, each linked to an employee (Step 4).",
], story)

h2("14–15. Menus & Navigation", story)
para("Verified menu structure (from the manifest data files):", story)
bullets([
    "<b>Security → Electronic Signatures</b> — requests, logs, sessions, attempts.",
    "<b>Security → Signature Logs</b> — the immutable signature history.",
    "<b>Security → Integrity Checks</b> — verification of signature evidence.",
    "Configuration (meanings, policies) under Settings / the module's config views.",
], story)

h2("16–17. Configuration & Field-by-field — Signature Meaning", story)
para(
    "Signature Meaning is the controlled-vocabulary object required by 21 CFR "
    "11.50(a)(3). The model is <font name='Consolas'>ls.signature.meaning</font>; "
    "the following fields are verified in the source "
    "(<font name='Consolas'>ls_signature_meaning.py</font>):", story)
two_col_kv([
    ("name", "Meaning wording shown on screen and on printed signature "
             "manifestations (e.g. 'Approved by'). Translatable."),
    ("code", "Stable technical identifier for reports and integrations. "
             "Validated by regex <font name='Consolas'>^[A-Z][A-Z0-9_]{1,31}$</font> "
             "(2–32 chars, upper-case letter, digits, underscores). Unique per company."),
    ("sequence", "Order in selection lists."),
    ("description", "When this meaning applies; shown to the signer in the wizard."),
    ("require_reason (Reason Mandatory)",
     "If enabled, the signer must record a free-text reason. Used for negative "
     "decisions such as rejection."),
    ("company_id", "Owning company; the meaning is company-specific."),
    ("group_ids (Authorised Groups)",
     "Groups whose members may use this meaning. Empty = any user with the "
     "Signer role."),
    ("active", "Archive (not delete) to preserve history."),
], story)

h2("18. Business Rules (verified)", story)
bullets([
    "A meaning code must be unique per company (DB constraint "
    "<font name='Consolas'>UNIQUE(code, company_id)</font>).",
    "The code format is enforced at validation; invalid codes raise a "
    "<font name='Consolas'>ValidationError</font>.",
    "A meaning is available to a user only if it has no authorised groups, or "
    "the user is a member of one of them (<font name='Consolas'>is_available_to()</font>).",
], story)

h2("22–23. Electronic Signatures & Audit Trail", story)
para(
    "Each executed signature is written to the immutable signature log with the "
    "printed name, the date/time, the meaning and (if required) the reason, "
    "satisfying 21 CFR 11.50. Signature/record linking (21 CFR 11.70) is provided "
    "by the signature mixin attached to signed models. Attempts — including "
    "failed/unauthorised attempts — are recorded and notify the Security Unit "
    "group (21 CFR 11.300(d)). The full audit trail of signature configuration "
    "changes is handled by <font name='Consolas'>ls_audit_trail</font> (Step 7).", story)

h2("24. Notifications", story)
bullets([
    "Security Unit is notified immediately on attempted unauthorised use of an "
    "identification code or password (21 CFR 11.300(d)).",
    "Signature request workflows notify the requested signer(s).",
], story)

h2("25–27. Documents, Records, Reports", story)
bullets([
    "<b>Signature manifestation</b> report — renders name, date/time, meaning "
    "(21 CFR 11.50).",
    "<b>Signature certificate</b> report — per-signature evidence.",
    "<b>Integrity check</b> records — periodic verification of the signature "
    "evidence store.",
], story)

h2("47–52. Testing & CSV", story)
para(
    "Minimum validation scope for the electronic signature module (21 CFR Part "
    "11 / Annex 11):", story)
std_table(
    ["Test", "Scope", "Evidence"],
    [
        ["IQ", "Module installed; roles & meanings configured; cron scheduled.",
         "Install record, config screenshots, role assignment matrix."],
        ["OQ — meaning control", "Create, validate code-format, archive meanings.",
         "Test scripts + pass/fail for each rule."],
        ["OQ — authorisation", "Signer not in an authorised group cannot use a "
         "restricted meaning; Security Unit notified on unauthorised attempt.",
         "Test log, notification capture."],
        ["OQ — manifestation", "Signed record shows name, date/time, meaning.",
         "Manifestation report sample."],
        ["PQ", "End-to-end SOP approval + batch release signature in the "
         "production-like process.",
         "Signed records, manifestation reports, audit trail extract."],
        ["Integrity", "Run integrity check; verify tamper detection.",
         "Integrity check report."],
    ],
    col_ratios=[0.20, 0.46, 0.34])
story.append(Paragraph("Table 1.9 — Electronic signature validation scope.", style_caption))

h2("39. Common Mistakes", story)
bullets([
    "Granting the Manager role write/delete on signature records — the module "
    "deliberately withholds this; do not override it.",
    "Letting users share identification codes/passwords. Each signer is an "
    "individual.",
    "Treating the signature log as editable. It is immutable evidence.",
], story)

h2("57. References", story)
bullets([
    "FDA 21 CFR Part 11 §11.50, §11.70, §11.200, §11.300.",
    "EU GMP Annex 11 §2.4–2.5.",
    "<font name='Consolas'>ls_electronic_signature</font> — manifest, "
    "<font name='Consolas'>models/ls_signature_meaning.py</font>, "
    "<font name='Consolas'>security/ls_signature_groups.xml</font>.",
    "Functional Specification §7.14 (Electronic Signatures).",
], story)


# ===========================================================================
# STEP 7 — Audit Trail
# ===========================================================================
story.append(PageBreak())
h1("Step 7 — Audit Trail", story, kicker="Step 7 · Tier A")
module_status_row("VERIFIED",
                  "<font name='Consolas'>ls_audit_trail</font> v19.0.1.0.0, "
                  "AGPL-3. Depends on base, mail. Verified: manifest, models "
                  "(<font name='Consolas'>ls_audit_trail_rule.py</font>, "
                  "<font name='Consolas'>ls_audit_trail_log.py</font>, evidence "
                  "pack, verification), security groups, record rules, crons.", story)

h2("1. Business Objective", story)
para(
    "Provide a tamper-evident, field-level audit trail for GxP-regulated Odoo "
    "data, capturing who changed what, when, from what to what, and why — with "
    "integrity verification and exportable evidence packs.", story)

h2("6. Regulatory Context", story)
reg_callout(
    "<b>FDA 21 CFR Part 11 §11.10(e)</b> requires secure, computer-generated, "
    "time-stamped audit trails recording the date and time of operator entries "
    "and actions that create, modify, or delete electronic records, without "
    "obscuring previous values. <b>EU GMP Annex 11 §9 (Audit Trails)</b> requires "
    "audit trails generated by the system, with change and deletion reasons, "
    "retained for the record retention period and available for review. "
    "ALCOA+ (Attributable, Legible, Contemporaneous, Original, Accurate + "
    "Complete, Consistent, Enduring, Available) underpins both.", story)

h2("8. Required Modules", story)
two_col_kv([
    ("Native Odoo", "<font name='Consolas'>base</font>, <font name='Consolas'>mail</font>"),
    ("OCA", "<font name='Consolas'>auditlog</font> (VERIFIED present) — generic "
            "field-level logging; retained as defence-in-depth. The regulated "
            "trail of record is <font name='Consolas'>ls_audit_trail</font>."),
    ("Life Sciences", "<font name='Consolas'>ls_audit_trail</font> (VERIFIED)."),
], story)

h2("12. Roles and Permissions (verified)", story)
verified_note(
    "Three roles, chained by <font name='Consolas'>implied_ids</font>. The "
    "module deliberately omits a category (ASSUMPTION: Odoo 19 field-name "
    "uncertainty) and relies on group name + implied ids.", story)
std_table(
    ["Role", "Implies", "Verified purpose (from source comments)"],
    [
        ["Audit Trail / Viewer", "—",
         "Read the audit trail of the user's own companies. No export, verify or "
         "configure rights."],
        ["Audit Trail / Auditor", "Viewer",
         "Read the trail, run integrity verifications and produce evidence packs. "
         "<b>Cannot change what is audited.</b>"],
        ["Audit Trail / Administrator", "Auditor",
         "Configure audit rules and execute approved retention runs. "
         "<b>Segregation of duties requires this group be held by a different "
         "person than the auditor group.</b>"],
    ],
    col_ratios=[0.22, 0.14, 0.64])
story.append(Paragraph("Table 1.10 — Audit trail roles (verified in source).", style_caption))

h2("13. Required Master Data", story)
bullets([
    "<b>Audit rules</b> — for each regulated model, which fields and which "
    "operations (create/write/unlink) are audited, and the justification.",
    "Company scoping per rule.",
], story)

h2("16–17. Configuration & Field-by-field — Audit Rule", story)
para(
    "The audit rule (<font name='Consolas'>ls.audit_trail.rule</font>) is the "
    "configuration object of the engine. Verified fields from "
    "<font name='Consolas'>ls_audit_trail_rule.py</font>:", story)
two_col_kv([
    ("name", "Free-text label shown in the rule list. Tracked in the rule's own chatter."),
    ("active", "Archived rules are ignored by the engine."),
    ("model_id (Audited Model)", "The <font name='Consolas'>ir.model</font> whose records are audited. "
                                  "Cascade-deleted with the model."),
    ("model_name", "Related stored technical name; indexed for fast lookups."),
    ("company_id", "Empty = applies to every company; set = applies only to that "
                   "company's users."),
    ("log_create / log_write / log_unlink",
     "Audit creations / modifications / deletions. At least one must be on "
     "(DB-enforced)."),
    ("field_ids (Audited Fields)",
     "Fields written to the trail. Empty = audit every stored field except the "
     "technical fields id/create_uid/create_date/write_uid/write_date/display_name."),
    ("excluded_field_ids (Excluded Fields)",
     "Fields never audited, even when Audited Fields is empty. Use for high-volume "
     "or confidential fields."),
    ("entry_count", "Computed count of audit entries for the audited model."),
    ("note (Justification)",
     "Documented reason for the scope. Regulated organisations are expected to "
     "justify why a model/field is audited or excluded."),
], story)

h2("18. Business Rules (verified)", story)
bullets([
    "<b>One rule per model per company</b> — DB constraint "
    "<font name='Consolas'>UNIQUE(model_id, company_id)</font>.",
    "<b>At least one operation</b> must be audited — enforced at validation.",
    "<b>Fields must belong to the model</b> — foreign fields are rejected.",
    "<b>The engine never audits itself</b>: models in "
    "<font name='Consolas'>NON_AUDITABLE_MODELS</font> (the audit engine's own "
    "models) are rejected, so a configuration change cannot recurse into the "
    "engine being reconfigured.",
    "<b>Abstract and transient models are rejected</b> — abstract models own no "
    "table; transient records are cleared by the vacuum job and are not part of "
    "the regulated record set.",
    "<b>Rule changes clear the cached audit configuration</b> so new rules take "
    "effect immediately.",
    "<b>Rule changes are recorded in the rule's own chatter, not in the audit "
    "log</b> — by design, to avoid self-recursion.",
], story)

callout("Verified design decision — segregation of duties",
    "The Administrator role can configure rules and run retention; the Auditor "
    "role can read, verify and export evidence but cannot configure. The source "
    "comment explicitly requires these be held by different people. This is a "
    "textbook GxP segregation-of-duties control and should be reflected in the "
    "role-to-user mapping recorded in the QMS.", story, kind="reg")

h2("24. Notifications & 26. Generated Records", story)
bullets([
    "Audit entries: <font name='Consolas'>ls.audit_trail.log</font> (header) + "
    "<font name='Consolas'>ls.audit_trail.log.line</font> (field-level old/new "
    "values).",
    "Integrity verifications: <font name='Consolas'>ls.audit_trail.verification</font>.",
    "Evidence packs: <font name='Consolas'>ls.audit_trail.evidence_pack</font> — "
    "tamper-evident, exportable bundles for inspectors.",
    "Retention runs: scheduled, approved purges past the retention period "
    "(Annex 11 §9 retention).",
], story)

h2("27. Reports", story)
bullets([
    "Audit log report (filterable by model, user, date, operation).",
    "Evidence pack report — the inspection-ready extract.",
    "Integrity verification report.",
], story)

h2("47–52. Testing & CSV", story)
std_table(
    ["Test", "Scope", "Evidence"],
    [
        ["IQ", "Module installed; rules configured; crons (verification, "
         "retention) scheduled.", "Install + config evidence."],
        ["OQ — field capture", "Change a field on an audited model; verify "
         "old/new value, user, timestamp captured.", "Log extract."],
        ["OQ — scope", "Excluded field is not captured; technical fields are "
         "skipped by default.", "Log extract comparison."],
        ["OQ — non-auditable rejection", "Creating a rule on an audit-engine "
         "model raises ValidationError.", "Error screenshot."],
        ["OQ — integrity", "Tamper with a log record; integrity check detects it.",
         "Verification report."],
        ["PQ", "End-to-end batch record change → audit entry → evidence pack "
         "export.", "Evidence pack sample."],
        ["Retention", "Approved retention run purges only records past the "
         "retention period.", "Retention run report."],
    ],
    col_ratios=[0.22, 0.44, 0.34])
story.append(Paragraph("Table 1.11 — Audit trail validation scope.", style_caption))

h2("39. Common Mistakes", story)
bullets([
    "Auditing transient/wizard models — they are cleared by the vacuum job and "
    "are not part of the regulated record set (the engine rejects them).",
    "Auditing every field of a high-volume model without an exclusion list — "
    "bloats the trail and slows verification.",
    "Allowing the same person to hold both Auditor and Administrator roles — "
    "breaks segregation of duties.",
    "Editing audit log records directly in the database — destroys integrity and "
    "is detectable by the verification job.",
], story)

h2("40. Best Practices", story)
bullets([
    "Justify every rule's scope in the <font name='Consolas'>note</font> field; "
    "inspectors ask <i>why</i> a field is or is not audited.",
    "Run the integrity verification cron regularly and review its results.",
    "Test the restore-and-replay of an evidence pack during periodic review.",
], story)

h2("55–56. Backup & Disaster Recovery", story)
para(
    "The audit trail is part of the regulated record set and must be included in "
    "the validated backup. Treat evidence packs as additional, tamper-evident "
    "snapshots suitable for off-site/immutable storage. See Volume 6 for the "
    "full strategy.", story)

h2("57. References", story)
bullets([
    "FDA 21 CFR Part 11 §11.10(e); EU GMP Annex 11 §9 (Audit Trails).",
    "ALCOA+ data-integrity principles (Volume 6).",
    "<font name='Consolas'>ls_audit_trail</font> — manifest, "
    "<font name='Consolas'>models/ls_audit_trail_rule.py</font>, "
    "<font name='Consolas'>models/ls_audit_trail_log.py</font>, "
    "<font name='Consolas'>security/ls_audit_trail_groups.xml</font>.",
    "Functional Specification §7.15 (Audit Trail).",
], story)


# ===========================================================================
# BUILD
# ===========================================================================
doc = GuideDocTemplate(
    OUTPUT_PDF,
    pagesize=A4,
    leftMargin=LEFT_M, rightMargin=RIGHT_M,
    topMargin=TOP_M, bottomMargin=BOTTOM_M,
    title="Life Sciences Suite — Implementation & Operational Guide (Foundation)",
    author="Life Sciences Suite Architecture Team",
    creator="Life Sciences Suite Architecture Team",
    subject="Foundation (Volume 0–1): empty-DB init through audit trail, "
            "grounded in the verified Odoo 19 Community Life Sciences codebase.",
)

doc.multiBuild(story, onFirstPage=lambda c, d: None, onLaterPages=_header_footer)
print("WROTE:", OUTPUT_PDF)
print("Pages:", doc.page)
