# Copyright 2026 Life Sciences Suite
# License AGPL-3.0 or later (https://www.gnu.org/licenses/agpl-3.0).
{
    "name": "Life Sciences - Deviation Management",
    "version": "19.0.1.0.1",
    "category": "Life Sciences/Quality",
    "summary": "Record, classify, investigate, disposition and close GxP deviations",
    "author": "Life Sciences Suite Architecture Team",
    "website": "https://github.com/OCA",
    "license": "AGPL-3",
    "depends": [
        "base",
        "mail",
        "hr",
        "stock",
        "mrp",
        "maintenance",
    ],
    "data": [
        "security/ls_deviation_security.xml",
        "security/ir.model.access.csv",
        "data/ir_sequence_data.xml",
        "data/ls_deviation_category_data.xml",
        "data/ls_deviation_type_data.xml",
        "data/ls_deviation_rca_method_data.xml",
        "data/mail_message_subtype_data.xml",
        "data/mail_template_data.xml",
        "data/ir_cron_data.xml",
        "views/ls_deviation_category_views.xml",
        "views/ls_deviation_type_views.xml",
        "views/ls_deviation_rca_method_views.xml",
        "views/ls_deviation_tag_views.xml",
        "views/ls_deviation_action_views.xml",
        "views/ls_deviation_investigation_views.xml",
        "views/ls_deviation_disposition_views.xml",
        "views/ls_deviation_stage_log_views.xml",
        "views/ls_deviation_views.xml",
        "wizards/ls_deviation_close_wizard_views.xml",
        "wizards/ls_deviation_cancel_wizard_views.xml",
        "wizards/ls_deviation_due_date_wizard_views.xml",
        "views/res_config_settings_views.xml",
        "report/ls_deviation_report.xml",
        "report/ls_deviation_report_templates.xml",
        "views/ls_deviation_menus.xml",
    ],
    "demo": [
        "demo/ls_deviation_demo.xml",
    ],
    "application": True,
}
